<?php

//general

$l_yes 			 = "Ano";
$l_no			 = "Ne";
$l_here			 = "zde";
$l_submit		 = "Odeslat";
$l_reset		 = "Vymazat";
$l_all			 = "Vsechno";

$l_ore			 = "Ruda";
$l_organics		 = "Potraviny";
$l_goods		 = "Zbozi";
$l_energy		 = "Energie";
$l_colonists		 = "Koloniste";
$l_credits 		 = "Kredity";
$l_units		 = "jednotek ";
$l_special		 = "Zvlastni";

$l_cargo		 = "Naklad";
$l_fighters		 = "Stihaci ";
$l_mines		 = "Miny ";
$l_torps		 = "Torpeda";

$l_none			 = "Zadne";
$l_unnamed		 = "Bez nazvu";
$l_name			 = "Nazev";
$l_unowned		 = "Bez vlastnika";
$l_unknown		 = "Neznamy";
$l_clickme 		 = "Kliknete zde";
$l_player  		 = "Kapitan";
$l_ship			 = "Lod";
$l_set			 = "nastavit";
$l_realspace		 = "Realny vesmir";
$l_armourpts		 = "Pancerovani (body)";


// main.php

$l_main_title 		 = "Hlavni menu";

$l_traderoutes		 = "Obchodni cesty";
$l_trade_control	 = "Rizeni obchodu";

$l_youhave 		 = "Mate ";
$l_turns_used		 = "Vycerpano tahu: ";
$l_turns_have		 = "Tahu k dispozici: ";
$l_score		 = "Skore: ";
$l_sector		 = "Sektor";
$l_help			 = "Napoveda";
$l_faq		         = "Otazky a odpovedi";
$l_feedback		 = "Napiste nam";
$l_forums		 = "Forum";
$l_logout		 = "Odhlasit";

$l_commands		 = "Prikazy";
$l_command_no		 = "Prikaz neni k dispozici.";
$l_devices		 = "Zarizeni";
$l_planets		 = "Planety";
$l_log			 = "Automaticky denik";
$l_sector_def		 = "Obrana sektoru";
$l_defense		 = "Obrana";
$l_read_msg		 = "Cteni zprav";
$l_send_msg		 = "Odeslat zpravu";
$l_rankings		 = "Hodnoceni";
$l_teams		 = "Aliance";
$l_ohno			 = "Sebezniceni";
$l_options		 = "Nastaveni";
$l_navcomp		 = "Navigacni pocitac";

$l_incompletemove 	 = "Jeste jste nedokoncil predchozi presun.";
$l_clicktocontinue	 = "Pokracovat";
$l_toplanetmenu   	 = "pro menu planety.";
$l_nonexistant_pl	 = "Na neexistujici planetu???";
$l_abord		 = ", na palube lodi ";
$l_messages_wait	 = " novych zprav.";

$l_no_warplink		 = "No warp links";
$l_scan			 = "pruzkum";
$l_fullscan		 = "Uplny pruzkum";

$l_port			 = "Brana";
$l_tradingport		 = "Obchodni brana";
$l_planet_in_sec	 = "Planety v sektoru ";
$l_ships_in_sec		 = "Jine lode v sektoru ";
$l_sector_0		 = "Tady u Slunce (Sektor 0) je prilis husty provoz, takze nelze od sebe odlisit jednotlive lode!";

// report.php

$l_report_title		 = "Hlaseni o stavu lodi";

$l_level		 = "Uroven";

$l_ship_levels		 = "Urovne soucasti lode";
$l_hull			 = "Trup lode";
$l_engines		 = "Motory";
$l_power		 = "Vykon";
$l_computer		 = "Pocitac";
$l_sensors		 = "Senzory";
$l_armour		 = "Pancerovani";
$l_shields		 = "Stity";
$l_beams		 = "Laserove zbrane";
$l_torp_launch	         = "Vrhace torped";
$l_cloak		 = "Maskovani";
$l_holds		 = "Skladove bunky";
$l_deflect		 = "Odchylovace min";
$l_ewd			 = "Nouzove zarizeni Warp";


$l_arm_weap		 = "Pancerovani & Zbrane";
$l_beacons		 = "Kosmicke majaky";
$l_warpedit		 = "Warp Editor";
$l_genesis		 = "Zarodkova torpeda";
$l_escape_pod		 = "Unikova kapsle";
$l_fuel_scoop		 = "Fuel Scoop (naberac paliva)";

// device.php

$l_device_title		 = "Zarizeni";

$l_device_expl		 = "Vase lod je vybavena nasledujicimi zarizenimi (kliknutim na zarizeni ho pouzijete):";
$l_device		 = "Zarizeni";
$l_qty			 = "Mnozstvi";
$l_usage		 = "Pouziti";
$l_manual		 = "Rucne";
$l_automatic		 = "Automaticky";

// port.php port2.php

$l_trade		 = "Obchodovani";
$l_title_port		 = "Obchodovani branou";
$l_title_trade		 = "Zbozi na prodej";
$l_sector_war		 = "Valecna blokada";
$l_war_info		 = "V tomto sektoru je valka. Nemuzete dosahnout brany kvuli nepratelskym silam.";
$l_no_trade		 = "Obchodovani zakazano";
$l_no_trade_out		 = "Obchodovani touto branou neni dovoleno pro cizince.";
$l_no_trade_info	 = "Obchodovani touto branou neni dovoleno";
$l_buying		 = "Nakup";
$l_selling		 = "Prodej";
$l_commodity		 = "Zbozi";
$l_amount		 = "Mnozstvi";
$l_price		 = "Cena";
$l_buy			 = "Koupit";
$l_sell			 = "Prodat";
$l_trade_st_info	 = "Mate [free_holds] prazdnych skladovych bunek, muzete jeste nalozit [free_power] energie a mate [credits] kreditu.";
$l_special_port		 = "Zvlastni brana";
$l_no_credits		 = "Nedostatek kreditu";
$l_creds_to_spend	 = "Muzete utratit [credits] kreditu.";
$l_cost			 = "Cena";
$l_avail		 = "K dispozici";
$l_profit		 = "Zisk";
$l_current		 = "Nyni";
$l_current_qty		 = "Nynejsi mnozstvi";
$l_max			 = "Maximum";
$l_ifyouneedmore	 = "Pokud potrebujete vice, muzete zkusit tyto brany [igb] ";
$l_ifyouneedplan	 = "Pouzit planetarni";
$l_igb_term		 = "IGB Bankovni Terminal";
$l_upgrade		 = "Vylepsit?";
$l_unlimited		 = "Neomezeno";
$l_full			 = "Plne";
$l_equipped		 = "Vybaveno";
$l_n_a			 = "---";
$l_item			 = "Polozka";
$l_totalcost		 = "Celkova cena";
$l_would_dump	         = "Pokud chcete vylozit vsechny sve kolonisty zde, kliknete";
$l_noport		 = "Zde neni zadna brana!";
$l_trade_turnneed	 = "Potrebujete alespon jeden tah, abyste mohli obchodovat branou nebo na planete.";
$l_returnto_port         = " <A HREF=port.php>Kliknete zde</A> pro navrat do menu brany.";
$l_notenough_cargo	 = "Nemate dostatek volnych skladovych bunek pro nalozeni zbozi, ktere chcete nakoupit.";
$l_notenough_power	 = "Nemate dostatek volnych bunek pro uskladneni energie, kterou chcete koupit.";
$l_notenough_credits	 = "Nemate dostatek kreditu pro dokonceni transakce.";
$l_notenough_turns	 = "Nemate dostatek tahu pro dokonceni transakce.";
$l_notenough_ore	 = "Nemate dostatek rudy pro dokonceni transakce.";
$l_notenough_goods	 = "Nemate dostatek zbozi pro dokonceni transakce.";
$l_notenough_energy	 = "Namate dostatek energie pro dokonceni transakce.";
$l_notenough_organics	 = "Nemate dostatek potravin pro dokonceni transakce.";
$l_exceed_organics	 = "Mnozstvi potravin presahlo zasobu/poptavku.  ";
$l_exceed_ore            = "Mnozstvi rudy presahlo zasobu/poptavku.  ";
$l_exceed_energy         = "Number of energy exceeds the supply/demand.  ";
$l_exceed_goods          = "Mnozstvi zbozi presahlo zasobu/poptavku.  ";
$l_trade_result		 = "Vysledky tohoto obchodovani";
$l_traded_ore		 = "Obchod s rudou";
$l_traded_goods		 = "Obchod se zbozim";
$l_traded_organics	 = "Obchod s potravinami";
$l_traded_energy	 = "Obchod s energii";
$l_trade_complete	 = "Obchod dokoncen";
$l_trade_upgraded = "vylepseno";
$l_trade_added = "pridano";
$l_trade_installed = "instalovano";


// planet.php planet2.php planet3.php
$l_planet_title		 = "Menu planety";
$l_planet_none		 = "Nejste ve stejnem sektoru jako tato planeta a tak s ni nemuzete nic delat.";
$l_planet_capture1	 = "obsadit"; // thats the link's text
$l_planet_capture2	 = "Muzete planetu [capture] nebo ji proste opustit nechranenou.";
$l_planet_unowned	 = "Tato planeta nikomu nepatri.";
$l_planet_unnamed        = "Vitejte na dosud nepojmenovane planete patrici hraci jmenem [name].";
$l_planet_named		 = "Vitejte na planete [planetname] jejimz vlastnikem je [name].";
$l_planet_onsurface	 = "Nachazite se na povrchu planety.";
$l_planet_orbit 	 = "Nachazite se na orbite planety.";
$l_planet_leave_link     = "Opustit";
$l_planet_leave          = "[leave] planetu";
$l_planet_name_link = "Pojmenovat";
$l_planet_name2 = "[name] planetu";
$l_planet_land_link      = "Pristat";
$l_planet_land           = "[land] na planete";
$l_planet_logout	 = "Zde se muzete <a href=logout.php>odhlasit</a> v bezpeci Vasi planety.";
$l_planet_selling	 = "Planeta v soucasnosti prodava zbozi.";
$l_planet_not_selling    = "Planeta v soucasnosti neprodava zbozi.";
$l_planet_transfer_link	 = "Presun";
$l_planet_transfer	 = "[transfer] zbozi/zdroju/kolunistu na planetu nebo z planety";
$l_planet_hasbase	 = "Na teto planete mate zakladnu.";

$l_planet_perc		 = "Procenta produkce";
$l_planet_interest	 = "* Produkce kreditu mimo bankovni zajmy je 100 - ostatni procenta";
$l_planet_update	 = "Zmenit";
$l_planet_tsell_link	 = "prodej";
$l_planet_tsell		 = "Zmente planetarni [selling] zbozi";
$l_planet_bbase_link	 = "postavit zakladnu";
$l_planet_bbase		 = "S dostatkem zbozi a kreditu zde muzete [build], ktera napomuze planetarni obrane.";
$l_planet_bbuild	 = "Zakladna postavena";
$l_planet_mcorp_linkC	 = "planetu aliance";
$l_planet_mcorp_linkP	 = "normalni planetu";
$l_planet_mcorp		 = "Muzete zmenit tuto planetu na [planet].";
$l_planet_buy_link	 = "Nakoupit";
$l_planet_buy		 = "[buy] zbozi z planety";
$l_planet_att_link	 = "Utocit";
$l_planet_att		 = "[attack] na planetu";
$l_planet_att_sure	 = "Jste si JISTY...";
$l_planet_scn_link	 = "Prozkoumat";
$l_planet_scn		 = "[scan] planetu sensory";
$l_planet_nowsell        = "Planeta nyni nabizi sve zbozi.";
$l_planet_nownosell      = "Planeta nyni nenabizi sve zbozi.";
$l_planet_iname		 = "Jak pojmenujete tuto planetu?";
$l_planet_cname		 = "Jmeno planety bylo zmeneno na ";
$l_planet_landed	 = "Pristal jste na povrchu planety.";
$l_planet_left		 = "Uz nejste na povrchu planety.";
$l_planet_cinfo		 = "Mate misto pro [cargo] kusu dalsiho nakladu.  Mate kapacitu pro uskladneni [energy] dalsi energie.";
$l_planet_toplanet	 = "Na planetu?";
$l_planet_baseinfo	 = "Pro postaveni zakladny je treba alespon $base_credits kreditu, $base_ore rudy, $base_organics potravin, a $base_goods zbozi na planete.";
$l_planet_p_under        = "Nemuzete zmenit procenta produkce na zaporne cislo.";
$l_planet_p_over	 = "Celkovy soucet procent produkce nemuze presahnout 100%.";
$l_planet_p_changed	 = "Procenta produkce byla zmenena.";
$l_plant_scn_turn	 = "Pro provedeni pruzkumu planety potrebujete alespon jeden tah.";
$l_planet_noscan	 = "Senzory se nemohou zamerit na cil!";
$l_planet_logscanA	 = "[name] se pokusil prozkoumat jednu z Vasich planet v sektoru [sector], ale neuspel.";
$l_planet_logscanB	 = "Jedna z Vasich planet v sektoru [sector] byla prozkoumana senzory hrace jmenem [name].";
$l_planet_scn_report	 = "Vysledky pruzkumu [name], vlastnika:  [owner]";
$l_base	  		 = "Zakladna";
$l_planet_ison		 = "je na planete.";
$l_planet_captured	 = "Planeta obsazena";
$l_planet_notdef	 = "Planeta nema obranu!";
$l_planet_caplog	 = "Vase planeta '[planetname]' v sektoru [sector] byla obsazenam hracem jmenem [name].";

$l_planet2_title	 = "Planetarni presun";
$l_planet2_noturn	 = "Pro planetarni presun potrebujete alespon jeden tah.";
$l_planet2_noten 	 = "Namete dostatek ";
$l_planet2_fortr	 = "pro pozadovany presun.";
$l_planet2_settr	 = "Mnozstvi pro presun bylo nastaveno na";
$l_planet2_losup	 = "Planeta je schopna dodat pouze ";
$l_planet2_notowner	 = "Nevlastnite tuto planetu.";
$l_planet2_compl	 = "Presun PROVEDEN.";
$l_planet2_power	 = "energetickych kapacit";
$l_planet2_comp 	 = "vypocetni kapacity";
$l_planet2_laun 	 = "kapacity vypoustecu";
$l_planet2_nocorptransfer = "Nemuzete prenaset kredity z/na aliancni planetu.";

$l_planet3_title	 = "Obchodovani na planete";

// planet-report.php

$l_pr_title		 = "Hlaseni o planetach";
$l_pr_teamlink		 = "Zobrazit planety aliace";
$l_pr_noplanet		 = "V dosahu nejsou zadne planety";
$l_pr_clicktosort	 = "Kliknutim na zahlavi sloupce vystup seradite.";
$l_pr_totals		 = "Soucty";

// rsmove.php
$l_rs_title 		= "Pohyb v realnem vesmiru";
$l_rs_whichsector       = "Do jakeho sektoru se chcete dostate realnym vesmirem?";
$l_rs_insector		= "Jste prave v sektoru [sector] - k dispozici jsou sektory od 0 do [sector_max].";
$l_rs_submit		= "Vypocitat";
$l_rs_movetime		= "S Vasimi motory bude treba [triptime] tahu pro provedeni cesty.";
$l_rs_energy		= "Nabirate [energy] energie";
$l_rs_noturns		= "Nemate k dispozici dostatek tahu, na tuto cestu se nemuzete vydat.";
$l_rs_engage_link	= "spustit";
$l_rs_engage		= "Mate [turns] tahu. [engage] motory?";

$l_rs_invalid		= "Chybny cil";
$l_rs_ready 		= "Nachazite se v sektoru [sector]. Spotreboval jste [triptime] tahu a ziskal [energy] energie.";

// navcomp.php	

$l_nav_title		 = "Navigacni pocitac";
$l_nav_nocomp		 = "Navigacni pocitac neni k dispozici";
$l_nav_query		 = "Zadejte sektor do ktereho chcete nalezt cestu: ";
$l_nav_pathfnd		 = "Cesta nalezena";
$l_nav_answ1		 = "Bude treba ";
$l_nav_answ2		 = "tahu pro cestu do tohoto sektoru.";
$l_nav_proper		 = "Vase pocitacova technologie nedostacuje pro vypocet warpove cesty na takovou vzdalenost.";


// attack.php

$l_att_title		 = "Utok na lod";
$l_att_notarg		 = "Cil se nenachazi v tomto sektoru.";
$l_att_noturn		 = "Pro utok potrebujete alespon jeden tah.";
$l_att_noatt		 = "Utoceni v tomto sektoru neni dovoleno.";
$l_att_flee		 = "Cil se obratnym manevrovanim vyhnul!";
$l_att_ewd		 = "Cil aktivoval nouzove warp zarizeni, kdyz jste na nej zautocil!";
$l_att_att		 = "Zautocit na ";
$l_att_beams		 = "Zasahy laserem:";
$l_att_torps		 = "Zasahy torped:";
$l_att_fighters		 = "Utok stihacu:";
$l_att_lost		 = "ztrata";
$l_att_ylost		 = "Ztratil jste";
$l_att_sdown		 = " - stity jsou vyrazeny!";
$l_att_ydown		 = "Vase stity jsou vyrazeny!";
$l_att_shits		 = " - ucinnost stitu snizena na";
$l_att_yhits		 = "Ucinnost stitu byla snizena na";
$l_att_dmg		 = "poskozeni";
$l_att_sarm		 = " - pancerovani prorazeno!";
$l_att_yarm		 = "Pancerovani Vasi lode bylo prorazeno!";
$l_att_ashit		 = " - zasahem snizena ucinnost pancerovani na";
$l_att_ayhit		 = "Zasahem snizena ucinnost Vaseho pancerovani na";
$l_att_lostf		 = " - zniceni vsichni stihaci.";
$l_att_ylostf		 = "Ztratil jste vsechny svoje stihace.";
$l_att_sdest		 = " - lod byla znicena.";
$l_att_espod		 = "Byla vypustena unikova kapsle!";
$l_att_ysalv		 = "Zachranil jste [salv_ore] rudy, [salv_organics] potravin, [salv_goods] zbozi, a [ship_salvage_rate]% lodi za [ship_salvage] kreditu.<BR>Vase hodnoceni se zmenilo o [rating_change] bodu.";
$l_att_andused		 = "a pouzito";
$l_att_stilship		 = "Nepodarilo se Vam znicit lod kapitana jmenem [name].";
$l_att_atyou		 = "zautocil na Vas";
$l_att_and		 = "a";
$l_att_yshiplost	 = "Vase lod byla znicena!";
$l_att_salv		 = "[name] zachranil [salv_ore] rudy, [salv_organics] potravin, [salv_goods] zbozi, a [ship_salvage_rate]% lodi za  [ship_salvage] kreditu";

// warpedit 1-3.php

$l_warp_title		 = "Pouziti Warp Editoru";
$l_warp_turn		 = "Potrebujete alespon jeden tah pro pouziti warp editoru.";
$l_warp_none		 = "Nemate zadny warp editor.";
$l_warp_forbid		 = "Pouziti warp editoru v tomto sektoru neni dovoleno.";
$l_warp_nolink		 = "Z tohoto sektoru nejsou zadna spojeni.";
$l_warp_linkto		 = "Z tohoto sektoru vedou spojeni do ";
$l_warp_query		 = "Do ktereho sektoru chcete vytvorit spojeni?";
$l_warp_oneway		 = "Jednosmerne?";
$l_warp_dest		 = "Nebo muzete zrusit spojeni do sektoru.";
$l_warp_destquery	 = "Do ktereho sektoru chcete zrusit spojeni?";
$l_warp_bothway		 = "Obousmerne";
$l_warp_nosector	 = "Sektor neexistuje.";
$l_warp_twoerror	 = "Pouziti Warp editoru pro vytvoreni obousmerneho spojeni do sektoru [target_sector] neni dovoleno.";
$l_warp_sectex		 = "Nelze vytvorit Warpove spojeni z tohoto sektoru protoze by bylo prekroceno maximum $link_max spojeni na sektor.";
$l_warp_linked		 = "Cilovy sektor ([target_sector]) jiz ma spojeni s timto sektorem.";
$l_warp_unlinked	 = "Cilovy sektor ([target_sector]) nema spojeni s timto sektorem.";
$l_warp_coneway	         = "Vytvoreno jednosmerne spojeni do";
$l_warp_ctwoway		 = "Vytvoreno spojeni z a do";
$l_warp_forbidtwo	 = "Pouziti Warp editoru pro zruseni obousmerneho spojeni se sektorem [target_sector] neni dovoleno.";
$l_warp_removed		 = "Zruseno spojeni do";
$l_warp_removedtwo	 = "Zruseno spojeni z a do";

// genesis.php

$l_gns_title		 = "Pouziti zarodkoveho zarizeni";
$l_gns_turn		 = "Potrebujete alespon jeden tah pro pouziti zarodkoveho zarizeni.";
$l_gns_onplanet		 = "Nemuzete pouzit toto zarizeni na povrchu planety.";
$l_gns_full		 = "Tento solarni system je uz plny.";
$l_gns_planetex		 = "V tomto sektoru jiz je planeta.";
$l_gns_nogenesis	 = "Nemate zadne zarodkove zarizeni.";
$l_gns_forbid		 = "Vytvoreni planety v tomto sektoru neni dovoleno.";
$l_gns_bforbid		 = "Zakladny v tomto sektoru rusi Vase zarodkove zarizeni. Vytvoreni planety neni mozne.";
$l_gns_pcreate		 = "Planeta vytvorena.";

// ship.php

$l_ship_title		 = "Rizeni lode";
$l_ship_the		 = "";
$l_ship_nolonger	 = "uz neni v sektory";
$l_ship_youc		 = "Pred Vami je lod jmenem ";
$l_ship_owned		 = "jejimz vlastnikem je";
$l_ship_perform		 = "Muzete provest nasledujici akce:";

// selfdestruct.php

$l_die_title		 = "Sebezniceni";
$l_die_rusure		 = "Jste si jisty, ze chcete znicit Vasi lod? Tato akce Vas vyradi ze hry.";
$l_die_goodbye		 = "Zbohem kruta galaxie!";
$l_die_check		 = "Skutecne chcete byt vyrazen ze hry?";
$l_die_nonono		 = "NE! NE! NE!";
$l_die_what		 = "Na co asi myslim?";
$l_die_count		 = "5.. 4.. 3.. 2.. 1.. Bum!";
$l_die_vapor		 = "Vase lod a vse na palupe se vyparilo.";
$l_die_please		 = "<A HREF=logout.php>Odhlaste se</A> prosim.";
$l_die_exploit		 = "Nehrajte si s vecmi, kterym nerozumite.";

// move.php

$l_move_title 		 = "Presun";
$l_move_turn		 = "Pro presun potrebujete alespon jeden tah.";
$l_move_failed		 = "Presun se NEPODARIL!";

// scan.php

$l_scan_title		 = "Prozkoumat lod sensory";
$l_scan_turn		 = "Potrebujete alespon jeden tah pro pruzkum jine lode.";
$l_scan_ron		 = "Vysledky pruzkumu";
$l_scan_capt		 = "Kapitan:";
$l_scan_arma		 = "Vyzbroj:";
$l_scan_carry		 = "Naklad:";

// lrscan.php

$l_lrs_title		 = "Dalkovy pruzkum";
$l_lrs_nofull		 = "Vase pruzkumova zarizeni nedisponuji plnym rozsahem pruzkumovych moznosti.";
$l_lrs_noturns		 = "Potrebujete alespon $fullscan_cost tah(u), aby byl proveden uplny dalkovy pruzkum.";
$l_lrs_used		 = "Pouzito";
$l_lrs_turns		 = "tah(u)";
$l_lrs_left		 = "zbyva";
$l_lrs_reach		 = "Nasledujici mista mohou byt dosazena ze sektoru [sector]:";
$l_lrs_links		 = "Spojeni";
$l_lrs_ships		 = "Lode";
$l_lrs_click		 = "Kliknete na cislo pro presun do prislusneho sektoru.";
$l_lrs_cantscan		 = "Sektor neni mozne z tohoto sektoru prozkoumat!";
$l_lrs_zero		 = "Sektor 0 je prilis preplneny, nez aby bylo mozne hledat lode!";
$l_lrs_moveto		 = "pro presun do sektoru";

// log.php

$l_log_months = array('Leden','Unor','Brezen','Duben','Kveten','Cerven','Cervenec','Srpen','Zari','Rijen','Listopad','Prosinec');
$l_log_months_short = array('Leden','Unor','Brezen','Duben','Kveten','Cerven','Cervenec','Srpen','Zari','Rijen','Listopad','Prosinec');
$l_log_pod = "Nastesti jste mel unikovou kapsli!";
$l_log_nopod = "<font color=yellow><b>Nemel jste k dispozici unikovou kapsli - zahynul jste.</b></font>";
$l_log_log = "Automaticky denik kapitana zvaneho [player]";
$l_log_start = "Zaznam deniku ze dne ";
$l_log_end = "Konec deniku pro ";
$l_log_click = "<A HREF=$interface><font color=#00ff00>Navrat do hlavniho menu</font></A>.";
$l_log_note = "POZNAMKA: Pokud se tato stranka zobrazi nespravne nebo pokud proste nemate v lasce dynamicke HTML, muzete ho <a href=options.php><font color=#00FF00>vypnout</font> zde";

$l_log_text[LOG_LOGIN] = "Prihlasil jste se z adresy [ip].";
$l_log_title[LOG_LOGIN] = "Prihlaseni do systemu";
$l_log_text[LOG_LOGOUT] = "You have logged out, from [ip].";
$l_log_title[LOG_LOGOUT] = "Odhlaseni ze systemu";
$l_log_text[LOG_ATTACK_OUTMAN] = "[player] byl odhalen pri utoku na nas a Vase vyborne pilotni schopnosti a dobre motory umoznili se tomuto utoku vyhnout.";
$l_log_title[LOG_ATTACK_OUTMAN] = "Evasive action!";
$l_log_text[LOG_ATTACK_OUTSCAN] = "Vase sensory zachytili pokus kapitana zvaneho [player] zamerit na Vasi lod svoje zbranes, ale Vase maskovaci zarizeni obelstilo jeho primitivni sensory.";
$l_log_title[LOG_ATTACK_OUTSCAN] = "Maskovani bylo uspesne!";
$l_log_text[LOG_ATTACK_EWD] = "Jste prekvapen zradnym utokem kapitana zvaneho [player]. Vidite jak se k Vasi lodi blizi bojove hlavice ve stejnem okamziku, kdy krecovite tisknete tlacitko nouzoveho warp zarizeni. Svet okolo Vas potemnel a na milisekundu jste si uz myslel, ze jste mrtvy. Kdyz jste nakonec otevrel oci. vidite ze jste byl nekam bezpecne transportovan. Ale kam presne, to nevite...";
$l_log_title[LOG_ATTACK_EWD] = "Nouzovy warp!";
$l_log_text[LOG_ATTACK_EWDFAIL] = "Vase senzory zachytilli lod kapitana zvaneho [player], ktery na Vas utoci. \"Lepsi je byt v bezpeci nez nebyt\", pomyslel jste si a stiskl tlacitko nouzoveho warp zarizeni. Slysite ale podivne zvuky prichazejici z motoru a po cele lodi je citit pach spalenych vedeni. \"Zatraceny kram!\", zaklel jste a nakopnul pocitac. Pocitac na protest pipnul a Vy se pripravujete na bitvu...";
$l_log_title[LOG_ATTACK_EWDFAIL] = "Nouzovy warp<font color=red>selhal!</font>";
$l_log_text[LOG_ATTACK_LOSE] = "Na Vasi lod utoci kapitan zvany [player]. Delate vsechno mozne, ale proti nadupanym zbranim toho zatraceneho blazna zvaneho \"[player]\" nemate zadnou sanci. Vase lod byla znicena. ";
$l_log_title[LOG_ATTACK_LOSE] = "<font color=red>Bitvu jste prohral!</font>";
$l_log_text[LOG_ATTACKED_WIN] = "Na Vasi lod zautocil kapitan zvany [player]. Po kratke bitve utoky prestaly. Ztratil jste [armor] pancerovani a [fighters] stihacu v soubojich.";
$l_log_title[LOG_ATTACKED_WIN] = "<font color=yellow>Souboj!</font>";
$l_log_text[LOG_TOLL_PAID] = "Zaplatil jste [toll] kreditu za vstup do sektoru [sector]. Prisahal jste, ze najdete zpusob jak dostat svoje penize zpatky.";
$l_log_title[LOG_TOLL_PAID] = "Vydirani";
$l_log_text[LOG_HIT_MINES] = "Narazil jste do [mines] min pri ceste sektorem [sector].";
$l_log_title[LOG_HIT_MINES] = "<font color=yellow>Vybuch min!</font>";
$l_log_text[LOG_SHIP_DESTROYED_MINES] = "Vase lod byla znicena v minovem poli v sektoru [sector]. ";
$l_log_title[LOG_SHIP_DESTROYED_MINES] = "<font color=red>Vybuch min!</font>";
$l_log_text[LOG_PLANET_DEFEATED_D] = "Vase planeta prihodne nazvana \"[planet_name]\" v sektoru [sector] byla po bitve obsazena kapitanem zvanym [name]. Nastesti velka loajalita tamejsich obyvatel zabranila nepriteli ziskat planetu pod svou spravu. Statecni obyvatele zvolili radeji smrt nez podruci cizi nadvlady a celou planetu znicili. Naridil jste provest velkolepe pohrebni obrady pro tyto statecne obyvatele.";
$l_log_title[LOG_PLANET_DEFEATED_D] = "<font color=yellow>Planeta znicena</font>";
$l_log_text[LOG_PLANET_DEFEATED] = "Vase planeta [planet_name] v sektoru [sector] byla po bitve obsazena bidakem zvanym tez [name]. Obyvatele privitali noveho vladce. Na BNN jste videl i dukazy: \"Jsme stastni, ze jsme se zbavili toho stareho paprdy! Nestojime o tu ztracenou existenci, ktera nas nedokazala chranit!\". Prisahal jste, ze za tyhle drzosti Vam jeste zaplati.";
$l_log_title[LOG_PLANET_DEFEATED] = "<font color=red>Planeta obsazena nepritelem!</font>";
$l_log_text[LOG_PLANET_NOT_DEFEATED] = "Na Vasi planetu [planet_name] v sektoru [sector] zautocil [name]. Obyvatelstvo zorganizovalo obranu a znicilo utocnika. Z trosek jeho lodi navic bylo ukoristeno: [goods] zbozi, [ore] rudy, [organics] potravin a prodej [salvage]% hodnotnych trosek lode Vam vydelal [credits] krreditu.";
$l_log_title[LOG_PLANET_NOT_DEFEATED] = "Vitezstvi!";
$l_log_title[LOG_RAW] = "Poznamka";
$l_log_text[LOG_TOLL_RECV] = "Vasi stihaci v sektoru [sector] vybrali \"dan\" ve vysi [toll] kreditu.";
$l_log_title[LOG_TOLL_RECV] = "Prijem z vypalneho";
$l_log_text[LOG_DEFS_DESTROYED] = "[quantity] [type] bylo zniceno v sektoru [sector].";
$l_log_title[LOG_DEFS_DESTROYED] = "Obrana sektoru byla znicena";
$l_log_text[LOG_PLANET_EJECT] = "Byl jste vyhosten z planety v sektoru [sector], protoze kapitan [name] opustil alianci.";
$l_log_title[LOG_PLANET_EJECT] = "Vyhosteni!";
$l_log_text[LOG_BADLOGIN] = "Byl zaznamenam neuspesny pokus o prihlaseni do systemu z adresy [ip].";
$l_log_title[LOG_BADLOGIN] = "Neuspesny pokus o prihlaseni";
$l_log_text[LOG_PLANET_SCAN] = "[name] provedl senzoricky pruzkum Vasi planety [planet_name] v sektoru [sector].";
$l_log_title[LOG_PLANET_SCAN] = "Planeta zkoumana sensory";
$l_log_text[LOG_PLANET_SCAN_FAIL] = "[name] se pokusil o senzoricky pruzkum Vasi planety [planet_name] v sektoru [sector], ale neuspel.";
$l_log_title[LOG_PLANET_SCAN_FAIL] = "Neuspesny pokus o senzoricky pruzkum planety";
$l_log_text[LOG_SHIP_SCAN] = "[player] provedl senzoricky pruzkum Vasi lode.";
$l_log_title[LOG_SHIP_SCAN] = "Senzoricky pruzkum lode";
$l_log_text[LOG_SHIP_SCAN_FAIL] = "[player] se pokusil o senzoricky pruzkum Vasi lode, ale neuspel.";
$l_log_title[LOG_SHIP_SCAN_FAIL] = "Neuspesny pokus o senzoricky pruzkum lode";
$l_log_text[LOG_FURANGEE_ATTACK] = "Utoci [player]...";
$l_log_title[LOG_FURANGEE_ATTACK] = "Utok";
$l_log_text[LOG_STARVATION] = "Jedna z Vasich planet v sektoru [sector] nemuze uzivit obyvatelstvo! Je treba vice potravin. [starvation] kolonistu zemrelo hlady.";
$l_log_title[LOG_STARVATION] = "<font color=yellow>Hladomor!</font>";
$l_log_text[LOG_TOW] = "Vase lod byla odvlecena ze sektoru [sector] do sektoru [newsector], protoze velikost trupu lode presahla maximum ([hull]) povolene pro tento sektor.";
$l_log_title[LOG_TOW] = "Odvleceni!";
$l_log_text[LOG_DEFS_DESTROYED_F] = "Znicil jste [fighters] hlidkujicich stihacu v sektoru [sector].";
$l_log_title[LOG_DEFS_DESTROYED_F] = "Stihaci zniceni";
$l_log_text[LOG_DEFS_KABOOM] = "Vase lod byla znicena utokem stihacu v sektoru [sector]. ";
$l_log_title[LOG_DEFS_KABOOM] = "<font color=red>Lod znicena!</font>";
$l_log_text[LOG_HARAKIRI] = "Uz jste byl unaven rizenim teto kosmicke barky, takze jste se rozhodl, ze vesmiru bude trochu lepsi, kdyz ho opustite. Autorizovano adresou [ip].";
$l_log_title[LOG_HARAKIRI] = "<font color=red>Sebezniceni!</font>";
$l_log_text[LOG_TEAM_REJECT] = "[player] odmitl pozvani ke clenstvi v Vasi alianci [teamname].";
$l_log_title[LOG_TEAM_REJECT] = "Pozvani odmitnuto";
$l_log_text[LOG_TEAM_RENAME] = "Prejmenoval jste Vasi alianci na [team].";
$l_log_title[LOG_TEAM_RENAME] = "Aliance zmenila jmeno";
$l_log_text[LOG_TEAM_M_RENAME] = "Koordinator Vasi aliance zmenil jeji jmeno na [team].";
$l_log_title[LOG_TEAM_M_RENAME] = "Aliance zmenila jmeno";
$l_log_text[LOG_TEAM_KICK] = "Byl jste vyhosten z aliance [team].";
$l_log_title[LOG_TEAM_KICK] = "Vyhosteni z aliance!";
$l_log_text[LOG_TEAM_CREATE] = "Zalozil jste novou alianci s nazvem [team].";
$l_log_title[LOG_TEAM_CREATE] = "Zalozeni nove aliance";
$l_log_text[LOG_TEAM_LEAVE] = "Opustil jste alianci [team].";
$l_log_title[LOG_TEAM_LEAVE] = "Opusteni aliance";
$l_log_text[LOG_TEAM_NEWLEAD] = "Opustil jste alianci [team]. Vedeni aliance po Vas prevzal kapitan [name].";
$l_log_title[LOG_TEAM_NEWLEAD] = "Opusteni aliance";
$l_log_text[LOG_TEAM_LEAD] = "Koordinator aliance [team] s erozhodl tuto alianci opustit. Byl jste vybran, abyste ho nahradil v jeho funkci.";
$l_log_title[LOG_TEAM_LEAD] = "Povyseni!";
$l_log_text[LOG_TEAM_JOIN] = "Pripojil jste se k alianci [team].";
$l_log_title[LOG_TEAM_JOIN] = "Pripojeni k alianci";
$l_log_text[LOG_TEAM_NEWMEMBER] = "[name] se stal novym clenem aliance [team]. Zase jste o krok blize k vlade nad celoou galaxii.";
$l_log_title[LOG_TEAM_NEWMEMBER] = "Novy clen v alianci";
$l_log_text[LOG_TEAM_INVITE] = "Obdrzel jste pozvani ke clenstvi v alianci [team].";
$l_log_title[LOG_TEAM_INVITE] = "Pozvanka";
$l_log_text[LOG_TEAM_NOT_LEAVE] = "[player] opustil Vasi alianci.";
$l_log_title[LOG_TEAM_NOT_LEAVE] = "Aliance ztratila clena";
$l_log_text[LOG_ADMIN_HARAKIRI] = "[player] provedel sebezniceni z adresy [ip].";
$l_log_title[LOG_ADMIN_HARAKIRI] = "Sebezniceni";
$l_log_text[LOG_ADMIN_ILLEGVALUE] = "[player] ma [quantity] [type], s max [holds] skladovych bunek";
$l_log_title[LOG_ADMIN_ILLEGVALUE] = "Neplatna hodnota lodi";
$l_log_text[LOG_ADMIN_PLANETDEL] = "[attacker] se pokusil obsadit planetu kapitana zvaneho [defender] v sektoru [sector]. Neuspel, protoze plameta byla znicena.";
$l_log_title[LOG_ADMIN_PLANETDEL] = "Planeta znicena";
$l_log_text[LOG_DEFENCE_DEGRADE] = "Ucinnost stihacu branicich sektor [sector] se snizila o [degrade]% kvuli nedostatku energie.";
$l_log_test[LOG_DEFENCE_DEGRADE] = "Obrana sektoru snizena.";

// modify-defences.php

$l_md_title		 = "Obrana sektoru";
$l_md_invalid		 = "Nespravna obrana sektoru";
$l_md_nolonger		 = "Zvolena obrana sektoru zde jiz neni.";
$l_md_you		 = "you";
$l_md_bmines		 = "Vase lasery byly zniceny";
$l_md_msgdownerb	 = "[name] znicil [mines] min v sektoru [sector].";
$l_md_retr		 = "You retrieved";
$l_md_mode		 = "Zvoleni stihaci presly do rezimu \"[mode]\".";
$l_md_consist		 = "Obrana tohoto sektoru sestava z [qty] [type] kapitana zvaneho [owner].";
$l_md_youcan		 = "Muzete";
$l_md_retrieve		 = "Obnovit (retrieve)";
$l_md_change		 = "Zmenit nastaveni stihacu";
$l_md_cmode		 = "Rezim stihacu";
$l_md_attack		 = "Utok";
$l_md_toll		 = "Vypalne";
$l_md_attdef		 = "Byl detekovan utok na sektor. Vsichni stihaci se ucastni obrany.(???or this is a message when setting was changed???)";
$l_md_noturn	  	 = "Potrebujete alespon jeden tah.";
$l_md_nothere            = "Musite byt ve stejnem sektoru jako sektorova obrana.";
$l_md_notyours           = "Akce zamitnuta. Obrana v tomto sektoru nepatri k Vasim jednotkam.";
$l_md_yours              = "Nemuzete zautocit na svoje vlastni obranne jednotky.";

// news.php

$l_news_title		 = "Novinky ve vesmiru BlackNova (Blacknova News - BNN)";
$l_news_info		 = "BNN patri mezi hlavni zpravodajske agentury<br>
                            zamerene na novinky a informace.<br>
                            Funguje  24 hodin, sedm dni v tydnu<br>
                            prostrednictvim zamestancu v centrale BNN<br>
                            na Alpha Centauri a zvlastnich zpravodaju po cele galaxii!";
$l_news_for		 = "Zpravy";
$l_news_prev		 = "predchozi den";
$l_news_next		 = "nasledujici den";
$l_news_none		 = "Omlouvame se, ale dnes nejsou zadne zpravy.";
$l_news_flash		 = "Bleskove zpravy";

// dump.php

$l_dump_title		 = "Vylozeni kolonistu";
$l_dump_turn		 = "Pro vylozeni kolonistu je treba alespon jeden tah.";
$l_dump_nocol		 = "Na sve lodi nemate zadne kolonisty, ktere byste mohl vylozit.";
$l_dump_dumped		 = "Koloniste byly vylozeni blizko skladiste.";
$l_dump_nono		 = "Musite byt blizko skladiste, abyste mohl vylozit kolonisty.";

// readmail.php

$l_readm_title		 = "Cteni zpravy";

$l_readm_delete		 = "ZPRAVA VYMAZANA";
$l_readm_nomessage	 = "Nemate zadne zpravy...";
$l_readm_center		 = "Stredisko prijmu zprav";
$l_readm_sender		 = "Odesilatel";
$l_readm_captn		 = "Kapitan lodi";
$l_readm_del		 = "Smazat";
$l_readm_repl		 = "Odpovedet";

// mailto2.php

$l_sendm_title		 = "Odeslani zpravy";
$l_sendm_to		 = "Pro";
$l_sendm_from		 = "Od";
$l_sendm_ally		 = "Aliance:";
$l_sendm_subj		 = "Predmet";
$l_sendm_mess		 = "Zprava";
$l_sendm_send		 = "Odeslat";
$l_sendm_sent		 = "Zprava odeslana";

// zoneinfo.php

$l_zi_title		 = "Informace o zone";
$l_zi_nexist		 = "Tato cast vesmiru neexistuje!";
$l_zi_feds		 = "Federace";
$l_zi_traders		 = "Koalice volneho obchodu";
$l_zi_nobody		 = "Nikdo";
$l_zi_war		 = "Prostor pro konkurencni boj";
$l_zi_allow		 = "Mozne";
$l_zi_notallow		 = "Nemozne";
$l_zi_limit		 = "Omezeno na vlastnika a alianci";
$l_zi_ul		 = "Neomezeno";
$l_zi_control		 = "Jste v dozorni rade teto zony";
$l_zi_tochange		 = "muzete zmenit jeji zakony.";
$l_zi_owner		 = "Vlastnik zony";
$l_zi_maxhull		 = "Maximalni povolena velikost trupu lode";

// zoneedit.php

$l_ze_title		 = "Editace zony";
$l_ze_notowner		 = "Nejste vlastnikem teto zony, takze ji nemuzete editovat.";
$l_ze_name		 = "Nazev zony";
$l_ze_allow		 = "Mozne";
$l_ze_attacks		 = "Je mozne utocit na ostatni lode";
$l_ze_genesis		 = "Je mozne vytvaret nove planety";
$l_ze_return		 = "zpet na stranku informaci o zone";
$l_ze_saved		 = "Vase zmeny byly ulozeny.";

// teams.php

$l_team_title		 = "Aliance";
$l_team_menu		 = "zpet do menu aliance";
$l_team_galax		 = "Aliance v galaxii:";
$l_team_members		 = "Clenove";
$l_team_coord		 = "Koordinator";
$l_team_member		 = "Clen";
$l_team_noinvite	 = "Nikdo Vas nepozval, abyste se stal clenem nejake aliance.";
$l_team_ifyouwant	 = "Pokud se chcete stat clenem nejake aliance, poslete zpravu jejimu koordinatorovi, aby Vas do aliance pozval.";
$l_team_tocreate	 = "pro zalozeni nove aliance.";
$l_team_injoin		 = "Jste zvan, abyste se pripojil k alianci ";
$l_team_tojoin		 = "pripojit";
$l_team_or		 = "nebo";
$l_team_reject		 = "odmitnout pozvani.";
$l_team_ed		 = "Zmenit";
$l_team_inv		 = "Pozvat";
$l_team_leave		 = "Opustit";
$l_team_eject		 = "Vyloucit";
$l_team_pending		 = "Neodpovezena pozvani pro";
$l_team_noinvites	 = "Nikdo nebyl pozvan aby se pripojil do aliance";
$l_team_confirmleave	 = "Skutecne chcete opustit alianci";
$l_team_onlymember	 = "Jste poslednim (jedinym) clenem aliance [team_name], ktera timto zanika.";
$l_team_youarecoord	 = "Jste koordinatorem aliance";
$l_team_relinq		 = "Musite se vzdat Vasi role ve prospech jineho hrace.";
$l_team_newc		 = "Novy koordinator:";
$l_team_youveleft	 = "Opustil jste alianci";
$l_team_relto		 = "Vzdat se funkci koordinatora ve prospech ";
$l_team_welcome		 = "Vitejte v alianci";
$l_team_noinviteto	 = "Nebyl jste pozvan do teto skupiny.";
$l_team_ejectsure	 = "Skutecne chcete z aliance vyloucit";
$l_team_ejected 	 = "byl vyloucen z aliance!";
$l_team_testing		 = "Faze testovani...";
$l_team_pw		 = "Heslo";
$l_team_entername	 = "Zvolte jmeno pro alianci";
$l_team_enterdesc	 = "Zadejte popis aliance";
$l_team_hcreated	 = "byla vytvorena a Vy jste jejim sefem";
$l_team_alliance	 = "Aliance";
$l_team_selectp		 = "Vyberte, ktereho hrace chcete pozvat";
$l_team_isorry		 = "Omlouvam se, ale [name] uz obdrzel pozvani do nejake aliance - jen jedno pozvani muze byt zaslano";
$l_team_plinvted	 = "Hrac byl pozvan.<BR>Musite pockat, dokud hrac neprijme Vase pozvani.";
$l_team_refuse		 = "Zrusil jste pozvani k pripojeni do aliance";
$l_team_edname		 = "Zmente nazev Vasi aliance";
$l_team_eddesc		 = "Zmente popis Vasi aliance";
$l_team_hasbeenr	 = "byla prejmenovana.";
$l_team_error		 = "<b><font color=red>Nastala chyba</font></b><br>Nejste sefem teto aliance.";
$l_team_notmember	 = "Nejste clenem zadne aliance";
$l_team_urejected	 = "<B>UPOZORNENI</B> - byl jste vyloucen z aliance";
$l_team_noalliances	 = "V tento okamzik v galaxii neexistuji zadne aliance.";

// ranking.php

$l_ranks_title		 = "Nejlepsich $max_rank hracu";
$l_ranks_none		 = "Zadne vysledky k zobrazeni.";
$l_ranks_pnum		 = "Celkovy pocet hracu";
$l_ranks_dships		 = "Hraci se znicenymi lodemi nejsou zapocitavani.";
$l_ranks_rank		 = "Hodnoceni";
$l_ranks_lastlog	 = "Naposled prihlasen";
$l_ranks_good		 = "Buh";
$l_ranks_evil		 = "Dabel";

// beacon.php

$l_beacon_title		 = "Vypusteni kosmickeho majaku";
$l_beacon_notpermitted	 = "Vypousteni kosmickych majaku v tomto sektoru neni dovoleno.";
$l_beacon_reads		 = "Soucasny majak hlasi";
$l_beacon_none		 = "V soucasnosti neni v tomto sektoru zadny majak.";
$l_beacon_enter		 = "Zadejte text pro majak";
$l_beacon_nowreads	 = "Majak nyni hlasi";
$l_beacon_donthave	 = "Nemate zadny kosmicky majak.";

// emerwarp.php

$l_ewd_title		 = "Pouzit nouzove Warp zarizeni";
$l_ewd_used		 = "Nouzove Warp zarizeni bylo spusteno - prilet do sektoru [sector].";
$l_ewd_none		 = "Nemate zadne nouzove Warp zarizeni.";

// defence-report.php

$l_sdf_title		 = "Hlaseni obrany sektoru";
$l_sdf_none		 = "V tomto sektoru jste nevypustil zadnou obranu.";
$l_sdf_type		 = "Typ";
$l_sdf_mode		 = "Rezim";

// traderoute.php
// cause its rather big i put everything in own vars than to re-use
// the old ones so we could export to own file if performance problems
// should occur

$l_tdr_title    	 = "Obchodni cesty";
$l_tdr_newtdr   	 = "Zde muzete vytvorit <a href=\"traderoute.php?command=new\">novou obchodni cestu</a>";
$l_tdr_modtdrset         = "Zde muzete zmenit <a href=\"traderoute.php?command=settings\">globalni obchodni nastaveni</a>";
$l_tdr_confdel  	 = "Potvrdte <a href=\"traderoute.php?command=delete&confirm=yes&traderoute_id=[tdr_id]\">zruseni</a> nasledujici obchodni cesty :";
$l_tdr_noactive 	 = "Nemate zadne aktivni obchodni cesty.";
$l_tdr_curtdr   	 = "Vase obchodni cesty";
$l_tdr_deltdr   	 = "Zrusit obchodni cestu";
$l_tdr_src      	 = "Zdroj";
$l_tdr_srctype  	 = "Typ zdroje";
$l_tdr_dest     	 = "Cil";
$l_tdr_desttype 	 = "Typ cile";
$l_tdr_move     	 = "Presun";
$l_tdr_circuit  	 = "Okruh";
$l_tdr_change   	 = "Akce";
$l_tdr_portin   	 = "Brana v";
$l_tdr_planet   	 = "Planeta";
$l_tdr_nonexistance      = "Neexistujici planeta!";
$l_tdr_na       	 = "---";
$l_tdr_cargo    	 = "Naklad";
$l_tdr_none     	 = "Zadny";
$l_tdr_colonists         = "Koloniste";
$l_tdr_fighters 	 = "Stihacky";
$l_tdr_torps    	 = "Torpeda";
$l_tdr_escooped 	 = "[tdr_dist_triptime] tahu<br>[tdr_dist_scooped] energie ziskano";
$l_tdr_warp     	 = "Warp";
$l_tdr_turns    	 = "tahu";
$l_tdr_way      	 = "cesta";
$l_tdr_ways     	 = "cesty";
$l_tdr_edit     	 = "Zmenit";
$l_tdr_del      	 = "Zrusit";
$l_tdr_nowlink1 	 = "Neexistuje warpove spojeni ze sektoru [tdr_src_sector_id] do sektoru [tdr_dest_sector_id]";
$l_tdr_nowlink2 	 = "Neexistuje warpove spojeni ze sektoru [tdr_dest_sector_id] do sektoru [tdr_src_sector_id]";
$l_tdr_sportissrc        = "Pokud je zdrojem zvlastni brana, musi byt cilem pro kolonizaci planeta.";
$l_tdr_notownplanet      = "Nemuzete kolonizovat planetu, kterou nevlastnite Vy nebo Vas tym.";
$l_tdr_planetisdest      = "Planeta muze byt cilem pouze kdyz zdroj je zvlastni brana.";
$l_tdr_samecom 		 = "Nemuzete sestavit obchodni cestu pro brany, ktere nabizeji stejne zbozi.";
$l_tdr_sportcom 	 = "Nemuzete prodavat zbozi z planety ve zvlastni brane.";
$l_tdr_editerr  	 = "Chyba editace : obchodni cesta nebyla nalezena v databazi";
$l_tdr_maxtdr   	 = "Dosahl jste maximalniho mozneho poctu obchodnich cest.";
$l_tdr_createnew         = "Vytvorit novou";
$l_tdr_editinga 	 = "Zmenit";
$l_tdr_traderoute        = "obchodni cestu";
$l_tdr_unnamed  	 = "Bezejmena";
$l_tdr_cursector         = "Prave jste v sektoru";
$l_tdr_selspoint         = "Zvolte vychozi bod :";
$l_tdr_port     	 = "Brana";
$l_tdr_insector 	 = "v sektoru";
$l_tdr_selendpoint       = "Zvolte cilovy bod";
$l_tdr_selmovetype       = "Zvolte zpusob presunu";
$l_tdr_realspace         = "Realny vesmir";
$l_tdr_selcircuit        = "Zvolte okruh";
$l_tdr_oneway   	 = "Jednosmerna";
$l_tdr_errnotvalidport   = "Chyba : zdrojova brana [tdr_port_id] nevypada jako platna.";
$l_tdr_bothways 	 = "Obousmerna";
$l_tdr_create   	 = "Create";
$l_tdr_modify   	 = "Zmenit";
$l_tdr_returnmenu        = "Zpet do <a href=traderoute.php>menu obchodnich cest</a>.";
$l_tdr_errnotvalidport   = "Chyba : zdrojova brana [tdr_port_id] neni platnou branou.";
$l_tdr_errnoport         = "Chyba : v sektoru [tdr_port_id] neni zadna brana.";
$l_tdr_errnosrc    	 = "Chyba : zadana zdrojova planeta neexistuje.";
$l_tdr_errnotownnotsell  = "Chyba : nevlastnite planetu [tdr_source_name] v sektoru [tdr_source_sector_id] a planeta neprodava.";
$l_tdr_errnotvaliddestport= "Chyba : cilova brana [tdr_port_id] neni platnou branou.";
$l_tdr_errnoport2        = "Chyba : v sektoru [tdr_port_id] neni zadna brana.";
$l_tdr_errnodestplanet   = "Chyba : zadana cilova planeta neexistuje.";
$l_tdr_errnotownnotsell2 = "Chyba : nevlastnite planetu [tdr_dest_name] v sektoru [tdr_dest_sector_id] a planeta neprodava.";
$l_tdr_newtdrcreated     = "Nova obchodni cesta byla vytvorena!";
$l_tdr_tdrmodified       = "Obchodni cesta byla zmenena!";
$l_tdr_doesntexist       = "Tato obchodni cesta neexistuje!";
$l_tdr_notowntdr         = "Tato obchodni cesta Vam nepatri!";
$l_tdr_tdrdeleted        = "Obchodni cesta byla zrusena.";
$l_tdr_globalset         = "Globalni nastaveni obchodnich cest";
$l_tdr_tdrsportsrc       = "Pro obchodni cesty, kde je zdrojem zvlastni brana, obchodovat";
$l_tdr_tdrescooped       = "Pro obchodni cesty, ktere vedou realnym vesmirem, jak chcete nalozit se ziskanou energii?";
$l_tdr_trade    	 = "Obchodovat";
$l_tdr_keep    	 	 = "Drzet";
$l_tdr_save    	 	 = "Ulozit";
$l_tdr_globalsetsaved    = "Globalni nastaveni obchodnich cest ulozeno.";
$l_tdr_engagenonexist    = "Pokousite se pouzit neexistujici obchodni cestu!";
$l_tdr_invalidspoint     = "Startovni brana nevypada jako platna!";
$l_tdr_inittdr  	 = "Nejste v sektoru [tdr_source_id]! Musite byt ve vychozim sektoru obchodni cesty, abyste se na ni mohli vydat!";
$l_tdr_invalidsrc        = "Zdrojova planeta nevypada jako platna!";
$l_tdr_inittdrsector     = "Nejste v sektoru [tdr_source_sector_id]! Musite byt ve vychozim sektoru obchodni cesty, abyste se na ni mohli vydat!";
$l_tdr_notyourplanet     = "Nejste vlastnikem planety [tdr_source_name] v sektoru [tdr_source_sector_id]!";
$l_tdr_invalidssector    = "Vychozi sektoru nevypada jako platny!";
$l_tdr_invaliddport      = "Cilova brana nevypada jako platna!";
$l_tdr_invaliddplanet    = "Cilova planeta nevypada jako platna!";
$l_tdr_invaliddsector    = "Cilovy sektor nevypada jako platny!";
$l_tdr_moreturnsneeded   = "Pro vykonani teto obchodni cesty je treba [tdr_dist_triptime] tahu. Ale Vy mate pouze [tdr_playerinfo_turns] tahu.";
$l_tdr_tdrhostdef        = "Nemuzete pouzit obchodni cesty mezi sektory s nepratelskou obranou. Musite tuto obranu nejprve odstranit.";
$l_tdr_globalsetbuynothing= "Vase globalni nastaveni je nastaveno tak, ze nic nekupujete! Touto obchodni cestou pouze ztratite tahy!";
$l_tdr_nosrcporttrade    = "Obchodovani ze zdrojove brany neni dovoleno.";
$l_tdr_tradesrcportoutsider= "Obchodovani ve zdrojove brane neni cizincum dovoleno";
$l_tdr_nodestporttrade   = "Obchodovani z cilove brany neni dovoleno.";
$l_tdr_tradedestportoutsider= "Obchodovani v cilove brane neni cizincum dovoleno";
$l_tdr_tdrres  		 = "Hlaseni o obchodni ceste";
$l_tdr_bought  		 = "Nakoupeno";
$l_tdr_nothingtotrade    = "Nic na prodej";
$l_tdr_sold   	  	 = "Prodano";
$l_tdr_ore    		 = "Ruda";
$l_tdr_portisfull        = "Brana je zaplnena";
$l_tdr_goods    	 = "zbozi";
$l_tdr_organics 	 = "potravin";
$l_tdr_energy   	 = "energie";
$l_tdr_portisempty       = "Brana je prazdna";
$l_tdr_loaded   	 = "Nalozeno";
$l_tdr_nothingtoload     = "Nic k nalozeni";
$l_tdr_scooped  	 = "Nabrano";
$l_tdr_dumped   	 = "Vylozeno";
$l_tdr_planetisovercrowded= "Planeta je preplnena";
$l_tdr_nothingtodump     = "Nic k vylozeni";
$l_tdr_onlyonewaytdr     = "Nic, obchodni cesta byla jen jednosmerna";
$l_tdr_profit 		 = "Zisk";
$l_tdr_cost   		 = "Cena";
$l_tdr_totalprofit       = "Celkovy zisk";
$l_tdr_totalcost         = "Celkova cena";
$l_tdr_credits  	 = "Kreditu";
$l_tdr_turnsused         = "Pouzito tahu";
$l_tdr_turnsleft         = "Zbylo tahu";
$l_tdr_engageagain       = "A kliknutim zde se muzete <A HREF=\"traderoute.php?engage=[tdr_engage]\">vydat na stejnou cestu znovu</A>.";

// IGB.php

$l_igb_title    = "Intergalakticka banka";
$l_igb_malfunction      = "Tento IGB terminal nefunguje. Intergalakticka banka se Vam omlouva za zpusobene potize.";
$l_igb_quit     = "Konec";
$l_igb_login    = "Prihlasit";
$l_igb_welcometoigb     = "Vita Vas Terminal Intergalakticke banky";
$l_igb_accountholder    = "Vlastnik uctu";
$l_igb_shipaccount      = "Lodni ucet";
$l_igb_igbaccount       = "Ucet IGB";
$l_igb_operations       = "Operace";
$l_igb_withdraw = "Splatit";
$l_igb_deposit  = "Ulozit";
$l_igb_transfer = "Prevest";
$l_igb_back     = "Zpatky";
$l_igb_logout   = "Odhlasit";
$l_igb_withdrawfunds    = "Splatit penize";
$l_igb_fundsavailable   = "Penize k dispozici";
$l_igb_selwithdrawamount        = "Kolik chcete splatit";
$l_igb_depositfunds     = "Ulozit penize";
$l_igb_seldepositamount = "Kolik si chcete ulozit";
$l_igb_transfertype     = "Zpusob prevodu";
$l_igb_toanothership    = "Na jinou lod";
$l_igb_shiptransfer     = "Lodni prevod";
$l_igb_fromplanet       = "Z jedne planety na jinou";
$l_igb_unnamed  = "Bezejmena";
$l_igb_in       = "v";
$l_igb_none     = "Nic";
$l_igb_destination      = "Cil";
$l_igb_planettransfer   = "Planetarni prevod";
$l_igb_sendyourself     = "Nemuzete poslat penize sami sobe!";
$l_igb_unknowntargetship        = "Neznama cilova lod!";
$l_igb_min_turns        = "Kapitan [igb_target_char_name] musi mit odehrano alespon [igb_min_turns] tahu, nez muze ziskat penize.";
$l_igb_min_turns2       = "Musite mit odehrano alespon [igb_min_turns] tahu nez muzete zacit posilat penize.";
$l_igb_mustwait = "Uz jste provedl prevod na [igb_target_char_name] v poslednich [igb_trate] minutach. Musite pockat jeste [igb_difftime] minut nez budete moci prevest penize tomuto kapitanovi znovu.";
$l_igb_maxtransfer      = "Maximalni mozny prevod";
$l_igb_unlimited        = "Neomezeno";
$l_igb_maxtransferpercent       = "Nejvyssi mozny prevod ([igb_percent]% ciste hodnoty)";
$l_igb_recipient        = "Prijemce";
$l_igb_seltransferamount        = "Kolik chcete prevest";
$l_igb_transferrate     = "Aktualni sazba za prevod je [igb_num_percent]% z celkove hodnoty. Bude automaticky vypoctena z prevadene castky.";
$l_igb_errplanetsrcanddest      = "Stejna planeta nemuze byt zaroven zdrojem i cilem.";
$l_igb_errunknownplanet = "Databazova chyba! Neznama planeta!";
$l_igb_errnotyourplanet = "Nemuzete prevadet penize z/na planetu, kterou nevlastnite.";
$l_igb_srcplanet        = "Zdroj -> Planeta";
$l_igb_destplanet       = "Cil -> Planeta";
$l_igb_transferrate2     = "Aktualni sazba za prevod je [igb_num_percent]% z celkove hodnoty. Bude automaticky vypoctena z prevadene castky.";
$l_igb_errsendyourself  = "Nemuzete poslat penize sam sobe!";
$l_igb_min_turns3        = "Kapitan [igb_target_char_name] musi mit odehrano alespon [igb_min_turns] tahu, nez muze prijimat penize.";
$l_igb_min_turns4       = "Musite mit odehrano alespon [igb_min_turns] tahu, nez muzete posilat penize.";
$l_igb_mustwait2 = "Uz jste provedl prevod na [igb_target_char_name] v poslednich [igb_trate] minutach. Musite pockat jeste [igb_difftime] minut nez budete moci prevest penize tomuto kapitanovi znovu.";
$l_igb_invalidtransferinput     = "Chybny vklad pro prevod.";
$l_igb_nozeroamount     = "Prevadana castka nemuze but nulova.";
$l_igb_notenoughcredits = "Nemate dostatek kreditu pro provedeni teto operace.";
$l_igb_amounttoogreat   = "Castka, kterou jste zadal je vyssi nez mamimalni mozna castka pro prevod.";
$l_igb_transfersuccessful       = "Prevod byl uspesne proveden";
$l_igb_creditsto        = "kredity byly prevedeny na";
$l_igb_transferamount   = "Prevedena castka";
$l_igb_transferfee      = "Poplatek za prevod";
$l_igb_amounttransferred        = "Prevedena castka";
$l_igb_notenoughcredits2        = "Na zdrojove planete neni dostatek kreditu pro provedeni teto transakce.";
$l_igb_to       = "do";
$l_igb_ctransferredfrom = "kredity byly prevedeny od ";
$l_igb_invaliddepositinput      = "Chybny vstup pro vklad.";
$l_igb_nozeroamount2    = "Vyska vkladu nemuze byt nulova.";
$l_igb_operationsuccessful      = "Operace byla uspesne provedena";
$l_igb_creditstoyou     = "Kredity byly prevedeny na Vas IGB ucet.";
$l_igb_accounts = "Ucty";
$l_igb_invalidwithdrawinput     = "Chybny vstup pro splatku.";
$l_igb_nozeroamount3    = "Vyse splatky nemuze byt nulova.";
$l_igb_creditstoyourship        = "Kredity byly prevedeny na ucet Vasi lodi.";
$l_igb_igberrreport     = "IGB Hlazeni o chybe";
$l_igb_source   = "Zdroj";

// combat.php

$l_cmb_atleastoneturn   = "Pro utok na planetu potrebujete alespon jeden tah.";
$l_cmb_shipenergybb     = "Energie lodi pred pouzitim laseru";
$l_cmb_shipenergyab     = "Energie lodi po pouziti laseru";
$l_cmb_shipenergyas     = "Energie lodi spotrebovana do stitu";
$l_cmb_shiptorpsbtl     = "Torpeda na lodi pre vypustenim";
$l_cmb_shiptorpsatl     = "Torpeda na lodi po vypusteni";
$l_cmb_planettorpdamage = "Poskozeni planetarnimi torpedy";
$l_cmb_attackertorpdamage       = "Poskozeni utocnikovymi torpedy";
$l_cmb_beams    = "Lasery";
$l_cmb_fighters = "Stihaci";
$l_cmb_shields  = "Stity";
$l_cmb_torps    = "Torpeda";
$l_cmb_torpdamage       = "Poskozeni torpedy";
$l_cmb_armor    = "Pancerovani";
$l_cmb_you      = "Vase lod";
$l_cmb_planet   = "Planeta";
$l_cmb_combatflow       = "Prubeh boje";
$l_cmb_defender = "Obrance";
$l_cmb_attackingplanet  = "Zautocil jste na planetu v sektoru";
$l_cmb_youfireyourbeams = "Vase lod vypalila z laserovych del";
$l_cmb_defenselost      = "Vystrely z Vasich laserovych del ztratila planetarni obrana [cmb_planetfighters] stihacu";
$l_cmb_defenselost2     = "Planetarni obrana ztratila [cmb_attackerbeams] stihacu, ale dalsi priletaji!";
$l_cmb_planetarybeams   = "Lasery vypalene z planety znicili [cmb_temp] Vasich stihacu";
$l_cmb_planetarybeams   = "Planetarni lasery znicili [cmb_planetbeams] Vasich stihacu";
$l_cmb_youdestroyedplanetshields        = "Vase lasery znicili planetarni stity";
$l_cmb_beamsexhausted   = "Stacil jste znicit [cmb_attackerbeams] planetarnich stitu predtim, nez se Vase lasery pretizili.";
$l_cmb_breachedyourshields      = "Planetarni lasery prorazili Vase stity";
$l_cmb_destroyedyourshields     = "Planetarni lasery znicili [cmb_planetbeams] Vasich stitu";
$l_cmb_breachedyourarmor        = "Planetarni lasery prorazili pancerovani Vasi lodi";
$l_cmb_destroyedyourarmor       = "Planetarni lasery poskodili [cmb_planetbeams] pancerovani Vasi lodi";
$l_cmb_torpedoexchangephase     = "Faze vypousteni torped";
$l_cmb_nofightersleft   = "Vase torpeda znicila [cmb_planetfighters] planetarnich stihacu. Planeta zustala bez stihacu.";
$l_cmb_youdestroyfighters       = "Vase torpeda znicila [cmb_attackertorpdamage] planetarnich stihacu";
$l_cmb_planettorpsdestroy       = "Planetarni torpeda znicila [cmb_temp] Vasich stihacu";
$l_cmb_planettorpsdestroy2      = "Planetarni torpeda znicila [cmb_planettorpdamage] Vasich stihacu";
$l_cmb_torpsbreachedyourarmor   = "Planetarni torpeda prorazila pancerovani Vasi lodi";
$l_cmb_planettorpsdestroy3      = "Planetarni torpeda znicila [cmb_planettorpdamage] pancerovani Vasi lodi";
$l_cmb_youdestroyedallfighters  = "Vase torpeda znicila vsechny planetarni stihace";
$l_cmb_youdestroyplanetfighters = "Vase torpeda znicila [cmb_attackertorpdamage] planetarnich stihacu";
$l_cmb_fightercombatphase       = "Souboj stihacu";
$l_cmb_youdestroyedallfighters2  = "Vasi stihaci znicili vsechny planetarni stihace.";
$l_cmb_youdestroyplanetfighters2        = "Vasi stihaci znicili [cmb_attackerfighters] planetarnich stihacu";
$l_cmb_allyourfightersdestroyed = "Vsichni Vasi stihaci byli zniceni";
$l_cmb_fightertofighterlost     = "V soubojich stihacu jste ztratil [cmb_planetfighters] stihacu";
$l_cmb_youbreachedplanetshields = "Vasi stihaci prorazili planetarni stity";
$l_cmb_shieldsremainup  = "Vasi stihaci znicili [cmb_attackerfighters] planetarnich stitu, ale ty stale jeste drzi.";
$l_cmb_fighterswarm     = "Vyrojilo se mnoho planetarnich stihacu a prorazili pancerovani Vasi lodi";
$l_cmb_swarmandrepel    = "Vyrojilo se mnoho planetarnich stihacu, ale pancerovani Vasi lodi vydrzelo";
$l_cmb_engshiptoshipcombat      = "Souboj lode proti lodi.";
$l_cmb_shipdock = "V planetarnim doku se nachazi [cmb_shipsonplanet] lodi!";
$l_cmb_approachattackvector     = "prileta v utocne formaci";
$l_cmb_noshipsdocked    = "V planetarnim doku neni zadna lod.";
$l_cmb_yourshipdestroyed        = "Vase lod byla znicena!";
$l_cmb_escapepod        = "Nastesti jste unikl v unikove kapsli!";
$l_cmb_finalcombatstats = "Zaverecne vysledky boje";
$l_cmb_youlostfighters  = "Ztratil jste [cmb_fighters_lost] z [cmb_playerinfo_ship_fighters] stihacu.";
$l_cmb_youlostarmorpoints       = "Ztratil jste [cmb_armor_lost] z [cmb_playerinfo_armour_pts] pancerovani, zbyva Vam tedy [cmb_attackerarmor].";
$l_cmb_energyused       = "Na boj jste vycerpal [cmb_energy] energie z celkoveho mnozstvi [cmb_playerinfo_ship_energy].";
$l_cmb_planetdefeated   = "Planet byla dobita";
$l_cmb_citizenswanttodie        = "Obyvatele planety se rozhodli radeji zemrit, nez aby slouzili neschopnemu vladci jako jste Vy. Pouzitim silneho lasery z orbity planety udelali diru do planerarniho jadra. Mel jste uz jen cas pro utek na orbitu, nez se vsechno zmenilo na lavovou kouli.";
$l_cmb_youmaycapture    = "Muzete planetu <a href=planet.php?planet_id=[cmb_planetinfo_planet_id]&command=capture>obsadit</a> nebo ji nechat bez obrany.";
$l_cmb_youmaycapture2   = "Muzete planetu <a href=planet.php?planet_id=[cmb_planetinfo_planet_id]&command=capture>obsadit</a> nebo ji nechat bez obrany.";
$l_cmb_planetnotdefeated        = "Planeta se neubranila";
$l_cmb_planetstatistics = "Statistika planety";
$l_cmb_fighterloststat  = "Ztraceno stihacu: [cmb_fighters_lost] z [cmb_planetinfo_fighters] ([cmb_planetfighters] nazivu)";
$l_cmb_energyleft       = "Zbyva energie";
$l_cmb_startingstats    = "Vychozi stav";
$l_cmb_statattackerbeams        = "Attackerbeams";
$l_cmb_statattackerfighters     = "Attackerfighters";
$l_cmb_statattackershields      = "Attackershields";
$l_cmb_statattackertorps        = "Attackertorps";
$l_cmb_statattackerarmor        = "Attackerarmor";
$l_cmb_statattackertorpdamage   = "Attackertorpdamage";
$l_cmb_isattackingyou   = "na Vas utoci";
$l_cmb_beamexchange     = "Laserova palba";
$l_cmb_beamsdestroy     = "Vase lasery znicili [cmb_lost] nepratelskych stihacu";
$l_cmb_beamsdestroy2    = "Vase lasery znicili [cmb_attackerbeams] nepratelskych stihacu, ale dalsi prave priletaji";
$l_cmb_nobeamsareleft   = "Uz nemate zadne lasery, ktere by mohli palit na priletajici stihace!";
$l_cmb_beamshavenotarget        = "Vase lasery nemaji zadny cil, po kterem by mohli vypalit";
$l_cmb_fighterdestroyedbybeams  = "Lod [cmb_targetinfo_ship_name] znicila svymi lasery [cmb_lost] Vasich stihacu<BR>";
$l_cmb_beamsdestroystillhave    = "Lod [cmb_targetinfo_ship_name] znicila svymi lasery [cmb_targetbeams] Vasich stihacu, ale stale Vam jich jeste [cmb_attackerfighters] zustalo";
$l_cmb_fighterunhindered        = "Nepritel uz nema zadne lasery, ktery by mohli zabranit Vasim stihacum v utoku.";
$l_cmb_youhavenofightersleft    = "Nemate zadne stihace, ktere byste mohl poslat do utoku";
$l_cmb_breachedsomeshields      = "Prorazil jste stity lode [cmb_targetinfo_ship_name] Vasimi lasery";
$l_cmb_shieldsarehitbybeams     = "Stity lode [cmb_targetinfo_ship_name] byly zasazeny Vasimi lasery a poskozeny na [cmb_attackerbeams]";
$l_cmb_nobeamslefttoattack      = "Namete k dispozici lasery, ktere by mohli palit na stity lode [cmb_targetinfo_ship_name]";
$l_cmb_yourshieldsbreachedby    = "Lasery lode [cmb_targetinfo_ship_name] prorazili Vase stity";
$l_cmb_yourshieldsarehit        = "Lasery lode [cmb_targetinfo_ship_name] svym zasahem snizili ucinnost Vasich stitu na [cmb_targetbeams].";
$l_cmb_hehasnobeamslefttoattack = "Lod [cmb_targetinfo_ship_name] uz nema lasery, kterymi by mohla palit na Vase stity";
$l_cmb_yourbeamsbreachedhim     = "Palba z Vasich laseru prorazila pancerovani lode [cmb_targetinfo_ship_name]";
$l_cmb_yourbeamshavedonedamage  = "Palba z Vasich laseru znizila ucinnost pancerovani lode [cmb_attackerbeams] na [cmb_targetinfo_ship_name]";
$l_cmb_nobeamstoattackarmor     = "Nemate laserovou kapacitu pro palbu na pancerovani lode [cmb_targetinfo_ship_name]";
$l_cmb_yourarmorbreachedbybeams = "Pancerovani Vasi lode bylo prorazeno laserovou palbou z lode [cmb_targetinfo_ship_name]";
$l_cmb_yourarmorhitdamaged      = "Ucinnost pancerovani Vasi lode byla snizena laserovou palbou z lode [cmb_targetinfo_ship_name] na [cmb_targetbeams]";
$l_cmb_torpedoexchange  = "Vypousteni torped";
$l_cmb_hehasnobeamslefttoattackyou      = "Lod [cmb_targetinfo_ship_name] uz nema laserovou kapacitu pro utok proti pancerovani Vasi lode";
$l_cmb_yourtorpsdestroy = "Torpeda vypustena z Vasi lodi znicila [cmb_lost] stihacu lode [cmb_targetinfo_ship_name]";
$l_cmb_yourtorpsdestroy2        = "Torpeda vypustena z Vasi lodi znicila [cmb_attackertorpdamage] stihacu lode [cmb_targetinfo_ship_name]";
$l_cmb_youhavenotorpsleft       = "Uz nemate zadna torpeda, abyste je mohl vypustit proti stihacum lode [cmb_targetinfo_ship_name].";
$l_cmb_hehasnofighterleft       = "Lod [cmb_targetinfo_ship_name] uz nema zadne dalsi stihace, kteri by mohli nicit Vase torpeda";
$l_cmb_torpsdestroyyou  = "Lod [cmb_targetinfo_ship_name] znicila svymi torpedy [cmb_lost] Vasich stihacu";
$l_cmb_someonedestroyedfighters = "Lod [cmb_targetinfo_ship_name] znicila [cmb_targettorpdmg] Vasich stihacu svymi torpedy";
$l_cmb_hehasnotorpsleftforyou   = "Lod [cmb_targetinfo_ship_name] uz nema zadna dalsi torpeda, ktera by mohla vypustit proti Vasim stihacum";
$l_cmb_youhavenofightersanymore = "Nemate zadne dalsi stihace, kteri by mohli vyletet proti torpedum z lode [cmb_targetinfo_ship_name]";
$l_cmb_youbreachedwithtorps     = "Prorazil jste pancerovani lode [cmb_targetinfo_ship_name] Vasimi torpedy";
$l_cmb_hisarmorishitbytorps     = "[cmb_targetinfo_ship_name]'s armor is hit for [cmb_attackertorpdamage] damage by your torpedos";
$l_cmb_notorpslefttoattackarmor = "Nemate uz zadna torpeda, ktera byste mohl vypustit proti pancerovani lode [cmb_targetinfo_ship_name]";
$l_cmb_yourarmorbreachedbytorps = "Pancerovani Vasi lode bylo prorazeno torpedy z lode [cmb_targetinfo_ship_name]";
$l_cmb_yourarmorhitdmgtorps     = "Ucinnost pancerovani Vasi lode byla snizeno na [cmb_targettorpdmg] zasahem torped z lode [cmb_targetinfo_ship_name]";
$l_cmb_hehasnotorpsforyourarmor = "[cmb_targetinfo_ship_name] nema zadna dalsi torpeda pro utok na pancerovani Vasi lodi";
$l_cmb_fightersattackexchange   = "Bitva stihacu";
$l_cmb_enemylostallfighters     = "Lod [cmb_targetinfo_ship_name] uz ztratila vsechny stihace.";
$l_cmb_helostsomefighters       = "Lod [cmb_targetinfo_ship_name] ztratila [cmb_attackerfighters] stihacu.";
$l_cmb_youlostallfighters       = "Prisel jste uz o vsechny Vase stihace.";
$l_cmb_youalsolostsomefighters  = "Ztratil jste [cmb_targetfighters] stihacu.";
$l_cmb_hehasnofightersleftattack        = "Lod [cmb_targetinfo_ship_name] uz nema zadne dalsi stihace na obranu pred Vasimi";
$l_cmb_younofightersattackleft  = "Nemate zadne dalsi stihace pro obranu pred stihaci z lode [cmb_targetinfo_ship_name]";
$l_cmb_youbreachedarmorwithfighters     = "Vasi stihaci prorazili pancerovani lode [cmb_targetinfo_ship_name]";
$l_cmb_youhitarmordmgfighters   = "Vasi stihaci snizili ucinnost pancerovani lode [cmb_targetinfo_ship_name] na  [cmb_attackerfighters]";
$l_cmb_youhavenofighterstoarmor = "Uz nemate zadne dalsi stihace, ktere byste mohl vyslat proti pancerovani lode [cmb_targetinfo_ship_name]";
$l_cmb_hasbreachedarmorfighters = "Stihaci z lode [cmb_targetinfo_ship_name] prorazili pancerovani Vasi lode";
$l_cmb_yourarmorishitfordmgby   = "Ucinnost pancerovani Vasi lode byla snizena na [cmb_targetfighters] utokem stihacu z lode [cmb_targetinfo_ship_name]";
$l_cmb_nofightersleftheforyourarmor     = "[cmb_targetinfo_ship_name] nema zadne dalsi stihace, kteri by mohli byt vyslani pro utok na pancerovani Vasi lode";
$l_cmb_hehasbeendestroyed       = "Lod [cmb_targetinfo_ship_name] byla znicena";
$l_cmb_escapepodlaunched        = "Byla vypustena unikova kapsle!";
$l_cmb_yousalvaged      = "Zachranil jste [cmb_salv_ore] rudy, [cmb_salv_organics] potravin, [cmb_salv_goods] zbozi a [cmb_salvage_rate]% lodi za [cmb_salvage] kreditu.<BR>Vase hodnoceni se zmenilo o [cmb_number_rating_change] bodu.";
$l_cmb_youdidntdestroyhim       = "Nepodarilo se Vam znicit lod [cmb_targetinfo_ship_name]";
$l_cmb_shiptoshipcombatstats    = "Vysledek boje lode proti lodi";

// check_mines.php

$l_chm_youhitsomemines  = "Vase lod byla zasazena vybuchem [chm_roll] min!";
$l_chm_hehitminesinsector       = "Lod kapitana jmenem [chm_playerinfo_character_name] byla zasazena vybuchem [chm_roll] min v sektoru [chm_sector].";
$l_chm_youlostminedeflectors    = "Vase lod prisla o [chm_roll] odchylovacu min.";
$l_chm_youlostallminedeflectors = "Vase lod prisla o vsechny odchylovace min.";
$l_chm_youhadnominedeflectors  = "Vase lod nema zadne odchylovace min.";
$l_chm_yourshieldshitforminesdmg        = "Stity Vasi lode byly vybuchem poskozeny o [chm_mines_left].";
$l_chm_yourshieldsaredown       = "Vase lod je bez stitu!";
$l_chm_youlostallyourshields    = "Vase lod prisla o vsechny stity!";
$l_chm_yourarmorhitforminesdmg  = "Pancerovani Vasi lodi bylo zasazeno [chm_mines_left].";
$l_chm_yourhullisbreached       = "Trup Vasi lodi je prorazen!";
$l_chm_hewasdestroyedbyyourmines        = "[chm_playerinfo_character_name] byl znicen vybuchem Vami nastrazenych min v sektoru [chm_sector].";
$l_chm_yourshiphasbeendestroyed = "Vase lod byla znicena!";
$l_chm_luckescapepod    = "Nastesti jste unikl v unikove kapsli!";

// check_fighters.php

$l_chf_youretreatback   = "Ustoupil jste zpatky do sektoru, ze ktereho jste priletel";
$l_chf_notenoughcreditstoll     = "Nemate dostatek kreditu pro zaplaceni myta.";
$l_chf_movefailed       = "Presun se nepodaril.";
$l_chf_youpaidsometoll  = "Zaplatil jste [chf_tollstring] kreditu za myto.";
$l_chf_thefightersdetectyou     = "Stihaci detekovali Vasi pritomnost!";
$l_chf_therearetotalfightersindest      = "V cilovem sektoru se nachazi [chf_total_sector_fighters] stihacu.";
$l_chf_creditsdemanded  = "Pozaduji [chf_number_fighterstoll] kreditu za vstup do tohoto sektoru.";
$l_chf_youcanretreat    = "Muzete <BR><INPUT TYPE=RADIO NAME=response VALUE=retreat><B>Ustoupit</B> - spotrebujete tah navic.<BR></INPUT>";
$l_chf_inputpay = "<INPUT TYPE=RADIO NAME=response CHECKED VALUE=pay><B>Zaplatit</B> poplatek a vstoupit do sektoru bez nebezpeci napadeni.<BR></INPUT>";
$l_chf_inputfight       = "<INPUT TYPE=RADIO NAME=response CHECKED VALUE=fight><B>Bojovat</B> - musite znicit vsechny stihace predtim, nez muzete vstoupit do sektoru.<BR></INPUT>";
$l_chf_inputcloak       = "<INPUT TYPE=RADIO NAME=response CHECKED VALUE=sneak><B>Maskovat se</B> - pouzit maskovaci zarizeni a pokusit se uniknout pozornosti stihacu.<BR></INPUT>";
$l_chf_go       = "Provest";

// mines.php

$l_mines_title			="Vypousteni min a stihacu v sektoru";
$l_mines_noturn		 	="Pro zrizeni obrany sektoru potrebujete alespon jeden tah.";
$l_mines_nopermit		="Zrizeni obrany v tomto sektoru neni dovoleno.";
$l_mines_nodeploy		="Zde nemuzete instalovat obranu. Jina lod nebo aliance zde uz obranu instalovala pred Vami.";
$l_mines_info1			="Nachazite se v sektoru [sector]. Je tu [mines] min a [fighters] stihacu.";
$l_mines_info2			="Pro vypusteni mate k dispozici [mines] min a [fighters] stihacu";
$l_mines_deploy			="Vypustit";
$l_mines_deployed		="Vypusteno";
$l_mines_att			="Utok";
$l_mines_toll			="Vypalne";
$l_mines_notorps		="Nemate dostatek torped.";
$l_mines_nofighters		="Nemate dostatek stihacu";
$l_mines_dmines			="Vypusteno [mines] min.";
$l_mines_dfighter		="Vypusteno [fighters] stihacu v rezimu \"[mode]\".";

//alliance-planets.php

$l_teamplanet_title		="Hlaseni o aliancnich planetach";
$l_teamplanet_notally		="Nejste v alianci.";
$l_teamplanet_personal		="Zobrazit normalni planety";
$l_teamplanet_noplanet		="Vase aliance nema zadne planety";

$l_feedback_title		="Odeslat \"zpetnou vazbu\"";
$l_feedback_to			="PRO:";
$l_feedback_from		="OD:";
$l_feedback_topi		="PREDMET:";
$l_feedback_feedback		="\"ZPETNA VAZBA\"";
$l_feedback_message		="ZPRAVA";
$l_feedback_messent		="Zprava odeslana";
$l_feedback_subj		="Blacknova game feedback";
$l_feedback_info		="Please send feedback in english, czech or slovak. <BR>Piste prosim anglicky, cesky nebo slovensky."; // gameadmins put all your languages here

// corp.php
$l_corpm_title			="Aliancni menu";
$l_corpm_tocorp			="Planeta je nyni aliancni planetou!";
$l_corpm_topersonal		="Planeta je nyni normalni planetou!";
$l_corpm_exploit		="Vase sensory zachytily cast policejni zpravy:.....zacina delat chyby, sit kolem nej se uz stahuje....<BR>Proc se nemuzete zbavit dojmu, ze to bylo o Vas???";


// login.php login2.php
$l_login_title			="Prihlaseni do systemu";
$l_login_email			="E-mailova adresa:";
$l_login_pw			="Heslo:";
$l_login_chooseres		="Nelze rozpoznat rozliseni Vasi obrazovky. Zvolte si, ktere Vam nejlepe vyhovuje:";
$l_login_newp			= "Kliknete sem, pokud jste <A HREF=\"new.php\">NOVY HRAC</A>.";
$l_login_prbs			= "Problemy, potize?";
$l_login_emailus		= "Napiste nam";
$l_login_sclosed		= "Server je uzavren";
$l_login_closed_message		="Server je az do odvolani uzavren.";
$l_login_title2			="Druha cast prihlazeni do systemu";
$l_login_banned			="<b>Administrator Vas vyloucil z teto hry. Vase pritomnost na tomto serveru se stala nezadouci. Zkuste se priste chovat korektne.</b>";
$l_login_died			="Vase lod byla znicena, ale Vy a Vase posadka jste unikli v zachranne kapsli.  Zde se muzete <A HREF=main.php>nalodit</A> na novou lod.";
$l_login_newbie			="Pro zavaznost Vasich hrichu a necstnost utoku proti Vam se Federace milosrdne rozhodla, ze zaplati klonovani z Vasich pozustatku. Bohuzel, v teto dobe nemaji nove klony moznost vlastnit majetek, krome zakladnich zivostnich potreb. Budete vybaven zakladni lodi a nekolika kredity abyste mohl zacit znovu. Snad bude Vas novy zivot lepsi.";
$l_login_newlife		="Kliknutim zde zacnete <A HREF=main.php>novy zivot</A>.";
$l_login_looser			="Nemel jste zadnou unikovou kapsli a protoze jste v tomto zivote nebyl prilis uspesny, Federace zamitla Vase klonovani. Vase pozustaky se rozleteli prostorem a mozna, ze poslouzi jednou jako zaklad zivota nekde jinde...za nekolik bilionu let.<BR><BR>Snad budete mit priste vice stesti...";
$l_login_4gotpw1		= "Zadal jste nespravne heslo.<BR><BR>  Pokud jste zapomel Vase heslo, ";
$l_login_4gotpw2		= " a posleme Vam ho nba Vasi e-mailovou adresu.<BR><BR> Jinak,";
$l_login_4gotpw3		= "to zkuste znovu.  Tento pokus proveden z IP adresy ";
$l_login_noone			= "Hrac neexistuje! - Vytvorte <A HREF=new.php>noveho hrace</A>.";

// new.php new2.php
$l_new_title			= "Registrace noveho hrace";
$l_new_title2			= "Registrace noveho hrace - faze 2";
$l_new_shipname			= "Nazev lode";
$l_new_pname			= "Jmeno hrace";
$l_new_info			= "Slibujeme, ze Vase adresa nebude poskytnuta zadne treti strane.  Bude pouzita pro zaslani hesla, ktere server vygeneruje.";
$l_new_closed_message		="Hra byla uzavrena kvuli turnaji";
$l_new_blank			="E-mail, nazev lode a jmeno hrace nemohou byt prazdne.";
$l_new_inuse			="Tato E-mailova adresa je jiz v systemu pouzita.";
$l_new_4gotpw1			="Pokud jste zapomel Vase heslo,";
$l_new_4gotpw2			="a my Vam ho zasleme na Vasi e-mailovou adresu.";
$l_new_inusechar		="Jmeno hrace \"$character\" je uz obsazeno.";
$l_new_inuseship		="Nazev lode \"$shipname\" uz je v systemu pouzito.";
$l_new_pwsent			="Heslo bylo odeslano k $username.";
$l_new_login			="na prihlasovaci stranku.";
$l_new_err			="Vratte se zpatky nebo to <a href=new.php>zkuste znovu</a>.";
$l_new_topic			="Heslo do BlackNova Traders";
$l_new_message			="Dobry den,\n\nNekdo z IP adresy $ip si vyzadal zaslani hesla do BlackNova Traders.\n\nVase heslo je: [pass]\n\nDekujeme Vam\n\nBlackNova Traders web tym.";

// logout.php

$l_logout_score			="Vase skore je";
$l_logout_text			="[name] je odhlasen.  Zde se muzete <A HREF=index.php>vratit do hry</A>.";

// mail.php

$l_mail_title			="Poslat heslo e-mailem";
$l_mail_noplayer		="Hrac nenalezen! - Zde muzete <a href=new.php>vytvorit noveho hrace</a>.";
$l_mail_sent			="Heslo bylo odeslano na ";
$l_mail_topic			="Heslo do $game_name";
$l_mail_message			="Dobry den,\n\nnekdo z IP adresy $ip si vyzadal zaslani hesla do $game_name na tuto adresu.\n\nVase heslo je: [pass]\n\nDekujeme Vam\n\n$game_name web tym.";

// global_funcs.php

$l_global_mmenu			="<A HREF=main.php>Navrat do hlavniho menu</A>.";
$l_global_mlogin		="Navrat do <A HREF=login.php>prihlasovaci obrazovky</A>.";
$l_global_needlogin		="Je treba, abyste se <A HREF=login.php>prihlasil</A>.";
$l_global_died			="Hrac je MRTVY! Zde se muzete dozvedet <a href=log.php>co se stalo</a><BR><BR>Snad budete mit priste vice stesti!";
$l_global_warzone		="Zone je nyni valecnou zonou!";
$l_global_nzone			="Zone is neutralni zonou.";
$l_global_team			="Zone nyni patri alianci";
$l_global_player		="Zone nyni patri hraci";

// texts for the news flashes

$l_news_planets		  = " planet";
$l_news_cols		      = " milionu kolonistu";
$l_news_p_headline = "Rise kapiptana zvaneho [player] nyni ma ";

$l_killheadline=" byl zabit pri nehode";
$l_news_killed = "[name] byl pri dnesni tragicke nehode zabit. Kolik statecnosti projevil kapitan zvany [name] kdyz opoustel palubu lodi jako posleni a zjistil, ze na neho nezbylo misto v unikove kapsli. At odpociva v pokoji!";
$l_news_p_text5		= "Rozsirujici se rize [name] ma nyni jiz pet planet,
                   BNN bude aktivity teto rise podrobneji sledovat!";
$l_news_p_text10		= "Neustale se rozrustajici rise [name] nyni ovlada jiz deset planet.
                   Reporteri BNN predpovidaji, ze dalsi expanse rise [name]
                   muze vest k valce!";
$l_news_p_text25		= "Obrovska rise [name] jiz kolonizovala 25,
                   v rozhovoru nam tiskovy mluvci [name] sdelil, ze dalsi expanze uz bude pomalejsi!";
$l_news_p_text50		= "Neuveritelne velke imperium [name], nyni zastupuje jiz 50 planet
                   a stava se v cele galaxii hrozivou svou silou. Jeden z reporteru BNN
                   odhalil, ze [name] vylepsuje zbranove systemy svych lodi a 
                   pripravuje se na velkou valecnou ofenzivu. V rozhovoru nam tiskovy mluvci [name] 
                   sdelil, ze tato vylepseni jsou provadena jen pro obranne ucely!";
$l_news_c_text25		= "Rozsirujici se rise [name] ma nyni  25 milionu kolonistu,
                   BNN bude aktivity teto rise sledovat pozorne i v budoucnosti, 
                   ale uz ted je zrejme ze maji stale se zvysujici prirustky obyvatel!";
$l_news_c_text100		= "Prosperujici rise [name] nyni ma 100 milionu kolonistu.
                   Po velkych prirustcich obyvatel se zda, ze kolonie [name]
		   jsou dobrym mistem k rodinnemu zivotu!";
$l_news_c_text500		= "Rozsahle imperium [name] ma nyni jiz 500 milionu kolonistu,
                   Tiskovy mluvci [name] nam v rozhovoru rekl, ze kolonizace teprve zacne!";
$l_news_c_text1000		= "Prelidnene imperium [name] dosahlo jednoho bilionu kolonistu.
                   jak zjistili reporteri BNN, tato velka populacni exploze byla dosazena 
		   masivnim nasazenim klonovacich technik, diky kterym ma [name] tak velike 
		   prirustky. Ekonomicky rust je diky tak velike populaci skutecne 
		   enromni. BNN doufa, ze tyto prostredky nebudou zneuzity pro 
		   nakup valecnych prostredku";


// LAST ADDED : MOD TO TRADEROUTES
$l_tdr_notowner = "Tato obchodni cesta Vam nepatri";

// ADDITION TO login.php

$l_login_lang = "Jazyk";
$l_login_settings = "Herni nastaveni";
$l_login_change = "Zmenit";

// ADDITION TO log.php

$l_log_titlet = "Prohlizeni automatickeho deniku";

// ADDITION TO main.php

$l_main_warpto = "Warpem do";
$l_main_other = "Jinam";

// ADDITION TO planet.php
$l_planet_noone = "nikdo";

// ADDITION TO log.php
$l_log_text[LOG_PLANET_CAPTURED] = "Obsadil jste planetu patrici kapitanovi zvanemu [owner]. Bylo zde [cols] kolonistu a [credits] kreditu.";
$l_log_title[LOG_PLANET_CAPTURED] = "Planeta obsazena!";

// Options.php

$l_opt_title = "Nastaveni";
$l_opt_chpass = "Zmena hesla";
$l_opt_curpass = "Aktualni heslo:";
$l_opt_newpass = "Nove heslo:";
$l_opt_newpagain = "Nove heslo (znovu):";
$l_opt_userint = "Uzivatelske rozhrani";
$l_opt_usenew = "Pouzivat novy vzhled?";
$l_opt_lang = "Jazyk";
$l_opt_select = "Zvolte jeden:";
$l_opt_enabled = "Povoleno";
$l_opt_save = "Ulozit";

// Option2.php

$l_opt2_title = "Ulozeni nastaveni";
$l_opt2_passunchanged = "Heslo nebylo zmeneno.<BR><BR>";
$l_opt2_srcpassfalse = "Puvodni heslo je nespravne. Heslo nebylo zmeneno.<BR><BR>";
$l_opt2_newpassnomatch = "Pole s novym heslem nejsou stejna. Heslo nebylo zmeneno.<BR><BR>";
$l_opt2_passchanged = "Heslo bylo zmeneno.<BR><BR>";
$l_opt2_passchangeerr = "Chyba pri zmene hesla<BR><BR>";
$l_opt2_userintup = "Nastaveni uzivatelskeho rozhrani bylo zmeneno.<BR><BR>";
$l_opt2_userintfail = "Nebylo mozne ulozit nastaveni uzivatelskeho rozhrani.<BR><BR>";
$l_opt2_chlang = "Jazyk byl nastaven na [lang].<p>";
$l_opt2_dhtmlup = "Nastaveni dynamickeho HTML bylo zmeneno.<BR><BR>";
$l_opt2_dhtmlfail = "Nebylo mozne ulozit nastaveni dynamickeho HTML.<BR><BR>";

// Presets.php

$l_pre_title = "Zmenit nastaveni pro realny vesmir";
$l_pre_exceed = "Predvolba [preset] presahla maximum z [sector_max] sektoru. Predvolby nebyly ulozeny.<BR><BR>";
$l_pre_set = "Predvolba 1 nastavena na [preset1], predvolba 2 nastavena na [preset2] a predvolba 3 nastavena na [preset3].<BR><BR>";
$l_pre_save = "Ulozit";

// Mailto.php

$l_mt_title = "Odeslat zpravu";
$l_mt_from = "Od:";
$l_mt_subject = "Predmet:";
$l_mt_message = "Zprava:";
$l_mt_sent = "Zprava odeslana";
$l_mt_send = "Odeslat";

// sector_fighters.php
$l_sf_attacking = "Stihaci branici tento sekto na Vas utoci!<BR>";
$l_sf_destfight = "Vase lasery znicili [lost] stihacu<BR>";
$l_sf_destfightb = "Vase lasery znicili [lost] stihacu<BR>";
$l_sf_torphit = "Zasahy torped:";
$l_sf_destfightt = "Vase torpeda znicila [lost] stihacu<BR>";
$l_sf_fighthit = "Utok stihacu:";
$l_sf_destfightall = "Znicil jste vsechny stihace.<BR>";
$l_sf_destfightt2 = "Znicil jste [lost] stihacu.<BR>";
$l_sf_lostfight = "Ztratil jste vsechny stihace.<BR>";
$l_sf_lostfight2 = "Ztratil jste [lost] stihacu.<BR>";
$l_sf_armorbreach = "Pancerovani Vasi lodi je prorazeno!<BR>";
$l_sf_armorbreach2 = "Ucinnost pancerovani Vasi lodi byla snizena na [lost].<BR>";
$l_sf_sendlog = "Kapitan [player] znicil [lost] stihaci branicich sektor [sector].";
$l_sf_lreport = "Ucinnost pancerovani Vasi lodi byla snizena o [armor], prisel jste o [fighters] stihacu a vypustil jste [torps] torped.<BR><BR>";
$l_sf_shipdestroyed = "Vase lod byla znicena!<BR><BR>";
$l_sf_sendlog2 = "Stihaci branici sektor [sector] znicili lod kapitana zvaneho [player].";
$l_sf_escape = "Nastesti mate unikovou kapsli!<BR><BR>";

// Zone names

$l_zname[1] = "Zona bez pravidel";
$l_zname[2] = "Prostor Federace";
$l_zname[3] = "Zona volneho obchodu";
$l_zname[4] = "Valecna zona";


?>
