<?php

//general

$l_yes 			 = "Yes";
$l_no			 = "No";
$l_here			 = "here";
$l_submit		 = "Submit";
$l_reset		 = "Reset";
$l_all			 = "All";

$l_ore			 = "Ore";
$l_organics		 = "Organics";
$l_goods		 = "Goods";
$l_energy		 = "Energy";
$l_colonists		 = "Colonists";
$l_credits 		 = "Credits";
$l_units		 = "units of ";

$l_cargo		 = "Cargo";
$l_fighters		 = "Fighters ";
$l_mines		 = "Mines ";
$l_torps		 = "Torpedoes";

$l_none			 = "None";
$l_unnamed		 = "Unnamed";
$l_name			 = "Name";
$l_unowned		 = "Unowned";
$l_unknown		 = "Unknown";
$l_clickme 		 = "Click here";
$l_player  		 = "Player";
$l_ship			 = "Ship";
$l_set			 = "set";
$l_realspace		 = "Realspace";
$l_armourpts		 = "Armour points";


// main.php

$l_main_title 		 = "Main Menu";

$l_traderoutes		 = "Trade Routes";
$l_trade_control	 = "Trade Control";

$l_youhave 		 = "You have ";
$l_turns_used		 = "Turns used: ";
$l_turns_have		 = "Turns available: ";
$l_score		 = "Score: ";
$l_sector		 = "Sector";
$l_help			 = "Help";
$l_faq		         = "FAQ";
$l_feedback		 = "Feedback";
$l_forums		 = "Forums";
$l_logout		 = "Logout";

$l_commands		 = "Commands";
$l_command_no		 = "Command not available.";
$l_devices		 = "Devices";
$l_planets		 = "Planets";
$l_log			 = "Log";
$l_sector_def		 = "Sector Defences";
$l_defense		 = "Defenses";
$l_read_msg		 = "Read Messages";
$l_send_msg		 = "Send Messages";
$l_rankings		 = "Rankings";
$l_teams		 = "Alliances";
$l_ohno			 = "Self-Destruct";
$l_options		 = "Options";
$l_navcomp		 = "Nav Computer";

$l_incompletemove 	 = "You haven't completed your previous move.";
$l_clicktocontinue	 = "Click Here to continue";
$l_toplanetmenu   	 = "to go to the planet menu.";
$l_nonexistant_pl	 = "On a non-existent planet???";
$l_abord		 = ", aboard the ";
$l_messages_wait	 = " Messages waiting for you.";

$l_no_warplink		 = "No warp links";
$l_scan			 = "scan";
$l_fullscan		 = "Full scan";

$l_port			 = "Port";
$l_tradingport		 = "Trading port";
$l_planet_in_sec	 = "Planets in sector ";
$l_ships_in_sec		 = "Other ships in sector ";
$l_sector_0		 = "There is so much traffic in Sol (Sector 0) that you cannot even isolate other ships!";

// report.php

$l_report_title		 = "Ship Report";

$l_level		 = "Level";

$l_ship_levels		 = "Ship Component Levels";
$l_hull			 = "Hull";
$l_engines		 = "Engines";
$l_power		 = "Power";
$l_computer		 = "Computer";
$l_sensors		 = "Sensors";
$l_armour		 = "Armour";
$l_shields		 = "Shields";
$l_beams		 = "Beam Weapons";
$l_torp_launch	         = "Torpedo launchers";
$l_cloak		 = "Cloak";
$l_holds		 = "Holds";
$l_deflect		 = "Mine Deflectors";
$l_ewd			 = "Emegency Warp Device";


$l_arm_weap		 = "Armour & Weapons";
$l_beacons		 = "Space Beacons";
$l_warpedit		 = "Warp Editors";
$l_genesis		 = "Genesis Torpedoes";
$l_escape_pod		 = "Escape Pod";
$l_fuel_scoop		 = "Fuel Scoop";

// device.php

$l_device_title		 = "Devices";

$l_device_expl		 = "Your ship is equipped with the following devices (click on a device to use it):";
$l_device		 = "Device";
$l_qty			 = "Quantity";
$l_usage		 = "Usage";
$l_manual		 = "Manual";	
$l_automatic		 = "Automatic";

// port.php port2.php

$l_trade		 = "Trade";
$l_title_port		 = "Port Trading";
$l_title_trade		 = "Trading Commodities";
$l_sector_war		 = "War embargo";
$l_war_info		 = "War is raging in this sector. You can't reach the port through all the hostile forces.";
$l_no_trade		 = "Trade forbidden";
$l_no_trade_out		 = "Trading at this port is not allowed for outsiders";
$l_no_trade_info	 = "Trading at this port is not allowed";
$l_buying		 = "Buying";
$l_selling		 = "Selling";
$l_commodity		 = "Commodity";
$l_amount		 = "Amount";
$l_price		 = "Price";
$l_buy			 = "Buy";
$l_sell			 = "Sell";
$l_trade_st_info	 = "You have [free_holds] empty cargo holds, can carry [free_power] more energy units, and have [credits] credits.";
$l_special_port		 = "Special Port";
$l_no_credits		 = "Not enough credits";
$l_creds_to_spend	 = "You have [credits] credits to spend.";
$l_cost			 = "Cost";
$l_avail		 = "Available";
$l_profit		 = "Profit";
$l_current		 = "Current";
$l_current_qty		 = "Current Quantities";
$l_max			 = "Max";
$l_ifyouneedmore	 = "If you need more you may access this port's [igb] ";
$l_ifyouneedplan	 = "Access the planet's";
$l_igb_term		 = "IGB Banking Terminal";
$l_upgrade		 = "Upgrade?";
$l_unlimited		 = "Unlimited";
$l_full			 = "Full";
$l_equipped		 = "Equipped";
$l_n_a			 = "n/a";
$l_item			 = "Item";
$l_totalcost		 = "Total cost";
$l_would_dump	         = "If you would like to dump all your colonists here, click ";
$l_noport		 = "There is no port here!";
$l_trade_turnneed	 = "You need at least one turn to trade at a port or planet.";
$l_returnto_port         = " Click <A HREF=port.php3>here</A> to return to the port menu.";
$l_notenough_cargo	 = "You do not have enough free cargo holds for the commodities you wish to purchase.";
$l_notenough_power	 = "You do not have enough free power storage for the energy you wish to purchase.";
$l_notenough_credits	 = "You do not have enough credits to complete the transaction.";
$l_notenough_turns	 = "You do not have enough turns to complete the transaction.";
$l_notenough_ore	 = "You do not have enough ore to complete the transaction.";
$l_notenough_goods	 = "You do not have enough goods to complete the transaction.";
$l_notenough_energy	 = "You do not have enough energy to complete the transaction.";
$l_notenough_organics	 = "You do not have enough organics to complete the transaction.";
$l_exceed_organics	 = "Number of organics exceeds the supply/demand.  ";
$l_exceed_ore            = "Number of ore exceeds the supply/demand.  ";
$l_exceed_energy         = "Number of energy exceeds the supply/demand.  ";
$l_exceed_goods          = "Number of goods exceeds the supply/demand.  ";
$l_trade_result		 = "Results for this trade";
$l_traded_ore		 = "Traded Ore";
$l_traded_goods		 = "Traded Goods";
$l_traded_organics	 = "Traded Organics";
$l_traded_energy	 = "Traded Energy";
$l_trade_complete	 = "Trade completed";

// planet.php planet2.php planet3.php
$l_planet_title		 = "Planet Menu";
$l_planet_none		 = "You are not in the same sector as this planet, so you can't interact with it.";
$l_planet_capture1	 = "capture"; // thats the link's text
$l_planet_capture2	 = "You may [capture] the planet or just leave it undefended.";
$l_planet_unowned	 = "This planet is unowned";
$l_planet_unnamed        = "Welcome to [name]'s un-named planet.";
$l_planet_named		 = "Welcome to [planetname], owned by [name].";
$l_planet_onsurface	 = "You are presently on the surface of the planet.";
$l_planet_orbit 	 = "You are presently in orbit of the planet.";
$l_planet_leave_link     = "Leave";
$l_planet_leave          = "[leave] Planet";
$l_planet_land_link      = "Land";
$l_planet_land           = "[land] on Planet";
$l_planet_logout	 = "You can also <a href=logout.php3>log-out</a> in the safety of your planet.";
$l_planet_selling	 = "Planet is presently selling commodities.";
$l_planet_not_selling    = "Planet is not presently selling commodities.";
$l_planet_transfer_link	 = "Transfer";
$l_planet_transfer	 = "[transfer] commodities/resources/colonists to/from Planet";
$l_planet_hasbase	 = "You have a bsae on this planet.";

$l_planet_perc		 = "Production Percentages";
$l_planet_interest	 = "* Production of credits beyond banking interest is 100 - other percentages";
$l_planet_update	 = "Update";
$l_planet_tsell_link	 = "Selling";
$l_planet_tsell		 = "Toggle planet [selling] commodities";
$l_planet_bbase_link	 = "build a base";
$l_planet_bbase		 = "With enough commodites and credits, you can [build] to help defend the planet.";
$l_planet_bbuild	 = "Base constructed";
$l_planet_mcorp_linkC	 = "Corporate Planet";
$l_planet_mcorp_linkP	 = "Personal Planet";
$l_planet_mcorp		 = "You can also make this planet a [planet].";
$l_planet_buy_link	 = "Buy";
$l_planet_buy		 = "[buy] commodities from Planet";
$l_planet_att_link	 = "Attack";
$l_planet_att		 = "[attack] on Planet";
$l_planet_att_sure	 = "Are you SURE...";
$l_planet_scn_link	 = "Scan";
$l_planet_scn		 = "[scan] Planet";
$l_planet_nowsell        = "Planet now set to sell.";
$l_planet_nownosell      = "Planet now set not to sell.";
$l_planet_iname		 = "Enter new planet name";
$l_planet_cname		 = "Planet name changed to ";
$l_planet_landed	 = "You have landed on the planet's surface.";
$l_planet_left		 = "You are no longer on the planet's surface.";
$l_planet_cinfo		 = "You have room for [cargo] units of additional cargo.  You have capacity for [energy] units of addtional power.";
$l_planet_toplanet	 = "To Planet?";
$l_planet_baseinfo	 = "To build a base there must be at least $base_credits credits, $base_ore units of ore, $base_organics units of organics, and $base_goods units of goods on the planet .";
$l_planet_p_under        = "You may not change production percentages to a negative number.";
$l_planet_p_over	 = "You may not change production percentages to higher than a total of 100%.";
$l_planet_p_changed	 = "Production percentages changed.";
$l_plant_scn_turn	 = "You need at least one turn to scan a planet.";
$l_planet_noscan	 = "Sensors cannot get a fix on target!";
$l_planet_logscanA	 = "[name] attempted to scan one of your planets in sector [sector], but failed.";
$l_planet_logscanA	 = "One of your planets in sector [sector] was scanned by [name].";
$l_planet_scn_report	 = "Scan results on [name], owned by:  [owner]";
$l_base	  		 = "Base";
$l_planet_ison		 = "is on the planet.";
$l_planet_captured	 = "Planet captured";
$l_planet_notdef	 = "Planet not defeated!";
$l_planet_caplog	 = "Your planet '[planetname]' in sector [sector] was captured by [name].";

$l_planet2_title	 = "Planetary Transfer";
$l_planet2_noturn	 = "You need at least one turn to perform a planetary transfer.";
$l_planet2_noten 	 = "You don't have enough ";
$l_planet2_fortr	 = "for the requested transfer.";
$l_planet2_settr	 = "Setting transfer amount to ";
$l_planet2_losup	 = "The planet was only able to supply ";
$l_planet2_notowner	 = "You do not own this planet.";
$l_planet2_compl	 = "Transfer complete.";
$l_planet2_power	 = "power capacity";
$l_planet2_comp 	 = "computer capacity";
$l_planet2_laun 	 = "launcher capacity";

$l_planet3_title	 = "Trading at Planet";

// planet-report.php

$l_pr_title		 = "Planet Report";
$l_pr_teamlink		 = "Show alliance planets";
$l_pr_noplanet		 = "You have no planets so far";
$l_pr_clicktosort	 = "Click on column header to sort.";
$l_pr_totals		 = "Totals";

// rsmove.php
$l_rs_title 		= "RealSpace Move";
$l_rs_whichsector       = "Which sector would you like to reach through RealSpace?";
$l_rs_insector		= "You are presently in sector [sector] - and there are sectors available from 0 to [sector_max].";
$l_rs_submit		= "Compute";
$l_rs_movetime		= "With your engines, it will take [triptime] turns to complete the journey.";
$l_rs_energy		= "You would gather [energy] units of energy";
$l_rs_noturns		= "You do not have enough turns left, and cannot embark on this journey.";
$l_rs_engage_link	= "Engage";
$l_rs_engage		= "You have [turns] turns. [engage] engines?";

$l_rs_invalid		= "Invalid Destination";
$l_rs_ready 		= "You are now in sector [sector]. You used [triptime] turns, and gained [energy] energy units.";

// navcomp.php	

$l_nav_title		 = "Navigation Computer";
$l_nav_nocomp		 = "Navigation computer is not available";
$l_nav_query		 = "Enter sector to find path to: ";
$l_nav_pathfnd		 = "Path found";
$l_nav_answ1		 = "It will take you";
$l_nav_answ2		 = "turns to get to this sector.";
$l_nav_proper		 = "Your computer technology is too primitive to compute a warp route to that distance.";

?>
