<?php

//general

$l_yes 			 = "Yes";
$l_no			 = "No";
$l_here			 = "here";
$l_submit		 = "Submit";
$l_reset		 = "Reset";
$l_all			 = "All";

$l_ore			 = "Ore";
$l_organics		 = "Organics";
$l_goods		 = "Goods";
$l_energy		 = "Energy";
$l_colonists		 = "Colonists";
$l_credits 		 = "Credits";
$l_units		 = "units of ";

$l_cargo		 = "Cargo";
$l_fighters		 = "Fighters ";
$l_mines		 = "Mines ";
$l_torps		 = "Torpedoes";

$l_none			 = "None";
$l_unnamed		 = "Unnamed";
$l_name			 = "Name";
$l_unowned		 = "Unowned";
$l_unknown		 = "Unknown";
$l_clickme 		 = "Click here";
$l_player  		 = "Player";
$l_ship			 = "Ship";
$l_set			 = "set";
$l_realspace		 = "Realspace";
$l_armourpts		 = "Armour points";


// main.php

$l_main_title 		 = "Main Menu";

$l_traderoutes		 = "Trade Routes";
$l_trade_control	 = "Trade Control";

$l_youhave 		 = "You have ";
$l_turns_used		 = "Turns used: ";
$l_turns_have		 = "Turns available: ";
$l_score		 = "Score: ";
$l_sector		 = "Sector";
$l_help			 = "Help";
$l_faq		         = "FAQ";
$l_feedback		 = "Feedback";
$l_forums		 = "Forums";
$l_logout		 = "Logout";

$l_commands		 = "Commands";
$l_command_no		 = "Command not available.";
$l_devices		 = "Devices";
$l_planets		 = "Planets";
$l_log			 = "Log";
$l_sector_def		 = "Sector Defences";
$l_defense		 = "Defenses";
$l_read_msg		 = "Read Messages";
$l_send_msg		 = "Send Messages";
$l_rankings		 = "Rankings";
$l_teams		 = "Alliances";
$l_ohno			 = "Self-Destruct";
$l_options		 = "Options";
$l_navcomp		 = "Nav Computer";

$l_incompletemove 	 = "You haven't completed your previous move.";
$l_clicktocontinue	 = "Click Here to continue";
$l_toplanetmenu   	 = "to go to the planet menu.";
$l_nonexistant_pl	 = "On a non-existent planet???";
$l_abord		 = ", aboard the ";
$l_messages_wait	 = " Messages waiting for you.";

$l_no_warplink		 = "No warp links";
$l_scan			 = "scan";
$l_fullscan		 = "Full scan";

$l_port			 = "Port";
$l_tradingport		 = "Trading port";
$l_planet_in_sec	 = "Planets in sector ";
$l_ships_in_sec		 = "Other ships in sector ";
$l_sector_0		 = "There is so much traffic in Sol (Sector 0) that you cannot even isolate other ships!";

// report.php

$l_report_title		 = "Ship Report";

$l_level		 = "Level";

$l_ship_levels		 = "Ship Component Levels";
$l_hull			 = "Hull";
$l_engines		 = "Engines";
$l_power		 = "Power";
$l_computer		 = "Computer";
$l_sensors		 = "Sensors";
$l_armour		 = "Armour";
$l_shields		 = "Shields";
$l_beams		 = "Beam Weapons";
$l_torp_launch	         = "Torpedo launchers";
$l_cloak		 = "Cloak";
$l_holds		 = "Holds";
$l_deflect		 = "Mine Deflectors";
$l_ewd			 = "Emegency Warp Device";


$l_arm_weap		 = "Armour & Weapons";
$l_beacons		 = "Space Beacons";
$l_warpedit		 = "Warp Editors";
$l_genesis		 = "Genesis Torpedoes";
$l_escape_pod		 = "Escape Pod";
$l_fuel_scoop		 = "Fuel Scoop";

// device.php

$l_device_title		 = "Devices";

$l_device_expl		 = "Your ship is equipped with the following devices (click on a device to use it):";
$l_device		 = "Device";
$l_qty			 = "Quantity";
$l_usage		 = "Usage";
$l_manual		 = "Manual";	
$l_automatic		 = "Automatic";

// port.php port2.php

$l_trade		 = "Trade";
$l_title_port		 = "Port Trading";
$l_title_trade		 = "Trading Commodities";
$l_sector_war		 = "War embargo";
$l_war_info		 = "War is raging in this sector. You can't reach the port through all the hostile forces.";
$l_no_trade		 = "Trade forbidden";
$l_no_trade_out		 = "Trading at this port is not allowed for outsiders";
$l_no_trade_info	 = "Trading at this port is not allowed";
$l_buying		 = "Buying";
$l_selling		 = "Selling";
$l_commodity		 = "Commodity";
$l_amount		 = "Amount";
$l_price		 = "Price";
$l_buy			 = "Buy";
$l_sell			 = "Sell";
$l_trade_st_info	 = "You have [free_holds] empty cargo holds, can carry [free_power] more energy units, and have [credits] credits.";
$l_special_port		 = "Special Port";
$l_no_credits		 = "Not enough credits";
$l_creds_to_spend	 = "You have [credits] credits to spend.";
$l_cost			 = "Cost";
$l_avail		 = "Available";
$l_profit		 = "Profit";
$l_current		 = "Current";
$l_current_qty		 = "Current Quantities";
$l_max			 = "Max";
$l_ifyouneedmore	 = "If you need more you may access this port's [igb] ";
$l_ifyouneedplan	 = "Access the planet's";
$l_igb_term		 = "IGB Banking Terminal";
$l_upgrade		 = "Upgrade?";
$l_unlimited		 = "Unlimited";
$l_full			 = "Full";
$l_equipped		 = "Equipped";
$l_n_a			 = "n/a";
$l_item			 = "Item";
$l_totalcost		 = "Total cost";
$l_would_dump	         = "If you would like to dump all your colonists here, click ";
$l_noport		 = "There is no port here!";
$l_trade_turnneed	 = "You need at least one turn to trade at a port or planet.";
$l_returnto_port         = " Click <A HREF=port.php3>here</A> to return to the port menu.";
$l_notenough_cargo	 = "You do not have enough free cargo holds for the commodities you wish to purchase.";
$l_notenough_power	 = "You do not have enough free power storage for the energy you wish to purchase.";
$l_notenough_credits	 = "You do not have enough credits to complete the transaction.";
$l_notenough_turns	 = "You do not have enough turns to complete the transaction.";
$l_notenough_ore	 = "You do not have enough ore to complete the transaction.";
$l_notenough_goods	 = "You do not have enough goods to complete the transaction.";
$l_notenough_energy	 = "You do not have enough energy to complete the transaction.";
$l_notenough_organics	 = "You do not have enough organics to complete the transaction.";
$l_exceed_organics	 = "Number of organics exceeds the supply/demand.  ";
$l_exceed_ore            = "Number of ore exceeds the supply/demand.  ";
$l_exceed_energy         = "Number of energy exceeds the supply/demand.  ";
$l_exceed_goods          = "Number of goods exceeds the supply/demand.  ";
$l_trade_result		 = "Results for this trade";
$l_traded_ore		 = "Traded Ore";
$l_traded_goods		 = "Traded Goods";
$l_traded_organics	 = "Traded Organics";
$l_traded_energy	 = "Traded Energy";
$l_trade_complete	 = "Trade completed";

// planet.php planet2.php planet3.php
$l_planet_title		 = "Planet Menu";
$l_planet_none		 = "You are not in the same sector as this planet, so you can't interact with it.";
$l_planet_capture1	 = "capture"; // thats the link's text
$l_planet_capture2	 = "You may [capture] the planet or just leave it undefended.";
$l_planet_unowned	 = "This planet is unowned";
$l_planet_unnamed        = "Welcome to [name]'s un-named planet.";
$l_planet_named		 = "Welcome to [planetname], owned by [name].";
$l_planet_onsurface	 = "You are presently on the surface of the planet.";
$l_planet_orbit 	 = "You are presently in orbit of the planet.";
$l_planet_leave_link     = "Leave";
$l_planet_leave          = "[leave] Planet";
$l_planet_land_link      = "Land";
$l_planet_land           = "[land] on Planet";
$l_planet_logout	 = "You can also <a href=logout.php3>log-out</a> in the safety of your planet.";
$l_planet_selling	 = "Planet is presently selling commodities.";
$l_planet_not_selling    = "Planet is not presently selling commodities.";
$l_planet_transfer_link	 = "Transfer";
$l_planet_transfer	 = "[transfer] commodities/resources/colonists to/from Planet";
$l_planet_hasbase	 = "You have a base on this planet.";

$l_planet_perc		 = "Production Percentages";
$l_planet_interest	 = "* Production of credits beyond banking interest is 100 - other percentages";
$l_planet_update	 = "Update";
$l_planet_tsell_link	 = "Selling";
$l_planet_tsell		 = "Toggle planet [selling] commodities";
$l_planet_bbase_link	 = "build a base";
$l_planet_bbase		 = "With enough commodites and credits, you can [build] to help defend the planet.";
$l_planet_bbuild	 = "Base constructed";
$l_planet_mcorp_linkC	 = "Corporate Planet";
$l_planet_mcorp_linkP	 = "Personal Planet";
$l_planet_mcorp		 = "You can also make this planet a [planet].";
$l_planet_buy_link	 = "Buy";
$l_planet_buy		 = "[buy] commodities from Planet";
$l_planet_att_link	 = "Attack";
$l_planet_att		 = "[attack] on Planet";
$l_planet_att_sure	 = "Are you SURE...";
$l_planet_scn_link	 = "Scan";
$l_planet_scn		 = "[scan] Planet";
$l_planet_nowsell        = "Planet now set to sell.";
$l_planet_nownosell      = "Planet now set not to sell.";
$l_planet_iname		 = "Enter new planet name";
$l_planet_cname		 = "Planet name changed to ";
$l_planet_landed	 = "You have landed on the planet's surface.";
$l_planet_left		 = "You are no longer on the planet's surface.";
$l_planet_cinfo		 = "You have room for [cargo] units of additional cargo.  You have capacity for [energy] units of addtional power.";
$l_planet_toplanet	 = "To Planet?";
$l_planet_baseinfo	 = "To build a base there must be at least $base_credits credits, $base_ore units of ore, $base_organics units of organics, and $base_goods units of goods on the planet .";
$l_planet_p_under        = "You may not change production percentages to a negative number.";
$l_planet_p_over	 = "You may not change production percentages to higher than a total of 100%.";
$l_planet_p_changed	 = "Production percentages changed.";
$l_plant_scn_turn	 = "You need at least one turn to scan a planet.";
$l_planet_noscan	 = "Sensors cannot get a fix on target!";
$l_planet_logscanA	 = "[name] attempted to scan one of your planets in sector [sector], but failed.";
$l_planet_logscanB	 = "One of your planets in sector [sector] was scanned by [name].";
$l_planet_scn_report	 = "Scan results on [name], owned by:  [owner]";
$l_base	  		 = "Base";
$l_planet_ison		 = "is on the planet.";
$l_planet_captured	 = "Planet captured";
$l_planet_notdef	 = "Planet not defeated!";
$l_planet_caplog	 = "Your planet '[planetname]' in sector [sector] was captured by [name].";

$l_planet2_title	 = "Planetary Transfer";
$l_planet2_noturn	 = "You need at least one turn to perform a planetary transfer.";
$l_planet2_noten 	 = "You don't have enough ";
$l_planet2_fortr	 = "for the requested transfer.";
$l_planet2_settr	 = "Setting transfer amount to ";
$l_planet2_losup	 = "The planet was only able to supply ";
$l_planet2_notowner	 = "You do not own this planet.";
$l_planet2_compl	 = "Transfer complete.";
$l_planet2_power	 = "power capacity";
$l_planet2_comp 	 = "computer capacity";
$l_planet2_laun 	 = "launcher capacity";
$l_planet2_nocorptransfer = "You cannot transfer credits to or from corporate planets.";

$l_planet3_title	 = "Trading at Planet";

// planet-report.php

$l_pr_title		 = "Planet Report";
$l_pr_teamlink		 = "Show alliance planets";
$l_pr_noplanet		 = "You have no planets so far";
$l_pr_clicktosort	 = "Click on column header to sort.";
$l_pr_totals		 = "Totals";

// rsmove.php
$l_rs_title 		= "RealSpace Move";
$l_rs_whichsector       = "Which sector would you like to reach through RealSpace?";
$l_rs_insector		= "You are presently in sector [sector] - and there are sectors available from 0 to [sector_max].";
$l_rs_submit		= "Compute";
$l_rs_movetime		= "With your engines, it will take [triptime] turns to complete the journey.";
$l_rs_energy		= "You would gather [energy] units of energy";
$l_rs_noturns		= "You do not have enough turns left, and cannot embark on this journey.";
$l_rs_engage_link	= "Engage";
$l_rs_engage		= "You have [turns] turns. [engage] engines?";

$l_rs_invalid		= "Invalid Destination";
$l_rs_ready 		= "You are now in sector [sector]. You used [triptime] turns, and gained [energy] energy units.";

// navcomp.php	

$l_nav_title		 = "Navigation Computer";
$l_nav_nocomp		 = "Navigation computer is not available";
$l_nav_query		 = "Enter sector to find path to: ";
$l_nav_pathfnd		 = "Path found";
$l_nav_answ1		 = "It will take you";
$l_nav_answ2		 = "turns to get to this sector.";
$l_nav_proper		 = "Your computer technology is too primitive to compute a warp route to that distance.";


// attack.php

$l_att_title		 = "Attack Ship";
$l_att_notarg		 = "Target not in this sector.";
$l_att_noturn		 = "You need at least one turn to attack.";
$l_att_noatt		 = "Attacking someone in this sector is not permitted.";
$l_att_flee		 = "Target out maneuvered you!";
$l_att_ewd		 = "Target engaged an emergency warp device when attacked!";
$l_att_att		 = "Attacking ";
$l_att_beams		 = "Beams hit:";
$l_att_torps		 = "Torpedos hit:";
$l_att_fighters		 = "Fighters Attack:";
$l_att_lost		 = "lost";
$l_att_ylost		 = "You lost";
$l_att_sdown		 = "'s shields are down!";
$l_att_ydown		 = "Your shields are down!";
$l_att_shits		 = "'s shields are hit for";
$l_att_yhits		 = "Your shields are hit for";
$l_att_dmg		 = "damage";
$l_att_sarm		 = "'s armour breached!";
$l_att_yarm		 = "Your armour has been breached!";
$l_att_ashit		 = "'s armour is hit for";
$l_att_ayhit		 = "Your armour is hit for";
$l_att_lostf		 = "lost all fighters.";
$l_att_ylostf		 = "You lost all fighters.";
$l_att_sdest		 = "'s ship has been destroyed.";
$l_att_espod		 = "An escape pod was launched!";
$l_att_ysalv		 = "You salvaged [salv_ore] units of ore, [salv_organics] units of organics, [salv_goods] units of goods, and salvaged [ship_salvage_rate]% of the ship for [ship_salvage] credits.<BR>Your rating changed by [rating_change] points.";
$l_att_andused		 = "and used";
$l_att_stilship		 = "You did not destory [name]'s ship.";
$l_att_atyou		 = "attacked you";
$l_att_and		 = "and";
$l_att_yshiplost	 = "Your ship has been destroyed!";
$l_att_salv		 = "[name] salvaged [salv_ore] units of ore, [salv_organics] units of organics, [salv_goods] units of goods, and salvaged [ship_salvage_rate]% of the ship for [ship_salvage] credits";

// warpedit 1-3.php

$l_warp_title		 = "Use Warp Editor";
$l_warp_turn		 = "You need at least one turn to use a warp editor.";
$l_warp_none		 = "You do not have any warp editors.";
$l_warp_forbid		 = "Using a Warp Editor in this sector is not permitted.";
$l_warp_nolink		 = "There are no links out of this sector.";
$l_warp_linkto		 = "Links lead from this sector to";
$l_warp_query		 = "What sector would you like to create a link to?";
$l_warp_oneway		 = "One-way?";
$l_warp_dest		 = "Alternately, you may destroy a link to sector.";
$l_warp_destquery	 = "What sector would you like to remove a link to?";
$l_warp_bothway		 = "Both-ways";
$l_warp_nosector	 = "Sector does not exist.";
$l_warp_twoerror	 = "Using a Warp Editor to create a two-way link to sector [target_sector] is not permitted.";
$l_warp_sectex		 = "Cannot create warp link from current sector - that would exceed the maximum of $link_max per sector.";
$l_warp_linked		 = "Target sector ([target_sector]) already has a link from this sector.";
$l_warp_unlinked	 = "Target sector ([target_sector]) does not have a link from this sector.";
$l_warp_coneway	         = "Link created one-way to";
$l_warp_ctwoway		 = "Link created to and from";
$l_warp_forbidtwo	 = "Using a Warp Editor to remove a two-way link to sector [target_sector] is not permitted.";
$l_warp_removed		 = "Link removed to";
$l_warp_removedtwo	 = "Link removed to and from";

// genesis.php

$l_gns_title		 = "Use Genesis Device";
$l_gns_turn		 = "You need at least one turn to use a genesis device.";
$l_gns_onplanet		 = "You can't use this device while on the planet surface.";
$l_gns_full		 = "This solar system is already full.";
$l_gns_planetex		 = "There is already a planet in this sector.";
$l_gns_nogenesis	 = "You do not have any genesis devices.";
$l_gns_forbid		 = "Creating a planet in this sector is not permitted.";
$l_gns_bforbid		 = "The bases in this sector are interfering with your genesis device. Planet creation not possible.";
$l_gns_pcreate		 = "Planet created.";

// ship.php

$l_ship_title		 = "Ship Commands";
$l_ship_the		 = "The";
$l_ship_nolonger	 = "is no longer in sector";
$l_ship_youc		 = "You see the";
$l_ship_owned		 = "owned by";
$l_ship_perform		 = "You can perform the following actions:";

// selfdestruct.php

$l_die_title		 = "Self-Destruct";
$l_die_rusure		 = "Are you sure you wish to destroy your ship? This will remove you from the game.";
$l_die_goodbye		 = "Goodbye cruel galaxy!";
$l_die_check		 = "Are you positive that you wish to remove yourself from the game?";
$l_die_nonono		 = "NO! NO! NO!";
$l_die_what		 = "What was I thinking?";
$l_die_count		 = "5.. 4.. 3.. 2.. 1.. Boom!";
$l_die_vapor		 = "You ship and all aboard have been vaporized.";
$l_die_please		 = "Please, <A HREF=logout.php3>logout</A>";
$l_die_exploit		 = "Don't play with what you don't understand.";

// move.php

$l_move_title 		 = "Move";
$l_move_turn		 = "You need at least one turn to move.";
$l_move_failed		 = "Move failed!";

// scan.php

$l_scan_title		 = "Scan Ship";
$l_scan_turn		 = "You need at least one turn to scan another ship.";
$l_scan_ron		 = "Scan results on";
$l_scan_capt		 = "Captained by:";
$l_scan_arma		 = "Armament:";
$l_scan_carry		 = "Carrying:";

// lrscan.php

$l_lrs_title		 = "Long Range Scan";
$l_lrs_nofull		 = "Your scanners do not possess full long range scan capabilities.";
$l_lrs_noturns		 = "You need at least $fullscan_cost turn(s) to run a full long range scan.";
$l_lrs_used		 = "Used";
$l_lrs_turns		 = "turn(s)";
$l_lrs_left		 = "left";
$l_lrs_reach		 = "The following locations can be reached from sector [sector]:";
$l_lrs_links		 = "Links";
$l_lrs_ships		 = "Ships";
$l_lrs_click		 = "Click one of the links to move to that sector.";
$l_lrs_cantscan		 = "Can't scan sector from current sector!";
$l_lrs_zero		 = "Sector 0 is too crowded to scan for ships!";
$l_lrs_moveto		 = "to move to sector";

// log.php

$l_log_months = array('January','February','March','April','May','June','July','August','September','October','November','December');
$l_log_months_short = array('Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec');
$l_log_pod = "Luckily, you had an escape pod!";
$l_log_nopod = "<font color=yellow><b>You did not have an escape pod, you died.</b></font>";

$l_log_text[LOG_LOGIN] = "You have logged in, from [ip].";
$l_log_title[LOG_LOGIN] = "Logged in";
$l_log_text[LOG_LOGOUT] = "You have logged out, from [ip].";
$l_log_title[LOG_LOGOUT] = "Logged out";
$l_log_text[LOG_ATTACK_OUTMAN] = "[player] was spotted on an attack vector, but your great pilot skills and good engines allowed you to outmaneuver the enemy.";
$l_log_title[LOG_ATTACK_OUTMAN] = "Evasive action!";
$l_log_text[LOG_ATTACK_OUTSCAN] = "You detected [player]'s weapons trying to fix on your ship, but your cloak generators managed to fool the enemy's primitive sensor circuits.";
$l_log_title[LOG_ATTACK_OUTSCAN] = "Cloak successful!";
$l_log_text[LOG_ATTACK_EWD] = "You are surprised by [player]'s treacherous attack. You can see the incoming warheads as you reach frantically for the emergency warp button. The world blurs around you and, for a milisecond, you think you are dead. When you finally open your eyes, you see that you were safely transported elsewhere. But where exactly, you do not know...";
$l_log_title[LOG_ATTACK_EWD] = "Emergency warp!";
$l_log_text[LOG_ATTACK_EWDFAIL] = "Your sensors detect [player]'s ship on an attack vector. \"Better be safe than sorry\", you think, hitting the emergency warp button. You hear a strange choking sound coming from the engines room and smell burned circuitry. \"Stupid piece of crap!\", you yell, kicking at the computer. The computer emits beeps of protestation as you prepare for the incoming battle...";
$l_log_title[LOG_ATTACK_EWDFAIL] = "Emergency warp <font color=red>failed!</font>";
$l_log_text[LOG_ATTACK_LOSE] = "You ship is being attacked by [player]. Try as you might, you cannot defend yourself against [player]'s superior weaponry. Your ship was destroyed. ";
$l_log_title[LOG_ATTACK_LOSE] = "<font color=red>Combat lost!</font>";
$l_log_text[LOG_ATTACKED_WIN] = "You ship was attacked by [player]. You battle for a while, then the fight breaks down. You lost [armor] armor points and [fighters] fighters in the skirmish.";
$l_log_title[LOG_ATTACKED_WIN] = "<font color=yellow>Skirmish!</font>";
$l_log_text[LOG_TOLL_PAID] = "You had to pay [toll] credits to enter sector [sector]. You promise yourself that you'll find a way to get your money back.";
$l_log_title[LOG_TOLL_PAID] = "Extortion";
$l_log_text[LOG_HIT_MINES] = "You hit [mines] mines when travelling in sector [sector].";
$l_log_title[LOG_HIT_MINES] = "<font color=yellow>Mines alert!</font>";
$l_log_text[LOG_SHIP_DESTROYED_MINES] = "Your ship was destroyed by a minefield in sector [sector]. ";
$l_log_title[LOG_SHIP_DESTROYED_MINES] = "<font color=red>Mines alert!</font>";
$l_log_text[LOG_PLANET_DEFEATED_D] = "Your planet [planet_name] in sector [sector] was captured in battle by [name]. Fortunately, the strong loyalty of your citizens played in your favor. They have bravely chosen to destroy the planet rather than have it fall into enemy hands. You organize superb funerals in the memory of your faithful people.";
$l_log_title[LOG_PLANET_DEFEATED_D] = "<font color=yellow>Planet destroyed</font>";
$l_log_text[LOG_PLANET_DEFEATED] = "Your planet [planet_name] in sector [sector] was captured in battle by the wretched [name]. The people of the planet welcome their new ruler. You hear a testimony on BNN : \"We're glad to be rid of that old fart! We don't want no stinking loser who can't protect us!\". You swear to make them pay for their arrogance.";
$l_log_title[LOG_PLANET_DEFEATED] = "<font color=red>Planet captured!</font>";
$l_log_text[LOG_PLANET_NOT_DEFEATED] = "Your planet [planet_name] in sector [sector] was attacked by [name]. The citizens organized a valliant defense however, and managed to destroy the opponent. They salvage some resources from the space debris : [goods] goods, [ore] ore, [organics] organics and [salvage]% of the ship's worth of [credits] credits.";
$l_log_title[LOG_PLANET_NOT_DEFEATED] = "Victory!";
$l_log_title[LOG_RAW] = "Notice";
$l_log_text[LOG_TOLL_RECV] = "Your fighters in sector [sector] have collected a 'tax' of [toll] credits.";
$l_log_title[LOG_TOLL_RECV] = "Toll income";
$l_log_text[LOG_DEFS_DESTROYED] = "[quantity] [type] were destroyed in sector [sector].";
$l_log_title[LOG_DEFS_DESTROYED] = "Sector defenses destroyed";
$l_log_text[LOG_PLANET_EJECT] = "You have been ejected from the planet in sector [sector] because [name] left the alliance.";
$l_log_title[LOG_PLANET_EJECT] = "Ejected!";
$l_log_text[LOG_BADLOGIN] = "There has been a bad login attempt from [ip].";
$l_log_title[LOG_BADLOGIN] = "Bad login";
$l_log_text[LOG_PLANET_SCAN] = "[name] has scanned your planet [planet_name] in sector [sector].";
$l_log_title[LOG_PLANET_SCAN] = "Planet scan";
$l_log_text[LOG_PLANET_SCAN_FAIL] = "[name] has attempted to scan your planet [planet_name] in sector [sector], but failed.";
$l_log_title[LOG_PLANET_SCAN_FAIL] = "Planet scan failed";
$l_log_text[LOG_SHIP_SCAN] = "[player] has scanned your ship.";
$l_log_title[LOG_SHIP_SCAN] = "Ship scan";
$l_log_text[LOG_SHIP_SCAN_FAIL] = "[player] has attempted to scan your ship, but failed.";
$l_log_title[LOG_SHIP_SCAN_FAIL] = "Ship scan failed";
$l_log_text[LOG_FURANGEE_ATTACK] = "Attacking [player]...";
$l_log_title[LOG_FURANGEE_ATTACK] = "Attack";
$l_log_text[LOG_STARVATION] = "One of your planet in [sector] cannot sustain its population! More organics is needed. [starvation] colonists died of hunger.";
$l_log_title[LOG_STARVATION] = "<font color=yellow>Starvation!</font>";
$l_log_text[LOG_TOW] = "Your ship has been towed from sector [sector] to sector [newsector] because your hull size exceeded the limit value of [hull].";
$l_log_title[LOG_TOW] = "Towed!";
$l_log_text[LOG_DEFS_DESTROYED_F] = "You have destroyed [fighters] patrolling fighters in sector [sector].";
$l_log_title[LOG_DEFS_DESTROYED_F] = "Fighters destroyed";
$l_log_text[LOG_DEFS_KABOOM] = "You were destroyed by a fighters force in sector [sector]. ";
$l_log_title[LOG_DEFS_KABOOM] = "<font color=red>Ship destroyed!</font>";
$l_log_text[LOG_HARAKIRI] = "You were tired of captaining this space barge, so you decided the universe would be better without it. Authorized by [ip].";
$l_log_title[LOG_HARAKIRI] = "<font color=red>Self-destructed!</font>";
$l_log_text[LOG_TEAM_REJECT] = "[player] has rejected an invitation to join your alliance, [teamname].";
$l_log_title[LOG_TEAM_REJECT] = "Invitation rejected";
$l_log_text[LOG_TEAM_RENAME] = "You have renamed your alliance to [team].";
$l_log_title[LOG_TEAM_RENAME] = "Alliance renamed";
$l_log_text[LOG_TEAM_M_RENAME] = "Your alliance coordinator renamed the alliance to [team].";
$l_log_title[LOG_TEAM_M_RENAME] = "Alliance renamed";
$l_log_text[LOG_TEAM_KICK] = "You have been ejected from the alliance [team].";
$l_log_title[LOG_TEAM_KICK] = "Ejected from alliance!";
$l_log_text[LOG_TEAM_CREATE] = "You have created a new alliance, [team].";
$l_log_title[LOG_TEAM_CREATE] = "Created new alliance";
$l_log_text[LOG_TEAM_LEAVE] = "You have left alliance [team].";
$l_log_title[LOG_TEAM_LEAVE] = "Left alliance";
$l_log_text[LOG_TEAM_NEWLEAD] = "You have left the alliance [team]. You relinquished the alliance leadership to [name].";
$l_log_title[LOG_TEAM_NEWLEAD] = "Left alliance";
$l_log_text[LOG_TEAM_LEAD] = "Your alliance coordinator has decided to leave [team]. You have been appointed to take its place.";
$l_log_title[LOG_TEAM_LEAD] = "Promotion!";
$l_log_text[LOG_TEAM_JOIN] = "You have joined the alliance [team].";
$l_log_title[LOG_TEAM_JOIN] = "Joined alliance";
$l_log_text[LOG_TEAM_NEWMEMBER] = "[name] has accepted to join [team]. This brings you one step further to galactic domination.";
$l_log_title[LOG_TEAM_NEWMEMBER] = "New alliance member";
$l_log_text[LOG_TEAM_INVITE] = "You have been invited to be part of [team].";
$l_log_title[LOG_TEAM_INVITE] = "Invitation";
$l_log_text[LOG_TEAM_NOT_LEAVE] = "[player] has left your alliance.";
$l_log_title[LOG_TEAM_NOT_LEAVE] = "Alliance loses a member";
$l_log_text[LOG_ADMIN_HARAKIRI] = "[player] has self-destructed from ip [ip].";
$l_log_title[LOG_ADMIN_HARAKIRI] = "Self-destruct";
$l_log_text[LOG_ADMIN_ILLEGVALUE] = "[player] had [quantity] [type], with max holds of [holds]";
$l_log_title[LOG_ADMIN_ILLEGVALUE] = "Illegal ship value";
$l_log_text[LOG_ADMIN_PLANETDEL] = "[attacker] has attempted to capture [defender]'s planet in sector [sector]. Planet was destroyed instead.";
$l_log_title[LOG_ADMIN_PLANETDEL] = "Planet destroyed";
$l_log_text[LOG_DEFENCE_DEGRADE] = "Sector Defences Fighters in sector [sector] degraded by [degrade] percent due to insufficient energy.";
$l_log_test[LOG_DEFENCE_DEGRADE] = "Sector Defences degraded.";

// modify-defences.php

$l_md_title		 = "Sector Defences";
$l_md_invalid		 = "Invalid Sector Defence";
$l_md_nolonger		 = "The sector defence selected is no longer there.";
$l_md_you		 = "you";
$l_md_bmines		 = "Your beams destroyed";
$l_md_msgdownerb	 = "[name] destroyed [mines] mines in sector [sector].";
$l_md_retr		 = "You retrieved";
$l_md_mode		 = "The fighters selected have been set to [mode] mode.";
$l_md_consist		 = "This sector defence consists of [qty] [type] owned by [owner].";
$l_md_youcan		 = "You can";
$l_md_retrieve		 = "Retrieve";
$l_md_change		 = "Change Fighter settings";
$l_md_cmode		 = "Fighter mode";
$l_md_attack		 = "Attack";
$l_md_toll		 = "Toll";
$l_md_attdef		 = "Attack the Sector Defences. All sector fighters will retaliate.";

// news.php

$l_news_title		 = "BlackNova Universe News";
$l_news_info		 = "BNN is among the galaxy's leaders<br>
                            in news and information delivery.<br>
                            Staffed 24 hours, seven days a week by a <br>
                            dedicated staff in BNN's galaxy headquarters <br>
                            in Alpha Centaury and in bureaus galaxywide!";
$l_news_for		 = "News for";
$l_news_prev		 = "previous day";
$l_news_next		 = "next day";
$l_news_none		 = "Sorry, no news today.";
$l_news_flash		 = "News Flash";

// dump.php

$l_dump_title		 = "Dumping colonists";
$l_dump_turn		 = "You need at least one turn to dump colonists.";
$l_dump_nocol		 = "You have no colonists on your ship to begin with.";
$l_dump_dumped		 = "Colonists dumped at supply depot.";
$l_dump_nono		 = "You need to be at a supply depot to do this.";

// readmail.php

$l_readm_title		 = "Read Message";

$l_readm_delete		 = "MESSAGE DELETED";
$l_readm_nomessage	 = "You have no Messages waiting for you...";
$l_readm_center		 = "Message Receiving Center";
$l_readm_sender		 = "Message Sender";
$l_readm_captn		 = "Captain of the";
$l_readm_del		 = "Delete";
$l_readm_repl		 = "Reply";

// mailto2.php

$l_sendm_title		 = "Send Message";
$l_sendm_to		 = "To";
$l_sendm_from		 = "From";
$l_sendm_ally		 = "Alliance:";
$l_sendm_subj		 = "Subject";
$l_sendm_mess		 = "Message";
$l_sendm_send		 = "Send";
$l_sendm_sent		 = "Message Sent";

// zoneinfo.php

$l_zi_title		 = "Zone Information";
$l_zi_nexist		 = "This section of space does not exist!";
$l_zi_feds		 = "Federation";
$l_zi_traders		 = "The Free-Trade Coalition";
$l_zi_nobody		 = "Nobody";
$l_zi_war		 = "Contested space";
$l_zi_allow		 = "Allowed";
$l_zi_notallow		 = "Not allowed";
$l_zi_limit		 = "Limited to owner and allies";
$l_zi_ul		 = "Unlimited";
$l_zi_control		 = "You are in control of this zone";
$l_zi_tochange		 = "to change its laws.";
$l_zi_owner		 = "Zone owner";
$l_zi_maxhull		 = "Maximum hull size allowed";

// zoneedit.php

$l_ze_title		 = "Edit Zone";
$l_ze_notowner		 = "You are not owner of this zone so you can't edit it.";
$l_ze_name		 = "Zone name";
$l_ze_allow		 = "Allow";
$l_ze_attacks		 = "Allow attacking other ships";
$l_ze_genesis		 = "Allow creating new planets";
$l_ze_return		 = "to return to the zone information page";
$l_ze_saved		 = "Your changes have been saved.";

// teams.php

$l_team_title		 = "Alliances";
$l_team_menu		 = "to go back to the Alliances Menu";
$l_team_galax		 = "Alliances present in the Galaxy:";
$l_team_members		 = "Members";
$l_team_coord		 = "Co-ordinator";
$l_team_member		 = "Member";
$l_team_noinvite	 = "Nobody has invited you to join an alliance.";
$l_team_ifyouwant	 = "If you want to join an alliance, send a message to its co-ordinator asking to be invited.";
$l_team_tocreate	 = "to create a new alliance.";
$l_team_injoin		 = "You have been invited to join";
$l_team_tojoin		 = "to join";
$l_team_or		 = "or";
$l_team_reject		 = "to reject the invitation.";
$l_team_ed		 = "Edit";
$l_team_inv		 = "Invite";
$l_team_leave		 = "Leave";
$l_team_eject		 = "Eject";
$l_team_pending		 = "Invitation pending for";
$l_team_noinvites	 = "Nobody has been invited to be part of";
$l_team_confirmleave	 = "Are you sure you want to leave";
$l_team_onlymember	 = "You were the only member, thus [team_name] is no more.";
$l_team_youarecoord	 = "You are the co-ordinator of";
$l_team_relinq		 = "You must relinquish your role to another player.";
$l_team_newc		 = "New co-ordinator:";
$l_team_youveleft	 = "You have left alliance";
$l_team_relto		 = "relinquishing the functions of co-ordinator to";
$l_team_welcome		 = "Welcome to alliance";
$l_team_noinviteto	 = "You have not been invited in to that team.";
$l_team_ejectsure	 = "Are you sure you want to eject";
$l_team_ejected 	 = "has been eject from the alliance!";
$l_team_testing		 = "Testing phase...";
$l_team_pw		 = "Password";
$l_team_entername	 = "Enter the name of the Alliance";
$l_team_enterdesc	 = "Enter a description of the Alliance";
$l_team_hcreated	 = "has been created and you are its leader";
$l_team_alliance	 = "Alliance";
$l_team_selectp		 = "Select the Player you want to invite";
$l_team_isorry		 = "Sorry, but [name] has already been invited to be part of an alliance - only one invitation can be active at any given time";
$l_team_plinvted	 = "Player invited.<BR>You must wait for that player to aknowledge your invitation.";
$l_team_refuse		 = "You have refused the invitation to join";
$l_team_edname		 = "Edit the name of your Alliance";
$l_team_eddesc		 = "Edit the description for your Alliance";
$l_team_hasbeenr	 = "has been renamed.";
$l_team_error		 = "<b><font color=red>An error occured</font></b><br>You are not the leader of this Alliance.";
$l_team_notmember	 = "You are not a member of any alliance";
$l_team_urejected	 = "<B>ATTENTION</B> - you have been ejected from";
$l_team_noalliances	 = "There are no alliances in the Galaxy at this time.";

// ranking.php

$l_ranks_title		 = "Top $max_rank Players";
$l_ranks_none		 = "No Results to show.";
$l_ranks_pnum		 = "Total number of players";
$l_ranks_dships		 = "Players with destroyed ships are not counted.";
$l_ranks_rank		 = "Rank";
$l_ranks_lastlog	 = "Last login";
$l_ranks_good		 = "Good";
$l_ranks_evil		 = "Evil";

// beacon.php

$l_beacon_title		 = "Deploy Space Beacon";
$l_beacon_notpermitted	 = "Deploying space beacons in this sector is not permitted.";
$l_beacon_reads		 = "Present beacon reads";
$l_beacon_none		 = "There presently isn't a beacon in this sector.";
$l_beacon_enter		 = "Enter text for beacon";
$l_beacon_nowreads	 = "Beacon now reads";
$l_beacon_donthave	 = "You do not have a space beacon.";

// emerwarp.php

$l_ewd_title		 = "Use Emergency Warp Device";
$l_ewd_used		 = "Emergency warp device engaged - arrived in sector [sector].";
$l_ewd_none		 = "You do not have an emergency warp device.";

// defence-report.php

$l_sdf_title		 = "Sector Defence Report";
$l_sdf_none		 = "You have no sector defences deployed.";
$l_sdf_type		 = "Type";
$l_sdf_mode		 = "Mode";

// traderoute.php
// cause its rather big i put everything in own vars than to re-use
// the old ones so we could export to own file if performance problems
// should occur

$l_tdr_title    	 = "Trade Routes";
$l_tdr_newtdr   	 = "Click <a href=\"traderoute.php?command=new\">here</a> to 
create a new trade route";
$l_tdr_modtdrset         = "To modify your global trade settings, click <a 
href=\"traderoute.php?command=settings\">here</a>";
$l_tdr_confdel  	 = "Click <a 
href=\"traderoute.php?command=delete&confirm=yes&traderoute_id=[tdr_id]\">here</a> 
to confirm deletion of the following trade route :";
$l_tdr_noactive 	 = "You do not have any active trade routes to display.";
$l_tdr_curtdr   	 = "Current Trade Routes";
$l_tdr_deltdr   	 = "Delete Trade Route";
$l_tdr_src      	 = "Source";
$l_tdr_srctype  	 = "Src Type";
$l_tdr_dest     	 = "Destination";
$l_tdr_desttype 	 = "Dest Type";
$l_tdr_move     	 = "Move";
$l_tdr_circuit  	 = "Circuit";
$l_tdr_change   	 = "Change";
$l_tdr_portin   	 = "Port in";
$l_tdr_planet   	 = "Planet";
$l_tdr_nonexistance      = "Non-existant planet!";
$l_tdr_na       	 = "N/A";
$l_tdr_cargo    	 = "Cargo";
$l_tdr_none     	 = "None";
$l_tdr_colonists         = "Colonists";
$l_tdr_fighters 	 = "Fighters";
$l_tdr_torps    	 = "Torpedoes";
$l_tdr_escooped 	 = "[tdr_dist_triptime] turns<br>[tdr_dist_scooped] energy 
scooped";
$l_tdr_warp     	 = "Warp";
$l_tdr_turns    	 = "turns";
$l_tdr_way      	 = "way";
$l_tdr_ways     	 = "ways";
$l_tdr_edit     	 = "Edit";
$l_tdr_del      	 = "Delete";
$l_tdr_nowlink1 	 = "There is no warp link from sector [tdr_src_sector_id] to 
sector [tdr_dest_sector_id]";
$l_tdr_nowlink2 	 = "There is no warp link from sector [tdr_dest_sector_id] to 
sector [tdr_src_sector_id]";
$l_tdr_sportissrc        = "If a special port is source, a planet must be the 
destination for colonization.";
$l_tdr_notownplanet      = "You can't colonize a planet that you or your team 
don't own.";
$l_tdr_planetisdest      = "A planet can be a destination only when source is 
a special port.";
$l_tdr_samecom 		 = "You can't make a traderoute for ports selling the same 
commodities.";
$l_tdr_sportcom 	 = "You can't sell commodities from a planet in a special 
port.";
$l_tdr_editerr  	 = "Edit error : trade route not found in DB";
$l_tdr_maxtdr   	 = "Sorry you have reached the maximum number of trade routes 
allowed.";
$l_tdr_createnew         = "Creating a new";
$l_tdr_editinga 	 = "Editing a";
$l_tdr_traderoute        = "trade route";
$l_tdr_unnamed  	 = "Unnamed";
$l_tdr_cursector         = "You are currently in sector";
$l_tdr_selspoint         = "Please select starting point :";
$l_tdr_port     	 = "Port";
$l_tdr_insector 	 = "in sector";
$l_tdr_selendpoint       = "Please select ending point";
$l_tdr_selmovetype       = "Please select move type";
$l_tdr_realspace         = "Real Space";
$l_tdr_selcircuit        = "Please select circuit";
$l_tdr_oneway   	 = "One way";
$l_tdr_errnotvalidport   = "Error : the source port [tdr_port_id] does not 
seem to be valid.";
$l_tdr_bothways 	 = "Both ways";
$l_tdr_create   	 = "Create";
$l_tdr_modify   	 = "Modify";
$l_tdr_returnmenu        = "Click <a href=traderoute.php>here</a> to return to 
the trade routes menu.";
$l_tdr_errnotvalidport   = "Error : the source port [tdr_port_id] is not a 
valid port.";
$l_tdr_errnoport         = "Error : there is no port at sector [tdr_port_id].";
$l_tdr_errnosrc    	 = "Error : specified source planet doesn't exist.";
$l_tdr_errnotownnotsell  = "Error : you do not own planet [tdr_source_name] 
in sector [tdr_source_sector_id] and planet is not selling.";
$l_tdr_errnotvaliddestport= "Error : the destination port [tdr_port_id] 
is not a valid port.";
$l_tdr_errnoport2        = "Error : there is no port at sector [tdr_port_id].";
$l_tdr_errnodestplanet   = "Error : specified destination planet does not 
exist.";
$l_tdr_errnotownnotsell2 = "Error : you do not own planet [tdr_dest_name] in sector [tdr_dest_sector_id] and planet is not selling.";
$l_tdr_newtdrcreated     = "New trade route created!";
$l_tdr_tdrmodified       = "Trade route modified!";
$l_tdr_doesntexist       = "That trade route doesn't exist!";
$l_tdr_notowntdr         = "You do not own that traderoute!";
$l_tdr_tdrdeleted        = "Trade route deleted.";
$l_tdr_globalset         = "Global trade route settings";
$l_tdr_tdrsportsrc       = "For trade routes having a special port as a 
source, trade";
$l_tdr_tdrescooped       = "For real space trade routes, what to do with the 
energy scooped?";
$l_tdr_trade    	 = "Trade";
$l_tdr_keep    	 	 = "Keep";
$l_tdr_save    	 	 = "Save";
$l_tdr_globalsetsaved    = "Global trade route settings saved.";
$l_tdr_engagenonexist    = "Tried to engage a non-exiDestination sector does 
not seem to be valid!sting trade route!";
$l_tdr_invalidspoint     = "Starting port does not seem to be valid!";
$l_tdr_inittdr  	 = "You are not in sector [tdr_source_id]! You must be in 
starting sector before you initiate a trade route!";
$l_tdr_invalidsrc        = "Source planet doesn't seem to be a valid planet!";
$l_tdr_inittdrsector     = "You are not in sector [tdr_source_sector_id]! You 
must be in starting sector before you initiate a trade route!";
$l_tdr_notyourplanet     = "You do not own planet [tdr_source_name] in sector 
[tdr_source_sector_id]!";
$l_tdr_invalidssector    = "Starting sector does not seem to be valid!";
$l_tdr_invaliddport      = "Destination port does not seem to be valid!";
$l_tdr_invaliddplanet    = "Destination planet doesn't seem to be a valid 
planet!";
$l_tdr_invaliddsector    = "Destination sector does not seem to be valid!";
$l_tdr_moreturnsneeded   = "This trade route requires [tdr_dist_triptime] 
turns to complete. You only have [tdr_playerinfo_turns] left.";
$l_tdr_tdrhostdef        = "You can not use trade routes between sectors with 
hostile defences. You must defeat the defences first.";
$l_tdr_globalsetbuynothing= "Your global settings are set to buy 
nothing! You would only waste turns doing this route!";
$l_tdr_nosrcporttrade    = "Trading from source port is not allowed.";
$l_tdr_tradesrcportoutsider= "Trading at source port is not allowed for 
outsiders";
$l_tdr_nodestporttrade   = "Trading from destination port is not allowed.";
$l_tdr_tradedestportoutsider= "Trading at destination port is not allowed 
for outsiders";
$l_tdr_notyourplanet     = "You do not own planet [tdr_source_name] in sector 
[tdr_source_sector_id]!";
$l_tdr_invalidssector    = "Starting sector does not seem to be valid!";
$l_tdr_invaliddport      = "Destination port does not seem to be valid!";
$l_tdr_invaliddplanet    = "Destination planet doesn't seem to be a valid 
planet!";
$l_tdr_invaliddsector    = "Destination sector does not seem to be valid!";
$l_tdr_moreturnsneeded   = "This trade route requires [tdr_dist_triptime] 
turns to complete. You only have [tdr_playerinfo_turns] left.";
$l_tdr_tdrhostdef        = "You can not use trade routes between sectors with 
hostile defences. You must defeat the defences first.";
$l_tdr_globalsetbuynothing= "Your global settings are set to buy 
nothing! You would only waste turns doing this route!";
$l_tdr_nosrcporttrade    = "Trading from source port is not allowed.";
$l_tdr_tradesrcportoutsider= "Trading at source port is not allowed for 
outsiders";
$l_tdr_nodestporttrade   = "Trading from destination port is not allowed.";
$l_tdr_tradedestportoutsider= "Trading at destination port is not allowed 
for outsiders";
$l_tdr_tdrres  		 = "Trade Route Results";
$l_tdr_bought  		 = "Bought";
$l_tdr_nothingtotrade    = "Nothing to trade";
$l_tdr_sold   	  	 = "Sold";
$l_tdr_ore    		 = "Ore";
$l_tdr_portisfull        = "Port is full";
$l_tdr_goods    	 = "goods";
$l_tdr_organics 	 = "organics";
$l_tdr_energy   	 = "energy";
$l_tdr_portisempty       = "Port is empty";
$l_tdr_loaded   	 = "Loaded";
$l_tdr_nothingtoload     = "Nothing to load";
$l_tdr_scooped  	 = "Scooped";
$l_tdr_dumped   	 = "Dumped";
$l_tdr_planetisovercrowded= "Planet is overcrowded";
$l_tdr_nothingtodump     = "Nothing to dump";
$l_tdr_onlyonewaytdr     = "Did nothing, traderoute was one way only";
$l_tdr_profit 		 = "Profit";
$l_tdr_cost   		 = "Cost";
$l_tdr_totalprofit       = "Total profit";
$l_tdr_totalcost         = "Total cost";
$l_tdr_credits  	 = "Credits";
$l_tdr_turnsused         = "Turns used";
$l_tdr_turnsleft         = "Turns left";
$l_tdr_engageagain       = "Click <A 
HREF=\"traderoute.php?engage=[tdr_engage]\">here</A> to do this trade route 
again.";

// IGB.php

$l_igb_title    = "The Intergalactic Bank";
$l_igb_malfunction      = "This IGB terminal is malfunctionning. The Intergalatic Bank wishes to apologize for any inconvenience.";
$l_igb_quit     = "Quit";
$l_igb_login    = "Login";
$l_igb_welcometoigb     = "Welcome to this Intergalactic Banking Terminal";
$l_igb_accountholder    = "Account Holder";
$l_igb_shipaccount      = "Ship Account";
$l_igb_igbaccount       = "IGB Account";
$l_igb_operations       = "Operations";
$l_igb_withdraw = "Withdraw";
$l_igb_deposit  = "Deposit";
$l_igb_transfer = "Transfer";
$l_igb_back     = "Back";
$l_igb_logout   = "Logout";
$l_igb_withdrawfunds    = "Withdraw Funds";
$l_igb_fundsavailable   = "Funds available";
$l_igb_selwithdrawamount        = "Please select amount to withdraw";
$l_igb_depositfunds     = "Deposit Funds";
$l_igb_seldepositamount = "Please select amount to deposit";
$l_igb_transfertype     = "Transfer Type";
$l_igb_toanothership    = "To another ship";
$l_igb_shiptransfer     = "Ship Transfer";
$l_igb_fromplanet       = "From a planet to another";
$l_igb_unnamed  = "Unnamed";
$l_igb_in       = "in";
$l_igb_none     = "None";
$l_igb_destination      = "Destination";
$l_igb_planettransfer   = "Planet Transfer";
$l_igb_sendyourself     = "You can't send money to yourself!";
$l_igb_unknowntargetship        = "Unknown target ship!";
$l_igb_min_turns        = "Player [igb_target_char_name] must have played at least [igb_min_turns] turns before he can receive money.";
$l_igb_min_turns2       = "You must have played at least [igb_min_turns] turns before you can send money.";
$l_igb_mustwait = "You have already made a transfer to [igb_target_char_name] in the last [igb_trate] minutes. You must wait [igb_difftime] minutes before you can transfer credits to that player again.";
$l_igb_maxtransfer      = "Maximum transfer allowed";
$l_igb_unlimited        = "Unlimited";
$l_igb_maxtransferpercent       = "Maximum transfer allowed ([igb_percent]% of net worth)";
$l_igb_recipient        = "Recipient";
$l_igb_seltransferamount        = "Please select amount to transfer";
$l_igb_transferrate     = "Current rate for transfers is [igb_num_percent]% of total amount. It will automatically be deduced from the amount you transfer.";
$l_igb_errplanetsrcanddest      = "The same planet can't be both source and destination.";
$l_igb_errunknownplanet = "DB Error! Unknown Planet!";
$l_igb_errnotyourplanet = "You can't transfer money from/to a planet you do not own.";
$l_igb_srcplanet        = "Src -> Planet";
$l_igb_destplanet       = "Dst -> Planet";
$l_igb_transferrate2     = "Current rate for transfers is [igb_num_percent]% of total amount. It will automatically be deduced from the amount you transfer.";
$l_igb_errsendyourself  = "You can't send money to yourself!";
$l_igb_min_turns3        = "Player [igb_target_char_name] must have played at least [igb_min_turns] turns before he can receive money.";
$l_igb_min_turns4       = "You must have played at least [igb_min_turns] turns before you can send money.";
$l_igb_mustwait2 = "You have already made a transfer to [igb_target_char_name] in the last [igb_trate] minutes. You must wait [igb_difftime] minutes before you can transfer credits to that player again.";
$l_igb_invalidtransferinput     = "Invalid input for transfer.";
$l_igb_nozeroamount     = "Amount to transfer must not be zero.";
$l_igb_notenoughcredits = "You do not have enough credits to perform this operation.";
$l_igb_amounttoogreat   = "The amount you entered was greater than your maximum transfer allowed.";
$l_igb_transfersuccessful       = "Transfer Successful";
$l_igb_creditsto        = "credits have been transferred to";
$l_igb_transferamount   = "Transfer Amount";
$l_igb_transferfee      = "Transfer Fee";
$l_igb_amounttransferred        = "Amount Transferred";
$l_igb_notenoughcredits2        = "There are not enough credits on source planet to complete that transaction.";
$l_igb_to       = "to";
$l_igb_ctransferredfrom = "credits have been transferred from";
$l_igb_invaliddepositinput      = "Invalid input for deposit.";
$l_igb_nozeroamount2    = "Amount to deposit must not be zero.";
$l_igb_operationsuccessful      = "Operation successful";
$l_igb_creditstoyou     = "Credits have been transfered to your IGB account.";
$l_igb_accounts = "Accounts";
$l_igb_invalidwithdrawinput     = "Invalid input for withdraw.";
$l_igb_nozeroamount3    = "Amount to withdraw must not be zero.";
$l_igb_creditstoyourship        = "Credits have been transfered to your ship account.";
$l_igb_igberrreport     = "IGB Error Report";
$l_igb_source   = "Source";
?>
