<?php

//general

$l_yes 			 = "Oui";
$l_no			 = "Non";
$l_here			 = "ici";
$l_submit		 = "Envoyer";
$l_reset		 = "Restaurer";
$l_all			 = "Tout";

$l_ore			 = "Métaux";
$l_organics		 = "Végétaux";
$l_goods		 = "Produits";
$l_energy		 = "Énergie";
$l_colonists		 = "Colons";
$l_credits 		 = "Crédits";
$l_units		 = "unités de ";

$l_cargo		 = "Cargaison";
$l_fighters		 = "Intercepteurs ";
$l_mines		 = "Mines ";
$l_torps		 = "Torpilles";

$l_none			 = "Aucun";
$l_unnamed		 = "Sans Nom";
$l_name			 = "Nom";
$l_unowned		 = "Libre";
$l_unknown		 = "Inconnu";
$l_clickme 		 = "Cliquer ici";
$l_player  		 = "Joueur";
$l_ship			 = "Vaisseau";
$l_set			 = "Mod";
$l_realspace		 = "Espace Réel";
$l_armourpts		 = "Points d'armure";


// main.php

$l_main_title 		 = "Menu Principal";

$l_traderoutes		 = "Commerce";
$l_trade_control	 = "Modifier";

$l_youhave 		 = "Vous avez ";
$l_turns_used		 = "Tours utilisés: ";
$l_turns_have		 = "Tours disponibles: ";
$l_score		 = "Points: ";
$l_sector		 = "Secteur";
$l_help			 = "Aide";
$l_faq		         = "FAQ";
$l_feedback		 = "Commentaires";
$l_forums		 = "Forums";
$l_logout		 = "Quitter";

$l_commands		 = "Commandes";
$l_command_no		 = "Commande non disponible.";
$l_devices		 = "Appareils";
$l_planets		 = "Planètes";
$l_log			 = "Journal";
$l_sector_def		 = "Défenses";
$l_defense		 = "Défenses";
$l_read_msg		 = "Lire Messages";
$l_send_msg		 = "Écrire Messages";
$l_rankings		 = "Rangs";
$l_teams		 = "Alliances";
$l_ohno			 = "Auto-Destruction";
$l_options		 = "Options";
$l_navcomp		 = "Ordinateur";

$l_incompletemove 	 = "Vous n'avez pas complété votre dernier déplacement.";
$l_clicktocontinue	 = "Cliquez ici pour continuer";
$l_toplanetmenu   	 = "Pour aller au menu de planète.";
$l_nonexistant_pl	 = "Sur une planète qui n'existe pas???";
$l_abord		 = ", à bord du ";
$l_messages_wait	 = " Messages qui vous attendent.";

$l_no_warplink		 = "Aucun liens";
$l_scan			 = "sonder";
$l_fullscan		 = "Sonder tout";

$l_port			 = "Port";
$l_tradingport		 = "Port commercial";
$l_planet_in_sec	 = "Planètes dans le secteur ";
$l_ships_in_sec		 = "Autres vaisseaux dans le secteur ";
$l_sector_0		 = "Il y a tellement de déplacements dans Sol (Secteur 0) que vous ne pouvez distinguer les vaisseaux entre eux!";

// report.php

$l_report_title		 = "État du vaisseau";

$l_level		 = "Niveau";

$l_ship_levels		 = "Niveau des composants";
$l_hull			 = "Coque";
$l_engines		 = "Moteurs";
$l_power		 = "Puissance";
$l_computer		 = "Ordinateur";
$l_sensors		 = "Sondeurs";
$l_armour		 = "Armure";
$l_shields		 = "Boucliers";
$l_beams		 = "Rayons";
$l_torp_launch	         = "Lanceurs de torpilles";
$l_cloak		 = "Camouflage";
$l_holds		 = "Cargaison";
$l_deflect		 = "Déflecteurs (mines)";
$l_ewd			 = "Hyper-espace d'urgence";


$l_arm_weap		 = "Armes & Armures";
$l_beacons		 = "Bouées Spatiales";
$l_warpedit		 = "Éditeurs de liens";
$l_genesis		 = "Torpilles Genesis";
$l_escape_pod		 = "Module de secours";
$l_fuel_scoop		 = "Collecteur d'énergie";

// device.php

$l_device_title		 = "Appareils";

$l_device_expl		 = "Votre vaisseau est équippé des appareils suivants (Cliquez sur un appareil pour l'utiliser) :";
$l_device		 = "Appareil";
$l_qty			 = "Quantité";
$l_usage		 = "Utilisation";
$l_manual		 = "Manuel";	
$l_automatic		 = "Automatique";

// port.php port2.php

$l_trade		 = "Acheter/Vendre";
$l_title_port		 = "Port Commercial";
$l_title_trade		 = "Commerce de biens";
$l_sector_war		 = "Embargo de guerre";
$l_war_info		 = "La guerre fait rage dans ce secteur. Vous ne pouvez atteindre le port à travers les forces hostiles.";
$l_no_trade		 = "Commerce interdit";
$l_no_trade_out		 = "Le commerce à ce port n'est pas permis pour les étrangers";
$l_no_trade_info	 = "Le commerce à ce port est interdit.";
$l_buying		 = "Achète";
$l_selling		 = "Vends";
$l_commodity		 = "Commodité";
$l_amount		 = "Quantité";
$l_price		 = "Prix";
$l_buy			 = "Acheter";
$l_sell			 = "Vendre";
$l_trade_st_info	 = "Vous avez [free_holds] unités d'espace libre, pouvez transporter [free_power] unités d'énergie additionnelles et vous disposez de [credits] crédits.";
$l_special_port		 = "Port Spécial";
$l_no_credits		 = "Pas assez de crédits";
$l_creds_to_spend	 = "Vous avez [credits] crédits à dépenser.";
$l_cost			 = "Coût";
$l_avail		 = "Disponible";
$l_profit		 = "Profit";
$l_current		 = "Présent";
$l_current_qty		 = "Quantités présentes";
$l_max			 = "Max";
$l_ifyouneedmore	 = "Si vous avez besoin de plus de crédits vous pouvez accéder au [igb] ";
$l_ifyouneedplan	 = "Accéder au ";
$l_igb_term		 = "Terminal Bancaire IGB";
$l_upgrade		 = "Améliorer?";
$l_unlimited		 = "Illimité";
$l_full			 = "Plein";
$l_equipped		 = "Équippé";
$l_n_a			 = "N/D";
$l_item			 = "Item";
$l_totalcost		 = "Coût Total";
$l_would_dump	         = "Si vous aimeriez laisser tous les colons que vous transportez ici, cliquez ";
$l_noport		 = "Il n'y a aucun port ici!";
$l_trade_turnneed	 = "Vous avez besoin d'au moins un tour pour faire du commerce à un port ou planète.";
$l_returnto_port         = " Cliquer <A HREF=port.php3>ici</A> pour retourner au menu du port.";
$l_notenough_cargo	 = "Vous n'avez pas assez d'espace pour stocker les commodités que vous voulez acheter.";
$l_notenough_power	 = "Vous ne disposez pas d'assez de puissance pour stocker l'énergie que vous voulez acheter.";
$l_notenough_credits	 = "Vous n'avez pas suffisament de crédits pour conclure cette transaction.";
$l_notenough_turns	 = "Vous n'avez pas suffisament de tours pour conclure cette transaction.";
$l_notenough_ore	 = "Vous ne disposez pas d'assez de métaux pour conclure cette transaction.";
$l_notenough_goods	 = "Vous ne disposez pas d'assez de produits pour conclure cette transaction.";
$l_notenough_energy	 = "Vous ne disposez pas d'assez d'énergie pour conclure cette transaction.";
$l_notenough_organics	 = "Vous ne disposez pas d'assez de végétaux pour conclure cette transaction.";
$l_exceed_organics	 = "Le nombre de végétaux dépasse l'offre/demande.  ";
$l_exceed_ore            = "Le nombre de métaux dépasse l'offre/demande.  ";
$l_exceed_energy         = "Le nombre d'énergie dépasse l'offre/demande.  ";
$l_exceed_goods          = "Le nombre de produits dépasse l'offre/demande.  ";
$l_trade_result		 = "Résultats pour cette transaction:";
$l_traded_ore		 = "Métaux échangés";
$l_traded_goods		 = "Produits échangés";
$l_traded_organics	 = "Végétaux échangés";
$l_traded_energy	 = "Énergie Échangée";
$l_trade_complete	 = "Transaction complète";
$l_trade_upgraded = "Amélioré";
$l_trade_added = "ajoutés";
$l_trade_installed = "installé";


// planet.php planet2.php planet3.php
$l_planet_title		 = "Menu de planète";
$l_planet_none		 = "Vous n'êtes pas dans le même secteur que cette planète, alors vous ne pouvez interagir avec elle.";
$l_planet_capture1	 = "capturer"; // thats the link's text
$l_planet_capture2	 = "Vous pouvez [capture] la planète ou simplement la laisser sans défense.";
$l_planet_unowned	 = "Cette planète n'a aucun propriétaire";
$l_planet_unnamed        = "Bienvenue sur la planète de [name]";
$l_planet_named		 = "Bienvenue sur [planetname], appartenant à [name].";
$l_planet_onsurface	 = "Vous êtes présentement sur la surface de la planète.";
$l_planet_orbit 	 = "Vous êtes présentement en orbite autour de la planète.";
$l_planet_leave_link     = "Décoller";
$l_planet_leave          = "[leave] de la planète";
$l_planet_land_link      = "Atterir";
$l_planet_land           = "[land] sur la planète";
$l_planet_name_link = "Nommer";
$l_planet_name2 = "[name] la planète";
$l_planet_logout	 = "Vous pouvez aussi <a href=logout.php3>Quitter</a> le jeu sous la protection de votre planète.";
$l_planet_selling	 = "La planète vend des commodités. ";
$l_planet_not_selling    = "La planète ne vend aucune commodité. ";
$l_planet_transfer_link	 = "Transférer";
$l_planet_transfer	 = "[transfer] des commodités/ressources/colons de/sur la planète";
$l_planet_hasbase	 = "Vous avez une base sur cette planète.";

$l_planet_perc		 = "Pourcentages de production";
$l_planet_interest	 = "* La production de crédits, mis à part les intérêts bancaires, est 100 - production d'autres commodités";
$l_planet_update	 = "Changer";
$l_planet_tsell_link	 = "vente";
$l_planet_tsell		 = "Changer la [selling] de commodités";
$l_planet_bbase_link	 = "construire une base";
$l_planet_bbase		 = "Avec assez de commodités et de crédits, vous pouvez [build] pour aider à la defense de votre planète.";
$l_planet_bbuild	 = "Base construite";
$l_planet_mcorp_linkC	 = "Planète Corporative";
$l_planet_mcorp_linkP	 = "Planète Personnelle";
$l_planet_mcorp		 = "Vous pouvez faire de cette planète une [planet].";
$l_planet_buy_link	 = "Acheter";
$l_planet_buy		 = "[buy] des commodités de la planète";
$l_planet_att_link	 = "Attaquer";
$l_planet_att		 = "[attack] la planète";
$l_planet_att_sure	 = "Êtes vous CERTAIN...";
$l_planet_scn_link	 = "Sonder";
$l_planet_scn		 = "[scan] la planète";
$l_planet_nowsell        = "La planète vend maintenant des commodités.";
$l_planet_nownosell      = "La planète ne vend plus de commodités.";
$l_planet_iname		 = "Entrer le nouveau nom de la planète";
$l_planet_cname		 = "La planète à été renommée ";
$l_planet_landed	 = "Vous avez atteri sur la surface de la planète.";
$l_planet_left		 = "Vous n'êtes plus sur la surface de la planète.";
$l_planet_cinfo		 = "Vous avez de la place pour [cargo] unités de cargaison supplémentaires.  Vous avez la capacité pour [energy] unités d'énergie en plus.";
$l_planet_toplanet	 = "Vers la planète?";
$l_planet_baseinfo	 = "Pour construire une base vous devez avoir au moins $base_credits crédits, $base_ore unités de métaux, $base_organics unités végétaux, et $base_goods unités of produits sur la planète.";
$l_planet_p_under        = "Vous ne pouvez choisir un nombre négatif pour un pourcentage de production.";
$l_planet_p_over	 = "La somme des pourcentages de production ne peut dépasser 100%.";
$l_planet_p_changed	 = "Les pourcentages de production ont été modifiés.";
$l_plant_scn_turn	 = "Vous avez besoin d'au moins un tour pour sonder une planète.";
$l_planet_noscan	 = "Les sondeurs ne parviennent pas à se vérouiller sur la cible!";
$l_planet_scn_report	 = "Résultat de la sonde sur [name], appartenant à:  [owner]";
$l_base	  		 = "Base";
$l_planet_ison		 = "est sur la planète.";
$l_planet_captured	 = "Planète capturée";
$l_planet_notdef	 = "La planète n'a pas été vaincue!";

$l_planet2_title	 = "Transfer Planétaire";
$l_planet2_noturn	 = "Vous avez besoin d'au moins un tour pour effectuer un transfer.";
$l_planet2_noten 	 = "Vous n'avez pas assez de ";
$l_planet2_fortr	 = "pour effectuer le transfer.";
$l_planet2_settr	 = "La quantité transférée ajustée à ";
$l_planet2_losup	 = "La planète est capable de fournir seulement ";
$l_planet2_notowner	 = "Cette planète ne vous appartient pas.";
$l_planet2_compl	 = "Transfer complété.";
$l_planet2_power	 = "puissance";
$l_planet2_comp 	 = "ordinateurs";
$l_planet2_laun 	 = "lanceurs de torpilles";
$l_planet2_nocorptransfer = "Vous ne pouvez transferer des crédits sur une planète corporative.";

$l_planet3_title	 = "Commerce de planète";

// planet-report.php

$l_pr_title		 = "Rapport des planètes";
$l_pr_teamlink		 = "Montrer les planètes de votre alliance";
$l_pr_noplanet		 = "Vous ne possédez aucune planète.";
$l_pr_clicktosort	 = "Cliquez sur un en-tête pour trier les résultats.";
$l_pr_totals		 = "Totaux";

// rsmove.php
$l_rs_title 		= "Déplacement en espace réel";
$l_rs_whichsector       = "Quel secteur aimeriez-vous atteindre à travers l'espace réel?";
$l_rs_insector		= "Vous êtes présentement dans le secteur [sector] - et les secteurs disponibles vont de 0 à [sector_max].";
$l_rs_submit		= "Calculer";
$l_rs_movetime		= "Avec vos moteurs, vous prendrez [triptime] tours pour compléter le voyage.";
$l_rs_energy		= "Vous collecterez [energy] unités d'énergie";
$l_rs_noturns		= "Vous n'avez pas assez de tours disponibles, donc vous ne pouvez faire ce voyage.";
$l_rs_engage_link	= "activer";
$l_rs_engage		= "Vous avez [turns] tours. [engage] les moteurs?";

$l_rs_invalid		= "Destination non-valide";
$l_rs_ready 		= "Vous êtes maintenant dans le sector [sector]. Vous avez utilisé [triptime] tours et collecté [energy] unités d'énergie.";

// navcomp.php	

$l_nav_title		 = "Ordinateur de bord";
$l_nav_nocomp		 = "L'ordinateur de bord n'est pas disponible";
$l_nav_query		 = "Entrez le sector que vous voudriez atteindre: ";
$l_nav_pathfnd		 = "Chemin trouvé:";
$l_nav_answ1		 = "Vous utiliserez";
$l_nav_answ2		 = "tours pour atteindre ce secteur.";
$l_nav_proper		 = "La technologie de votre ordinateur est trop primitive pour calculer un chemin jusqu'à ce secteur.";


// attack.php

$l_att_title		 = "Attaque de vaisseau";
$l_att_notarg		 = "La cible n'est pas dans ce secteur.";
$l_att_noturn		 = "Vous avez besoin d'au moins un tour pour pouvoir attaquer.";
$l_att_noatt		 = "Il n'est pas permis d'attaquer quelqu'un dans ce secteur.";
$l_att_flee		 = "Le vaisseau ennemi vous échape!";
$l_att_ewd		 = "Le vaisseau est entré d'urgence dans l'hyper-espace quand vous l'avez attaqué!";
$l_att_att		 = "Attaque sur ";
$l_att_beams		 = "Rayons touchent:";
$l_att_torps		 = "Torpilles touchent:";
$l_att_fighters		 = "Intercepteurs attaquent:";
$l_att_lost		 = "a perdu";
$l_att_ylost		 = "Vous avez perdu";
$l_att_sdown		 = " -> Boucliers tombent!";
$l_att_ydown		 = "Vos boucliers sont tombés!";
$l_att_shits		 = " -> Boucliers touchés de";
$l_att_yhits		 = "Vos boucliers sont touchés de";
$l_att_dmg		 = "points de dommage";
$l_att_sarm		 = " -> Armure pénétrée";
$l_att_yarm		 = "Votre armure est pénétrée!";
$l_att_ashit		 = " -> Armure touchée de";
$l_att_ayhit		 = "Votre armure est touchée de";
$l_att_lostf		 = "a perdu tous ses intercepteurs.";
$l_att_ylostf		 = "Vous avez perdu tous vos intercepteurs.";
$l_att_sdest		 = " -> Vaisseau détruit.";
$l_att_espod		 = "Un module de secours a été lancé!";
$l_att_ysalv		 = "Vous récupérez [salv_ore] unités de métaux, [salv_organics] unités de végétaux, [salv_goods] unités de produits, et [ship_salvage_rate]% du vaisseau pour [ship_salvage] crédits.<BR>Vous gagnez [rating_change] points.";
$l_att_andused		 = "et utilisé";
$l_att_stilship		 = "Vous n'avez pas détruit le vaisseau de [name].";
$l_att_atyou		 = "attacked you";
$l_att_and		 = "et";
$l_att_yshiplost	 = "Votre vaisseau a été détruit!";
$l_att_salv		 = "[name] a récupéré [salv_ore] unités de métaux, [salv_organics] unités de végétaux, [salv_goods] unités de produits, et [ship_salvage_rate]% du vaisseau pour [ship_salvage] crédits";

// warpedit 1-3.php

$l_warp_title		 = "Éditeur de liens";
$l_warp_turn		 = "Vous avez besoin d'au moins un tour pour utiliser un éditeur de liens.";
$l_warp_none		 = "Vous n'avez aucun éditeur de liens.";
$l_warp_forbid		 = "Il n'est pas permis d'utiliser un éditeur de liens.";
$l_warp_nolink		 = "Il n'y a aucun lien sortant de ce secteur.";
$l_warp_linkto		 = "Il y a des liens de ce secteur vers";
$l_warp_query		 = "Vers quel secteur voudriez-vous créer un lien?";
$l_warp_oneway		 = "Sens unique?";
$l_warp_dest		 = "Vous pouvez aussi détruire un lien vers ce secteur";
$l_warp_destquery	 = "Vers quel secteur voudriez-vous détruire le lien?";
$l_warp_bothway		 = "Deux sens";
$l_warp_nosector	 = "Ce secteur n'existe pas.";
$l_warp_twoerror	 = "L'utilisation d'un éditeur de lien pour créer un lien vers [target_sector] n'est pas permis.";
$l_warp_sectex		 = "Vous ne pouvez créer un lien à partir du secteur courant - vous dépasseriez la limited de $link_max par secteur.";
$l_warp_linked		 = "Le secteur cible ([target_sector]) à déjà un lien à partir de ce secteur.";
$l_warp_unlinked	 = "Le secteur cible ([target_sector]) n'a pas de lien à partir de ce secteur.";
$l_warp_coneway	         = "Lien a sens unique créé vers";
$l_warp_ctwoway		 = "Lien créé de et vers";
$l_warp_forbidtwo	 = "L'utilisation d'un éditeur de lien pour détruire un lien de/vers [target_sector] n'est pas permis.";
$l_warp_removed		 = "Le lien à été détruit, vers";
$l_warp_removedtwo	 = "Le lien à été détruit, de et vers";

// genesis.php

$l_gns_title		 = "Torpille Genesis";
$l_gns_turn		 = "You need at least one turn to use a genesis device.";
$l_gns_onplanet		 = "You can't use this device while on the planet surface.";
$l_gns_full		 = "This solar system is already full.";
$l_gns_planetex		 = "There is already a planet in this sector.";
$l_gns_nogenesis	 = "You do not have any genesis devices.";
$l_gns_forbid		 = "Creating a planet in this sector is not permitted.";
$l_gns_bforbid		 = "The bases in this sector are interfering with your genesis device. Planet creation not possible.";
$l_gns_pcreate		 = "Planet created.";

// ship.php

$l_ship_title		 = "Ship Commands";
$l_ship_the		 = "The";
$l_ship_nolonger	 = "is no longer in sector";
$l_ship_youc		 = "You see the";
$l_ship_owned		 = "owned by";
$l_ship_perform		 = "You can perform the following actions:";

// selfdestruct.php

$l_die_title		 = "Self-Destruct";
$l_die_rusure		 = "Are you sure you wish to destroy your ship? This will remove you from the game.";
$l_die_goodbye		 = "Goodbye cruel galaxy!";
$l_die_check		 = "Are you positive that you wish to remove yourself from the game?";
$l_die_nonono		 = "NO! NO! NO!";
$l_die_what		 = "What was I thinking?";
$l_die_count		 = "5.. 4.. 3.. 2.. 1.. Boom!";
$l_die_vapor		 = "You ship and all aboard have been vaporized.";
$l_die_please		 = "Please, <A HREF=logout.php3>logout</A>";
$l_die_exploit		 = "Don't play with what you don't understand.";

// move.php

$l_move_title 		 = "Move";
$l_move_turn		 = "You need at least one turn to move.";
$l_move_failed		 = "Move failed!";

// scan.php

$l_scan_title		 = "Scan Ship";
$l_scan_turn		 = "You need at least one turn to scan another ship.";
$l_scan_ron		 = "Scan results on";
$l_scan_capt		 = "Captained by:";
$l_scan_arma		 = "Armament:";
$l_scan_carry		 = "Carrying:";

// lrscan.php

$l_lrs_title		 = "Long Range Scan";
$l_lrs_nofull		 = "Your scanners do not possess full long range scan capabilities.";
$l_lrs_noturns		 = "You need at least $fullscan_cost turn(s) to run a full long range scan.";
$l_lrs_used		 = "Used";
$l_lrs_turns		 = "turn(s)";
$l_lrs_left		 = "left";
$l_lrs_reach		 = "The following locations can be reached from sector [sector]:";
$l_lrs_links		 = "Links";
$l_lrs_ships		 = "Ships";
$l_lrs_click		 = "Click one of the links to move to that sector.";
$l_lrs_cantscan		 = "Can't scan sector from current sector!";
$l_lrs_zero		 = "Sector 0 is too crowded to scan for ships!";
$l_lrs_moveto		 = "to move to sector";

// log.php

$l_log_months = array('January','February','March','April','May','June','July','August','September','October','November','December');
$l_log_months_short = array('Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec');
$l_log_pod = "Luckily, you had an escape pod!";
$l_log_nopod = "<font color=yellow><b>You did not have an escape pod, you died.</b></font>";

$l_log_text[LOG_LOGIN] = "You have logged in, from [ip].";
$l_log_title[LOG_LOGIN] = "Logged in";
$l_log_text[LOG_LOGOUT] = "You have logged out, from [ip].";
$l_log_title[LOG_LOGOUT] = "Logged out";
$l_log_text[LOG_ATTACK_OUTMAN] = "[player] was spotted on an attack vector, but your great pilot skills and good engines allowed you to outmaneuver the enemy.";
$l_log_title[LOG_ATTACK_OUTMAN] = "Evasive action!";
$l_log_text[LOG_ATTACK_OUTSCAN] = "You detected [player]'s weapons trying to fix on your ship, but your cloak generators managed to fool the enemy's primitive sensor circuits.";
$l_log_title[LOG_ATTACK_OUTSCAN] = "Cloak successful!";
$l_log_text[LOG_ATTACK_EWD] = "You are surprised by [player]'s treacherous attack. You can see the incoming warheads as you reach frantically for the emergency warp button. The world blurs around you and, for a milisecond, you think you are dead. When you finally open your eyes, you see that you were safely transported elsewhere. But where exactly, you do not know...";
$l_log_title[LOG_ATTACK_EWD] = "Emergency warp!";
$l_log_text[LOG_ATTACK_EWDFAIL] = "Your sensors detect [player]'s ship on an attack vector. \"Better be safe than sorry\", you think, hitting the emergency warp button. You hear a strange choking sound coming from the engines room and smell burned circuitry. \"Stupid piece of crap!\", you yell, kicking at the computer. The computer emits beeps of protestation as you prepare for the incoming battle...";
$l_log_title[LOG_ATTACK_EWDFAIL] = "Emergency warp <font color=red>failed!</font>";
$l_log_text[LOG_ATTACK_LOSE] = "You ship is being attacked by [player]. Try as you might, you cannot defend yourself against [player]'s superior weaponry. Your ship was destroyed. ";
$l_log_title[LOG_ATTACK_LOSE] = "<font color=red>Combat lost!</font>";
$l_log_text[LOG_ATTACKED_WIN] = "You ship was attacked by [player]. You battle for a while, then the fight breaks down. You lost [armor] armor points and [fighters] fighters in the skirmish.";
$l_log_title[LOG_ATTACKED_WIN] = "<font color=yellow>Skirmish!</font>";
$l_log_text[LOG_TOLL_PAID] = "You had to pay [toll] credits to enter sector [sector]. You promise yourself that you'll find a way to get your money back.";
$l_log_title[LOG_TOLL_PAID] = "Extortion";
$l_log_text[LOG_HIT_MINES] = "You hit [mines] mines when travelling in sector [sector].";
$l_log_title[LOG_HIT_MINES] = "<font color=yellow>Mines alert!</font>";
$l_log_text[LOG_SHIP_DESTROYED_MINES] = "Your ship was destroyed by a minefield in sector [sector]. ";
$l_log_title[LOG_SHIP_DESTROYED_MINES] = "<font color=red>Mines alert!</font>";
$l_log_text[LOG_PLANET_DEFEATED_D] = "Your planet [planet_name] in sector [sector] was captured in battle by [name]. Fortunately, the strong loyalty of your citizens played in your favor. They have bravely chosen to destroy the planet rather than have it fall into enemy hands. You organize superb funerals in the memory of your faithful people.";
$l_log_title[LOG_PLANET_DEFEATED_D] = "<font color=yellow>Planet destroyed</font>";
$l_log_text[LOG_PLANET_DEFEATED] = "Your planet [planet_name] in sector [sector] was captured in battle by the wretched [name]. The people of the planet welcome their new ruler. You hear a testimony on BNN : \"We're glad to be rid of that old fart! We don't want no stinking loser who can't protect us!\". You swear to make them pay for their arrogance.";
$l_log_title[LOG_PLANET_DEFEATED] = "<font color=red>Planet captured!</font>";
$l_log_text[LOG_PLANET_NOT_DEFEATED] = "Your planet [planet_name] in sector [sector] was attacked by [name]. The citizens organized a valliant defense however, and managed to destroy the opponent. They salvage some resources from the space debris : [goods] goods, [ore] ore, [organics] organics and [salvage]% of the ship's worth of [credits] credits.";
$l_log_title[LOG_PLANET_NOT_DEFEATED] = "Victory!";
$l_log_title[LOG_RAW] = "Notice";
$l_log_text[LOG_TOLL_RECV] = "Your fighters in sector [sector] have collected a 'tax' of [toll] credits.";
$l_log_title[LOG_TOLL_RECV] = "Toll income";
$l_log_text[LOG_DEFS_DESTROYED] = "[quantity] [type] were destroyed in sector [sector].";
$l_log_title[LOG_DEFS_DESTROYED] = "Sector defenses destroyed";
$l_log_text[LOG_PLANET_EJECT] = "You have been ejected from the planet in sector [sector] because [name] left the alliance.";
$l_log_title[LOG_PLANET_EJECT] = "Ejected!";
$l_log_text[LOG_BADLOGIN] = "There has been a bad login attempt from [ip].";
$l_log_title[LOG_BADLOGIN] = "Bad login";
$l_log_text[LOG_PLANET_SCAN] = "[name] has scanned your planet [planet_name] in sector [sector].";
$l_log_title[LOG_PLANET_SCAN] = "Planet scan";
$l_log_text[LOG_PLANET_SCAN_FAIL] = "[name] has attempted to scan your planet [planet_name] in sector [sector], but failed.";
$l_log_title[LOG_PLANET_SCAN_FAIL] = "Planet scan failed";
$l_log_text[LOG_SHIP_SCAN] = "[player] has scanned your ship.";
$l_log_title[LOG_SHIP_SCAN] = "Ship scan";
$l_log_text[LOG_SHIP_SCAN_FAIL] = "[player] has attempted to scan your ship, but failed.";
$l_log_title[LOG_SHIP_SCAN_FAIL] = "Ship scan failed";
$l_log_text[LOG_FURANGEE_ATTACK] = "Attacking [player]...";
$l_log_title[LOG_FURANGEE_ATTACK] = "Attack";
$l_log_text[LOG_STARVATION] = "One of your planet in [sector] cannot sustain its population! More organics is needed. [starvation] colonists died of hunger.";
$l_log_title[LOG_STARVATION] = "<font color=yellow>Starvation!</font>";
$l_log_text[LOG_TOW] = "Your ship has been towed from sector [sector] to sector [newsector] because your hull size exceeded the limit value of [hull].";
$l_log_title[LOG_TOW] = "Towed!";
$l_log_text[LOG_DEFS_DESTROYED_F] = "You have destroyed [fighters] patrolling fighters in sector [sector].";
$l_log_title[LOG_DEFS_DESTROYED_F] = "Fighters destroyed";
$l_log_text[LOG_DEFS_KABOOM] = "You were destroyed by a fighters force in sector [sector]. ";
$l_log_title[LOG_DEFS_KABOOM] = "<font color=red>Ship destroyed!</font>";
$l_log_text[LOG_HARAKIRI] = "You were tired of captaining this space barge, so you decided the universe would be better without it. Authorized by [ip].";
$l_log_title[LOG_HARAKIRI] = "<font color=red>Self-destructed!</font>";
$l_log_text[LOG_TEAM_REJECT] = "[player] has rejected an invitation to join your alliance, [teamname].";
$l_log_title[LOG_TEAM_REJECT] = "Invitation rejected";
$l_log_text[LOG_TEAM_RENAME] = "You have renamed your alliance to [team].";
$l_log_title[LOG_TEAM_RENAME] = "Alliance renamed";
$l_log_text[LOG_TEAM_M_RENAME] = "Your alliance coordinator renamed the alliance to [team].";
$l_log_title[LOG_TEAM_M_RENAME] = "Alliance renamed";
$l_log_text[LOG_TEAM_KICK] = "You have been ejected from the alliance [team].";
$l_log_title[LOG_TEAM_KICK] = "Ejected from alliance!";
$l_log_text[LOG_TEAM_CREATE] = "You have created a new alliance, [team].";
$l_log_title[LOG_TEAM_CREATE] = "Created new alliance";
$l_log_text[LOG_TEAM_LEAVE] = "You have left alliance [team].";
$l_log_title[LOG_TEAM_LEAVE] = "Left alliance";
$l_log_text[LOG_TEAM_NEWLEAD] = "You have left the alliance [team]. You relinquished the alliance leadership to [name].";
$l_log_title[LOG_TEAM_NEWLEAD] = "Left alliance";
$l_log_text[LOG_TEAM_LEAD] = "Your alliance coordinator has decided to leave [team]. You have been appointed to take its place.";
$l_log_title[LOG_TEAM_LEAD] = "Promotion!";
$l_log_text[LOG_TEAM_JOIN] = "You have joined the alliance [team].";
$l_log_title[LOG_TEAM_JOIN] = "Joined alliance";
$l_log_text[LOG_TEAM_NEWMEMBER] = "[name] has accepted to join [team]. This brings you one step further to galactic domination.";
$l_log_title[LOG_TEAM_NEWMEMBER] = "New alliance member";
$l_log_text[LOG_TEAM_INVITE] = "You have been invited to be part of [team].";
$l_log_title[LOG_TEAM_INVITE] = "Invitation";
$l_log_text[LOG_TEAM_NOT_LEAVE] = "[player] has left your alliance.";
$l_log_title[LOG_TEAM_NOT_LEAVE] = "Alliance loses a member";
$l_log_text[LOG_ADMIN_HARAKIRI] = "[player] has self-destructed from ip [ip].";
$l_log_title[LOG_ADMIN_HARAKIRI] = "Self-destruct";
$l_log_text[LOG_ADMIN_ILLEGVALUE] = "[player] had [quantity] [type], with max holds of [holds]";
$l_log_title[LOG_ADMIN_ILLEGVALUE] = "Illegal ship value";
$l_log_text[LOG_ADMIN_PLANETDEL] = "[attacker] has attempted to capture [defender]'s planet in sector [sector]. Planet was destroyed instead.";
$l_log_title[LOG_ADMIN_PLANETDEL] = "Planet destroyed";
$l_log_text[LOG_DEFENCE_DEGRADE] = "Sector Defences Fighters in sector [sector] degraded by [degrade] percent due to insufficient energy.";
$l_log_test[LOG_DEFENCE_DEGRADE] = "Sector Defences degraded.";

// modify-defences.php

$l_md_title		 = "Sector Defences";
$l_md_invalid		 = "Invalid Sector Defence";
$l_md_nolonger		 = "The sector defence selected is no longer there.";
$l_md_you		 = "you";
$l_md_bmines		 = "Your beams destroyed";
$l_md_msgdownerb	 = "[name] destroyed [mines] mines in sector [sector].";
$l_md_retr		 = "You retrieved";
$l_md_mode		 = "The fighters selected have been set to [mode] mode.";
$l_md_consist		 = "This sector defence consists of [qty] [type] owned by [owner].";
$l_md_youcan		 = "You can";
$l_md_retrieve		 = "Retrieve";
$l_md_change		 = "Change Fighter settings";
$l_md_cmode		 = "Fighter mode";
$l_md_attack		 = "Attack";
$l_md_toll		 = "Toll";
$l_md_attdef		 = "Attack the Sector Defences. All sector fighters will retaliate.";

// news.php

$l_news_title		 = "BlackNova Universe News";
$l_news_info		 = "BNN is among the galaxy's leaders<br>
                            in news and information delivery.<br>
                            Staffed 24 hours, seven days a week by a <br>
                            dedicated staff in BNN's galaxy headquarters <br>
                            in Alpha Centauri and in bureaus galaxywide!";
$l_news_for		 = "News for";
$l_news_prev		 = "previous day";
$l_news_next		 = "next day";
$l_news_none		 = "Sorry, no news today.";
$l_news_flash		 = "News Flash";

// dump.php

$l_dump_title		 = "Dumping colonists";
$l_dump_turn		 = "You need at least one turn to dump colonists.";
$l_dump_nocol		 = "You have no colonists on your ship to begin with.";
$l_dump_dumped		 = "Colonists dumped at supply depot.";
$l_dump_nono		 = "You need to be at a supply depot to do this.";

// readmail.php

$l_readm_title		 = "Read Message";

$l_readm_delete		 = "MESSAGE DELETED";
$l_readm_nomessage	 = "You have no Messages waiting for you...";
$l_readm_center		 = "Message Receiving Center";
$l_readm_sender		 = "Message Sender";
$l_readm_captn		 = "Captain of the";
$l_readm_del		 = "Delete";
$l_readm_repl		 = "Reply";

// mailto2.php

$l_sendm_title		 = "Send Message";
$l_sendm_to		 = "To";
$l_sendm_from		 = "From";
$l_sendm_ally		 = "Alliance:";
$l_sendm_subj		 = "Subject";
$l_sendm_mess		 = "Message";
$l_sendm_send		 = "Send";
$l_sendm_sent		 = "Message Sent";

// zoneinfo.php

$l_zi_title		 = "Zone Information";
$l_zi_nexist		 = "This section of space does not exist!";
$l_zi_feds		 = "Federation";
$l_zi_traders		 = "The Free-Trade Coalition";
$l_zi_nobody		 = "Nobody";
$l_zi_war		 = "Contested space";
$l_zi_allow		 = "Allowed";
$l_zi_notallow		 = "Not allowed";
$l_zi_limit		 = "Limited to owner and allies";
$l_zi_ul		 = "Unlimited";
$l_zi_control		 = "You are in control of this zone";
$l_zi_tochange		 = "to change its laws.";
$l_zi_owner		 = "Zone owner";
$l_zi_maxhull		 = "Maximum hull size allowed";

// zoneedit.php

$l_ze_title		 = "Edit Zone";
$l_ze_notowner		 = "You are not owner of this zone so you can't edit it.";
$l_ze_name		 = "Zone name";
$l_ze_allow		 = "Allow";
$l_ze_attacks		 = "Allow attacking other ships";
$l_ze_genesis		 = "Allow creating new planets";
$l_ze_return		 = "to return to the zone information page";
$l_ze_saved		 = "Your changes have been saved.";

// teams.php

$l_team_title		 = "Alliances";
$l_team_menu		 = "to go back to the Alliances Menu";
$l_team_galax		 = "Alliances present in the Galaxy:";
$l_team_members		 = "Members";
$l_team_coord		 = "Co-ordinator";
$l_team_member		 = "Member";
$l_team_noinvite	 = "Nobody has invited you to join an alliance.";
$l_team_ifyouwant	 = "If you want to join an alliance, send a message to its co-ordinator asking to be invited.";
$l_team_tocreate	 = "to create a new alliance.";
$l_team_injoin		 = "You have been invited to join";
$l_team_tojoin		 = "to join";
$l_team_or		 = "or";
$l_team_reject		 = "to reject the invitation.";
$l_team_ed		 = "Edit";
$l_team_inv		 = "Invite";
$l_team_leave		 = "Leave";
$l_team_eject		 = "Eject";
$l_team_pending		 = "Invitation pending for";
$l_team_noinvites	 = "Nobody has been invited to be part of";
$l_team_confirmleave	 = "Are you sure you want to leave";
$l_team_onlymember	 = "You were the only member, thus [team_name] is no more.";
$l_team_youarecoord	 = "You are the co-ordinator of";
$l_team_relinq		 = "You must relinquish your role to another player.";
$l_team_newc		 = "New co-ordinator:";
$l_team_youveleft	 = "You have left alliance";
$l_team_relto		 = "relinquishing the functions of co-ordinator to";
$l_team_welcome		 = "Welcome to alliance";
$l_team_noinviteto	 = "You have not been invited in to that team.";
$l_team_ejectsure	 = "Are you sure you want to eject";
$l_team_ejected 	 = "has been eject from the alliance!";
$l_team_testing		 = "Testing phase...";
$l_team_pw		 = "Password";
$l_team_entername	 = "Enter the name of the Alliance";
$l_team_enterdesc	 = "Enter a description of the Alliance";
$l_team_hcreated	 = "has been created and you are its leader";
$l_team_alliance	 = "Alliance";
$l_team_selectp		 = "Select the Player you want to invite";
$l_team_isorry		 = "Sorry, but [name] has already been invited to be part of an alliance - only one invitation can be active at any given time";
$l_team_plinvted	 = "Player invited.<BR>You must wait for that player to aknowledge your invitation.";
$l_team_refuse		 = "You have refused the invitation to join";
$l_team_edname		 = "Edit the name of your Alliance";
$l_team_eddesc		 = "Edit the description for your Alliance";
$l_team_hasbeenr	 = "has been renamed.";
$l_team_error		 = "<b><font color=red>An error occured</font></b><br>You are not the leader of this Alliance.";
$l_team_notmember	 = "You are not a member of any alliance";
$l_team_urejected	 = "<B>ATTENTION</B> - you have been ejected from";
$l_team_noalliances	 = "There are no alliances in the Galaxy at this time.";

// ranking.php

$l_ranks_title		 = "Top $max_rank Players";
$l_ranks_none		 = "No Results to show.";
$l_ranks_pnum		 = "Total number of players";
$l_ranks_dships		 = "Players with destroyed ships are not counted.";
$l_ranks_rank		 = "Rank";
$l_ranks_lastlog	 = "Last login";
$l_ranks_good		 = "Good";
$l_ranks_evil		 = "Evil";

// beacon.php

$l_beacon_title		 = "Deploy Space Beacon";
$l_beacon_notpermitted	 = "Deploying space beacons in this sector is not permitted.";
$l_beacon_reads		 = "Present beacon reads";
$l_beacon_none		 = "There presently isn't a beacon in this sector.";
$l_beacon_enter		 = "Enter text for beacon";
$l_beacon_nowreads	 = "Beacon now reads";
$l_beacon_donthave	 = "You do not have a space beacon.";

// emerwarp.php

$l_ewd_title		 = "Use Emergency Warp Device";
$l_ewd_used		 = "Emergency warp device engaged - arrived in sector [sector].";
$l_ewd_none		 = "You do not have an emergency warp device.";

// defence-report.php

$l_sdf_title		 = "Sector Defence Report";
$l_sdf_none		 = "You have no sector defences deployed.";
$l_sdf_type		 = "Type";
$l_sdf_mode		 = "Mode";

// traderoute.php
// cause its rather big i put everything in own vars than to re-use
// the old ones so we could export to own file if performance problems
// should occur

$l_tdr_title    	 = "Trade Routes";
$l_tdr_newtdr   	 = "Click <a href=\"traderoute.php?command=new\">here</a> to 
create a new trade route";
$l_tdr_modtdrset         = "To modify your global trade settings, click <a 
href=\"traderoute.php?command=settings\">here</a>";
$l_tdr_confdel  	 = "Click <a 
href=\"traderoute.php?command=delete&confirm=yes&traderoute_id=[tdr_id]\">here</a> 
to confirm deletion of the following trade route :";
$l_tdr_noactive 	 = "You do not have any active trade routes to display.";
$l_tdr_curtdr   	 = "Current Trade Routes";
$l_tdr_deltdr   	 = "Delete Trade Route";
$l_tdr_src      	 = "Source";
$l_tdr_srctype  	 = "Src Type";
$l_tdr_dest     	 = "Destination";
$l_tdr_desttype 	 = "Dest Type";
$l_tdr_move     	 = "Move";
$l_tdr_circuit  	 = "Circuit";
$l_tdr_change   	 = "Change";
$l_tdr_portin   	 = "Port in";
$l_tdr_planet   	 = "Planet";
$l_tdr_nonexistance      = "Non-existant planet!";
$l_tdr_na       	 = "N/A";
$l_tdr_cargo    	 = "Cargo";
$l_tdr_none     	 = "None";
$l_tdr_colonists         = "Colonists";
$l_tdr_fighters 	 = "Fighters";
$l_tdr_torps    	 = "Torpedoes";
$l_tdr_escooped 	 = "[tdr_dist_triptime] turns<br>[tdr_dist_scooped] energy 
scooped";
$l_tdr_warp     	 = "Warp";
$l_tdr_turns    	 = "turns";
$l_tdr_way      	 = "way";
$l_tdr_ways     	 = "ways";
$l_tdr_edit     	 = "Edit";
$l_tdr_del      	 = "Delete";
$l_tdr_nowlink1 	 = "There is no warp link from sector [tdr_src_sector_id] to 
sector [tdr_dest_sector_id]";
$l_tdr_nowlink2 	 = "There is no warp link from sector [tdr_dest_sector_id] to 
sector [tdr_src_sector_id]";
$l_tdr_sportissrc        = "If a special port is source, a planet must be the 
destination for colonization.";
$l_tdr_notownplanet      = "You can't colonize a planet that you or your team 
don't own.";
$l_tdr_planetisdest      = "A planet can be a destination only when source is 
a special port.";
$l_tdr_samecom 		 = "You can't make a traderoute for ports selling the same 
commodities.";
$l_tdr_sportcom 	 = "You can't sell commodities from a planet in a special 
port.";
$l_tdr_editerr  	 = "Edit error : trade route not found in DB";
$l_tdr_maxtdr   	 = "Sorry you have reached the maximum number of trade routes 
allowed.";
$l_tdr_createnew         = "Creating a new";
$l_tdr_editinga 	 = "Editing a";
$l_tdr_traderoute        = "trade route";
$l_tdr_unnamed  	 = "Unnamed";
$l_tdr_cursector         = "You are currently in sector";
$l_tdr_selspoint         = "Please select starting point :";
$l_tdr_port     	 = "Port";
$l_tdr_insector 	 = "in sector";
$l_tdr_selendpoint       = "Please select ending point";
$l_tdr_selmovetype       = "Please select move type";
$l_tdr_realspace         = "Real Space";
$l_tdr_selcircuit        = "Please select circuit";
$l_tdr_oneway   	 = "One way";
$l_tdr_errnotvalidport   = "Error : the source port [tdr_port_id] does not 
seem to be valid.";
$l_tdr_bothways 	 = "Both ways";
$l_tdr_create   	 = "Create";
$l_tdr_modify   	 = "Modify";
$l_tdr_returnmenu        = "Click <a href=traderoute.php>here</a> to return to 
the trade routes menu.";
$l_tdr_errnotvalidport   = "Error : the source port [tdr_port_id] is not a 
valid port.";
$l_tdr_errnoport         = "Error : there is no port at sector [tdr_port_id].";
$l_tdr_errnosrc    	 = "Error : specified source planet doesn't exist.";
$l_tdr_errnotownnotsell  = "Error : you do not own planet [tdr_source_name] 
in sector [tdr_source_sector_id] and planet is not selling.";
$l_tdr_errnotvaliddestport= "Error : the destination port [tdr_port_id] 
is not a valid port.";
$l_tdr_errnoport2        = "Error : there is no port at sector [tdr_port_id].";
$l_tdr_errnodestplanet   = "Error : specified destination planet does not 
exist.";
$l_tdr_errnotownnotsell2 = "Error : you do not own planet [tdr_dest_name] in sector [tdr_dest_sector_id] and planet is not selling.";
$l_tdr_newtdrcreated     = "New trade route created!";
$l_tdr_tdrmodified       = "Trade route modified!";
$l_tdr_doesntexist       = "That trade route doesn't exist!";
$l_tdr_notowntdr         = "You do not own that traderoute!";
$l_tdr_tdrdeleted        = "Trade route deleted.";
$l_tdr_globalset         = "Global trade route settings";
$l_tdr_tdrsportsrc       = "For trade routes having a special port as a 
source, trade";
$l_tdr_tdrescooped       = "For real space trade routes, what to do with the 
energy scooped?";
$l_tdr_trade    	 = "Trade";
$l_tdr_keep    	 	 = "Keep";
$l_tdr_save    	 	 = "Save";
$l_tdr_globalsetsaved    = "Global trade route settings saved.";
$l_tdr_engagenonexist    = "Tried to engage a non-exiDestination sector does 
not seem to be valid!sting trade route!";
$l_tdr_invalidspoint     = "Starting port does not seem to be valid!";
$l_tdr_inittdr  	 = "You are not in sector [tdr_source_id]! You must be in 
starting sector before you initiate a trade route!";
$l_tdr_invalidsrc        = "Source planet doesn't seem to be a valid planet!";
$l_tdr_inittdrsector     = "You are not in sector [tdr_source_sector_id]! You 
must be in starting sector before you initiate a trade route!";
$l_tdr_notyourplanet     = "You do not own planet [tdr_source_name] in sector 
[tdr_source_sector_id]!";
$l_tdr_invalidssector    = "Starting sector does not seem to be valid!";
$l_tdr_invaliddport      = "Destination port does not seem to be valid!";
$l_tdr_invaliddplanet    = "Destination planet doesn't seem to be a valid 
planet!";
$l_tdr_invaliddsector    = "Destination sector does not seem to be valid!";
$l_tdr_moreturnsneeded   = "This trade route requires [tdr_dist_triptime] 
turns to complete. You only have [tdr_playerinfo_turns] left.";
$l_tdr_tdrhostdef        = "You can not use trade routes between sectors with 
hostile defences. You must defeat the defences first.";
$l_tdr_globalsetbuynothing= "Your global settings are set to buy 
nothing! You would only waste turns doing this route!";
$l_tdr_nosrcporttrade    = "Trading from source port is not allowed.";
$l_tdr_tradesrcportoutsider= "Trading at source port is not allowed for 
outsiders";
$l_tdr_nodestporttrade   = "Trading from destination port is not allowed.";
$l_tdr_tradedestportoutsider= "Trading at destination port is not allowed 
for outsiders";
$l_tdr_notyourplanet     = "You do not own planet [tdr_source_name] in sector 
[tdr_source_sector_id]!";
$l_tdr_invalidssector    = "Starting sector does not seem to be valid!";
$l_tdr_invaliddport      = "Destination port does not seem to be valid!";
$l_tdr_invaliddplanet    = "Destination planet doesn't seem to be a valid 
planet!";
$l_tdr_invaliddsector    = "Destination sector does not seem to be valid!";
$l_tdr_moreturnsneeded   = "This trade route requires [tdr_dist_triptime] 
turns to complete. You only have [tdr_playerinfo_turns] left.";
$l_tdr_tdrhostdef        = "You can not use trade routes between sectors with 
hostile defences. You must defeat the defences first.";
$l_tdr_globalsetbuynothing= "Your global settings are set to buy 
nothing! You would only waste turns doing this route!";
$l_tdr_nosrcporttrade    = "Trading from source port is not allowed.";
$l_tdr_tradesrcportoutsider= "Trading at source port is not allowed for 
outsiders";
$l_tdr_nodestporttrade   = "Trading from destination port is not allowed.";
$l_tdr_tradedestportoutsider= "Trading at destination port is not allowed 
for outsiders";
$l_tdr_tdrres  		 = "Trade Route Results";
$l_tdr_bought  		 = "Bought";
$l_tdr_nothingtotrade    = "Nothing to trade";
$l_tdr_sold   	  	 = "Sold";
$l_tdr_ore    		 = "Ore";
$l_tdr_portisfull        = "Port is full";
$l_tdr_goods    	 = "goods";
$l_tdr_organics 	 = "organics";
$l_tdr_energy   	 = "energy";
$l_tdr_portisempty       = "Port is empty";
$l_tdr_loaded   	 = "Loaded";
$l_tdr_nothingtoload     = "Nothing to load";
$l_tdr_scooped  	 = "Scooped";
$l_tdr_dumped   	 = "Dumped";
$l_tdr_planetisovercrowded= "Planet is overcrowded";
$l_tdr_nothingtodump     = "Nothing to dump";
$l_tdr_onlyonewaytdr     = "Did nothing, traderoute was one way only";
$l_tdr_profit 		 = "Profit";
$l_tdr_cost   		 = "Cost";
$l_tdr_totalprofit       = "Total profit";
$l_tdr_totalcost         = "Total cost";
$l_tdr_credits  	 = "Credits";
$l_tdr_turnsused         = "Turns used";
$l_tdr_turnsleft         = "Turns left";
$l_tdr_engageagain       = "Click <A 
HREF=\"traderoute.php?engage=[tdr_engage]\">here</A> to do this trade route 
again.";

// IGB.php

$l_igb_title    = "The Intergalactic Bank";
$l_igb_malfunction      = "This IGB terminal is malfunctionning. The Intergalatic Bank wishes to apologize for any inconvenience.";
$l_igb_quit     = "Quit";
$l_igb_login    = "Login";
$l_igb_welcometoigb     = "Welcome to this Intergalactic Banking Terminal";
$l_igb_accountholder    = "Account Holder";
$l_igb_shipaccount      = "Ship Account";
$l_igb_igbaccount       = "IGB Account";
$l_igb_operations       = "Operations";
$l_igb_withdraw = "Withdraw";
$l_igb_deposit  = "Deposit";
$l_igb_transfer = "Transfer";
$l_igb_back     = "Back";
$l_igb_logout   = "Logout";
$l_igb_withdrawfunds    = "Withdraw Funds";
$l_igb_fundsavailable   = "Funds available";
$l_igb_selwithdrawamount        = "Please select amount to withdraw";
$l_igb_depositfunds     = "Deposit Funds";
$l_igb_seldepositamount = "Please select amount to deposit";
$l_igb_transfertype     = "Transfer Type";
$l_igb_toanothership    = "To another ship";
$l_igb_shiptransfer     = "Ship Transfer";
$l_igb_fromplanet       = "From a planet to another";
$l_igb_unnamed  = "Unnamed";
$l_igb_in       = "in";
$l_igb_none     = "None";
$l_igb_destination      = "Destination";
$l_igb_planettransfer   = "Planet Transfer";
$l_igb_sendyourself     = "You can't send money to yourself!";
$l_igb_unknowntargetship        = "Unknown target ship!";
$l_igb_min_turns        = "Player [igb_target_char_name] must have played at least [igb_min_turns] turns before he can receive money.";
$l_igb_min_turns2       = "You must have played at least [igb_min_turns] turns before you can send money.";
$l_igb_mustwait = "You have already made a transfer to [igb_target_char_name] in the last [igb_trate] minutes. You must wait [igb_difftime] minutes before you can transfer credits to that player again.";
$l_igb_maxtransfer      = "Maximum transfer allowed";
$l_igb_unlimited        = "Unlimited";
$l_igb_maxtransferpercent       = "Maximum transfer allowed ([igb_percent]% of net worth)";
$l_igb_recipient        = "Recipient";
$l_igb_seltransferamount        = "Please select amount to transfer";
$l_igb_transferrate     = "Current rate for transfers is [igb_num_percent]% of total amount. It will automatically be deduced from the amount you transfer.";
$l_igb_errplanetsrcanddest      = "The same planet can't be both source and destination.";
$l_igb_errunknownplanet = "DB Error! Unknown Planet!";
$l_igb_errnotyourplanet = "You can't transfer money from/to a planet you do not own.";
$l_igb_srcplanet        = "Src -> Planet";
$l_igb_destplanet       = "Dst -> Planet";
$l_igb_transferrate2     = "Current rate for transfers is [igb_num_percent]% of total amount. It will automatically be deduced from the amount you transfer.";
$l_igb_errsendyourself  = "You can't send money to yourself!";
$l_igb_min_turns3        = "Player [igb_target_char_name] must have played at least [igb_min_turns] turns before he can receive money.";
$l_igb_min_turns4       = "You must have played at least [igb_min_turns] turns before you can send money.";
$l_igb_mustwait2 = "You have already made a transfer to [igb_target_char_name] in the last [igb_trate] minutes. You must wait [igb_difftime] minutes before you can transfer credits to that player again.";
$l_igb_invalidtransferinput     = "Invalid input for transfer.";
$l_igb_nozeroamount     = "Amount to transfer must not be zero.";
$l_igb_notenoughcredits = "You do not have enough credits to perform this operation.";
$l_igb_amounttoogreat   = "The amount you entered was greater than your maximum transfer allowed.";
$l_igb_transfersuccessful       = "Transfer Successful";
$l_igb_creditsto        = "credits have been transferred to";
$l_igb_transferamount   = "Transfer Amount";
$l_igb_transferfee      = "Transfer Fee";
$l_igb_amounttransferred        = "Amount Transferred";
$l_igb_notenoughcredits2        = "There are not enough credits on source planet to complete that transaction.";
$l_igb_to       = "to";
$l_igb_ctransferredfrom = "credits have been transferred from";
$l_igb_invaliddepositinput      = "Invalid input for deposit.";
$l_igb_nozeroamount2    = "Amount to deposit must not be zero.";
$l_igb_operationsuccessful      = "Operation successful";
$l_igb_creditstoyou     = "Credits have been transfered to your IGB account.";
$l_igb_accounts = "Accounts";
$l_igb_invalidwithdrawinput     = "Invalid input for withdraw.";
$l_igb_nozeroamount3    = "Amount to withdraw must not be zero.";
$l_igb_creditstoyourship        = "Credits have been transfered to your ship account.";
$l_igb_igberrreport     = "IGB Error Report";
$l_igb_source   = "Source";

// combat.php3

$l_cmb_atleastoneturn   = "You need at least one turn to attack a planet.";
$l_cmb_shipenergybb     = "Ship energy before beams";
$l_cmb_shipenergyab     = "Ship energy after beams";
$l_cmb_shipenergyas     = "Ship energy after shields";
$l_cmb_shiptorpsbtl     = "Ship torpedos before torp launch";
$l_cmb_shiptorpsatl     = "Ship torpedos after torp launch";
$l_cmb_planettorpdamage = "Planet torp damage";
$l_cmb_attackertorpdamage       = "Attacker torp damage";
$l_cmb_beams    = "Beams";
$l_cmb_fighters = "Fighters";
$l_cmb_shields  = "Shields";
$l_cmb_torps    = "Torps";
$l_cmb_torpdamage       = "Torp Damage";
$l_cmb_armor    = "Armor";
$l_cmb_you      = "You";
$l_cmb_planet   = "Planet";
$l_cmb_combatflow       = "Combat Flow";
$l_cmb_defender = "Defender";
$l_cmb_attackingplanet  = "Attacking planet in sector";
$l_cmb_youfireyourbeams = "You fire your beams";
$l_cmb_defenselost      = "Planetary defense lost [cmb_planetfighters] fighters to your beams";
$l_cmb_defenselost2     = "Planetary Defense lost [cmb_attackerbeams] fighters, but there are more coming!";
$l_cmb_planetarybeams   = "Planetary beams destroy [cmb_temp] of your fighters";
$l_cmb_planetarybeams   = "Planetary beams destroy [cmb_planetbeams] of your fighters";
$l_cmb_youdestroyedplanetshields        = "Your beams have destroyed the planetary shields";
$l_cmb_beamsexhausted   = "You destroy [cmb_attackerbeams] planetary shields before your beams are exhausted";
$l_cmb_breachedyourshields      = "Planetary beams have breached your shields";
$l_cmb_destroyedyourshields     = "Planetary beams have destroyed [cmb_planetbeams] of your shields";
$l_cmb_breachedyourarmor        = "Planetary beams have breached your armor";
$l_cmb_destroyedyourarmor       = "Planetary beams have destroyed [cmb_planetbeams] points of armor";
$l_cmb_torpedoexchangephase     = "Torpedo Exchange Phase";
$l_cmb_nofightersleft   = "Your torpedos destroy [cmb_planetfighters] planetary fighters, no fighters are left";
$l_cmb_youdestroyfighters       = "Your torpedos destroy [cmb_attackertorpdamage] planetary fighters";
$l_cmb_planettorpsdestroy       = "Planetary torpedos destroy [cmb_temp] of your fighters";
$l_cmb_planettorpsdestroy2      = "Planetary torpedos destroy [cmb_planettorpdamage] of your fighters";
$l_cmb_torpsbreachedyourarmor   = "Planetary torpedos have breached your armor";
$l_cmb_planettorpsdestroy3      = "Planetary torpedos have destroyed [cmb_planettorpdamage] points of armor";
$l_cmb_youdestroyedallfighters  = "Your torpedos have destroyed all the planetary fighters";
$l_cmb_youdestroyplanetfighters = "Your torpedos destroy [cmb_attackertorpdamage] planetary fighters";
$l_cmb_fightercombatphase       = "Fighter Combat Phase";
$l_cmb_youdestroyedallfighters2  = "Your fighters have destroyed all the planetary fighters.";
$l_cmb_youdestroyplanetfighters2        = "Your fighters have destroyed [cmb_attackerfighters] planetary fighters";
$l_cmb_allyourfightersdestroyed = "All your fighters were destroyed";
$l_cmb_fightertofighterlost     = "You lost [cmb_planetfighters] fighters in fighter to fighter combat";
$l_cmb_youbreachedplanetshields = "Your fighters have breached the planetary shields";
$l_cmb_shieldsremainup  = "Your fighters destroyed [cmb_attackerfighters] planetary shields, but they remain up";
$l_cmb_fighterswarm     = "Planetary fighters swarm your ship, your armor has been breached";
$l_cmb_swarmandrepel    = "Planetary fighters swarm your ship, but your armor repels them";
$l_cmb_engshiptoshipcombat      = "Engaging in Ship to Ship combat.";
$l_cmb_shipdock = "There are [cmb_shipsonplanet] ships docked at Spacedock!";
$l_cmb_approachattackvector     = "is approaching on an attack vector";
$l_cmb_noshipsdocked    = "There are NO ships docked at Spacedock!";
$l_cmb_yourshipdestroyed        = "Your ship has been destroyed!";
$l_cmb_escapepod        = "Luckily you have an escape pod!";
$l_cmb_finalcombatstats = "Final Combat Stats";
$l_cmb_youlostfighters  = "You lost [cmb_fighters_lost] out of [cmb_playerinfo_ship_fighters] total fighters.";
$l_cmb_youlostarmorpoints       = "You lost [cmb_armor_lost] out of [cmb_playerinfo_armour_pts] total armor points, you have [cmb_attackerarmor] points remaining.";
$l_cmb_energyused       = "You used [cmb_energy] energy, from a total of [cmb_playerinfo_ship_energy] energy.";
$l_cmb_planetdefeated   = "Planet defeated";
$l_cmb_citizenswanttodie        = "The citizens of this planet have decided they'd rather die than serve a pathetic ruler like you. They use a laser drill to dig a hole to the planet's core. You barely have time to escape into orbit before the whole planet is reduced to a ball of molten lava.";
$l_cmb_youmaycapture    = "You may <a href=planet.php3?planet_id=[cmb_planetinfo_planet_id]&command=capture>capture</a> the planet or just leave it undefended.";
$l_cmb_youmaycapture2   = "You may <a href=planet.php3?planet_id=[cmb_planetinfo_planet_id]&command=capture>capture</a> the planet or just leave it undefended.";
$l_cmb_planetnotdefeated        = "Planet not defeated";
$l_cmb_planetstatistics = "Planet statistics";
$l_cmb_fighterloststat  = "Fighters lost: [cmb_fighters_lost] out of [cmb_planetinfo_fighters] ([cmb_planetfighters] alive)";
$l_cmb_energyleft       = "Energy left";
$l_cmb_startingstats    = "Starting stats";
$l_cmb_statattackerbeams        = "Attackerbeams";
$l_cmb_statattackerfighters     = "Attackerfighters";
$l_cmb_statattackershields      = "Attackershields";
$l_cmb_statattackertorps        = "Attackertorps";
$l_cmb_statattackerarmor        = "Attackerarmor";
$l_cmb_statattackertorpdamage   = "Attackertorpdamage";
$l_cmb_isattackingyou   = "is attacking you";
$l_cmb_beamexchange     = "Beam exchange";
$l_cmb_beamsdestroy     = "Your beams destroy [cmb_lost] fighters";
$l_cmb_beamsdestroy2    = "Your beams destroy [cmb_attackerbeams] fighters, but there are more coming";
$l_cmb_nobeamsareleft   = "You have no beams left to destroy the incoming fighters!";
$l_cmb_beamshavenotarget        = "Your beams have no fighter targets to destroy";
$l_cmb_fighterdestroyedbybeams  = "[cmb_targetinfo_ship_name] destroyed [cmb_lost] of your fighters with beams<BR>";
$l_cmb_beamsdestroystillhave    = "[cmb_targetinfo_ship_name] destroyed [cmb_targetbeams] of your fighters with beams, but you still have [cmb_attackerfighters] left";
$l_cmb_fighterunhindered        = "Your fighters attack unhindered, the enemy has no beams left.";
$l_cmb_youhavenofightersleft    = "You have no fighters left to attack with";
$l_cmb_breachedsomeshields      = "You have breached [cmb_targetinfo_ship_name]'s shields with your beams";
$l_cmb_shieldsarehitbybeams     = "[cmb_targetinfo_ship_name]'s shields are hit for [cmb_attackerbeams] damage by your beams";
$l_cmb_nobeamslefttoattack      = "You have no beams left to attack [cmb_targetinfo_ship_name]'s shields";
$l_cmb_yourshieldsbreachedby    = "[cmb_targetinfo_ship_name]'s beams have breached your shields";
$l_cmb_yourshieldsarehit        = "[cmb_targetinfo_ship_name]'s beams have hit your shields for [cmb_targetbeams] damage.";
$l_cmb_hehasnobeamslefttoattack = "[cmb_targetinfo_ship_name] has no beams left to attack your shields";
$l_cmb_yourbeamsbreachedhim     = "Your beams have breached [cmb_targetinfo_ship_name]'s armor";
$l_cmb_yourbeamshavedonedamage  = "Your beams have done [cmb_attackerbeams] damage to [cmb_targetinfo_ship_name]'s armor";
$l_cmb_nobeamstoattackarmor     = "You have no beams left to attack [cmb_targetinfo_ship_name]'s armor";
$l_cmb_yourarmorbreachedbybeams = "Your armor has been breached by [cmb_targetinfo_ship_name]'s beams";
$l_cmb_yourarmorhitdamaged      = "Your armor is hit for [cmb_targetbeams] damage by [cmb_targetinfo_ship_name]'s beams";
$l_cmb_torpedoexchange  = "Torpedo exchange";
$l_cmb_hehasnobeamslefttoattackyou      = "[cmb_targetinfo_ship_name] has no beams left to attack your armor";
$l_cmb_yourtorpsdestroy = "Your torpedos destroy [cmb_lost] of [cmb_targetinfo_ship_name]'s fighters";
$l_cmb_yourtorpsdestroy2        = "Your torpedos destroy [cmb_attackertorpdamage] of [cmb_targetinfo_ship_name]'s fighters";
$l_cmb_youhavenotorpsleft       = "You have no torpedo's left to attack [cmb_targetinfo_ship_name]'s fighters.";
$l_cmb_hehasnofighterleft       = "[cmb_targetinfo_ship_name] has no fighters left for you to destroy with torpedos";
$l_cmb_torpsdestroyyou  = "[cmb_targetinfo_ship_name]'s torpedo's destroy [cmb_lost] of your fighters";
$l_cmb_someonedestroyedfighters = "[cmb_targetinfo_ship_name] destroyed [cmb_targettorpdmg] of your fighters with torpedos";
$l_cmb_hehasnotorpsleftforyou   = "[cmb_targetinfo_ship_name] has no torpedo's left to attack your fighters";
$l_cmb_youhavenofightersanymore = "You have no fighters left to be destroyed by [cmb_targetinfo_ship_name]'s torpedo's";
$l_cmb_youbreachedwithtorps     = "You have breached [cmb_targetinfo_ship_name]'s armor with your torpedos";
$l_cmb_hisarmorishitbytorps     = "[cmb_targetinfo_ship_name]'s armor is hit for [cmb_attackertorpdamage] damage by your torpedos";
$l_cmb_notorpslefttoattackarmor = "You have no torpedo's left to attack [cmb_targetinfo_ship_name]'s armor";
$l_cmb_yourarmorbreachedbytorps = "Your armor has been breached by [cmb_targetinfo_ship_name]'s torpedos";
$l_cmb_yourarmorhitdmgtorps     = "Your armor is hit for [cmb_targettorpdmg] damage by [cmb_targetinfo_ship_name]'s torpedos";
$l_cmb_hehasnotorpsforyourarmor = "[cmb_targetinfo_ship_name] has no torpedo's left to attack your armor";
$l_cmb_fightersattackexchange   = "Fighters Attack exchange";
$l_cmb_enemylostallfighters     = "[cmb_targetinfo_ship_name] lost all fighters.";
$l_cmb_helostsomefighters       = "[cmb_targetinfo_ship_name] lost [cmb_attackerfighters] fighters.";
$l_cmb_youlostallfighters       = "You lost all fighters.";
$l_cmb_youalsolostsomefighters  = "You lost [cmb_targetfighters] fighters.";
$l_cmb_hehasnofightersleftattack        = "[cmb_targetinfo_ship_name] has no fighters left for your fighters to attack";
$l_cmb_younofightersattackleft  = "You have no fighters left to attack [cmb_targetinfo_ship_name]'s fighters";
$l_cmb_youbreachedarmorwithfighters     = "You have breached [cmb_targetinfo_ship_name]'s armor with your fighters";
$l_cmb_youhitarmordmgfighters   = "You hit [cmb_targetinfo_ship_name]'s armor for [cmb_attackerfighters] damage with your fighters";
$l_cmb_youhavenofighterstoarmor = "You have no fighters left to attack [cmb_targetinfo_ship_name]'s armor";
$l_cmb_hasbreachedarmorfighters = "[cmb_targetinfo_ship_name] has breached your armor with fighters";
$l_cmb_yourarmorishitfordmgby   = "Your armor is hit for [cmb_targetfighters] damage by [cmb_targetinfo_ship_name]'s fighters";
$l_cmb_nofightersleftheforyourarmor     = "[cmb_targetinfo_ship_name] has no fighters left to attack your armor";
$l_cmb_hehasbeendestroyed       = "[cmb_targetinfo_ship_name] has been destroyed";
$l_cmb_escapepodlaunched        = "An escape pod was launched!";
$l_cmb_yousalvaged      = "You salvaged [cmb_salv_ore] units of ore, [cmb_salv_organics] units of organics, [cmb_salv_goods] units of goods, and salvaged [cmb_salvage_rate]% of the ship for [cmb_salvage] credits.<BR>Your rating changed by [cmb_number_rating_change] points.";
$l_cmb_youdidntdestroyhim       = "You did not destory [cmb_targetinfo_ship_name]";
$l_cmb_shiptoshipcombatstats    = "Ship to Ship combat stats";

// check_mines.php3

$l_chm_youhitsomemines  = "You hit [chm_roll] mines!";
$l_chm_hehitminesinsector       = "[chm_playerinfo_character_name] hit [chm_roll] mines in sector [chm_sector].";
$l_chm_youlostminedeflectors    = "You lost [chm_roll] mine deflectors.";
$l_chm_youlostallminedeflectors = "You lost all your mine deflectors.";
$l_chm_youhadnominedeflectors  = "You had no mine deflectors.";
$l_chm_yourshieldshitforminesdmg        = "Your shields are hit for [chm_mines_left] damage.";
$l_chm_yourshieldsaredown       = "Your shields are down!";
$l_chm_youlostallyourshields    = "You lost all your shields!";
$l_chm_yourarmorhitforminesdmg  = "Your armour is hit for [chm_mines_left] damage.";
$l_chm_yourhullisbreached       = "Your hull is breached!";
$l_chm_hewasdestroyedbyyourmines        = "[chm_playerinfo_character_name] was destroyed by your mines in sector [chm_sector].";
$l_chm_yourshiphasbeendestroyed = "Your ship has been destroyed!";
$l_chm_luckescapepod    = "Luckily you have an escape pod!";

// check_fighters.php3

$l_chf_youretreatback   = "You retreat back to your previous location";
$l_chf_notenoughcreditstoll     = "You do not have enough credits to pay the toll.";
$l_chf_movefailed       = "Move failed.";
$l_chf_youpaidsometoll  = "You paid [chf_tollstring] credits for the toll.";
$l_chf_thefightersdetectyou     = "The fighters detect you!";
$l_chf_therearetotalfightersindest      = "There are [chf_total_sector_fighters] fighters in your destination sector.";
$l_chf_creditsdemanded  = "They demand [chf_number_fighterstoll] credits to enter this sector.";
$l_chf_youcanretreat    = "You can <BR><INPUT TYPE=RADIO NAME=response VALUE=retreat><B>Retreat</B> - Will cost an extra turn.<BR></INPUT>";
$l_chf_inputpay = "<INPUT TYPE=RADIO NAME=response CHECKED VALUE=pay><B>Pay</B> the toll and enter without harm from the fighters.<BR></INPUT>";
$l_chf_inputfight       = "<INPUT TYPE=RADIO NAME=response CHECKED VALUE=fight><B>Fight</B> - you must defeat all the fighters to enter the sector.<BR></INPUT>";
$l_chf_inputcloak       = "<INPUT TYPE=RADIO NAME=response CHECKED VALUE=sneak><B>Cloak</B> - Use your cloaking device and try to avoid the fighters.<BR></INPUT>";
$l_chf_go       = "Go";

// mines.php

$l_mines_title			="Deploy Sector Mines & Fighters";
$l_mines_noturn		 	="You need at least one turn to deploy sector defences.";
$l_mines_nopermit		="Deploying Mines and Fighters in this sector is not permitted.";
$l_mines_nodeploy		="Can not deploy here. Another Ship or Alliance has mines or fighters in this sector.";
$l_mines_info1			="You are presently in sector [sector]. There are [mines] mines and [fighters] fighters here.";
$l_mines_info2			="You have [mines] mines and [fighters] fighters available to deploy";
$l_mines_deploy			="Deploy";
$l_mines_deployed		="Deployed";
$l_mines_att			="Attack";
$l_mines_toll			="Toll";
$l_mines_notorps		="You do not have enough torpedos.";
$l_mines_nofighters		="You do not have enough fighters";
$l_mines_dmines			="Deployed [mines] mines.";
$l_mines_dfighter		="Deployed [fighters] fighters in [mode] mode.";

//alliance-planets.php

$l_teamplanet_title		="Alliance Planet Report";
$l_teamplanet_notally		="You aren't in an alliance.";
$l_teamplanet_personal		="Show personal planets";
$l_teamplanet_noplanet		="Your alliance has no planets";

$l_feedback_title		="Send Feedback";
$l_feedback_to			="TO:";
$l_feedback_from		="FROM:";
$l_feedback_topi		="SUBJECT:";
$l_feedback_feedback		="Feedback";
$l_feedback_message		="MESSAGE:";
$l_feedback_messent		="Message Sent";
$l_feedback_subj		="WTW Feedback";
$l_feedback_info		="Please send feedback in english only"; // gameadmins put all your languages here

// corp.php
$l_corpm_title			="Corporation Menu";
$l_corpm_tocorp			="Planet is now a Corporate Planet!";
$l_corpm_topersonal		="Planet is now a Personal Planet!";
$l_corpm_exploit		="You intercept a garbled borg message on your scanner... you should probably start worrying...";


?>
