<?php

//general

$l_yes 			 = "Oui";
$l_no			 = "Non";
$l_here			 = "ici";
$l_submit		 = "Envoyer";
$l_reset		 = "Restaurer";
$l_all			 = "Tout";

$l_ore			 = "Métaux";
$l_organics		 = "Végétaux";
$l_goods		 = "Produits";
$l_energy		 = "Énergie";
$l_colonists		 = "Colons";
$l_credits 		 = "Crédits";
$l_units		 = "unités de ";

$l_cargo		 = "Cargaison";
$l_fighters		 = "Intercepteurs ";
$l_mines		 = "Mines ";
$l_torps		 = "Torpilles";

$l_none			 = "Aucun";
$l_unnamed		 = "Sans Nom";
$l_name			 = "Nom";
$l_unowned		 = "Libre";
$l_unknown		 = "Inconnu";
$l_clickme 		 = "Cliquer ici";
$l_player  		 = "Joueur";
$l_ship			 = "Vaisseau";
$l_set			 = "Mod";
$l_realspace		 = "Espace Réel";
$l_armourpts		 = "Points d'armure";


// main.php

$l_main_title 		 = "Menu Principal";

$l_traderoutes		 = "Commerce";
$l_trade_control	 = "Modifier";

$l_youhave 		 = "Vous avez ";
$l_turns_used		 = "Tours utilisés: ";
$l_turns_have		 = "Tours disponibles: ";
$l_score		 = "Points: ";
$l_sector		 = "Secteur";
$l_help			 = "Aide";
$l_faq		         = "FAQ";
$l_feedback		 = "Commentaires";
$l_forums		 = "Forums";
$l_logout		 = "Quitter";

$l_commands		 = "Commandes";
$l_command_no		 = "Commande non disponible.";
$l_devices		 = "Appareils";
$l_planets		 = "Planètes";
$l_log			 = "Journal";
$l_sector_def		 = "Défenses";
$l_defense		 = "Défenses";
$l_read_msg		 = "Lire Messages";
$l_send_msg		 = "Écrire Messages";
$l_rankings		 = "Rangs";
$l_teams		 = "Alliances";
$l_ohno			 = "Auto-Destruction";
$l_options		 = "Options";
$l_navcomp		 = "Ordinateur";

$l_incompletemove 	 = "Vous n'avez pas complété votre dernier déplacement.";
$l_clicktocontinue	 = "Cliquez ici pour continuer";
$l_toplanetmenu   	 = "Pour aller au menu de planète.";
$l_nonexistant_pl	 = "Sur une planète qui n'existe pas???";
$l_abord		 = ", à bord du ";
$l_messages_wait	 = " Messages qui vous attendent.";

$l_no_warplink		 = "Aucun liens";
$l_scan			 = "sonder";
$l_fullscan		 = "Sonder tout";

$l_port			 = "Port";
$l_tradingport		 = "Port commercial";
$l_planet_in_sec	 = "Planètes dans le secteur ";
$l_ships_in_sec		 = "Autres vaisseaux dans le secteur ";
$l_sector_0		 = "Il y a tellement de déplacements dans Sol (Secteur 0) que vous ne pouvez distinguer les vaisseaux entre eux!";

// report.php

$l_report_title		 = "État du vaisseau";

$l_level		 = "Niveau";

$l_ship_levels		 = "Niveau des composants";
$l_hull			 = "Coque";
$l_engines		 = "Moteurs";
$l_power		 = "Puissance";
$l_computer		 = "Ordinateur";
$l_sensors		 = "Sondeurs";
$l_armour		 = "Armure";
$l_shields		 = "Boucliers";
$l_beams		 = "Rayons";
$l_torp_launch	         = "Lanceurs de torpilles";
$l_cloak		 = "Camouflage";
$l_holds		 = "Cargaison";
$l_deflect		 = "Déflecteurs (mines)";
$l_ewd			 = "Hyper-espace d'urgence";


$l_arm_weap		 = "Armes & Armures";
$l_beacons		 = "Bouées Spatiales";
$l_warpedit		 = "Éditeurs de liens";
$l_genesis		 = "Torpilles Genesis";
$l_escape_pod		 = "Module de secours";
$l_fuel_scoop		 = "Collecteur d'énergie";

// device.php

$l_device_title		 = "Appareils";

$l_device_expl		 = "Votre vaisseau est équippé des appareils suivants (Cliquez sur un appareil pour l'utiliser) :";
$l_device		 = "Appareil";
$l_qty			 = "Quantité";
$l_usage		 = "Utilisation";
$l_manual		 = "Manuel";	
$l_automatic		 = "Automatique";

// port.php port2.php

$l_trade		 = "Acheter/Vendre";
$l_title_port		 = "Port Commercial";
$l_title_trade		 = "Commerce de biens";
$l_sector_war		 = "Embargo de guerre";
$l_war_info		 = "La guerre fait rage dans ce secteur. Vous ne pouvez atteindre le port à travers les forces hostiles.";
$l_no_trade		 = "Commerce interdit";
$l_no_trade_out		 = "Le commerce à ce port n'est pas permis pour les étrangers";
$l_no_trade_info	 = "Le commerce à ce port est interdit.";
$l_buying		 = "Achète";
$l_selling		 = "Vends";
$l_commodity		 = "Commodité";
$l_amount		 = "Quantité";
$l_price		 = "Prix";
$l_buy			 = "Acheter";
$l_sell			 = "Vendre";
$l_trade_st_info	 = "Vous avez [free_holds] unités d'espace libre, pouvez transporter [free_power] unités d'énergie additionnelles et vous disposez de [credits] crédits.";
$l_special_port		 = "Port Spécial";
$l_no_credits		 = "Pas assez de crédits";
$l_creds_to_spend	 = "Vous avez [credits] crédits à dépenser.";
$l_cost			 = "Coût";
$l_avail		 = "Disponible";
$l_profit		 = "Profit";
$l_current		 = "Présent";
$l_current_qty		 = "Quantités présentes";
$l_max			 = "Max";
$l_ifyouneedmore	 = "Si vous avez besoin de plus de crédits vous pouvez accéder au [igb] ";
$l_ifyouneedplan	 = "Accéder au ";
$l_igb_term		 = "Terminal Bancaire IGB";
$l_upgrade		 = "Améliorer?";
$l_unlimited		 = "Illimité";
$l_full			 = "Plein";
$l_equipped		 = "Équippé";
$l_n_a			 = "N/D";
$l_item			 = "Item";
$l_totalcost		 = "Coût Total";
$l_would_dump	         = "Si vous aimeriez laisser tous les colons que vous transportez ici, cliquez ";
$l_noport		 = "Il n'y a aucun port ici!";
$l_trade_turnneed	 = "Vous avez besoin d'au moins un tour pour faire du commerce à un port ou planète.";
$l_returnto_port         = " Cliquer <A HREF=port.php3>ici</A> pour retourner au menu du port.";
$l_notenough_cargo	 = "Vous n'avez pas assez d'espace pour stocker les commodités que vous voulez acheter.";
$l_notenough_power	 = "Vous ne disposez pas d'assez de puissance pour stocker l'énergie que vous voulez acheter.";
$l_notenough_credits	 = "Vous n'avez pas suffisament de crédits pour conclure cette transaction.";
$l_notenough_turns	 = "Vous n'avez pas suffisament de tours pour conclure cette transaction.";
$l_notenough_ore	 = "Vous ne disposez pas d'assez de métaux pour conclure cette transaction.";
$l_notenough_goods	 = "Vous ne disposez pas d'assez de produits pour conclure cette transaction.";
$l_notenough_energy	 = "Vous ne disposez pas d'assez d'énergie pour conclure cette transaction.";
$l_notenough_organics	 = "Vous ne disposez pas d'assez de végétaux pour conclure cette transaction.";
$l_exceed_organics	 = "Le nombre de végétaux dépasse l'offre/demande.  ";
$l_exceed_ore            = "Le nombre de métaux dépasse l'offre/demande.  ";
$l_exceed_energy         = "Le nombre d'énergie dépasse l'offre/demande.  ";
$l_exceed_goods          = "Le nombre de produits dépasse l'offre/demande.  ";
$l_trade_result		 = "Résultats pour cette transaction:";
$l_traded_ore		 = "Métaux échangés";
$l_traded_goods		 = "Produits échangés";
$l_traded_organics	 = "Végétaux échangés";
$l_traded_energy	 = "Énergie Échangée";
$l_trade_complete	 = "Transaction complète";
$l_trade_upgraded = "Amélioré";
$l_trade_added = "ajoutés";
$l_trade_installed = "installé";


// planet.php planet2.php planet3.php
$l_planet_title		 = "Menu de planète";
$l_planet_none		 = "Vous n'êtes pas dans le même secteur que cette planète, alors vous ne pouvez interagir avec elle.";
$l_planet_capture1	 = "capturer"; // thats the link's text
$l_planet_capture2	 = "Vous pouvez [capture] la planète ou simplement la laisser sans défense.";
$l_planet_unowned	 = "Cette planète n'a aucun propriétaire";
$l_planet_unnamed        = "Bienvenue sur la planète de [name]";
$l_planet_named		 = "Bienvenue sur [planetname], appartenant à [name].";
$l_planet_onsurface	 = "Vous êtes présentement sur la surface de la planète.";
$l_planet_orbit 	 = "Vous êtes présentement en orbite autour de la planète.";
$l_planet_leave_link     = "Décoller";
$l_planet_leave          = "[leave] de la planète";
$l_planet_land_link      = "Atterir";
$l_planet_land           = "[land] sur la planète";
$l_planet_name_link = "Nommer";
$l_planet_name2 = "[name] la planète";
$l_planet_logout	 = "Vous pouvez aussi <a href=logout.php3>Quitter</a> le jeu sous la protection de votre planète.";
$l_planet_selling	 = "La planète vend des commodités. ";
$l_planet_not_selling    = "La planète ne vend aucune commodité. ";
$l_planet_transfer_link	 = "Transférer";
$l_planet_transfer	 = "[transfer] des commodités/ressources/colons de/sur la planète";
$l_planet_hasbase	 = "Vous avez une base sur cette planète.";

$l_planet_perc		 = "Pourcentages de production";
$l_planet_interest	 = "* La production de crédits, mis à part les intérêts bancaires, est 100 - production d'autres commodités";
$l_planet_update	 = "Changer";
$l_planet_tsell_link	 = "vente";
$l_planet_tsell		 = "Changer la [selling] de commodités";
$l_planet_bbase_link	 = "construire une base";
$l_planet_bbase		 = "Avec assez de commodités et de crédits, vous pouvez [build] pour aider à la defense de votre planète.";
$l_planet_bbuild	 = "Base construite";
$l_planet_mcorp_linkC	 = "Planète Corporative";
$l_planet_mcorp_linkP	 = "Planète Personnelle";
$l_planet_mcorp		 = "Vous pouvez faire de cette planète une [planet].";
$l_planet_buy_link	 = "Acheter";
$l_planet_buy		 = "[buy] des commodités de la planète";
$l_planet_att_link	 = "Attaquer";
$l_planet_att		 = "[attack] la planète";
$l_planet_att_sure	 = "Êtes vous CERTAIN...";
$l_planet_scn_link	 = "Sonder";
$l_planet_scn		 = "[scan] la planète";
$l_planet_nowsell        = "La planète vend maintenant des commodités.";
$l_planet_nownosell      = "La planète ne vend plus de commodités.";
$l_planet_iname		 = "Entrer le nouveau nom de la planète";
$l_planet_cname		 = "La planète à été renommée ";
$l_planet_landed	 = "Vous avez atteri sur la surface de la planète.";
$l_planet_left		 = "Vous n'êtes plus sur la surface de la planète.";
$l_planet_cinfo		 = "Vous avez de la place pour [cargo] unités de cargaison supplémentaires.  Vous avez la capacité pour [energy] unités d'énergie en plus.";
$l_planet_toplanet	 = "Vers la planète?";
$l_planet_baseinfo	 = "Pour construire une base vous devez avoir au moins $base_credits crédits, $base_ore unités de métaux, $base_organics unités végétaux, et $base_goods unités of produits sur la planète.";
$l_planet_p_under        = "Vous ne pouvez choisir un nombre négatif pour un pourcentage de production.";
$l_planet_p_over	 = "La somme des pourcentages de production ne peut dépasser 100%.";
$l_planet_p_changed	 = "Les pourcentages de production ont été modifiés.";
$l_plant_scn_turn	 = "Vous avez besoin d'au moins un tour pour sonder une planète.";
$l_planet_noscan	 = "Les sondeurs ne parviennent pas à se vérouiller sur la cible!";
$l_planet_scn_report	 = "Résultat de la sonde sur [name], appartenant à:  [owner]";
$l_base	  		 = "Base";
$l_planet_ison		 = "est sur la planète.";
$l_planet_captured	 = "Planète capturée";
$l_planet_notdef	 = "La planète n'a pas été vaincue!";

$l_planet2_title	 = "Transfer Planétaire";
$l_planet2_noturn	 = "Vous avez besoin d'au moins un tour pour effectuer un transfer.";
$l_planet2_noten 	 = "Vous n'avez pas assez de ";
$l_planet2_fortr	 = "pour effectuer le transfer.";
$l_planet2_settr	 = "La quantité transférée ajustée à ";
$l_planet2_losup	 = "La planète est capable de fournir seulement ";
$l_planet2_notowner	 = "Cette planète ne vous appartient pas.";
$l_planet2_compl	 = "Transfer complété.";
$l_planet2_power	 = "puissance";
$l_planet2_comp 	 = "ordinateurs";
$l_planet2_laun 	 = "lanceurs de torpilles";
$l_planet2_nocorptransfer = "Vous ne pouvez transferer des crédits sur une planète corporative.";

$l_planet3_title	 = "Commerce de planète";

// planet-report.php

$l_pr_title		 = "Rapport des planètes";
$l_pr_teamlink		 = "Montrer les planètes de votre alliance";
$l_pr_noplanet		 = "Vous ne possédez aucune planète.";
$l_pr_clicktosort	 = "Cliquez sur un en-tête pour trier les résultats.";
$l_pr_totals		 = "Totaux";

// rsmove.php
$l_rs_title 		= "Déplacement en espace réel";
$l_rs_whichsector       = "Quel secteur aimeriez-vous atteindre à travers l'espace réel?";
$l_rs_insector		= "Vous êtes présentement dans le secteur [sector] - et les secteurs disponibles vont de 0 à [sector_max].";
$l_rs_submit		= "Calculer";
$l_rs_movetime		= "Avec vos moteurs, vous prendrez [triptime] tours pour compléter le voyage.";
$l_rs_energy		= "Vous collecterez [energy] unités d'énergie";
$l_rs_noturns		= "Vous n'avez pas assez de tours disponibles, donc vous ne pouvez faire ce voyage.";
$l_rs_engage_link	= "activer";
$l_rs_engage		= "Vous avez [turns] tours. [engage] les moteurs?";

$l_rs_invalid		= "Destination non-valide";
$l_rs_ready 		= "Vous êtes maintenant dans le sector [sector]. Vous avez utilisé [triptime] tours et collecté [energy] unités d'énergie.";

// navcomp.php	

$l_nav_title		 = "Ordinateur de bord";
$l_nav_nocomp		 = "L'ordinateur de bord n'est pas disponible";
$l_nav_query		 = "Entrez le sector que vous voudriez atteindre: ";
$l_nav_pathfnd		 = "Chemin trouvé:";
$l_nav_answ1		 = "Vous utiliserez";
$l_nav_answ2		 = "tours pour atteindre ce secteur.";
$l_nav_proper		 = "La technologie de votre ordinateur est trop primitive pour calculer un chemin jusqu'à ce secteur.";


// attack.php

$l_att_title		 = "Attaque de vaisseau";
$l_att_notarg		 = "La cible n'est pas dans ce secteur.";
$l_att_noturn		 = "Vous avez besoin d'au moins un tour pour pouvoir attaquer.";
$l_att_noatt		 = "Il n'est pas permis d'attaquer quelqu'un dans ce secteur.";
$l_att_flee		 = "Le vaisseau ennemi vous échape!";
$l_att_ewd		 = "Le vaisseau est entré d'urgence dans l'hyper-espace quand vous l'avez attaqué!";
$l_att_att		 = "Attaque ";
$l_att_beams		 = "Rayons touchent:";
$l_att_torps		 = "Torpilles touchent:";
$l_att_fighters		 = "Intercepteurs attaquent:";
$l_att_lost		 = "a perdu";
$l_att_ylost		 = "Vous avez perdu";
$l_att_sdown		 = " -> Boucliers tombent!";
$l_att_ydown		 = "Vos boucliers sont tombés!";
$l_att_shits		 = " -> Boucliers touchés de";
$l_att_yhits		 = "Vos boucliers sont touchés de";
$l_att_dmg		 = "points de dommage";
$l_att_sarm		 = " -> Armure pénétrée";
$l_att_yarm		 = "Votre armure est pénétrée!";
$l_att_ashit		 = " -> Armure touchée de";
$l_att_ayhit		 = "Votre armure est touchée de";
$l_att_lostf		 = "a perdu tous ses intercepteurs.";
$l_att_ylostf		 = "Vous avez perdu tous vos intercepteurs.";
$l_att_sdest		 = " -> Vaisseau détruit.";
$l_att_espod		 = "Un module de secours a été lancé!";
$l_att_ysalv		 = "Vous récupérez [salv_ore] unités de métaux, [salv_organics] unités de végétaux, [salv_goods] unités de produits, et [ship_salvage_rate]% du vaisseau pour [ship_salvage] crédits.<BR>Vous gagnez [rating_change] points.";
$l_att_andused		 = "et utilisé";
$l_att_stilship		 = "Vous n'avez pas détruit le vaisseau de [name].";
$l_att_atyou		 = "attacked you";
$l_att_and		 = "et";
$l_att_yshiplost	 = "Votre vaisseau a été détruit!";
$l_att_salv		 = "[name] a récupéré [salv_ore] unités de métaux, [salv_organics] unités de végétaux, [salv_goods] unités de produits, et [ship_salvage_rate]% du vaisseau pour [ship_salvage] crédits";

// warpedit 1-3.php

$l_warp_title		 = "Éditeur de liens";
$l_warp_turn		 = "Vous avez besoin d'au moins un tour pour utiliser un éditeur de liens.";
$l_warp_none		 = "Vous n'avez aucun éditeur de liens.";
$l_warp_forbid		 = "Il n'est pas permis d'utiliser un éditeur de liens.";
$l_warp_nolink		 = "Il n'y a aucun lien sortant de ce secteur.";
$l_warp_linkto		 = "Il y a des liens de ce secteur vers";
$l_warp_query		 = "Vers quel secteur voudriez-vous créer un lien?";
$l_warp_oneway		 = "Sens unique?";
$l_warp_dest		 = "Vous pouvez aussi détruire un lien vers ce secteur";
$l_warp_destquery	 = "Vers quel secteur voudriez-vous détruire le lien?";
$l_warp_bothway		 = "Deux sens";
$l_warp_nosector	 = "Ce secteur n'existe pas.";
$l_warp_twoerror	 = "L'utilisation d'un éditeur de lien pour créer un lien vers [target_sector] n'est pas permis.";
$l_warp_sectex		 = "Vous ne pouvez créer un lien à partir du secteur courant - vous dépasseriez la limited de $link_max par secteur.";
$l_warp_linked		 = "Le secteur cible ([target_sector]) à déjà un lien à partir de ce secteur.";
$l_warp_unlinked	 = "Le secteur cible ([target_sector]) n'a pas de lien à partir de ce secteur.";
$l_warp_coneway	         = "Lien a sens unique créé vers";
$l_warp_ctwoway		 = "Lien créé de et vers";
$l_warp_forbidtwo	 = "L'utilisation d'un éditeur de lien pour détruire un lien de/vers [target_sector] n'est pas permis.";
$l_warp_removed		 = "Le lien à été détruit, vers";
$l_warp_removedtwo	 = "Le lien à été détruit, de et vers";

// genesis.php

$l_gns_title		 = "Torpille Genesis";
$l_gns_turn		 = "Vous avez besoin d'au moins un tour pour utiliser une torpille genesis.";
$l_gns_onplanet		 = "Vous ne pouvez utiliser une torpille genesis à la surface d'une planète.";
$l_gns_full		 = "Ce système solaire est déjà plein.";
$l_gns_nogenesis	 = "Vous ne possédez aucune torpille genesis.";
$l_gns_forbid		 = "La création d'une planète dans ce secteur n'est pas permise.";
$l_gns_bforbid		 = "Les bases dans se secteur interferent avec la torpille genesis. La création d'une planète est impossible.";
$l_gns_pcreate		 = "Une nouvelle planète est créée.";

// ship.php

$l_ship_title		 = "Vaisseau";
$l_ship_the		 = "Le";
$l_ship_nolonger	 = "n'est plus dans ce secteur.";
$l_ship_youc		 = "Vous voyez le";
$l_ship_owned		 = "appartenant à";
$l_ship_perform		 = "Vous pouvez performer les actions suivantes:";

// selfdestruct.php

$l_die_title		 = "Auto-destruction";
$l_die_rusure		 = "Êtes-vous certain que vous voulez détruire votre vaisseau? Cette action vous retirera du jeu.";
$l_die_goodbye		 = "Adieu, cruelle galaxie!";
$l_die_check		 = "Êtes-vous vraiment certain que vous voulez vous retirer du jeu?";
$l_die_nonono		 = "NON! NON! NON!";
$l_die_what		 = "À quoi je pensais?";
$l_die_count		 = "5.. 4.. 3.. 2.. 1.. Boom!";
$l_die_vapor		 = "Votre vaisseau et tous ceux à bord ont été vaporisés.";
$l_die_please		 = "S'il vous plaît, <A HREF=logout.php3>Quittez</A>";
$l_die_exploit		 = "Ne jouez pas avec ce que vous ne comprenez pas.";

// move.php

$l_move_title 		 = "Déplacement";
$l_move_turn		 = "Vous avez besoin d'au moins un tour pour vous déplacer.";
$l_move_failed		 = "Le déplacement a échoué!";

// scan.php

$l_scan_title		 = "Sonder un vaisseau";
$l_scan_turn		 = "Vous avez besoin d'au moins un tour pour sonder un autre vaisseau.";
$l_scan_ron		 = "Résultats de la sonde sur";
$l_scan_capt		 = "Capitaine:";
$l_scan_arma		 = "Armement:";
$l_scan_carry		 = "Cargaison:";

// lrscan.php

$l_lrs_title		 = "Sonde longue distance";
$l_lrs_nofull		 = "Vos sondeurs ne possèdent aucune fonction longue distance.";
$l_lrs_noturns		 = "Vous avez besoin d'au moins $fullscan_cost tour(s) pour performer un sondage complet.";
$l_lrs_used		 = "Vous avez utilisé";
$l_lrs_turns		 = "tour(s)";
$l_lrs_left		 = "restant";
$l_lrs_reach		 = "Les locations suivantes peuvent être atteinte à partir du secteur [sector]:";
$l_lrs_links		 = "Liens";
$l_lrs_ships		 = "Vaisseaux";
$l_lrs_click		 = "Cliquez sur un des liens pour vous déplacer vers ce secteur.";
$l_lrs_cantscan		 = "Vous ne pouvez sonder ce secteur à partir du secteur courant!";
$l_lrs_zero		 = "Le secteur 0 montre beaucoup trop d'activité pour isoler les vaisseaux!";
$l_lrs_moveto		 = "pour vous déplacer vers le secteur";

// log.php

$l_log_months = array('Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Décembre');
$l_log_months_short = array('Jan','Fév','Mar','Avr','Mai','Jun','Jui','Au','Sep','Oct','Nov','Déc');
$l_log_pod = "Heureusement, vous aviez un module de secours!";
$l_log_nopod = "<font color=yellow><b>Vous n'aviez pas de module de secours, vous êtes mort.</b></font>";
$l_log_log = "Journal de [player]";
$l_log_start = "Entrées pour";
$l_log_end = "Fin des entrées pour";
$l_log_click = "Cliquez <A HREF=$interface><font color=#00ff00>ici</font></A> pour retourner au menu principal.";
$l_log_note = "NOTE: Si cette page ne s'affiche pas correctement, ou si vous n'aimez pas les effets de HTML dynamique ou vous les trouvez agaçants, vous pouvez les désactiver <a href=options.php3><font color=#00FF00>ici</font>";

$l_log_text[LOG_LOGIN] = "Vous vous êtes connecté, à partir de [ip].";
$l_log_title[LOG_LOGIN] = "Connection";
$l_log_text[LOG_LOGOUT] = "Vous vous êtes déconnecté, à partir de [ip].";
$l_log_title[LOG_LOGOUT] = "Déconnection";
$l_log_text[LOG_ATTACK_OUTMAN] = "[player] a été ciblé sur un vecteur d'attaque, mais votre grand talent de pilote et vos moteurs supérieurs vous ont permis d'éviter l'ennemi.";
$l_log_title[LOG_ATTACK_OUTMAN] = "Esquive!";
$l_log_text[LOG_ATTACK_OUTSCAN] = "Vous avez détecté les armes de [player] qui essayaient de se verrouiller sur votre vaisseau, mais vos générateurs de camouflage vous ont permis de tromper l'armement primitif de votre ennemi.";
$l_log_title[LOG_ATTACK_OUTSCAN] = "Camouflage!";
$l_log_text[LOG_ATTACK_EWD] = "Vous êtes surpris par l'attaque en traitre de [player]. Vous pouvez apercevoir les missiles qui se dirigent vers vous pendant que vous courez vers le bouton d'hyper-espace d'urgence. L'univers se brouille autour de vous et, pour une milli-seconde, vous croyez que vous êtes mort. Quand vous ouvrez finallement les yeux, vous vous apercevez que vous avez été transporté dans un endroit plus sûr. Mais où est cet endroit, vous ne le savez pas...";
$l_log_title[LOG_ATTACK_EWD] = "Hyper-espace d'urgence!";
$l_log_text[LOG_ATTACK_EWDFAIL] = "Vos détecteurs se fixent sur le vaisseau de [player], qui est sur un vecteur d'attaque. \"Mieux vaut prévenir que guérir\", vous pensez, appuyant sur le bouton d'hyper-espace d'urgence. Vous entendez un son étrange d'étouffement venant de la salle des moteurs et vous sentez des circuits brûlés. \"Stupide boîte de conserve!\", vous criez, en donnant un coup de pied à l'ordinateur. Il émet des bips de protestation pendant que vous vous préparez pour le combat...";
$l_log_title[LOG_ATTACK_EWDFAIL] = "Hyper-espace d'urgence <font color=red>en panne!</font>";
$l_log_text[LOG_ATTACK_LOSE] = "Votre vaisseau est attaqué par [player]. Vous faites de votre mieux, mais vous ne pouvez vous défendre contre l'armement supérieur de [player]. Votre vaisseau a été détruit. ";
$l_log_title[LOG_ATTACK_LOSE] = "<font color=red>Combat perdu!</font>";
$l_log_text[LOG_ATTACKED_WIN] = "Votre vaisseau a été attaqué par [player]. Vous vous battez un moment, puis le combat cesse. Vous perdez [armor] points d'armure et [fighters] intercepteurs dans l'escarmouche.";
$l_log_title[LOG_ATTACKED_WIN] = "<font color=yellow>Escarmouche!</font>";
$l_log_text[LOG_TOLL_PAID] = "Vous avez dû payer [toll] crédits pour entrer dans le secteur [sector]. Vous vous promettez bien de trouvez un moyen de récupérer votre argent.";
$l_log_title[LOG_TOLL_PAID] = "Extortion";
$l_log_text[LOG_HIT_MINES] = "Vous frappez [mines] mines dans le secteur [sector].";
$l_log_title[LOG_HIT_MINES] = "<font color=yellow>Alerte, mines!</font>";
$l_log_text[LOG_SHIP_DESTROYED_MINES] = "Votre vaisseau a été détruit par un champ de mines dans le secteur [sector]. ";
$l_log_title[LOG_SHIP_DESTROYED_MINES] = "<font color=red>Alerte, mines!</font>";
$l_log_text[LOG_PLANET_DEFEATED_D] = "Votre planète [planet_name] dans le secteur [sector] a été capturée dans une féroce bataille par [name]. Heureusement, la forte loyauté de vos citoyens a joué en votre faveur. Ils ont bravement choisi de détruire la planète plutôt que de la laisser entre des mains ennemies. Vous organizez de superbes funérailles  en mémoire de vos gens fidèles.";
$l_log_title[LOG_PLANET_DEFEATED_D] = "<font color=yellow>Planète détruite</font>";
$l_log_text[LOG_PLANET_DEFEATED] = "Votre planète [planet_name] dans le secteur [sector] dans une féroce bataille par [name]. Les gens de la planète souhaitent la bienvenue à leur nouveau seigneur. Vous entendez un témoignage sur BNN : \"Nous sommes bien content d'être débarassé de ce vieux crouton! Nous ne voulons pas d'un perdant qui ne peut même pas assurer notre protection!\". Vous vous jurez de les faire payer pour leur arrogance.";
$l_log_title[LOG_PLANET_DEFEATED] = "<font color=red>Planète capturée!</font>";
$l_log_text[LOG_PLANET_NOT_DEFEATED] = "Votre planète [planet_name] dans le secteur [sector] a été attaquée par [name]. Les citoyens ont organisé une vaillante résistance, cependant, et ont réussi à détruire l'ennemi. Ils ont récupéré quelques ressources des débris : [goods] produits, [ore] métaux, [organics] végétaux et [salvage]% de la valeur du vaisseau pour [credits] crédits.";
$l_log_title[LOG_PLANET_NOT_DEFEATED] = "Victoire!";
$l_log_title[LOG_RAW] = "Notice";
$l_log_text[LOG_TOLL_RECV] = "Vos intercepteurs dans le secteur [sector] ont collecté une 'taxe' de [toll] crédits.";
$l_log_title[LOG_TOLL_RECV] = "Droits de passage";
$l_log_text[LOG_DEFS_DESTROYED] = "[quantity] [type] ont été détruits dans le secteur [sector].";
$l_log_title[LOG_DEFS_DESTROYED] = "Défenses détruites";
$l_log_text[LOG_PLANET_EJECT] = "Vous avez été éjecté de la planète dans le secteur [sector] parce que [name] à quitté votre alliance.";
$l_log_title[LOG_PLANET_EJECT] = "Éjecté!";
$l_log_text[LOG_BADLOGIN] = "Tentative de connection échouée à partir de [ip].";
$l_log_title[LOG_BADLOGIN] = "Mauvais mot de passe";
$l_log_text[LOG_PLANET_SCAN] = "[name] a sondé votre plànete [planet_name] dans le secteur [sector].";
$l_log_title[LOG_PLANET_SCAN] = "Planète sondée";
$l_log_text[LOG_PLANET_SCAN_FAIL] = "[name] a essayé de sonder votre planète [planet_name] dans le secteur [sector], mais a échoué.";
$l_log_title[LOG_PLANET_SCAN_FAIL] = "Tentative de sonde";
$l_log_text[LOG_SHIP_SCAN] = "[player] a sondé votre vaisseau.";
$l_log_title[LOG_SHIP_SCAN] = "Vaisseau sondé";
$l_log_text[LOG_SHIP_SCAN_FAIL] = "[player] a essayé de sonder votre vaisseau, mais a échoué.";
$l_log_title[LOG_SHIP_SCAN_FAIL] = "Tentative de sonde";
$l_log_text[LOG_FURANGEE_ATTACK] = "Attaque sur [player]...";
$l_log_title[LOG_FURANGEE_ATTACK] = "Attaque";
$l_log_text[LOG_STARVATION] = "Une de vos planètes dans le secteur [sector] ne peut soutenir sa population! Plus de végétaux sont nécéssaires. [starvation] colons sont morts de faim.";
$l_log_title[LOG_STARVATION] = "<font color=yellow>Famine!</font>";
$l_log_text[LOG_TOW] = "Votre vaisseau a été remorqué du secteur [sector] vers le secteur [newsector] parce que sa coque dépassait la limite persise de [hull].";
$l_log_title[LOG_TOW] = "Remorqué!";
$l_log_text[LOG_DEFS_DESTROYED_F] = "Vous avez détruit [fighters] intercepteurs dans le secteur [sector].";
$l_log_title[LOG_DEFS_DESTROYED_F] = "Intercepteurs détruits";
$l_log_text[LOG_DEFS_KABOOM] = "Votre vaisseau a été détruit par une force d'intercepteurs dans le secteur [sector]. ";
$l_log_title[LOG_DEFS_KABOOM] = "<font color=red>Vaisseau détruit!</font>";
$l_log_text[LOG_HARAKIRI] = "Vous êtes fatigué de commander cette poubelle volante. Vous décidez que l'univers sera un meilleur endroit sans vous. Votre vaisseau et tout son équipage sont vaporisés quand vous activez la commande d'auto-destruction. Authorisé à partir de [ip].";
$l_log_title[LOG_HARAKIRI] = "<font color=red>Auto-destruction!</font>";
$l_log_text[LOG_TEAM_REJECT] = "[player] a rejeté l'invitation pour faire partie de votre alliance [teamname].";
$l_log_title[LOG_TEAM_REJECT] = "Invitation rejetée";
$l_log_text[LOG_TEAM_RENAME] = "Vous avez renommé votre alliance [team].";
$l_log_title[LOG_TEAM_RENAME] = "Alliance renommée";
$l_log_text[LOG_TEAM_M_RENAME] = "Le co-ordinateur de votre alliance a rebaptisé l'alliance [team].";
$l_log_title[LOG_TEAM_M_RENAME] = "Alliance renommée";
$l_log_text[LOG_TEAM_KICK] = "Vous avez été éjecté de l'alliance [team].";
$l_log_title[LOG_TEAM_KICK] = "Éjecté!";
$l_log_text[LOG_TEAM_CREATE] = "Vous avez crée une nouvelle alliance, [team].";
$l_log_title[LOG_TEAM_CREATE] = "Nouvelle alliance créée";
$l_log_text[LOG_TEAM_LEAVE] = "Vous avez quitté l'alliance [team].";
$l_log_title[LOG_TEAM_LEAVE] = "Départ";
$l_log_text[LOG_TEAM_NEWLEAD] = "Vous avez quitté l'alliance [team]. Vous avez passé la direction de l'alliance à [name].";
$l_log_title[LOG_TEAM_NEWLEAD] = "Départ";
$l_log_text[LOG_TEAM_LEAD] = "Le co-ordinateur de votre alliance [team] a décidé de quitter l'alliance. Vous avez été désigné pour prendre sa place.";
$l_log_title[LOG_TEAM_LEAD] = "Promotion!";
$l_log_text[LOG_TEAM_JOIN] = "Vous êtes maintenant member de l'alliance [team].";
$l_log_title[LOG_TEAM_JOIN] = "Nouveau membre";
$l_log_text[LOG_TEAM_NEWMEMBER] = "[name] a accepté de se joindre à [team]. Ceci vous approche un peu plus de la domination totale!";
$l_log_title[LOG_TEAM_NEWMEMBER] = "Nouveau membre";
$l_log_text[LOG_TEAM_INVITE] = "Vous avez été invité pour faire partie de l'alliance [team].";
$l_log_title[LOG_TEAM_INVITE] = "Invitation";
$l_log_text[LOG_TEAM_NOT_LEAVE] = "[player] a quitté votre alliance.";
$l_log_title[LOG_TEAM_NOT_LEAVE] = "Alliance diminuée";
$l_log_text[LOG_ADMIN_HARAKIRI] = "[player] s'est auto-détruit à partir de [ip].";
$l_log_title[LOG_ADMIN_HARAKIRI] = "Auto-destruction";
$l_log_text[LOG_ADMIN_ILLEGVALUE] = "[player] avait [quantity] [type], alors que son maximum possible était [holds]";
$l_log_title[LOG_ADMIN_ILLEGVALUE] = "Valeur illégale";
$l_log_text[LOG_ADMIN_PLANETDEL] = "[attacker] a essayé de capturer la planète de [defender] dans le secteur [sector]. La planète a été détruite.";
$l_log_title[LOG_ADMIN_PLANETDEL] = "Planète détruite";
$l_log_text[LOG_DEFENCE_DEGRADE] = "Les intercepteurs dans le secteur [sector] ce sont dégradés de [degrade] pourcents parce qu'ils n'ont pas assez d'énergie.";
$l_log_test[LOG_DEFENCE_DEGRADE] = "Dégradation";

// modify-defences.php

$l_md_title		 = "Défenses de secteur";
$l_md_invalid		 = "Défense invalide";
$l_md_nolonger		 = "La défense que vous avez choisi n'est plus dans ce secteur.";
$l_md_you		 = "Vous";
$l_md_bmines		 = "Vos rayons détruisent";
$l_md_msgdownerb	 = "[name] a détruit [mines] mines dans le secteur [sector].";
$l_md_retr		 = "Vous récupérez";
$l_md_mode		 = "Les intercepteurs ont été placés en mode [mode].";
$l_md_consist		 = "Cette défense consiste de [qty] [type], appartenant à [owner].";
$l_md_youcan		 = "Vous pouvez";
$l_md_retrieve		 = "Récupérer";
$l_md_change		 = "Changer le mode des intercepteurs";
$l_md_cmode		 = "Mode des intercepteurs";
$l_md_attack		 = "Attaque";
$l_md_toll		 = "Taxe";
$l_md_attdef		 = "Attaquer les défenses de secteur. Tous les intercepteurs présents vont converger vers vous.";

// news.php

$l_news_title		 = "Nouvelles de l'Univers Blacknova";
$l_news_info		 = "BNN est la meilleur source<br>
                   de nouvelles et informations dans l'univers.<br>
                   Une équipe qui travaille 24 heures, sept jours par <br>
                   semaines vous apporte toutes les manchettes! Nos <br>
                   bureaux sont disséminés à travers toute la galaxie!";
$l_news_for		 = "Manchettes pour";
$l_news_prev		 = "jour précédent";
$l_news_next		 = "jour suivant";
$l_news_none		 = "Désolé, aucune nouvelles ajourd'hui.";
$l_news_flash		 = "Manchette!";

// dump.php

$l_dump_title		 = "Débarquement de colons";
$l_dump_turn		 = "Vous avez besoin d'au moins un tour pour débarquer des colons.";
$l_dump_nocol		 = "Vous n'avez aucun colon à bord.";
$l_dump_dumped		 = "Les colons ont été débarqués à la station.";
$l_dump_nono		 = "Vous avez besoin d'une station pour pouvoir débarquer des colons.";

// readmail.php

$l_readm_title		 = "Lire les messages";

$l_readm_delete		 = "MESSAGE EFFACÉ";
$l_readm_nomessage	 = "Vous n'avez aucun message en attente";
$l_readm_center		 = "Centre de messagerie";
$l_readm_sender		 = "Source";
$l_readm_captn		 = "Capitaine du ";
$l_readm_del		 = "Effacer";
$l_readm_repl		 = "Répondre";

// mailto2.php

$l_sendm_title		 = "Envoyer un message";
$l_sendm_to		 = "À";
$l_sendm_from		 = "De";
$l_sendm_ally		 = "Alliance:";
$l_sendm_subj		 = "Sujet";
$l_sendm_mess		 = "Message";
$l_sendm_send		 = "Envoyer";
$l_sendm_sent		 = "Message envoyé";

// zoneinfo.php

$l_zi_title		 = "Informations sur la zone";
$l_zi_nexist		 = "Cette section d'espace n'existe pas!";
$l_zi_feds		 = "Fédération";
$l_zi_traders		 = "La coalition du commerce libre";
$l_zi_nobody		 = "Personne";
$l_zi_war		 = "Espace contesté";
$l_zi_allow		 = "Permis";
$l_zi_notallow		 = "Non permis";
$l_zi_limit		 = "Limité aux allié";
$l_zi_ul		 = "Illimité";
$l_zi_control		 = "Vous êtes en contôle de cette zone";
$l_zi_tochange		 = "pour changer ses lois.";
$l_zi_owner		 = "Responsable de la zone";
$l_zi_maxhull		 = "Coque maximum permise";

// zoneedit.php

$l_ze_title		 = "Éditer une zone";
$l_ze_notowner		 = "Cette zone ne vous appartient pas alors vous ne pouvez la modifier.";
$l_ze_name		 = "Nom de la zone";
$l_ze_allow		 = "Permettre";
$l_ze_attacks		 = "Permettre l'attaque de vaisseaux";
$l_ze_genesis		 = "Permettre la création de planètes";
$l_ze_return		 = "pour retourner à la page d'information sur la zone.";
$l_ze_saved		 = "Vos modifications ont été sauvegardées.";

// teams.php

$l_team_title		 = "Alliances";
$l_team_menu		 = "pour retourner au menu des Alliances";
$l_team_galax		 = "Alliances dans la galaxie:";
$l_team_members		 = "Membres";
$l_team_coord		 = "Co-ordonateur";
$l_team_member		 = "Membre";
$l_team_noinvite	 = "Vous n'avez pas été invité à faire partie d'une alliance.";
$l_team_ifyouwant	 = "Si vous désirez joindre une alliance, envoyez un message à son co-ordinateur pour être invité.";
$l_team_tocreate	 = "pour créer une nouvelle alliance.";
$l_team_injoin		 = "Vous avez été invité à rejoindre";
$l_team_tojoin		 = "pour accepter";
$l_team_or		 = "ou";
$l_team_reject		 = "pour rejeter l'invitation.";
$l_team_ed		 = "Modifier";
$l_team_inv		 = "Inviter";
$l_team_leave		 = "Quitter";
$l_team_eject		 = "Éjecter";
$l_team_pending		 = "Invitations pour";
$l_team_noinvites	 = "Personne n'a été invité à faire partie de";
$l_team_confirmleave	 = "Êtes vous certain que vous voulez quitter";
$l_team_onlymember	 = "Vous étiez le seul membre, alors [team_name] n'existe plus.";
$l_team_youarecoord	 = "Vous êtes le co-ordonateur de";
$l_team_relinq		 = "Vous devez donner votre poste à un autre joueur.";
$l_team_newc		 = "Nouveau co-ordonateur:";
$l_team_youveleft	 = "Vous avez quitté l'alliance";
$l_team_relto		 = "laissant le rôle de co-ordonateur à";
$l_team_welcome		 = "Bienvenue dans l'alliance";
$l_team_noinviteto	 = "Vous n'avez pas été invité à faire partie de cette équipe.";
$l_team_ejectsure	 = "Êtes-vous certain de vouloir éjecter";
$l_team_ejected 	 = "a été éjecté de l'alliance!";
$l_team_testing		 = "Phase de test...";
$l_team_pw		 = "Mot de passe";
$l_team_entername	 = "Entrez le nom de l'alliance";
$l_team_enterdesc	 = "Entrez une description de l'alliance";
$l_team_hcreated	 = "à été créée et vous êtes son co-ordonateur";
$l_team_alliance	 = "Alliance";
$l_team_selectp		 = "Sélectionnez le joueur que vous désirez inviter";
$l_team_isorry		 = "Désolé, mais [name] à déjà reçu une invitation pour faire partie d'une alliance - seulement une invitation à la fois est permise";
$l_team_plinvted	 = "Le joueur a été invité.<BR>Vous devez attendre la réponse de ce joueur.";
$l_team_refuse		 = "Vous avez refusé l'invitation à vous joindre à";
$l_team_edname		 = "Modifier le nom de l'alliance";
$l_team_eddesc		 = "Modifier la description de l'alliance";
$l_team_hasbeenr	 = "a été renommée.";
$l_team_error		 = "<b><font color=red>Une erreur s'est produite</font></b><br>Vous n'êtes pas le co-ordonateur de cette Alliance.";
$l_team_notmember	 = "Vous n'êtes membre d'aucune alliance";
$l_team_urejected	 = "<B>ATTENTION</B> - vous avez été éjecté de";
$l_team_noalliances	 = "Il n'y a présentement aucune alliance dans la galaxie.";

// ranking.php

$l_ranks_title		 = "$max_rank meilleurs joueurs";
$l_ranks_none		 = "Aucun résultat à afficher.";
$l_ranks_pnum		 = "Nombre total de joueurs ";
$l_ranks_dships		 = "Les joueurs avec un vaisseau détruit ne sont pas comptés.";
$l_ranks_rank		 = "Rang";
$l_ranks_lastlog	 = "Dernière connection";
$l_ranks_good		 = "Bon";
$l_ranks_evil		 = "Mauvais";

// beacon.php

$l_beacon_title		 = "Déployer une bouée spatiale";
$l_beacon_notpermitted	 = "Les bouées spatiales ne sont pas permises dans ce secteur.";
$l_beacon_reads		 = "La bouée présente affiche :";
$l_beacon_none		 = "Il n'y a présentement aucune bouée dans ce secteur.";
$l_beacon_enter		 = "Entrez le texte de la bouée";
$l_beacon_nowreads	 = "La bouée affiche maintenant";
$l_beacon_donthave	 = "Vous n'avez aucun bouée.";

// emerwarp.php

$l_ewd_title		 = "Hyper-espace d'urgence";
$l_ewd_used		 = "Hyper-espace d'urgence engagé - vous arrivez dans le secteur [sector].";
$l_ewd_none		 = "Vous n'avez pas d'hyper-espace d'urgence.";

// defence-report.php

$l_sdf_title		 = "Rapport des défenses";
$l_sdf_none		 = "Vous n'avez aucune défense déployée.";
$l_sdf_type		 = "Type";
$l_sdf_mode		 = "Mode";

// traderoute.php
// cause its rather big i put everything in own vars than to re-use
// the old ones so we could export to own file if performance problems
// should occur

$l_tdr_title    	 = "Routes Commerciales";
$l_tdr_newtdr   	 = "Cliquez <a href=\"traderoute.php?command=new\">ici</a> pour créer une nouvelle route";
$l_tdr_modtdrset         = "Pour modifier les paramètres commerciaux globaux, cliquez <a href=\"traderoute.php?command=settings\">ici</a>";
$l_tdr_confdel  	 = "Clquez <a href=\"traderoute.php?command=delete&confirm=yes&traderoute_id=[tdr_id]\">ici</a> pour confirmer la destruction de la route suivante :";
$l_tdr_noactive 	 = "You do not have any active trade routes to display.";
$l_tdr_curtdr   	 = "Current Trade Routes";
$l_tdr_deltdr   	 = "Delete Trade Route";
$l_tdr_src      	 = "Source";
$l_tdr_srctype  	 = "Src Type";
$l_tdr_dest     	 = "Destination";
$l_tdr_desttype 	 = "Dest Type";
$l_tdr_move     	 = "Move";
$l_tdr_circuit  	 = "Circuit";
$l_tdr_change   	 = "Change";
$l_tdr_portin   	 = "Port in";
$l_tdr_planet   	 = "Planet";
$l_tdr_nonexistance      = "Non-existant planet!";
$l_tdr_na       	 = "N/A";
$l_tdr_cargo    	 = "Cargo";
$l_tdr_none     	 = "None";
$l_tdr_colonists         = "Colonists";
$l_tdr_fighters 	 = "Fighters";
$l_tdr_torps    	 = "Torpedoes";
$l_tdr_escooped 	 = "[tdr_dist_triptime] turns<br>[tdr_dist_scooped] energy 
scooped";
$l_tdr_warp     	 = "Warp";
$l_tdr_turns    	 = "turns";
$l_tdr_way      	 = "way";
$l_tdr_ways     	 = "ways";
$l_tdr_edit     	 = "Edit";
$l_tdr_del      	 = "Delete";
$l_tdr_nowlink1 	 = "There is no warp link from sector [tdr_src_sector_id] to 
sector [tdr_dest_sector_id]";
$l_tdr_nowlink2 	 = "There is no warp link from sector [tdr_dest_sector_id] to 
sector [tdr_src_sector_id]";
$l_tdr_sportissrc        = "If a special port is source, a planet must be the 
destination for colonization.";
$l_tdr_notownplanet      = "You can't colonize a planet that you or your team 
don't own.";
$l_tdr_planetisdest      = "A planet can be a destination only when source is 
a special port.";
$l_tdr_samecom 		 = "You can't make a traderoute for ports selling the same 
commodities.";
$l_tdr_sportcom 	 = "You can't sell commodities from a planet in a special 
port.";
$l_tdr_editerr  	 = "Edit error : trade route not found in DB";
$l_tdr_maxtdr   	 = "Sorry you have reached the maximum number of trade routes 
allowed.";
$l_tdr_createnew         = "Creating a new";
$l_tdr_editinga 	 = "Editing a";
$l_tdr_traderoute        = "trade route";
$l_tdr_unnamed  	 = "Unnamed";
$l_tdr_cursector         = "You are currently in sector";
$l_tdr_selspoint         = "Please select starting point :";
$l_tdr_port     	 = "Port";
$l_tdr_insector 	 = "in sector";
$l_tdr_selendpoint       = "Please select ending point";
$l_tdr_selmovetype       = "Please select move type";
$l_tdr_realspace         = "Real Space";
$l_tdr_selcircuit        = "Please select circuit";
$l_tdr_oneway   	 = "One way";
$l_tdr_errnotvalidport   = "Error : the source port [tdr_port_id] does not 
seem to be valid.";
$l_tdr_bothways 	 = "Both ways";
$l_tdr_create   	 = "Create";
$l_tdr_modify   	 = "Modify";
$l_tdr_returnmenu        = "Click <a href=traderoute.php>here</a> to return to 
the trade routes menu.";
$l_tdr_errnotvalidport   = "Error : the source port [tdr_port_id] is not a 
valid port.";
$l_tdr_errnoport         = "Error : there is no port at sector [tdr_port_id].";
$l_tdr_errnosrc    	 = "Error : specified source planet doesn't exist.";
$l_tdr_errnotownnotsell  = "Error : you do not own planet [tdr_source_name] 
in sector [tdr_source_sector_id] and planet is not selling.";
$l_tdr_errnotvaliddestport= "Error : the destination port [tdr_port_id] 
is not a valid port.";
$l_tdr_errnoport2        = "Error : there is no port at sector [tdr_port_id].";
$l_tdr_errnodestplanet   = "Error : specified destination planet does not 
exist.";
$l_tdr_errnotownnotsell2 = "Error : you do not own planet [tdr_dest_name] in sector [tdr_dest_sector_id] and planet is not selling.";
$l_tdr_newtdrcreated     = "New trade route created!";
$l_tdr_tdrmodified       = "Trade route modified!";
$l_tdr_doesntexist       = "That trade route doesn't exist!";
$l_tdr_notowntdr         = "You do not own that traderoute!";
$l_tdr_tdrdeleted        = "Trade route deleted.";
$l_tdr_globalset         = "Global trade route settings";
$l_tdr_tdrsportsrc       = "For trade routes having a special port as a 
source, trade";
$l_tdr_tdrescooped       = "For real space trade routes, what to do with the 
energy scooped?";
$l_tdr_trade    	 = "Trade";
$l_tdr_keep    	 	 = "Keep";
$l_tdr_save    	 	 = "Save";
$l_tdr_globalsetsaved    = "Global trade route settings saved.";
$l_tdr_engagenonexist    = "Tried to engage a non-exiDestination sector does 
not seem to be valid!sting trade route!";
$l_tdr_invalidspoint     = "Starting port does not seem to be valid!";
$l_tdr_inittdr  	 = "You are not in sector [tdr_source_id]! You must be in 
starting sector before you initiate a trade route!";
$l_tdr_invalidsrc        = "Source planet doesn't seem to be a valid planet!";
$l_tdr_inittdrsector     = "You are not in sector [tdr_source_sector_id]! You 
must be in starting sector before you initiate a trade route!";
$l_tdr_notyourplanet     = "You do not own planet [tdr_source_name] in sector 
[tdr_source_sector_id]!";
$l_tdr_invalidssector    = "Starting sector does not seem to be valid!";
$l_tdr_invaliddport      = "Destination port does not seem to be valid!";
$l_tdr_invaliddplanet    = "Destination planet doesn't seem to be a valid 
planet!";
$l_tdr_invaliddsector    = "Destination sector does not seem to be valid!";
$l_tdr_moreturnsneeded   = "This trade route requires [tdr_dist_triptime] 
turns to complete. You only have [tdr_playerinfo_turns] left.";
$l_tdr_tdrhostdef        = "You can not use trade routes between sectors with 
hostile defences. You must defeat the defences first.";
$l_tdr_globalsetbuynothing= "Your global settings are set to buy 
nothing! You would only waste turns doing this route!";
$l_tdr_nosrcporttrade    = "Trading from source port is not allowed.";
$l_tdr_tradesrcportoutsider= "Trading at source port is not allowed for 
outsiders";
$l_tdr_nodestporttrade   = "Trading from destination port is not allowed.";
$l_tdr_tradedestportoutsider= "Trading at destination port is not allowed 
for outsiders";
$l_tdr_notyourplanet     = "You do not own planet [tdr_source_name] in sector 
[tdr_source_sector_id]!";
$l_tdr_invalidssector    = "Starting sector does not seem to be valid!";
$l_tdr_invaliddport      = "Destination port does not seem to be valid!";
$l_tdr_invaliddplanet    = "Destination planet doesn't seem to be a valid 
planet!";
$l_tdr_invaliddsector    = "Destination sector does not seem to be valid!";
$l_tdr_moreturnsneeded   = "This trade route requires [tdr_dist_triptime] 
turns to complete. You only have [tdr_playerinfo_turns] left.";
$l_tdr_tdrhostdef        = "You can not use trade routes between sectors with 
hostile defences. You must defeat the defences first.";
$l_tdr_globalsetbuynothing= "Your global settings are set to buy 
nothing! You would only waste turns doing this route!";
$l_tdr_nosrcporttrade    = "Trading from source port is not allowed.";
$l_tdr_tradesrcportoutsider= "Trading at source port is not allowed for 
outsiders";
$l_tdr_nodestporttrade   = "Trading from destination port is not allowed.";
$l_tdr_tradedestportoutsider= "Trading at destination port is not allowed 
for outsiders";
$l_tdr_tdrres  		 = "Trade Route Results";
$l_tdr_bought  		 = "Bought";
$l_tdr_nothingtotrade    = "Nothing to trade";
$l_tdr_sold   	  	 = "Sold";
$l_tdr_ore    		 = "Ore";
$l_tdr_portisfull        = "Port is full";
$l_tdr_goods    	 = "goods";
$l_tdr_organics 	 = "organics";
$l_tdr_energy   	 = "energy";
$l_tdr_portisempty       = "Port is empty";
$l_tdr_loaded   	 = "Loaded";
$l_tdr_nothingtoload     = "Nothing to load";
$l_tdr_scooped  	 = "Scooped";
$l_tdr_dumped   	 = "Dumped";
$l_tdr_planetisovercrowded= "Planet is overcrowded";
$l_tdr_nothingtodump     = "Nothing to dump";
$l_tdr_onlyonewaytdr     = "Did nothing, traderoute was one way only";
$l_tdr_profit 		 = "Profit";
$l_tdr_cost   		 = "Cost";
$l_tdr_totalprofit       = "Total profit";
$l_tdr_totalcost         = "Total cost";
$l_tdr_credits  	 = "Credits";
$l_tdr_turnsused         = "Turns used";
$l_tdr_turnsleft         = "Turns left";
$l_tdr_engageagain       = "Click <A 
HREF=\"traderoute.php?engage=[tdr_engage]\">here</A> to do this trade route 
again.";

// IGB.php

$l_igb_title    = "The Intergalactic Bank";
$l_igb_malfunction      = "This IGB terminal is malfunctionning. The Intergalatic Bank wishes to apologize for any inconvenience.";
$l_igb_quit     = "Quit";
$l_igb_login    = "Login";
$l_igb_welcometoigb     = "Welcome to this Intergalactic Banking Terminal";
$l_igb_accountholder    = "Account Holder";
$l_igb_shipaccount      = "Ship Account";
$l_igb_igbaccount       = "IGB Account";
$l_igb_operations       = "Operations";
$l_igb_withdraw = "Withdraw";
$l_igb_deposit  = "Deposit";
$l_igb_transfer = "Transfer";
$l_igb_back     = "Back";
$l_igb_logout   = "Logout";
$l_igb_withdrawfunds    = "Withdraw Funds";
$l_igb_fundsavailable   = "Funds available";
$l_igb_selwithdrawamount        = "Please select amount to withdraw";
$l_igb_depositfunds     = "Deposit Funds";
$l_igb_seldepositamount = "Please select amount to deposit";
$l_igb_transfertype     = "Transfer Type";
$l_igb_toanothership    = "To another ship";
$l_igb_shiptransfer     = "Ship Transfer";
$l_igb_fromplanet       = "From a planet to another";
$l_igb_unnamed  = "Unnamed";
$l_igb_in       = "in";
$l_igb_none     = "None";
$l_igb_destination      = "Destination";
$l_igb_planettransfer   = "Planet Transfer";
$l_igb_sendyourself     = "You can't send money to yourself!";
$l_igb_unknowntargetship        = "Unknown target ship!";
$l_igb_min_turns        = "Player [igb_target_char_name] must have played at least [igb_min_turns] turns before he can receive money.";
$l_igb_min_turns2       = "You must have played at least [igb_min_turns] turns before you can send money.";
$l_igb_mustwait = "You have already made a transfer to [igb_target_char_name] in the last [igb_trate] minutes. You must wait [igb_difftime] minutes before you can transfer credits to that player again.";
$l_igb_maxtransfer      = "Maximum transfer allowed";
$l_igb_unlimited        = "Unlimited";
$l_igb_maxtransferpercent       = "Maximum transfer allowed ([igb_percent]% of net worth)";
$l_igb_recipient        = "Recipient";
$l_igb_seltransferamount        = "Please select amount to transfer";
$l_igb_transferrate     = "Current rate for transfers is [igb_num_percent]% of total amount. It will automatically be deduced from the amount you transfer.";
$l_igb_errplanetsrcanddest      = "The same planet can't be both source and destination.";
$l_igb_errunknownplanet = "DB Error! Unknown Planet!";
$l_igb_errnotyourplanet = "You can't transfer money from/to a planet you do not own.";
$l_igb_srcplanet        = "Src -> Planet";
$l_igb_destplanet       = "Dst -> Planet";
$l_igb_transferrate2     = "Current rate for transfers is [igb_num_percent]% of total amount. It will automatically be deduced from the amount you transfer.";
$l_igb_errsendyourself  = "You can't send money to yourself!";
$l_igb_min_turns3        = "Player [igb_target_char_name] must have played at least [igb_min_turns] turns before he can receive money.";
$l_igb_min_turns4       = "You must have played at least [igb_min_turns] turns before you can send money.";
$l_igb_mustwait2 = "You have already made a transfer to [igb_target_char_name] in the last [igb_trate] minutes. You must wait [igb_difftime] minutes before you can transfer credits to that player again.";
$l_igb_invalidtransferinput     = "Invalid input for transfer.";
$l_igb_nozeroamount     = "Amount to transfer must not be zero.";
$l_igb_notenoughcredits = "You do not have enough credits to perform this operation.";
$l_igb_amounttoogreat   = "The amount you entered was greater than your maximum transfer allowed.";
$l_igb_transfersuccessful       = "Transfer Successful";
$l_igb_creditsto        = "credits have been transferred to";
$l_igb_transferamount   = "Transfer Amount";
$l_igb_transferfee      = "Transfer Fee";
$l_igb_amounttransferred        = "Amount Transferred";
$l_igb_notenoughcredits2        = "There are not enough credits on source planet to complete that transaction.";
$l_igb_to       = "to";
$l_igb_ctransferredfrom = "credits have been transferred from";
$l_igb_invaliddepositinput      = "Invalid input for deposit.";
$l_igb_nozeroamount2    = "Amount to deposit must not be zero.";
$l_igb_operationsuccessful      = "Operation successful";
$l_igb_creditstoyou     = "Credits have been transfered to your IGB account.";
$l_igb_accounts = "Accounts";
$l_igb_invalidwithdrawinput     = "Invalid input for withdraw.";
$l_igb_nozeroamount3    = "Amount to withdraw must not be zero.";
$l_igb_creditstoyourship        = "Credits have been transfered to your ship account.";
$l_igb_igberrreport     = "IGB Error Report";
$l_igb_source   = "Source";

// combat.php3

$l_cmb_atleastoneturn   = "You need at least one turn to attack a planet.";
$l_cmb_shipenergybb     = "Ship energy before beams";
$l_cmb_shipenergyab     = "Ship energy after beams";
$l_cmb_shipenergyas     = "Ship energy after shields";
$l_cmb_shiptorpsbtl     = "Ship torpedos before torp launch";
$l_cmb_shiptorpsatl     = "Ship torpedos after torp launch";
$l_cmb_planettorpdamage = "Planet torp damage";
$l_cmb_attackertorpdamage       = "Attacker torp damage";
$l_cmb_beams    = "Beams";
$l_cmb_fighters = "Fighters";
$l_cmb_shields  = "Shields";
$l_cmb_torps    = "Torps";
$l_cmb_torpdamage       = "Torp Damage";
$l_cmb_armor    = "Armor";
$l_cmb_you      = "You";
$l_cmb_planet   = "Planet";
$l_cmb_combatflow       = "Combat Flow";
$l_cmb_defender = "Defender";
$l_cmb_attackingplanet  = "Attacking planet in sector";
$l_cmb_youfireyourbeams = "You fire your beams";
$l_cmb_defenselost      = "Planetary defense lost [cmb_planetfighters] fighters to your beams";
$l_cmb_defenselost2     = "Planetary Defense lost [cmb_attackerbeams] fighters, but there are more coming!";
$l_cmb_planetarybeams   = "Planetary beams destroy [cmb_temp] of your fighters";
$l_cmb_planetarybeams   = "Planetary beams destroy [cmb_planetbeams] of your fighters";
$l_cmb_youdestroyedplanetshields        = "Your beams have destroyed the planetary shields";
$l_cmb_beamsexhausted   = "You destroy [cmb_attackerbeams] planetary shields before your beams are exhausted";
$l_cmb_breachedyourshields      = "Planetary beams have breached your shields";
$l_cmb_destroyedyourshields     = "Planetary beams have destroyed [cmb_planetbeams] of your shields";
$l_cmb_breachedyourarmor        = "Planetary beams have breached your armor";
$l_cmb_destroyedyourarmor       = "Planetary beams have destroyed [cmb_planetbeams] points of armor";
$l_cmb_torpedoexchangephase     = "Torpedo Exchange Phase";
$l_cmb_nofightersleft   = "Your torpedos destroy [cmb_planetfighters] planetary fighters, no fighters are left";
$l_cmb_youdestroyfighters       = "Your torpedos destroy [cmb_attackertorpdamage] planetary fighters";
$l_cmb_planettorpsdestroy       = "Planetary torpedos destroy [cmb_temp] of your fighters";
$l_cmb_planettorpsdestroy2      = "Planetary torpedos destroy [cmb_planettorpdamage] of your fighters";
$l_cmb_torpsbreachedyourarmor   = "Planetary torpedos have breached your armor";
$l_cmb_planettorpsdestroy3      = "Planetary torpedos have destroyed [cmb_planettorpdamage] points of armor";
$l_cmb_youdestroyedallfighters  = "Your torpedos have destroyed all the planetary fighters";
$l_cmb_youdestroyplanetfighters = "Your torpedos destroy [cmb_attackertorpdamage] planetary fighters";
$l_cmb_fightercombatphase       = "Fighter Combat Phase";
$l_cmb_youdestroyedallfighters2  = "Your fighters have destroyed all the planetary fighters.";
$l_cmb_youdestroyplanetfighters2        = "Your fighters have destroyed [cmb_attackerfighters] planetary fighters";
$l_cmb_allyourfightersdestroyed = "All your fighters were destroyed";
$l_cmb_fightertofighterlost     = "You lost [cmb_planetfighters] fighters in fighter to fighter combat";
$l_cmb_youbreachedplanetshields = "Your fighters have breached the planetary shields";
$l_cmb_shieldsremainup  = "Your fighters destroyed [cmb_attackerfighters] planetary shields, but they remain up";
$l_cmb_fighterswarm     = "Planetary fighters swarm your ship, your armor has been breached";
$l_cmb_swarmandrepel    = "Planetary fighters swarm your ship, but your armor repels them";
$l_cmb_engshiptoshipcombat      = "Engaging in Ship to Ship combat.";
$l_cmb_shipdock = "There are [cmb_shipsonplanet] ships docked at Spacedock!";
$l_cmb_approachattackvector     = "is approaching on an attack vector";
$l_cmb_noshipsdocked    = "There are NO ships docked at Spacedock!";
$l_cmb_yourshipdestroyed        = "Your ship has been destroyed!";
$l_cmb_escapepod        = "Luckily you have an escape pod!";
$l_cmb_finalcombatstats = "Final Combat Stats";
$l_cmb_youlostfighters  = "You lost [cmb_fighters_lost] out of [cmb_playerinfo_ship_fighters] total fighters.";
$l_cmb_youlostarmorpoints       = "You lost [cmb_armor_lost] out of [cmb_playerinfo_armour_pts] total armor points, you have [cmb_attackerarmor] points remaining.";
$l_cmb_energyused       = "You used [cmb_energy] energy, from a total of [cmb_playerinfo_ship_energy] energy.";
$l_cmb_planetdefeated   = "Planet defeated";
$l_cmb_citizenswanttodie        = "The citizens of this planet have decided they'd rather die than serve a pathetic ruler like you. They use a laser drill to dig a hole to the planet's core. You barely have time to escape into orbit before the whole planet is reduced to a ball of molten lava.";
$l_cmb_youmaycapture    = "You may <a href=planet.php3?planet_id=[cmb_planetinfo_planet_id]&command=capture>capture</a> the planet or just leave it undefended.";
$l_cmb_youmaycapture2   = "You may <a href=planet.php3?planet_id=[cmb_planetinfo_planet_id]&command=capture>capture</a> the planet or just leave it undefended.";
$l_cmb_planetnotdefeated        = "Planet not defeated";
$l_cmb_planetstatistics = "Planet statistics";
$l_cmb_fighterloststat  = "Fighters lost: [cmb_fighters_lost] out of [cmb_planetinfo_fighters] ([cmb_planetfighters] alive)";
$l_cmb_energyleft       = "Energy left";
$l_cmb_startingstats    = "Starting stats";
$l_cmb_statattackerbeams        = "Attackerbeams";
$l_cmb_statattackerfighters     = "Attackerfighters";
$l_cmb_statattackershields      = "Attackershields";
$l_cmb_statattackertorps        = "Attackertorps";
$l_cmb_statattackerarmor        = "Attackerarmor";
$l_cmb_statattackertorpdamage   = "Attackertorpdamage";
$l_cmb_isattackingyou   = "is attacking you";
$l_cmb_beamexchange     = "Beam exchange";
$l_cmb_beamsdestroy     = "Your beams destroy [cmb_lost] fighters";
$l_cmb_beamsdestroy2    = "Your beams destroy [cmb_attackerbeams] fighters, but there are more coming";
$l_cmb_nobeamsareleft   = "You have no beams left to destroy the incoming fighters!";
$l_cmb_beamshavenotarget        = "Your beams have no fighter targets to destroy";
$l_cmb_fighterdestroyedbybeams  = "[cmb_targetinfo_ship_name] destroyed [cmb_lost] of your fighters with beams<BR>";
$l_cmb_beamsdestroystillhave    = "[cmb_targetinfo_ship_name] destroyed [cmb_targetbeams] of your fighters with beams, but you still have [cmb_attackerfighters] left";
$l_cmb_fighterunhindered        = "Your fighters attack unhindered, the enemy has no beams left.";
$l_cmb_youhavenofightersleft    = "You have no fighters left to attack with";
$l_cmb_breachedsomeshields      = "You have breached [cmb_targetinfo_ship_name]'s shields with your beams";
$l_cmb_shieldsarehitbybeams     = "[cmb_targetinfo_ship_name]'s shields are hit for [cmb_attackerbeams] damage by your beams";
$l_cmb_nobeamslefttoattack      = "You have no beams left to attack [cmb_targetinfo_ship_name]'s shields";
$l_cmb_yourshieldsbreachedby    = "[cmb_targetinfo_ship_name]'s beams have breached your shields";
$l_cmb_yourshieldsarehit        = "[cmb_targetinfo_ship_name]'s beams have hit your shields for [cmb_targetbeams] damage.";
$l_cmb_hehasnobeamslefttoattack = "[cmb_targetinfo_ship_name] has no beams left to attack your shields";
$l_cmb_yourbeamsbreachedhim     = "Your beams have breached [cmb_targetinfo_ship_name]'s armor";
$l_cmb_yourbeamshavedonedamage  = "Your beams have done [cmb_attackerbeams] damage to [cmb_targetinfo_ship_name]'s armor";
$l_cmb_nobeamstoattackarmor     = "You have no beams left to attack [cmb_targetinfo_ship_name]'s armor";
$l_cmb_yourarmorbreachedbybeams = "Your armor has been breached by [cmb_targetinfo_ship_name]'s beams";
$l_cmb_yourarmorhitdamaged      = "Your armor is hit for [cmb_targetbeams] damage by [cmb_targetinfo_ship_name]'s beams";
$l_cmb_torpedoexchange  = "Torpedo exchange";
$l_cmb_hehasnobeamslefttoattackyou      = "[cmb_targetinfo_ship_name] has no beams left to attack your armor";
$l_cmb_yourtorpsdestroy = "Your torpedos destroy [cmb_lost] of [cmb_targetinfo_ship_name]'s fighters";
$l_cmb_yourtorpsdestroy2        = "Your torpedos destroy [cmb_attackertorpdamage] of [cmb_targetinfo_ship_name]'s fighters";
$l_cmb_youhavenotorpsleft       = "You have no torpedo's left to attack [cmb_targetinfo_ship_name]'s fighters.";
$l_cmb_hehasnofighterleft       = "[cmb_targetinfo_ship_name] has no fighters left for you to destroy with torpedos";
$l_cmb_torpsdestroyyou  = "[cmb_targetinfo_ship_name]'s torpedo's destroy [cmb_lost] of your fighters";
$l_cmb_someonedestroyedfighters = "[cmb_targetinfo_ship_name] destroyed [cmb_targettorpdmg] of your fighters with torpedos";
$l_cmb_hehasnotorpsleftforyou   = "[cmb_targetinfo_ship_name] has no torpedo's left to attack your fighters";
$l_cmb_youhavenofightersanymore = "You have no fighters left to be destroyed by [cmb_targetinfo_ship_name]'s torpedo's";
$l_cmb_youbreachedwithtorps     = "You have breached [cmb_targetinfo_ship_name]'s armor with your torpedos";
$l_cmb_hisarmorishitbytorps     = "[cmb_targetinfo_ship_name]'s armor is hit for [cmb_attackertorpdamage] damage by your torpedos";
$l_cmb_notorpslefttoattackarmor = "You have no torpedo's left to attack [cmb_targetinfo_ship_name]'s armor";
$l_cmb_yourarmorbreachedbytorps = "Your armor has been breached by [cmb_targetinfo_ship_name]'s torpedos";
$l_cmb_yourarmorhitdmgtorps     = "Your armor is hit for [cmb_targettorpdmg] damage by [cmb_targetinfo_ship_name]'s torpedos";
$l_cmb_hehasnotorpsforyourarmor = "[cmb_targetinfo_ship_name] has no torpedo's left to attack your armor";
$l_cmb_fightersattackexchange   = "Fighters Attack exchange";
$l_cmb_enemylostallfighters     = "[cmb_targetinfo_ship_name] lost all fighters.";
$l_cmb_helostsomefighters       = "[cmb_targetinfo_ship_name] lost [cmb_attackerfighters] fighters.";
$l_cmb_youlostallfighters       = "You lost all fighters.";
$l_cmb_youalsolostsomefighters  = "You lost [cmb_targetfighters] fighters.";
$l_cmb_hehasnofightersleftattack        = "[cmb_targetinfo_ship_name] has no fighters left for your fighters to attack";
$l_cmb_younofightersattackleft  = "You have no fighters left to attack [cmb_targetinfo_ship_name]'s fighters";
$l_cmb_youbreachedarmorwithfighters     = "You have breached [cmb_targetinfo_ship_name]'s armor with your fighters";
$l_cmb_youhitarmordmgfighters   = "You hit [cmb_targetinfo_ship_name]'s armor for [cmb_attackerfighters] damage with your fighters";
$l_cmb_youhavenofighterstoarmor = "You have no fighters left to attack [cmb_targetinfo_ship_name]'s armor";
$l_cmb_hasbreachedarmorfighters = "[cmb_targetinfo_ship_name] has breached your armor with fighters";
$l_cmb_yourarmorishitfordmgby   = "Your armor is hit for [cmb_targetfighters] damage by [cmb_targetinfo_ship_name]'s fighters";
$l_cmb_nofightersleftheforyourarmor     = "[cmb_targetinfo_ship_name] has no fighters left to attack your armor";
$l_cmb_hehasbeendestroyed       = "[cmb_targetinfo_ship_name] has been destroyed";
$l_cmb_escapepodlaunched        = "An escape pod was launched!";
$l_cmb_yousalvaged      = "You salvaged [cmb_salv_ore] units of ore, [cmb_salv_organics] units of organics, [cmb_salv_goods] units of goods, and salvaged [cmb_salvage_rate]% of the ship for [cmb_salvage] credits.<BR>Your rating changed by [cmb_number_rating_change] points.";
$l_cmb_youdidntdestroyhim       = "You did not destory [cmb_targetinfo_ship_name]";
$l_cmb_shiptoshipcombatstats    = "Ship to Ship combat stats";

// check_mines.php3

$l_chm_youhitsomemines  = "You hit [chm_roll] mines!";
$l_chm_hehitminesinsector       = "[chm_playerinfo_character_name] hit [chm_roll] mines in sector [chm_sector].";
$l_chm_youlostminedeflectors    = "You lost [chm_roll] mine deflectors.";
$l_chm_youlostallminedeflectors = "You lost all your mine deflectors.";
$l_chm_youhadnominedeflectors  = "You had no mine deflectors.";
$l_chm_yourshieldshitforminesdmg        = "Your shields are hit for [chm_mines_left] damage.";
$l_chm_yourshieldsaredown       = "Your shields are down!";
$l_chm_youlostallyourshields    = "You lost all your shields!";
$l_chm_yourarmorhitforminesdmg  = "Your armour is hit for [chm_mines_left] damage.";
$l_chm_yourhullisbreached       = "Your hull is breached!";
$l_chm_hewasdestroyedbyyourmines        = "[chm_playerinfo_character_name] was destroyed by your mines in sector [chm_sector].";
$l_chm_yourshiphasbeendestroyed = "Your ship has been destroyed!";
$l_chm_luckescapepod    = "Luckily you have an escape pod!";

// check_fighters.php3

$l_chf_youretreatback   = "You retreat back to your previous location";
$l_chf_notenoughcreditstoll     = "You do not have enough credits to pay the toll.";
$l_chf_movefailed       = "Move failed.";
$l_chf_youpaidsometoll  = "You paid [chf_tollstring] credits for the toll.";
$l_chf_thefightersdetectyou     = "The fighters detect you!";
$l_chf_therearetotalfightersindest      = "There are [chf_total_sector_fighters] fighters in your destination sector.";
$l_chf_creditsdemanded  = "They demand [chf_number_fighterstoll] credits to enter this sector.";
$l_chf_youcanretreat    = "You can <BR><INPUT TYPE=RADIO NAME=response VALUE=retreat><B>Retreat</B> - Will cost an extra turn.<BR></INPUT>";
$l_chf_inputpay = "<INPUT TYPE=RADIO NAME=response CHECKED VALUE=pay><B>Pay</B> the toll and enter without harm from the fighters.<BR></INPUT>";
$l_chf_inputfight       = "<INPUT TYPE=RADIO NAME=response CHECKED VALUE=fight><B>Fight</B> - you must defeat all the fighters to enter the sector.<BR></INPUT>";
$l_chf_inputcloak       = "<INPUT TYPE=RADIO NAME=response CHECKED VALUE=sneak><B>Cloak</B> - Use your cloaking device and try to avoid the fighters.<BR></INPUT>";
$l_chf_go       = "Go";

// mines.php

$l_mines_title			="Deploy Sector Mines & Fighters";
$l_mines_noturn		 	="You need at least one turn to deploy sector defences.";
$l_mines_nopermit		="Deploying Mines and Fighters in this sector is not permitted.";
$l_mines_nodeploy		="Can not deploy here. Another Ship or Alliance has mines or fighters in this sector.";
$l_mines_info1			="You are presently in sector [sector]. There are [mines] mines and [fighters] fighters here.";
$l_mines_info2			="You have [mines] mines and [fighters] fighters available to deploy";
$l_mines_deploy			="Deploy";
$l_mines_deployed		="Deployed";
$l_mines_att			="Attack";
$l_mines_toll			="Toll";
$l_mines_notorps		="You do not have enough torpedos.";
$l_mines_nofighters		="You do not have enough fighters";
$l_mines_dmines			="Deployed [mines] mines.";
$l_mines_dfighter		="Deployed [fighters] fighters in [mode] mode.";

//alliance-planets.php

$l_teamplanet_title		="Alliance Planet Report";
$l_teamplanet_notally		="You aren't in an alliance.";
$l_teamplanet_personal		="Show personal planets";
$l_teamplanet_noplanet		="Your alliance has no planets";

$l_feedback_title		="Send Feedback";
$l_feedback_to			="TO:";
$l_feedback_from		="FROM:";
$l_feedback_topi		="SUBJECT:";
$l_feedback_feedback		="Feedback";
$l_feedback_message		="MESSAGE:";
$l_feedback_messent		="Message Sent";
$l_feedback_subj		="WTW Feedback";
$l_feedback_info		="Please send feedback in english only"; // gameadmins put all your languages here

// corp.php
$l_corpm_title			="Corporation Menu";
$l_corpm_tocorp			="Planet is now a Corporate Planet!";
$l_corpm_topersonal		="Planet is now a Personal Planet!";
$l_corpm_exploit		="You intercept a garbled borg message on your scanner... you should probably start worrying...";

// login.php login2.php
$l_login_title			="Login"; 
$l_login_email			="E-mail Address:";
$l_login_pw			="Password:";
$l_login_chooseres		="Unable to determine your screen resolution. Please choose the best fit:";
$l_login_newp			= "If you are a new player, click <A HREF=\"new.php3\">here</A>.";
$l_login_prbs			= "Problems?";
$l_login_emailus		= "E-mail us";
$l_login_sclosed		= "Server Closed";
$l_login_closed_message		="Server closed until further notice.";
$l_login_title2			="Login Phase Two"; 
$l_login_banned			="<b>You have been banned from this game by the administrator. You are no longer welcome to play on this server. Next time, behave.</b>";
$l_login_died			="Your ship was destroyed, but your escape pod saved you and your crew.  Click <A HREF=main.php3>here</A> to continue with a new ship.";
$l_login_newbie			="Due to the seriousness of this crime and the vicious attack against you, the Federation has graciously decided to provide a free of charge cloning from your remains.  Sadly, even in this day and age, new clones can not own property, aside from the basics to make a living.  You will be provided with a basic ship and a few credits to get you started.  Hopefully your next life will be better.";
$l_login_newlife		="Click <A HREF=main.php3>here</A> to continue in a new life.";
$l_login_looser			="You had no escape pod, and due to your modest success in this life, the Federation declines to clone you.  Your remains should eventually fall into a gravity well, hopefully to be used to create life elsewhere... several billion years from now.<BR><BR> Better luck next game...";
$l_login_4gotpw1		= "The password you entered is incorrect.<BR><BR>  If you have forgotten your password, ";
$l_login_4gotpw2		= "to have it e-mailed to you.<BR><BR>  Otherwise,";
$l_login_4gotpw3		= "to try again.  Attempt logged with IP address of";
$l_login_noone			= "No Such Player! - Create a new player <A HREF=new.php3>here</A>.";

// new.php new2.php
$l_new_title			= "Create New Player"; 
$l_new_title2			= "Create New Player Phase Two"; 
$l_new_shipname			= "Ship Name";
$l_new_pname			= "Player Character Name";
$l_new_info			= "We promise not to give out (or sell) your e-mail address to anyone.  It is required though, to send you your server generated password..";
$l_new_closed_message		="Game closed for tournament play";
$l_new_blank			="E-mail, ship name, and character name may not be blank.";
$l_new_inuse			="E-mail address is already in use.";
$l_new_4gotpw1			="If you have forgotten your password,";
$l_new_4gotpw2			="to have it e-mailed to you.";
$l_new_inusechar		="Character name $character, is already in use.";
$l_new_inuseship		="Ship name $shipname, is already in use.";
$l_new_pwsent			="Password has been sent to $username.";
$l_new_login			="to go to the login screen.";
$l_new_err			="Please go back or <a href=new.php3>click here</a> and try again.";
$l_new_topic			="Traders Password";
$l_new_message			="Greetings,\n\nSomeone from the IP address $ip requested that your password for Traders be sent to you.\n\nYour password is: [pass]\n\nThank you\n\nThe Traders web team.";

// logout.php

$l_logout_score			="You current score is";
$l_logout_text			="[name] is now logged out.  Click <A HREF=index.php3>here</A> to return to game.";

// mail.php

$l_mail_title			="Mail Password"; 
$l_mail_noplayer		="No Such Player! - Create a new player <a href=new.php3>here</a>.";
$l_mail_sent			="Password has been sent to";
$l_mail_topic			="$game_name Password";
$l_mail_message			="Greetings,\n\nSomeone from the IP address $ip requested that your password for $game_name be sent to you.\n\nYour password is: [pass]\n\nThank you\n\nThe $game_name web team.";


?>
