<?php

//general

$l_yes 			 = "Ja";
$l_no			 = "Nein";
$l_here			 = "hier";
$l_submit		 = "Best&auml;tigen";
$l_reset		 = "L&ouml;schen";
$l_all			 = "alle";

$l_ore			 = "Erz";
$l_organics		 = "Lebensmittel";
$l_goods		 = "G&uuml;ter";
$l_energy		 = "Energie";
$l_colonists		 = "Kolonisten";
$l_credits 		 = "Credits";
$l_units		 = "Einheiten ";

$l_cargo		 = "Fracht";
$l_fighters		 = "Fighter ";
$l_mines		 = "Minen ";
$l_torps		 = "Torpedos";

$l_none			 = "Keine";
$l_unnamed		 = "Unbenannt";
$l_name			 = "Name";
$l_unowned		 = "Unbesetzt";
$l_unknown		 = "Unbekannt";
$l_clickme 		 = "klicke hier";
$l_player  		 = "Spieler";
$l_ship			 = "Schiff";
$l_set			 = "setze";
$l_realspace		 = "Raumflug";
$l_armourpts		 = "Panzerungs Punkte";


// main.php

$l_main_title 		 = "Haupt Men&uuml;";

$l_traderoutes		 = "Handelsroute";
$l_trade_control	 = "Handelseinstellungen";

$l_youhave 		 = "Du hast ";
$l_turns_used		 = "Züge benutzt: ";
$l_turns_have		 = "Züge verfügbar: ";
$l_score		 = "Punkte: ";
$l_sector		 = "Sektor";
$l_help			 = "Hilfe";
$l_faq		         = "FAQ";
$l_feedback		 = "Feedback";
$l_forums		 = "Forum";
$l_logout		 = "Abmelden";

$l_commands		 = "Befehle";
$l_command_no		 = "Befehl nicht verfügbar.";
$l_devices		 = "Schiff";
$l_planets		 = "Planeten";
$l_log			 = "Logbuch";
$l_sector_def		 = "Sektor Verteidigung";
$l_defense		 = "Verteidigung";
$l_read_msg		 = "Lese Messis";
$l_send_msg		 = "Sende Messis";
$l_rankings		 = "R&auml;nge";
$l_teams		 = "Allianzen";
$l_ohno			 = "Selbstzerstörung";
$l_options		 = "Optionen";
$l_navcomp		 = "Navigation";

$l_incompletemove 	 = "Du hast Deinen vorherigen Zug nicht vollendet.";
$l_clicktocontinue	 = "Klicke hier um fortzufahren";
$l_toplanetmenu   	 = "um zum Planeten Men&uuml; zu gehen.";
$l_nonexistant_pl	 = "Auf einen nicht vorhandenen Planeten???";
$l_abord		 = ", an Bord der ";
$l_messages_wait	 = " Nachrichten warten auf Dich.";

$l_no_warplink		 = "Keine Warptore";
$l_scan			 = "scanne";
$l_fullscan		 = "voller Scan";

$l_port			 = "Hafen";
$l_tradingport		 = "Handelshafen";
$l_planet_in_sec	 = "Planeten in Sektor ";
$l_ships_in_sec		 = "Schiffe im Sektor ";
$l_sector_0		 = "Es gibt soviele Schiffe in Sol (Sektor 0), daß Deine Scanner keine Schiffe isolieren können!";

// report.php

$l_report_title		 = "Schiffs Report";

$l_level		 = "Level";

$l_ship_levels		 = "Schiff Levels";
$l_hull			 = "H&uuml;lle";
$l_engines		 = "Triebwerke";
$l_power		 = "Aggregate";
$l_computer		 = "Computer";
$l_sensors		 = "Sensoren";
$l_armour		 = "Panzerung";
$l_shields		 = "Schilde";
$l_beams		 = "Laserwaffen";
$l_torp_launch	         = "Torpedo-Phalanxen";
$l_cloak		 = "Tarnung";
$l_holds		 = "Frachtraum";
$l_deflect		 = "Minen Deflektoren";
$l_ewd			 = "Notfall Warp Ger&auml;t";


$l_arm_weap		 = "Panzerung & Waffen";
$l_beacons		 = "Raumsignal";
$l_warpedit		 = "Warptore";
$l_genesis		 = "Genesis Torpedo";
$l_escape_pod		 = "Rettungskapsel";
$l_fuel_scoop		 = "Sonnensegel";

// device.php

$l_device_title		 = "Schiffs Komponenten";

$l_device_expl		 = "Dein Schiff beeinhaltet folgende Komponenten (klicke auf die Komponente, die Du benutzen möchtest):";
$l_device		 = "Komponente";
$l_qty			 = "Menge";
$l_usage		 = "Benutze";
$l_manual		 = "Manuell";	
$l_automatic		 = "Automatisch";

// port.php port2.php

$l_trade		 = "Handel";
$l_title_port		 = "Handel im Raumhafen";
$l_title_trade		 = "Waren Handel";
$l_sector_war		 = "Kriegsembargo";
$l_war_info		 = "In diesem Sektor ist Krieg ausgebrochen. Auf Grund der Feindlichen Einheiten, kannst Du den Hafen nicht ereichen.";
$l_no_trade		 = "Handel verboten";
$l_no_trade_out		 = "Handeln in diesem Sektor ist für Aussenseiter nicht gestattet";
$l_no_trade_info	 = "Handeln in diesem Hafen ist nicht erlaubt";
$l_buying		 = "Ankauf";
$l_selling		 = "Verkauf";
$l_commodity		 = "Ware";
$l_amount		 = "Betrag";
$l_price		 = "Preis";
$l_buy			 = "Kaufen";
$l_sell			 = "Verkaufen";
$l_trade_st_info	 = "Du hast [free_holds] freien Frachtraum, Du hast noch Kapazität für [free_power] Energie Einheiten, und besitzt [credits] Credits.";
$l_special_port		 = "Spezial Hafen";
$l_no_credits		 = "Nicht gen&uuml;gend Credits";
$l_creds_to_spend	 = "Du hast [credits] Credits zum ausgeben.";
$l_cost			 = "Kosten";
$l_avail		 = "Verf&uuml;gbar";
$l_profit		 = "Profit";
$l_current		 = "momentan";
$l_current_qty		 = "derzeitige Menge";
$l_max			 = "Max";
$l_ifyouneedmore	 = "Wenn Du mehr benötigst, kannst Du von hier aus einen Zugang erstellen [igb] ";
$l_ifyouneedplan	 = "Zugang zum Planeten";
$l_igb_term		 = "IG Bank Terminal";
$l_upgrade		 = "Aufwerten?";
$l_unlimited		 = "Unbegrenzt";
$l_full			 = "Voll";
$l_equipped		 = "Eingebaut";
$l_n_a			 = "k/a";
$l_item			 = "Posten";
$l_totalcost		 = "Gesamtkosten";
$l_would_dump	         = "Wenn Du alle Deine Kolonisten abladen willst, klicke ";
$l_noport		 = "Hier ist kein Handelshafen";
$l_trade_turnneed	 = "Um in einem Hafen oder auf einem Planeten handeln zu können, benötigst Du einen Zug.";
$l_returnto_port         = " Klicke <A HREF=port.php3>hier</A> um zum Handels Menue zurückzukommen.";
$l_notenough_cargo	 = "Du hast nicht genügend Platz für die Waren die du kaufen willst.";
$l_notenough_power	 = "Du hast nicht genügend Energie-Kapazität, um den Handel durchzuf&uuml;hren.";
$l_notenough_credits	 = "Du hast nicht genügend Credits um den Transfer abzuschliessen";
$l_notenough_turns	 = "Du hast nicht genügend Z&uuml;ge um den Transfer durchzuf&uuml;hren.";
$l_notenough_ore	 = "Du hast nicht genügend Erz um den Transfer durchzuf&uuml;hren.";
$l_notenough_goods	 = "Du hast nicht genügend G&uuml;ter um den Transfer durchzuf&uuml;hren.";
$l_notenough_energy	 = "Du hast nicht genügend Energie um den Transfer durchzuf&uuml;hren";
$l_notenough_organics	 = "Du hast nicht genügend Lebensmittel um den Transfer durchzuf&uuml;hren";
$l_exceed_organics	 = "Anzahl der Lebensmittel überschreitet Angebot/Nachfrage.  ";
$l_exceed_ore            = "Anzahl an Erz überschreitet Angebot/Nachfrage.  ";
$l_exceed_energy         = "Anzahl an Energy überschreitet Angebot/Nachfrage.  ";
$l_exceed_goods          = "Anzahl der Güter überschreitet Angebot/Nachfrage.  ";
$l_trade_result		 = "Ergebnis dieses Handels";
$l_traded_ore		 = "Gehandeltes Erz";
$l_traded_goods		 = "Gehandelte G&uuml;ter";
$l_traded_organics	 = "Gehandelte Lebensmittel";
$l_traded_energy	 = "Gehandelte Energie";
$l_trade_complete	 = "Handel beendet";
$l_trade_upgraded 	 = "Aufgerüstet";
$l_trade_added 	 	 = "hinzugefügt";
$l_trade_installed 	 = "installiert";


// planet.php planet2.php planet3.php
$l_planet_title		 = "Planeten Men&uuml;";
$l_planet_none		 = "Du bist nicht im selben Sektor wie der Planet, deshalb kannst Du nicht mit ihm interagieren.";
$l_planet_capture1	 = "besetzen"; // thats the link's text
$l_planet_capture2	 = "Du kannst diesen Planeten [capture], oder ihn unbesetzt zurücklassen.";
$l_planet_unowned	 = "Dieser Planet ist unbesetzt";
$l_planet_unnamed        = "Willkommen auf [name]'s namenlosen Planeten.";
$l_planet_named		 = "Willkommen auf dem Planeten [planetname], der von [name] besetzt wurde.";
$l_planet_onsurface	 = "Du befindest Dich nun auf der Oberfl&auml;che des Planeten.";
$l_planet_orbit 	 = "Du befindest Dich nun im Orbit des Planetens.";
$l_planet_leave_link     = "Verlasse";
$l_planet_leave          = "[leave] Planet";
$l_planet_name_link 	 = "Benenne";
$l_planet_name2 	 = "[name] den Planeten";
$l_planet_land_link      = "Lande";
$l_planet_land           = "[land] auf dem Planeten";
$l_planet_logout	 = "Du kannst Dich im Schutze des Planeten <a href=logout.php3>ausloggen</a>.";
$l_planet_selling	 = "Der Planet verkauft nun seine Waren.";
$l_planet_not_selling    = "Der Planet verkauft nun seine Waren nicht mehr.";
$l_planet_transfer_link	 = "Transferiere";
$l_planet_transfer	 = "[transfer] Waren/Ressourcen/Kolonisten zum/vom Planeten";
$l_planet_hasbase	 = "Du hast eine Basis auf dem Planeten";

$l_planet_perc		 = "Produktions Verteilung";
$l_planet_interest	 = "* Die Geld Produktion ist abhängig von der Produktion der anderen Waren. Desto niedriger die Gesamtproduktion aller Waren (prozentual) ist, desto höher ist die Geld-Produktion";
$l_planet_update	 = "Aktualisieren";
$l_planet_tsell_link	 = "Verkaufs";
$l_planet_tsell		 = "&Auml;ndere das Verkaufsverhalten [selling] des Planeten";
$l_planet_bbase_link	 = "eine Basis";
$l_planet_bbase		 = "Mit genügen Waren und Credits, kanst Du [build] bauen als Planetenverteidung aufbauen.";
$l_planet_bbuild	 = "Basis gebaut";
$l_planet_mcorp_linkC	 = "verbündetem Planeten";
$l_planet_mcorp_linkP	 = "persönlichem Planeten";
$l_planet_mcorp		 = "Du kannst diesen Planeten zu einem [planet] machen.";
$l_planet_buy_link	 = "Kaufe";
$l_planet_buy		 = "[buy] Waren von dem Planeten";
$l_planet_att_link	 = "Attackiere";
$l_planet_att		 = "[attack] den Planeten";
$l_planet_att_sure	 = "Bist Du SICHER...";
$l_planet_scn_link	 = "Scanne";
$l_planet_scn		 = "[scan] den Planet";
$l_planet_nowsell        = "Der Planet verkauft nun seine Waren.";
$l_planet_nownosell      = "Der Planet verkauft seine Waren nun nicht mehr.";
$l_planet_iname		 = "Gib einen Namen für den Planeten ein";
$l_planet_cname		 = "Der Planet heisst nun ";
$l_planet_landed	 = "Du bist auf der Planetenoberfl&auml;che gelandet.";
$l_planet_left		 = "Du bist nicht länger auf der Planetenoberfl&auml;che.";
$l_planet_cinfo		 = "Du hast Raum für [cargo] zus&auml;tzliche Fracht.  Du hast Kapazit&auml;t für [energy] Einheiten zusätzlicher Energie.";
$l_planet_toplanet	 = "Zum Planeten?";
$l_planet_baseinfo	 = "Um eine Basis auf den Planeten bauen zu können, brauchst Du $base_credits Credits, $base_ore Erz, $base_organics Lebensmittel, und $base_goods Güter auf dem Planeten .";
$l_planet_p_under        = "Du kannst das Produktionslevel nicht unter Null setzen.";
$l_planet_p_over	 = "Du kannst nicht mehr als insgesamt 100% produzieren.";
$l_planet_p_changed	 = "Produktionsverteilung ge&auml;ndert.";
$l_plant_scn_turn	 = "Du benötigst einen Zug, um den Planeten zu scannen.";
$l_planet_noscan	 = "Die Sensoren konnten den Planeten nicht Scannen, sie wurden gest&ouml;rt.";
$l_planet_logscanA	 = "[name] hat vergebens versucht, einen Deiner Planeten im Sektor [sector] zu scannen.";
$l_planet_logscanB	 = "Einer von deinem Planten in Sektor [sector] wurde von [name] gescannt.";
$l_planet_scn_report	 = "Scan Resultate von [name], besetzt von:  [owner]";
$l_base	  		 = "Basis";
$l_planet_ison		 = "ist auf diesem Planeten.";
$l_planet_captured	 = "Planet erobert";
$l_planet_notdef	 = "Planet nicht besiegt";
$l_planet_caplog	 = "Dein Planet '[planetname]' in Sektor [sector] wurde von [name] erobert.";

$l_planet2_title	 = "Planetarer Transfer";
$l_planet2_noturn	 = "Du benötigst einen Zug um den planetaren Transfer durchzufüren.";
$l_planet2_noten 	 = "Du hast nicht genug ";
$l_planet2_fortr	 = "um den Transfer durchzufüren.";
$l_planet2_settr	 = "Setze die Transfer-Menge auf ";
$l_planet2_losup	 = "Der Planet konnte insgesammt nur soviel liefern: ";
$l_planet2_notowner	 = "Du besitzt diesen Planeten nicht.";
$l_planet2_compl	 = "Transfer komplett.";
$l_planet2_power	 = "Energie Kapazität";
$l_planet2_comp 	 = "Computer Kapazizät";
$l_planet2_laun 	 = "Torpedo-Phalanx Kapazizät";
$l_planet2_nocorptransfer = "Du kannst keine Credits zu oder von einem verbündeten Planeten transferieren.";

$l_planet3_title	 = "Handel mit Planet";

// planet-report.php

$l_pr_title		 = "Planet Report";
$l_pr_teamlink		 = "Zeige allierte Planeten";
$l_pr_noplanet		 = "Du hast noch keinen Planeten besetzt.";
$l_pr_clicktosort	 = "Klicke auf die Tabellenköpfe um zu sortieren.";
$l_pr_totals		 = "Insgesamt";

// rsmove.php
$l_rs_title 		= "Raumflug";
$l_rs_whichsector       = "Welchen Sektor möchtest Du per Raumflug ereichen?";
$l_rs_insector		= "Du bist derzeit in Sektor [sector] - und die Sektoren reichen von 0 bis [sector_max].";
$l_rs_submit		= "Berechnen";
$l_rs_movetime		= "Mit Deinen Triebwerken, benötigst Du [triptime] Z&uuml;ge um dort hinzufliegen.";
$l_rs_energy		= "Deine Sonnensegel würden [energy] Einheiten Energie aufsammeln";
$l_rs_noturns		= "Du hast nicht genug Z&uuml;ge &uuml;brig und kannst nicht aufbrechen.";
$l_rs_engage_link	= "Starte";
$l_rs_engage		= "Du hast [turns] Z&uuml;ge. [engage] Triebwerke?";

$l_rs_invalid		= "Ung&uuml;ltiges Ziel";
$l_rs_ready 		= "Du bist nun im Sektor [sector]. Du hast [triptime] Z&uuml;ge, und [energy] Energie.";

// navcomp.php	

$l_nav_title		 = "Navigations Computer";
$l_nav_nocomp		 = "Navigations Computer ist nicht verfügbar";
$l_nav_query		 = "Gib den Sektor ein, zu dem Du einen Weg benötigst: ";
$l_nav_pathfnd		 = "Weg gefunden";
$l_nav_answ1		 = "Es wird Dich";
$l_nav_answ2		 = "Züge kosten, um in den Sektor zu gelangen.";
$l_nav_proper		 = "Deine Computertechnologie ist zu primitiv, um eine Weg zu berechnen.";


// attack.php

$l_att_title		 = "Attackiere Schiff";
$l_att_notarg		 = "Ziel nicht in diesem Sektor.";
$l_att_noturn		 = "Du ben&ouml;tigst einen Zug um anzugreifen.";
$l_att_noatt		 = "Es ist verboten, jemanden in diesem Sektor anzugreifen.";
$l_att_flee		 = "Ziel fl&uuml;chtet vor Dir";
$l_att_ewd		 = "Das Ziel benutzt ein Notfall Warp Ger&auml;t, als es angegriffen wurde";
$l_att_att		 = "Angriff ";
$l_att_beams		 = "Laserwaffen Terffer:";
$l_att_torps		 = "Torpedo Treffer:";
$l_att_fighters		 = "Fighter Angriff:";
$l_att_lost		 = "verloren";
$l_att_ylost		 = "Du verlierst";
$l_att_sdown		 = "Schilde sind runter!";
$l_att_ydown		 = "Deine Schilde sind runter!";
$l_att_shits		 = "'s Schilde erhielten ";
$l_att_yhits		 = "Deine Schilde erhielten ";
$l_att_dmg		 = " Punkte Schaden";
$l_att_sarm		 = " 's Panzerung ist durchbrochen!";
$l_att_yarm		 = "Deine Panzerung ist durchbrochen";
$l_att_ashit		 = "'s Panzerung erhielt ";
$l_att_ayhit		 = "Deine Panzerung erhielt ";
$l_att_lostf		 = "verlor alle Fighter.";
$l_att_ylostf		 = "Du verlierst alle Fighter.";
$l_att_sdest		 = "s Schiff wurde zerstört.";
$l_att_espod		 = "Eine Rettungskapsel wurde gestartet!";
$l_att_ysalv		 = "Du erbeutest [salv_ore] Erz Einheiten, [salv_organics] Lebensmittel Einheiten, [salv_goods] Güter, und erhälst [ship_salvage_rate]% von dem Schiff, insgesamt [ship_salvage] Credits.<BR>Deine Punktzahl verändert sich um [rating_change] Punkte.";
$l_att_andused		 = "und benutztest";
$l_att_stilship		 = "Du hast [name]'s Schiff nicht zertört.";
$l_att_atyou		 = "greifen Dich an";
$l_att_and		 = "und";
$l_att_yshiplost	 = "Dein Schiff wurde zerstört!";
$l_att_salv		 = "[name] erbeutete [salv_ore] Erz Einheiten, [salv_organics] Lebensmittel Einheiten, [salv_goods] Güter, und erhielt [ship_salvage_rate]% des Schiffs, insgesamt [ship_salvage] Credits.";

// warpedit 1-3.php

$l_warp_title		 = "Benutze Warptor Kits";
$l_warp_turn		 = "Um den Warptore zu bauen oder zu zerst&ouml;ren, ben&ouml;tigst Du einen Zug.";
$l_warp_none		 = "Du besitzt keine Warptor Kits.";
$l_warp_forbid		 = "Es ist verboten, ein Warptor Kits in diesem Sektor zu benutzen.";
$l_warp_nolink		 = "Es gibt keine Warptore aus diesem Sektor heraus.";
$l_warp_linkto		 = "Warptore führen aus diesem Sektor nach";
$l_warp_query		 = "Zu welchem Sektor möchtest Du einen Warptor bauen?";
$l_warp_oneway		 = "Nur eine Richtung?";
$l_warp_dest		 = "Alternativ dazu, kannst Du auch ein Warptor zerst&ouml;ren.";
$l_warp_destquery	 = "In welchem Sektor möchtest Du ein Warptor zerst&ouml;ren?";
$l_warp_bothway		 = "Beide Richtungen";
$l_warp_nosector	 = "Sektor existiert nicht.";
$l_warp_twoerror	 = "Erstellen eines zwei-Wege Tors zum Sektor [target_sector] ist verboten.";
$l_warp_sectex		 = "Du kannst kein Warptor erstellen, da man maximal $link_max Tore pro Sektor erstellen kann.";
$l_warp_linked		 = "Der Ziel Sektor ([target_sector]) verfügt bereits über ein Warptor von diesem Sektor.";
$l_warp_unlinked	 = "Der Ziel Sektor ([target_sector]) verfügt nicht über ein Warptor von diesem Sektor.";
$l_warp_coneway	         = "Ein Warptor (eine Richtung) wurde erstellt von";
$l_warp_ctwoway		 = "Warptor wurde erstellt von und nach ";
$l_warp_forbidtwo	 = "Zerst&ouml;ren eines Warptors von und nach Sektor [target_sector] ist nicht möglich.";
$l_warp_removed		 = "Warptor zerst&ouml;rt zu Sektor ";
$l_warp_removedtwo	 = "Warptor zerst&ouml;rt von und nach Sektor";

// genesis.php

$l_gns_title		 = "Genesis Torpedo benutzen";
$l_gns_turn		 = "Du ben&ouml;tigst einen Zug, um den Genesis Torpedo abzufeuern.";
$l_gns_onplanet		 = "Du kannst dieses Ger&auml;t nicht auf der Planetenoberfl&auml;che benutzen.";
$l_gns_full		 = "Dieses Sonnensystem ist bereits voll!";
$l_gns_planetex		 = "Es gibt bereits einen Planeten in diesem Sektor.";
$l_gns_nogenesis	 = "Du besitzt keine Genesis Torpedos.";
$l_gns_forbid		 = "In diesem Sektor ist es verboten, einen Planeten zu erstellen.";
$l_gns_bforbid		 = "In diesem Sektor ist es unmöglich, einen Planeten zu erstellen. Die Planetenbais stört Dein Genesis Ger&auml;t.";
$l_gns_pcreate		 = "Planet wurde erschaffen.";

// ship.php

$l_ship_title		 = "Schiffs Kommando";
$l_ship_the		 = "Die";
$l_ship_nolonger	 = "ist nicht l&auml;nger im Sektor";
$l_ship_youc		 = "Du siehst die";
$l_ship_owned		 = "geführt von";
$l_ship_perform		 = "Du kannst folgende Aktionen durchführen:";

// selfdestruct.php

$l_die_title		 = "Selbst Zerstörung";
$l_die_rusure		 = "Bist Du Sicher, dass Du Dein Schiff zerst&ouml;ren m&ouml;chtest?.";
$l_die_goodbye		 = "Aufwiedersehen grausame Galaxie!";
$l_die_check		 = "Bist Du wirklich Sicher, dass Du wirklich aus dem Spiel ausscheiden m&ouml;chtest?";
$l_die_nonono		 = "Nein! Nein! Nein!";
$l_die_what		 = "Was habe ich mir nur dabei gedacht?";
$l_die_count		 = "5.. 4.. 3.. 2.. 1.. Boom!";
$l_die_vapor		 = "Dein Schiff und alle Passagiere wurden pulverisiert.";
$l_die_please		 = "Logge Dich bitte <A HREF=logout.php3>aus</A>";
$l_die_exploit		 = "Spiele nicht mit etwas, was Du nicht verstehst !";

// move.php

$l_move_title 		 = "Warptor benutzung";
$l_move_turn		 = "Du ben&ouml;tigst einen Zug um Warptore zu benutzen.";
$l_move_failed		 = "Warptor benutzung fehlgeschlagen!";

// scan.php

$l_scan_title		 = "Scanne Schiff";
$l_scan_turn		 = "Du ben&ouml;tigst einen Zug um ein anderes Schiff zu scannen.";
$l_scan_ron		 = "Scan Resultate von";
$l_scan_capt		 = "Gef&uuml;hrt von:";
$l_scan_arma		 = "Bewaffnung:";
$l_scan_carry		 = "Ladung:";

// lrscan.php

$l_lrs_title		 = "Scan mit langer Reichweite";
$l_lrs_nofull		 = "Dein Scanner besitzt nicht die F&auml;higkeit, um einen Scan mit langer Reichweite durchzuf&uuml;hren.";
$l_lrs_noturns		 = "Du benötigst $fullscan_cost Z&uuml;ge, um einen Scan mit weiter Reichweite durchzuführen.";
$l_lrs_used		 = "benutzt";
$l_lrs_turns		 = "Z&uuml;ge";
$l_lrs_left		 = "&uuml;brig";
$l_lrs_reach		 = "Die folgenen Sektoren k&ouml;nnen von Sektor [sector] ereicht werden:";
$l_lrs_links		 = "Warptore";
$l_lrs_ships		 = "Schiffe";
$l_lrs_click		 = "Klicke auf die Warptore, um zu dem Sektor zu gelangen.";
$l_lrs_cantscan		 = "Du kannst den Sektor nicht scannen";
$l_lrs_zero		 = "Sektor 0 ist zu &uuml;berf&uuml;llt um nach anderen Schiffen zu scannen!";
$l_lrs_moveto		 = " um zu folgendem Sektor zu gelangen:";

// log.php

$l_log_months = array('Januar','Februar','März','April','Mai','Juni','Juli','August','September','Oktober','November','Dezember');
$l_log_months_short = array('Jan','Feb','Mrz','Apr','Mai','Jun','Jul','Aug','Sep','Okt','Nov','Dez');
$l_log_pod = "Zum Gl&uuml;ck hattest du eine Fluchtkapsel!";
$l_log_nopod = "<font color=yellow><b>Du hattest keine Fluchtkapsel, und starbst.</b></font>";
$l_log_log = "[player]s Log"; 
$l_log_start = "Logbuch Eintrag für"; 
$l_log_end = "Ende des Logbuch Eintrags für"; 
$l_log_click = "Klicke <A HREF=$interface><font color=#00ff00>hhier</font></A> um zum Hauptmenü zurück zu kehren."; 
$l_log_note = "Hinweis: Wenn diese Seite nicht richtig angezeigt wird, oder wenn du einfach die dynamischen HTML effekte nicht magst oder sie dich nerven, kannst du sie <a href=options.php3><font color=#00FF00>hier</font> abstellen"; 

$l_log_text[LOG_LOGIN] = "Du hast Dich eingeloggt, mit der [ip].";
$l_log_title[LOG_LOGIN] = "Eingelogt";
$l_log_text[LOG_LOGOUT] = "Du hast Dich mit der [ip] ausgeloggt.";
$l_log_title[LOG_LOGOUT] = "Ausgelogt";
$l_log_text[LOG_ATTACK_OUTMAN] = "[player] wurde auf einem Angriffs Vektor gesichtet, aber deine Talent und deine guten Triebwerke erlaubten es dir dem Angriff auszuweichen.";
$l_log_title[LOG_ATTACK_OUTMAN] = "Ausweich Man&ouml;ver!";
$l_log_text[LOG_ATTACK_OUTSCAN] = "Du entdecktest [player] als er versuchte seine Waffen auf dein Schiff zu richten, aber deine Tarnung schützte dich vor seinen primitiven Sensoren.";
$l_log_title[LOG_ATTACK_OUTSCAN] = "Tarnung erfolgreich!";
$l_log_text[LOG_ATTACK_EWD] = "Du wurdest von [player]s hinterhältigen Attacke überrascht. Du siehst eine Fülle von Schüssen auf dich zukommen als du panisch auf den Knopf des Notfallwarps schlägst. Die Welt um dich herum verschwimmt, und für eine Sekunde glaubst du, du wärst tot. Als du dann schliesslich die Augen wieder öffnest, erkennst du, dass du dich woanders befindest. Wo auch immer...";
$l_log_title[LOG_ATTACK_EWD] = "Notfall Warp!";
$l_log_text[LOG_ATTACK_EWDFAIL] = "Deine Sensoren entdecken [player]s Schiff auf einem Angriffs Vektor. \"Lieber Jetzt als Nie\", denkst du Dir als du auf den Notfall Warp Knopf drückst. Du h&ouml;rst ein merkwürdiges Klicken und Krachen aus dem Maschinendeck und riechst schmorendes Plastik. \"Scheiss Kiste!\", schreist Du, und trittst den Computer. Der Computer piepst protestierend, als Du Dich auf den Angriff vorbereitest..";
$l_log_title[LOG_ATTACK_EWDFAIL] = "Notfall Warp <font color=red>fehlgeschlagen!</font>";
$l_log_text[LOG_ATTACK_LOSE] = "Dein Schiff wurde von [player] angegriffen. Du bist nicht imstande etwas gegen die übermächtigen Waffen von [player] auszurichten. Dein Schiff wurde zerstört. ";
$l_log_title[LOG_ATTACK_LOSE] = "<font color=red>Kampf verloren!</font>";
$l_log_text[LOG_ATTACKED_WIN] = "Du wurdest von [player] angegriffen. Du kämpfst eine Weile, dann endlich ist der Kampf vorrüber. Du verlorst [armor] Panzerungs Punkte und [fighters] Fighter in dem Gemetzel.";
$l_log_title[LOG_ATTACKED_WIN] = "<font color=yellow>Gemetzel!</font>";
$l_log_text[LOG_TOLL_PAID] = "Du hast [toll] Credits Zoll für den Einflug in Sektor [sector] gezahlt. Du versprichst Dir selbst, dass Du einen Weg finden wirst um Dein Geld zurückzubekommen.";
$l_log_title[LOG_TOLL_PAID] = "Erpressung";
$l_log_text[LOG_HIT_MINES] = "Bei Deiner Reise durch den Sektor [sector], wurdest Du von [mines] Minen getroffen.";
$l_log_title[LOG_HIT_MINES] = "<font color=yellow>Minen Alarm!</font>";
$l_log_text[LOG_SHIP_DESTROYED_MINES] = "Dein Schiff wurde in einem Minenfeld vom Sektor [sector] zerstört. ";
$l_log_title[LOG_SHIP_DESTROYED_MINES] = "<font color=red>Minen Alarm!</font>";
$l_log_text[LOG_PLANET_DEFEATED_D] = "Dein Planet [planet_name] in Sektor [sector] wurde übernommen von [name]. Glücklicherweise führte die Loyalität deiner Bürger dazu, dass sie den Planeten lieber zerstörten, als ihn in die Hände des Feindes fallen zu lassen! Du organisierst wunderschöne Todesfeiern in Gedanken an die vielen Toten.";
$l_log_title[LOG_PLANET_DEFEATED_D] = "<font color=yellow>Planet zerstört</font>";
$l_log_text[LOG_PLANET_DEFEATED] = "Dein Planet [planet_name] in Sektor [sector] wurde im Verlauf eines Kampfes von [name] übernommen. Die Leute auf dem Planeten heissen ihren neuen Herrscher willkommen. Du hörst einen Bericht in den BNN : \"Wir sind erfreut, dass die Schreckensherrschaft endlich ein Ende hat! Wir wollen nicht länger von einem stinkenden Verlierer regiert werden, der uns nicht einmal beschützen kann!\". Du schwörst, dass Sie für ihre Arroganz bezahlen werden.";
$l_log_title[LOG_PLANET_DEFEATED] = "<font color=red>Planet eingenommen!</font>";
$l_log_text[LOG_PLANET_NOT_DEFEATED] = "Dein Planet [planet_name] in Sektor [sector] wurde von [name] angegriffen. Deine Zivilisation verteidigte den Planeten und besiegte den Angreifer. Sie konnten : [goods] Güter, [ore] Erz, [organics] Lebensmittel und [salvage]% des Schiffes, Wert [credits] Credits  bergen.";
$l_log_title[LOG_PLANET_NOT_DEFEATED] = "Sieg!";
$l_log_title[LOG_RAW] = "Notiz";
$l_log_text[LOG_TOLL_RECV] = "Deine Fighter in Sektor [sector] haben [toll] Credits an Zoll eingenommen.";
$l_log_title[LOG_TOLL_RECV] = "Zoll Einnahmen";
$l_log_text[LOG_DEFS_DESTROYED] = "[quantity] ([type]) wurden im Sektor [sector] zerstört.";
$l_log_title[LOG_DEFS_DESTROYED] = "Sektor verteidigung zerstört";
$l_log_text[LOG_PLANET_EJECT] = "Du musstest den Planeten in Sektor [sector] verlassen, weil [name] die Allianz verlassen hat.";
$l_log_title[LOG_PLANET_EJECT] = "Not Start!";
$l_log_text[LOG_BADLOGIN] = "Fehlgeschlagener Login Versuch mit der IP: [ip].";
$l_log_title[LOG_BADLOGIN] = "Login fehlgeschlagen";
$l_log_text[LOG_PLANET_SCAN] = "[name] hat Deinen Planeten [planet_name] in Sektor [sector] gescannt.";
$l_log_title[LOG_PLANET_SCAN] = "Planeten Scan";
$l_log_text[LOG_PLANET_SCAN_FAIL] = "[name] hat vergebens versucht Deinen Planeten [planet_name] in Sektor [sector] zu scannen.";
$l_log_title[LOG_PLANET_SCAN_FAIL] = "Planeten Scan fehlgeschlagen";
$l_log_text[LOG_SHIP_SCAN] = "[player] hat Dein Schiff gescannt.";
$l_log_title[LOG_SHIP_SCAN] = "Shiff Scan";
$l_log_text[LOG_SHIP_SCAN_FAIL] = "[player] hat vergebens versucht, Dein schiff zu scannen.";
$l_log_title[LOG_SHIP_SCAN_FAIL] = "Schiff Scan fehlgeschlagen";
$l_log_text[LOG_FURANGEE_ATTACK] = "Greife [player] an...";
$l_log_title[LOG_FURANGEE_ATTACK] = "Angriff";
$l_log_text[LOG_STARVATION] = "Auf einem Deiner Planeten im Sektor [sector] kann sich die Bevölkerung nicht vergrößern. Es werden mehr Lebensmittel benötigt! Bedauerlicherweise sind [starvation] Kolonisten den Hungertod gestorben!";
$l_log_title[LOG_STARVATION] = "<font color=yellow>Hungersnot!</font>";
$l_log_text[LOG_TOW] = "Dein Schiff wurde vom Sektor [sector] zu Sektor [newsector] abgeschleppt, weil Deine Hüllengrösse die maximale Größe überstieg.";
$l_log_title[LOG_TOW] = "Abgeschleppt!";
$l_log_text[LOG_DEFS_DESTROYED_F] = "Du hast [fighters] patrolierende Fighter in Sektor [sector] zerstört.";
$l_log_title[LOG_DEFS_DESTROYED_F] = "Patrolie zerstört";
$l_log_text[LOG_DEFS_KABOOM] = "Du wurdest von feindlichen Fightern in Sektor [sector] zerstört. ";
$l_log_title[LOG_DEFS_KABOOM] = "<font color=red>Schiff zerstört!</font>";
$l_log_text[LOG_HARAKIRI] = "Du warst es leid Kapitän von einem grossen Haufen Müll zu sein, und so entschiedest du dich, das Universum wäre besser ohne diesen Müll. Authorisiert von [ip].";
$l_log_title[LOG_HARAKIRI] = "<font color=red>Selbstzerstörung!</font>";
$l_log_text[LOG_TEAM_REJECT] = "[player] hat die Einladung in die Allianz nicht angenommen, [teamname].";
$l_log_title[LOG_TEAM_REJECT] = "Einladung abgelehnt";
$l_log_text[LOG_TEAM_RENAME] = "Du hast Deine Allianz in [team] umbenannt.";
$l_log_title[LOG_TEAM_RENAME] = "Allianz umbenannt";
$l_log_text[LOG_TEAM_M_RENAME] = "Der Führer der Allianz hat die Allianz in [team] umbenannt.";
$l_log_title[LOG_TEAM_M_RENAME] = "Allianz umbenannt";
$l_log_text[LOG_TEAM_KICK] = "Du wurdest aus der [team] Allianz geworfen.";
$l_log_title[LOG_TEAM_KICK] = "Man hat Dich aus der Allianz geworfen.";
$l_log_text[LOG_TEAM_CREATE] = "Du hast eine neue Allianz mit dem Namen [team] erstellt.";
$l_log_title[LOG_TEAM_CREATE] = "Neue Allianz erstellt";
$l_log_text[LOG_TEAM_LEAVE] = "Du hast die [team] Allianz verlassen.";
$l_log_title[LOG_TEAM_LEAVE] = "Verlasse Allianz";
$l_log_text[LOG_TEAM_NEWLEAD] = "Du hast die Allianz [team] verlassen. Du hast die Führung der Allianz an [name] übergeben.";
$l_log_title[LOG_TEAM_NEWLEAD] = "Verlasse Allianz";
$l_log_text[LOG_TEAM_LEAD] = "Der [team] Allianz Coordinator hat sich entschlossen, daß Team zu verlassen. Du kannst nun seinen Platz einnehmen.";
$l_log_title[LOG_TEAM_LEAD] = "Promotion!";
$l_log_text[LOG_TEAM_JOIN] = "Du bist der Allianz [team] beigetreten.";
$l_log_title[LOG_TEAM_JOIN] = "Allianz Beitritt";
$l_log_text[LOG_TEAM_NEWMEMBER] = "[name] hat der Einladung der [team] Allianz zugestimmt.";
$l_log_title[LOG_TEAM_NEWMEMBER] = "Neues Allianz Mitglied";
$l_log_text[LOG_TEAM_INVITE] = "Du wurdest eingeladen, um der [team] -Allianz beizutreten.";
$l_log_title[LOG_TEAM_INVITE] = "Einladung";
$l_log_text[LOG_TEAM_NOT_LEAVE] = "[player] hat die Allianz verlassen";
$l_log_title[LOG_TEAM_NOT_LEAVE] = "Allianz verliert ein Mitglied";
$l_log_text[LOG_ADMIN_HARAKIRI] = "[player] has self-destructed from ip [ip].";
$l_log_title[LOG_ADMIN_HARAKIRI] = "Self-destruct";
$l_log_text[LOG_ADMIN_ILLEGVALUE] = "[player] had [quantity] [type], with max holds of [holds]";
$l_log_title[LOG_ADMIN_ILLEGVALUE] = "Illegal ship value";
$l_log_text[LOG_ADMIN_PLANETDEL] = "[attacker] has attempted to capture [defender]'s planet in sector [sector]. Planet was destroyed instead.";
$l_log_title[LOG_ADMIN_PLANETDEL] = "Planet destroyed";
$l_log_text[LOG_DEFENCE_DEGRADE] = "Sector Defences Fighters in sector [sector] degraded by [degrade] percent due to insufficient energy.";
$l_log_test[LOG_DEFENCE_DEGRADE] = "Sector Defences degraded.";

// modify-defences.php

$l_md_title		 = "Sektor Verteidigung";
$l_md_invalid		 = "Ungültige Sektorverteidigung";
$l_md_nolonger		 = "Die gewählte Sektorverteidigung ist nicht länger hier.";
$l_md_you		 = "Dich";
$l_md_bmines		 = "Deine Strahlenwaffen zerstören";
$l_md_msgdownerb	 = "[name] zerstörte [mines] Minen in Sektor [sector].";
$l_md_retr		 = "Du bargst";
$l_md_mode		 = "Die Fighter wurden in den [mode] Modus gewechselt.";
$l_md_consist		 = "Die Sektorverteidigung besteht aus [qty] ([type]) die [owner] gehören.";
$l_md_youcan		 = "Du kannst";
$l_md_retrieve		 = "Bergen";
$l_md_change		 = "Fighter Einstellungen wechseln";
$l_md_cmode		 = "Fighter Modus";
$l_md_attack		 = "Angriff";
$l_md_toll		 = "Zoll";
$l_md_attdef		 = "Greife die Sektor Verteidigung an. Alle Fighter werden partizipieren.";

// news.php

$l_news_title		 = "BlackNova Universe News";
$l_news_info		 = "BNN ist innerhalb der Galaxis führend<br>
                            in Sachen Nachrichten- und Informationsübermittlung.<br>
                            24 Stunden am Tag, 7 Tage die Woche, von egnagiertem <br>
                            Personal in BNN's Galaxie Hauptquartier <br>
                            auf Alpha Centaury und in Büros galaxienweit!";
$l_news_for		 = "Neuigkeiten für";
$l_news_prev		 = "vorheriger Tag";
$l_news_next		 = "nächster Tag";
$l_news_none		 = "Keine neuen Nachrichten heute.";
$l_news_flash		 = "News Flash";

// dump.php

$l_dump_title		 = "Kolonisten Abladen";
$l_dump_turn		 = "Du benötigst einen Zug um die Kolonisten abzuladen.";
$l_dump_nocol		 = "Du hast keine Kolonisten auf dem Schiff, die du abladen könntest.";
$l_dump_dumped		 = "Kolonisten beim abgeladen.";
$l_dump_nono		 = "Du musst bei einem Spezial Hafen sein, um das zu tun.";

// readmail.php

$l_readm_title		 = "Lese Nachricht";

$l_readm_delete		 = "NACHRICHT GELÖSCHT";
$l_readm_nomessage	 = "Keine Nachrichten warten auf Dich...";
$l_readm_center		 = "Nachrichten Empfangs-Center";
$l_readm_sender		 = "Nachrichten Sender";
$l_readm_captn		 = "Kapitän der";
$l_readm_del		 = "Löschen";
$l_readm_repl		 = "Antworten";

// mailto2.php

$l_sendm_title		 = "Sende Nachricht";
$l_sendm_to		 = "An";
$l_sendm_from		 = "Von";
$l_sendm_ally		 = "Allianz:";
$l_sendm_subj		 = "Betreff";
$l_sendm_mess		 = "Nachricht";
$l_sendm_send		 = "Sende";
$l_sendm_sent		 = "Nachricht gesendet";

// zoneinfo.php

$l_zi_title		 = "Zonen Information";
$l_zi_nexist		 = "Diese Sektion des Weltraums, existiert nicht!";
$l_zi_feds		 = "Föderation";
$l_zi_traders		 = "Die Freie Handels Koalition";
$l_zi_nobody		 = "Niemandem";
$l_zi_war		 = "Umkämpfter space";
$l_zi_allow		 = "Erlaubt";
$l_zi_notallow		 = "Nicht erlaubt";
$l_zi_limit		 = "Nur für Eigentümer udn Alliierte";
$l_zi_ul		 = "Unbegrenzt";
$l_zi_control		 = "Du bist im Besitz des Sektors";
$l_zi_tochange		 = "Um die Regeln zu ändern.";
$l_zi_owner		 = "Zonen Besitzer";
$l_zi_maxhull		 = "Maximale erlaubte Hüllengröße";

// zoneedit.php

$l_ze_title		 = "Verändere Zonen Regeln";
$l_ze_notowner		 = "Du kannst die Zonen Regeln nicht verändern, da Du nicht der Besitzer der Zone bist.";
$l_ze_name		 = "Zonen Name";
$l_ze_allow		 = "Erlaube";
$l_ze_attacks		 = "Erlaube Angriffe auf andere Schiffe";
$l_ze_genesis		 = "Erlaube neue Planeten zu erstellen";
$l_ze_return		 = "um zurück zur Informations-Seitezu gelangen";
$l_ze_saved		 = "Deine Veränderung wurde gespeichert.";

// teams.php

$l_team_title		 = "Alliances";
$l_team_menu		 = "to go back to the Alliances Menu";
$l_team_galax		 = "Alliances present in the Galaxy:";
$l_team_members		 = "Members";
$l_team_coord		 = "Co-ordinator";
$l_team_member		 = "Member";
$l_team_noinvite	 = "Nobody has invited you to join an alliance.";
$l_team_ifyouwant	 = "If you want to join an alliance, send a message to its co-ordinator asking to be invited.";
$l_team_tocreate	 = "to create a new alliance.";
$l_team_injoin		 = "You have been invited to join";
$l_team_tojoin		 = "to join";
$l_team_or		 = "or";
$l_team_reject		 = "to reject the invitation.";
$l_team_ed		 = "Edit";
$l_team_inv		 = "Invite";
$l_team_leave		 = "Leave";
$l_team_eject		 = "Eject";
$l_team_pending		 = "Invitation pending for";
$l_team_noinvites	 = "Nobody has been invited to be part of";
$l_team_confirmleave	 = "Are you sure you want to leave";
$l_team_onlymember	 = "You were the only member, thus [team_name] is no more.";
$l_team_youarecoord	 = "You are the co-ordinator of";
$l_team_relinq		 = "You must relinquish your role to another player.";
$l_team_newc		 = "New co-ordinator:";
$l_team_youveleft	 = "You have left alliance";
$l_team_relto		 = "relinquishing the functions of co-ordinator to";
$l_team_welcome		 = "Welcome to alliance";
$l_team_noinviteto	 = "You have not been invited in to that team.";
$l_team_ejectsure	 = "Are you sure you want to eject";
$l_team_ejected 	 = "has been eject from the alliance!";
$l_team_testing		 = "Testing phase...";
$l_team_pw		 = "Password";
$l_team_entername	 = "Enter the name of the Alliance";
$l_team_enterdesc	 = "Enter a description of the Alliance";
$l_team_hcreated	 = "has been created and you are its leader";
$l_team_alliance	 = "Alliance";
$l_team_selectp		 = "Select the Player you want to invite";
$l_team_isorry		 = "Sorry, but [name] has already been invited to be part of an alliance - only one invitation can be active at any given time";
$l_team_plinvted	 = "Player invited.<BR>You must wait for that player to aknowledge your invitation.";
$l_team_refuse		 = "You have refused the invitation to join";
$l_team_edname		 = "Edit the name of your Alliance";
$l_team_eddesc		 = "Edit the description for your Alliance";
$l_team_hasbeenr	 = "has been renamed.";
$l_team_error		 = "<b><font color=red>An error occured</font></b><br>You are not the leader of this Alliance.";
$l_team_notmember	 = "You are not a member of any alliance";
$l_team_urejected	 = "<B>ATTENTION</B> - you have been ejected from";
$l_team_noalliances	 = "There are no alliances in the Galaxy at this time.";

// ranking.php

$l_ranks_title		 = "Top $max_rank Players";
$l_ranks_none		 = "No Results to show.";
$l_ranks_pnum		 = "Total number of players";
$l_ranks_dships		 = "Players with destroyed ships are not counted.";
$l_ranks_rank		 = "Rank";
$l_ranks_lastlog	 = "Last login";
$l_ranks_good		 = "Good";
$l_ranks_evil		 = "Evil";

// beacon.php

$l_beacon_title		 = "Deploy Space Beacon";
$l_beacon_notpermitted	 = "Deploying space beacons in this sector is not permitted.";
$l_beacon_reads		 = "Present beacon reads";
$l_beacon_none		 = "There presently isn't a beacon in this sector.";
$l_beacon_enter		 = "Enter text for beacon";
$l_beacon_nowreads	 = "Beacon now reads";
$l_beacon_donthave	 = "You do not have a space beacon.";

// emerwarp.php

$l_ewd_title		 = "Use Emergency Warp Device";
$l_ewd_used		 = "Emergency warp device engaged - arrived in sector [sector].";
$l_ewd_none		 = "You do not have an emergency warp device.";

// defence-report.php

$l_sdf_title		 = "Sector Defence Report";
$l_sdf_none		 = "You have no sector defences deployed.";
$l_sdf_type		 = "Type";
$l_sdf_mode		 = "Mode";

// traderoute.php
// cause its rather big i put everything in own vars than to re-use
// the old ones so we could export to own file if performance problems
// should occur

$l_tdr_title    	 = "Trade Routes";
$l_tdr_newtdr   	 = "Click <a href=\"traderoute.php?command=new\">here</a> to 
create a new trade route";
$l_tdr_modtdrset         = "To modify your global trade settings, click <a 
href=\"traderoute.php?command=settings\">here</a>";
$l_tdr_confdel  	 = "Click <a 
href=\"traderoute.php?command=delete&confirm=yes&traderoute_id=[tdr_id]\">here</a> 
to confirm deletion of the following trade route :";
$l_tdr_noactive 	 = "You do not have any active trade routes to display.";
$l_tdr_curtdr   	 = "Current Trade Routes";
$l_tdr_deltdr   	 = "Delete Trade Route";
$l_tdr_src      	 = "Source";
$l_tdr_srctype  	 = "Src Type";
$l_tdr_dest     	 = "Destination";
$l_tdr_desttype 	 = "Dest Type";
$l_tdr_move     	 = "Move";
$l_tdr_circuit  	 = "Circuit";
$l_tdr_change   	 = "Change";
$l_tdr_portin   	 = "Port in";
$l_tdr_planet   	 = "Planet";
$l_tdr_nonexistance      = "Non-existant planet!";
$l_tdr_na       	 = "N/A";
$l_tdr_cargo    	 = "Cargo";
$l_tdr_none     	 = "None";
$l_tdr_colonists         = "Colonists";
$l_tdr_fighters 	 = "Fighters";
$l_tdr_torps    	 = "Torpedoes";
$l_tdr_escooped 	 = "[tdr_dist_triptime] turns<br>[tdr_dist_scooped] energy 
scooped";
$l_tdr_warp     	 = "Warp";
$l_tdr_turns    	 = "turns";
$l_tdr_way      	 = "way";
$l_tdr_ways     	 = "ways";
$l_tdr_edit     	 = "Edit";
$l_tdr_del      	 = "Delete";
$l_tdr_nowlink1 	 = "There is no warp link from sector [tdr_src_sector_id] to 
sector [tdr_dest_sector_id]";
$l_tdr_nowlink2 	 = "There is no warp link from sector [tdr_dest_sector_id] to 
sector [tdr_src_sector_id]";
$l_tdr_sportissrc        = "If a special port is source, a planet must be the 
destination for colonization.";
$l_tdr_notownplanet      = "You can't colonize a planet that you or your team 
don't own.";
$l_tdr_planetisdest      = "A planet can be a destination only when source is 
a special port.";
$l_tdr_samecom 		 = "You can't make a traderoute for ports selling the same 
commodities.";
$l_tdr_sportcom 	 = "You can't sell commodities from a planet in a special 
port.";
$l_tdr_editerr  	 = "Edit error : trade route not found in DB";
$l_tdr_maxtdr   	 = "Sorry you have reached the maximum number of trade routes 
allowed.";
$l_tdr_createnew         = "Creating a new";
$l_tdr_editinga 	 = "Editing a";
$l_tdr_traderoute        = "trade route";
$l_tdr_unnamed  	 = "Unnamed";
$l_tdr_cursector         = "You are currently in sector";
$l_tdr_selspoint         = "Please select starting point :";
$l_tdr_port     	 = "Port";
$l_tdr_insector 	 = "in sector";
$l_tdr_selendpoint       = "Please select ending point";
$l_tdr_selmovetype       = "Please select move type";
$l_tdr_realspace         = "Real Space";
$l_tdr_selcircuit        = "Please select circuit";
$l_tdr_oneway   	 = "One way";
$l_tdr_errnotvalidport   = "Error : the source port [tdr_port_id] does not 
seem to be valid.";
$l_tdr_bothways 	 = "Both ways";
$l_tdr_create   	 = "Create";
$l_tdr_modify   	 = "Modify";
$l_tdr_returnmenu        = "Click <a href=traderoute.php>here</a> to return to 
the trade routes menu.";
$l_tdr_errnotvalidport   = "Error : the source port [tdr_port_id] is not a 
valid port.";
$l_tdr_errnoport         = "Error : there is no port at sector [tdr_port_id].";
$l_tdr_errnosrc    	 = "Error : specified source planet doesn't exist.";
$l_tdr_errnotownnotsell  = "Error : you do not own planet [tdr_source_name] 
in sector [tdr_source_sector_id] and planet is not selling.";
$l_tdr_errnotvaliddestport= "Error : the destination port [tdr_port_id] 
is not a valid port.";
$l_tdr_errnoport2        = "Error : there is no port at sector [tdr_port_id].";
$l_tdr_errnodestplanet   = "Error : specified destination planet does not 
exist.";
$l_tdr_errnotownnotsell2 = "Error : you do not own planet [tdr_dest_name] in sector [tdr_dest_sector_id] and planet is not selling.";
$l_tdr_newtdrcreated     = "New trade route created!";
$l_tdr_tdrmodified       = "Trade route modified!";
$l_tdr_doesntexist       = "That trade route doesn't exist!";
$l_tdr_notowntdr         = "You do not own that traderoute!";
$l_tdr_tdrdeleted        = "Trade route deleted.";
$l_tdr_globalset         = "Global trade route settings";
$l_tdr_tdrsportsrc       = "For trade routes having a special port as a 
source, trade";
$l_tdr_tdrescooped       = "For real space trade routes, what to do with the 
energy scooped?";
$l_tdr_trade    	 = "Trade";
$l_tdr_keep    	 	 = "Keep";
$l_tdr_save    	 	 = "Save";
$l_tdr_globalsetsaved    = "Global trade route settings saved.";
$l_tdr_engagenonexist    = "Tried to engage a non-exiDestination sector does 
not seem to be valid!sting trade route!";
$l_tdr_invalidspoint     = "Starting port does not seem to be valid!";
$l_tdr_inittdr  	 = "You are not in sector [tdr_source_id]! You must be in 
starting sector before you initiate a trade route!";
$l_tdr_invalidsrc        = "Source planet doesn't seem to be a valid planet!";
$l_tdr_inittdrsector     = "You are not in sector [tdr_source_sector_id]! You 
must be in starting sector before you initiate a trade route!";
$l_tdr_notyourplanet     = "You do not own planet [tdr_source_name] in sector 
[tdr_source_sector_id]!";
$l_tdr_invalidssector    = "Starting sector does not seem to be valid!";
$l_tdr_invaliddport      = "Destination port does not seem to be valid!";
$l_tdr_invaliddplanet    = "Destination planet doesn't seem to be a valid 
planet!";
$l_tdr_invaliddsector    = "Destination sector does not seem to be valid!";
$l_tdr_moreturnsneeded   = "This trade route requires [tdr_dist_triptime] 
turns to complete. You only have [tdr_playerinfo_turns] left.";
$l_tdr_tdrhostdef        = "You can not use trade routes between sectors with 
hostile defences. You must defeat the defences first.";
$l_tdr_globalsetbuynothing= "Your global settings are set to buy 
nothing! You would only waste turns doing this route!";
$l_tdr_nosrcporttrade    = "Trading from source port is not allowed.";
$l_tdr_tradesrcportoutsider= "Trading at source port is not allowed for 
outsiders";
$l_tdr_nodestporttrade   = "Trading from destination port is not allowed.";
$l_tdr_tradedestportoutsider= "Trading at destination port is not allowed 
for outsiders";
$l_tdr_notyourplanet     = "You do not own planet [tdr_source_name] in sector 
[tdr_source_sector_id]!";
$l_tdr_invalidssector    = "Starting sector does not seem to be valid!";
$l_tdr_invaliddport      = "Destination port does not seem to be valid!";
$l_tdr_invaliddplanet    = "Destination planet doesn't seem to be a valid 
planet!";
$l_tdr_invaliddsector    = "Destination sector does not seem to be valid!";
$l_tdr_moreturnsneeded   = "This trade route requires [tdr_dist_triptime] 
turns to complete. You only have [tdr_playerinfo_turns] left.";
$l_tdr_tdrhostdef        = "You can not use trade routes between sectors with 
hostile defences. You must defeat the defences first.";
$l_tdr_globalsetbuynothing= "Your global settings are set to buy 
nothing! You would only waste turns doing this route!";
$l_tdr_nosrcporttrade    = "Trading from source port is not allowed.";
$l_tdr_tradesrcportoutsider= "Trading at source port is not allowed for 
outsiders";
$l_tdr_nodestporttrade   = "Trading from destination port is not allowed.";
$l_tdr_tradedestportoutsider= "Trading at destination port is not allowed 
for outsiders";
$l_tdr_tdrres  		 = "Trade Route Results";
$l_tdr_bought  		 = "Bought";
$l_tdr_nothingtotrade    = "Nothing to trade";
$l_tdr_sold   	  	 = "Sold";
$l_tdr_ore    		 = "Ore";
$l_tdr_portisfull        = "Port is full";
$l_tdr_goods    	 = "goods";
$l_tdr_organics 	 = "organics";
$l_tdr_energy   	 = "energy";
$l_tdr_portisempty       = "Port is empty";
$l_tdr_loaded   	 = "Loaded";
$l_tdr_nothingtoload     = "Nothing to load";
$l_tdr_scooped  	 = "Scooped";
$l_tdr_dumped   	 = "Dumped";
$l_tdr_planetisovercrowded= "Planet is overcrowded";
$l_tdr_nothingtodump     = "Nothing to dump";
$l_tdr_onlyonewaytdr     = "Did nothing, traderoute was one way only";
$l_tdr_profit 		 = "Profit";
$l_tdr_cost   		 = "Cost";
$l_tdr_totalprofit       = "Total profit";
$l_tdr_totalcost         = "Total cost";
$l_tdr_credits  	 = "Credits";
$l_tdr_turnsused         = "Turns used";
$l_tdr_turnsleft         = "Turns left";
$l_tdr_engageagain       = "Click <A 
HREF=\"traderoute.php?engage=[tdr_engage]\">here</A> to do this trade route 
again.";

// IGB.php

$l_igb_title    = "Die Intergalaktische Bank";
$l_igb_malfunction      = "Dieser IGB terminal hat eine Fehlfunktion. Die Intergalaktische Bank entschuldig sich für jegliche Schwierigkeiten.";
$l_igb_quit     = "Quit";
$l_igb_login    = "Login";
$l_igb_welcometoigb     = "Willkommen zu diesem Intergalaktischen Bank Terminal";
$l_igb_accountholder    = "Kontoinhaber";
$l_igb_shipaccount      = "Schiffskonto";
$l_igb_igbaccount       = "IGB Konto";
$l_igb_operations       = "Aufträge";
$l_igb_withdraw = "Auszahlen";
$l_igb_deposit  = "Einzahlen";
$l_igb_transfer = "Transferieren";
$l_igb_back     = "Zurück";
$l_igb_logout   = "Logout";
$l_igb_withdrawfunds    = "Kapital Abheben";
$l_igb_fundsavailable   = "Kapital verfügbar";
$l_igb_selwithdrawamount        = "Bitte wähle die Höhe der Auszahlung";
$l_igb_depositfunds     = "Kapital einzahlen";
$l_igb_seldepositamount = "Bitte wähle die Höhe der Einzahlung";
$l_igb_transfertype     = "Art des Transfers ";
$l_igb_toanothership    = "Zu einem anderen Schiff";
$l_igb_shiptransfer     = "Zum eigenem Schiff";
$l_igb_fromplanet       = "Von einem Planten zu einen anderem";
$l_igb_unnamed  = "Unbenannt";
$l_igb_in       = "in";
$l_igb_none     = "Kein";
$l_igb_destination      = "Ziel";
$l_igb_planettransfer   = "Planeten Transfer";
$l_igb_sendyourself     = "Du kannst dir nich selber Geld schicken!";
$l_igb_unknowntargetship        = "Unbekanntes Zielschiff!";
$l_igb_min_turns        = "Spieler [igb_target_char_name] muss mindestens [igb_min_turns] Züge gespielt haben um Geld empfangen zu können.";
$l_igb_min_turns2       = "Du musst mindestens [igb_min_turns] Züge gespielt haben um Geld zu senden.";
$l_igb_mustwait = "Du hast schon einen transfer zu [igb_target_char_name] in den letzten [igb_trate] Minuten getätigt. Du musst [igb_difftime] Minuten warten bevor Du zu diesem spieler wieder Credits senden kannst.";
$l_igb_maxtransfer      = "Maximaler erlaubter transfer";
$l_igb_unlimited        = "Unbegrenzt";
$l_igb_maxtransferpercent       = "Maximum Transfer erlaubt ([igb_percent]% vom Nettowert)";
$l_igb_recipient        = "Empfänger";
$l_igb_seltransferamount        = "Bitte wähle die Höhe des Transfers";
$l_igb_transferrate     = "Die jetzige Rate des Transfers beträgt [igb_num_percent]% der totalen Geldmenge. Sie wird automatisch reduziert auf die Geldmenge die du transferierst.";
$l_igb_errplanetsrcanddest      = "Ein Planet kann nich gleichzeitig die Quelle und das Ziel sein.";
$l_igb_errunknownplanet = "DB Fehler! Unbekannter Planet!";
$l_igb_errnotyourplanet = "Du kannst kein Geld von/zu einem Planeten transferieren der dir nich gehört.";
$l_igb_srcplanet        = "Quelle -> Planet";
$l_igb_destplanet       = "Ziel -> Planet";
$l_igb_transferrate2     = "Die jetzige Rate des Transfers beträgt [igb_num_percent]% der totalen Geldmenge. Sie wird automatisch reduziert>auf die Geldmenge die du transferierst.";
$l_igb_errsendyourself  = "Du kannst dir nich selber Geld schicken!";
$l_igb_min_turns3        = "Spieler [igb_target_char_name] muss mindestens [igb_min_turns] Züge gespielt haben um Geld empfangen zu können.";
$l_igb_min_turns4       = "Du musst mindestens [igb_min_turns] Züge gespielt haben um Geld zu senden.";
$l_igb_mustwait2 = "Du hast schon einen transfer zu [igb_target_char_name] in den letzten [igb_trate] Minuten getätigt. Du musst [igb_difftime] Minuten warten bevor Du zu diesem spieler wieder Credits senden kannst.";
$l_igb_invalidtransferinput     = "Falsche Eingabe des Transfers.";
$l_igb_nozeroamount     = "Die Höhe des Tranfers darf nich Null sein.";
$l_igb_notenoughcredits = "Du hast nich genug Credits um diesen Auftrag auszuführen.";
$l_igb_amounttoogreat   = "Die Geldmenge die du eingegeben hast is höher als deine maximal erlaubte Mengen.";
$l_igb_transfersuccessful       = "Transfer erfolgreich";
$l_igb_creditsto        = "Credits wurden transferiert zu";
$l_igb_transferamount   = "Transferhöhe";
$l_igb_transferfee      = "Transferpreis";
$l_igb_amounttransferred        = "Geldmenge Transferiert";
$l_igb_notenoughcredits2        = "Es sind nich genug Credits auf dem Quellplaneten um diesen Transfer zu beenden.";
$l_igb_to       = "zu";
$l_igb_ctransferredfrom = "Credits wurden transferiert von";
$l_igb_invaliddepositinput      = "Falsche Eingabe der Einzahlung.";
$l_igb_nozeroamount2    = "Die Höhe der Einzahlung darf nich Null sein.";
$l_igb_operationsuccessful      = "Auftrag erfolgreich";
$l_igb_creditstoyou     = "Credits wurden zu deinem IGB Konto transferiert.";
$l_igb_accounts = "Konto";
$l_igb_invalidwithdrawinput     = "Falsche Eingabe der Auszahlung.";
$l_igb_nozeroamount3    = "Die Höhe der Auszahlung darf nich Null sein.";
$l_igb_creditstoyourship        = "Credits wurden zu deinem Schiffskonto transferiert.";
$l_igb_igberrreport     = "IGB Fehler-Bericht";
$l_igb_source   = "Quelle";

// combat.php3

$l_cmb_atleastoneturn   = "Du brauchst mindesten ein Zug um einen Planeten angreifen zu können.";
$l_cmb_shipenergybb     = "Schiffsenergie vor dem benutzen STrahlenwaffen";
$l_cmb_shipenergyab     = "Schiffsenergie nach dem benutzen STrahlenwaffen";
$l_cmb_shipenergyas     = "Schiffsenergie vor den Schilden";
$l_cmb_shiptorpsbtl     = "Schiffstopredos vor dem abfeuern der Torpedos";
$l_cmb_shiptorpsatl     = "Schiffstopredos nach dem abfeuern der Torpedos";
$l_cmb_planettorpdamage = "Planetentorpedoschaden";
$l_cmb_attackertorpdamage       = "Angreifertorpedoschaden";
$l_cmb_beams    = "Strahlen";
$l_cmb_fighters = "Fighter";
$l_cmb_shields  = "Schilde";
$l_cmb_torps    = "Torpedos";
$l_cmb_torpdamage       = "Torpedoschaden";
$l_cmb_armor    = "Panzerung";
$l_cmb_you      = "Du";
$l_cmb_planet   = "Planet";
$l_cmb_combatflow       = "Kampfstarke";
$l_cmb_defender = "Verteidiger";
$l_cmb_attackingplanet  = "Planeten im Sektor angreifenr";
$l_cmb_youfireyourbeams = "Du feuerst diene STrahlenwaffen ab";
$l_cmb_defenselost      = "Planeten Verteidigung verlor [cmb_planetfighters] Fighter durch deine Strahlenwaffen";
$l_cmb_defenselost2     = "Planeten Verteidigung verlor [cmb_attackerbeams]  Fighter, aber es kommen noch mehr!";
$l_cmb_planetarybeams   = "Planeten Strahlenwaffen zerstörten [cmb_temp] von deinen Figtern";
$l_cmb_planetarybeams   = "Planeten Strahlenwaffen zerstörten [cmb_planetbeams] von deinen Figtern";
$l_cmb_youdestroyedplanetshields        = "Deine Strahlenwaffen haben die Schilde des Planeten zerstört";
$l_cmb_beamsexhausted   = "Du zerstörtest [cmb_attackerbeams] die Schilde des Planeten bevor deinn Strahlenwaffen aufgebraucht waren";
$l_cmb_breachedyourshields      = "Planeten Strahlenwaffen haben deine Schilde durchbrochen";
$l_cmb_destroyedyourshields     = "Planeten Strahlenwaffen haben [cmb_planetbeams] von diene Schilden zerstört";
$l_cmb_breachedyourarmor        = "Planeten Strahlenwaffen haben deine Panzerung durchbrochenr";
$l_cmb_destroyedyourarmor       = "Planeten Strahlenwaffen haben [cmb_planetbeams] Punkte diener Pazerung zerstört";
$l_cmb_torpedoexchangephase     = "Torpedokampf Phase";
$l_cmb_nofightersleft   = "Deine Torpedos zerstörten [cmb_planetfighters] Fighter des Planeten, keine Fighter übrig";
$l_cmb_youdestroyfighters       = "Deine Torpedos zerstörten [cmb_attackertorpdamage] Fighter des Planeten";
$l_cmb_planettorpsdestroy       = "Planetem Torpedos zerstörten [cmb_temp] von deinen Fightern";
$l_cmb_planettorpsdestroy2      = "Planetem Torpedos zerstörten [cmb_planettorpdamage] von deinen Fightern";
$l_cmb_torpsbreachedyourarmor   = "Planetem Torpedos haben deien Panzerung durchbrochen";
$l_cmb_planettorpsdestroy3      = "Planetem Torpedos haben [cmb_planettorpdamage] Punkte deiner Panzerung zerstört";
$l_cmb_youdestroyedallfighters  = "Deine Torpedos zerstörten alles Fighter des Planeten";
$l_cmb_youdestroyplanetfighters = "Deine Torpedos zerstörten [cmb_attackertorpdamage] Fighter des Planeten";
$l_cmb_fightercombatphase       = "Fighterkampf Phase";
$l_cmb_youdestroyedallfighters2  = "Deien ighter haben alle Fighter des Planeten zerstört.";
$l_cmb_youdestroyplanetfighters2        = "Deien ighter haben [cmb_attackerfighters] Fighter des Planeten zerstört";
$l_cmb_allyourfightersdestroyed = "Alle deine Fighter wurden zerstört";
$l_cmb_fightertofighterlost     = "Du hast [cmb_planetfighters] Fighter Fighterkampf verloren";
$l_cmb_youbreachedplanetshields = "Deien Fighter haben die Schilde des Planeten durchbrochen";
$l_cmb_shieldsremainup  = "Deien Fighter haben [cmb_attackerfighters] Schilde des Planeten zerstört,aber sie erholen sich";
$l_cmb_fighterswarm     = "fighter des Planeten uschwärmen dein Schiff,deien Panzerung wurde durchbrochen";
$l_cmb_swarmandrepel    = "fighter des Planeten uschwärmen dein Schiff, aber dien Panzerung konnte sie abwehren";
$l_cmb_engshiptoshipcombat      = "Aktievie Schiffskamof.";
$l_cmb_shipdock = "Es sind [cmb_shipsonplanet] Schiffe am Raumhafen angedockt!";
$l_cmb_approachattackvector     = "kommt aus einer Angriffposition auf dich zu";
$l_cmb_noshipsdocked    = "Es sind KEINE Schiffe am Raumhafen angedockt!";
$l_cmb_yourshipdestroyed        = "Dein Schiff wurde zerstört!";
$l_cmb_escapepod        = "Glücklichwerweis hattest Du eine Rettungskapsel!";
$l_cmb_finalcombatstats = "Final Combat Stats";
$l_cmb_youlostfighters  = "Du hast [cmb_fighters_lost] von deinen insgesamt [cmb_playerinfo_ship_fighters] Fightern verloren.";
$l_cmb_youlostarmorpoints       = "Du hast [cmb_armor_lost] von deinen insgesamt [cmb_playerinfo_armour_pts] Panzerungspunkten verloren, du hast noch [cmb_attackerarmor] Punkte übrig.";
$l_cmb_energyused       = "Du hast [cmb_energy] Energie, von deiner [cmb_playerinfo_ship_energy] Energier verbraucht.";
$l_cmb_planetdefeated   = "Planet wurde geschlagen";
$l_cmb_citizenswanttodie        = "Die Einwohner des Planeten haben entschieden eher zu sterben anstatt Dich als einen Anführer wie Dich  zu akzeptieren. Sie benutzten ein Lserbphrer um einn Loch zum kern des Planeten zu bohren.Du hattest grade noch Zeit genug um Dich von dem Planeten in den Orbit zu retten bevor der Planet auf eine Ball geschmolzener Lava reduziert wurde.";
$l_cmb_youmaycapture    = "Du kannst <a href=planet.php3?planet_id=[cmb_planetinfo_planet_id]&command=capture>capture</a> den Planeten oder sie unverteidigt zurücklassen.";
$l_cmb_youmaycapture2   = "Du kannst <a href=planet.php3?planet_id=[cmb_planetinfo_planet_id]&command=capture>capture</a> den Planeten oder sie unverteidigt zurücklassen.";
$l_cmb_planetnotdefeated        = "Planet urde nicht geschlagen";
$l_cmb_planetstatistics = "Planeten statistic";
$l_cmb_fighterloststat  = "Fighters verloren: [cmb_fighters_lost] von [cmb_planetinfo_fighters] ([cmb_planetfighters] sind am Leben)";
$l_cmb_energyleft       = "Energy übrig";
$l_cmb_startingstats    = "Starte Status";
$l_cmb_statattackerbeams        = "Strahkenwaffen des Angreifers";
$l_cmb_statattackerfighters     = "Fighter des Angreifers";
$l_cmb_statattackershields      = "Schilde des Angreifers";
$l_cmb_statattackertorps        = "Toorpedos des Angreifers";
$l_cmb_statattackerarmor        = "Panzerung des Angreifersr";
$l_cmb_statattackertorpdamage   = "Torpedoschade des Angreifers";
$l_cmb_isattackingyou   = "greift Dich an";
$l_cmb_beamexchange     = "Strahlenwaffenbeschuss";
$l_cmb_beamsdestroy     = "Deine Strahlenwaffen zerstörten [cmb_lost] Fighter";
$l_cmb_beamsdestroy2    = "Deine Strahlenwaffen zerstörten [cmb_attackerbeams] Fighter, aber es kommen mehr";
$l_cmb_nobeamsareleft   = "Du haste keine Strahlenwaffen mehr um die hernahenden Figter zu zerstören!";
$l_cmb_beamshavenotarget        = "Deine Strahlenwaffen habe keine Fighter zu zerstören";
$l_cmb_fighterdestroyedbybeams  = "[cmb_targetinfo_ship_name] zerstörte [cmb_lost] von deinen Fightern mit Strahlenwaffen<BR>";
$l_cmb_beamsdestroystillhave    = "[cmb_targetinfo_ship_name] zerstörte [cmb_targetbeams] von deinen Fightern mit Strahlenwaffen, aber du hast immernoch [cmb_attackerfighters] übrig";
$l_cmb_fighterunhindered        = "Deine Fighter attakieren ungehindert, der Gegner hat keine Strahlenwaffen mehr.";
$l_cmb_youhavenofightersleft    = "Du haste keine Fighter mehr um zu attackieren";
$l_cmb_breachedsomeshields      = "Du hast [cmb_targetinfo_ship_name]'s Schilde  mit diene Strahlenwaffen durchbrochen";
$l_cmb_shieldsarehitbybeams     = "[cmb_targetinfo_ship_name]'s Schilde wurden getroffen von [cmb_attackerbeams] und beschädigt von diene Strahlenwaffen";
$l_cmb_nobeamslefttoattack      = "Du ahste keien Strahlenwaffen mehr übrig um [cmb_targetinfo_ship_name]'s Schilde zu attackieren";
$l_cmb_yourshieldsbreachedby    = "[cmb_targetinfo_ship_name]'s Strahlenwaffen haben deine SChild durchbrochen";
$l_cmb_yourshieldsarehit        = "[cmb_targetinfo_ship_name]'s Strahlenwaffen haben deine Schilde getroffen und [cmb_targetbeams] neschädigt.";
$l_cmb_hehasnobeamslefttoattack = "[cmb_targetinfo_ship_name] hat keine Strahelnwaffen mehr um deine Schilde zu attackieren";
$l_cmb_yourbeamsbreachedhim     = "Deien Strahlenwaffen haben [cmb_targetinfo_ship_name]'s Panzreung durchbrochen";
$l_cmb_yourbeamshavedonedamage  = "Deien Strahelnwaffen aheb  [cmb_attackerbeams] an [cmb_targetinfo_ship_name]'s Panzerung angerichtet";
$l_cmb_nobeamstoattackarmor     = "Du hate keien Strahlenwaffen mehr ürig um [cmb_targetinfo_ship_name]'s Panzerung zu attackieren";
$l_cmb_yourarmorbreachedbybeams = "Deine Panzerung wurde won [cmb_targetinfo_ship_name]'s Strahlenwaffen durchbrochen";
$l_cmb_yourarmorhitdamaged      = "Deine Panzerung wunrde von [cmb_targetbeams] damage by [cmb_targetinfo_ship_name]'s Strahlenwaffen getroffen";
$l_cmb_torpedoexchange  = "Torpedobeschuss";
$l_cmb_hehasnobeamslefttoattackyou      = "[cmb_targetinfo_ship_name] hat keien Strahlenwaffen mehr übrig um deine Panzerung zu attackieren";
$l_cmb_yourtorpsdestroy = "Deine Torpedos zerstörten [cmb_lost] von [cmb_targetinfo_ship_name]'s Fightern";
$l_cmb_yourtorpsdestroy2        = "Deine Torpedos zerstörten [cmb_attackertorpdamage] von [cmb_targetinfo_ship_name]'s Fightern";
$l_cmb_youhavenotorpsleft       = "Du hast keine Torpedos mehr übrig um [cmb_targetinfo_ship_name]'s Fighter zu attackieren.";
$l_cmb_hehasnofighterleft       = "[cmb_targetinfo_ship_name] hat keien Fighter mehr , die Du mit dienen Torpedos zerstören könntest";
$l_cmb_torpsdestroyyou  = "[cmb_targetinfo_ship_name]'s Torpedos zerstörten  [cmb_lost] von deinen Figtern";
$l_cmb_someonedestroyedfighters = "[cmb_targetinfo_ship_name] zerstörte [cmb_targettorpdmg] von deinen Figtern mit Torpedos";
$l_cmb_hehasnotorpsleftforyou   = "[cmb_targetinfo_ship_name] hat keien Torpedos mehr übrig um deine Fighter zu attackieren";
$l_cmb_youhavenofightersanymore = "Du haste keien Fighter mehr die von [cmb_targetinfo_ship_name]'s torpedos Zerstört werden könnten";
$l_cmb_youbreachedwithtorps     = "Du hast [cmb_targetinfo_ship_name]'s Panzerung mit deinen Torpedos durchbrochen";
$l_cmb_hisarmorishitbytorps     = "[cmb_targetinfo_ship_name]'s Panzerung nahm [cmb_attackertorpdamage] Schaden von deinen Torpedos";
$l_cmb_notorpslefttoattackarmor = "Du ahst ekien Torpedos mehr übrig um [cmb_targetinfo_ship_name]'s Panzerung zuattackieren";
$l_cmb_yourarmorbreachedbytorps = "Deien panerung wurde von [cmb_targetinfo_ship_name]'s Torpedos durchbrochen";
$l_cmb_yourarmorhitdmgtorps     = "Deine Panzerung nahm  [cmb_targettorpdmg] Schaden von [cmb_targetinfo_ship_name]'s Torpedos";
$l_cmb_hehasnotorpsforyourarmor = "[cmb_targetinfo_ship_name] hat keine Torpedos mehr übrig um deine Panzerung zu attackieren";
$l_cmb_fightersattackexchange   = "Fighterkampf";
$l_cmb_enemylostallfighters     = "[cmb_targetinfo_ship_name] verlor alle seine Fighter.";
$l_cmb_helostsomefighters       = "[cmb_targetinfo_ship_name] verlor [cmb_attackerfighters] Fighter.";
$l_cmb_youlostallfighters       = "Du has alle deien Fighter verloren.";
$l_cmb_youalsolostsomefighters  = "Du hast [cmb_targetfighters] Fighter verloren.";
$l_cmb_hehasnofightersleftattack        = "[cmb_targetinfo_ship_name] hat keien Fighter mehr um deien FIght zu attackieren";
$l_cmb_younofightersattackleft  = "Du hast keien Fighter mehr übrig um [cmb_targetinfo_ship_name]'s Fighter zu attackieren";
$l_cmb_youbreachedarmorwithfighters     = "Du hast [cmb_targetinfo_ship_name]'s Panzerung mit deine Fightern durchbrochen";
$l_cmb_youhitarmordmgfighters   = "Du hast an [cmb_targetinfo_ship_name]'s Panzerung [cmb_attackerfighters] Schaden mit deinen Fightern angerichtet";
$l_cmb_youhavenofighterstoarmor = "Du hast keien Fighter mehr um [cmb_targetinfo_ship_name]'s Panzerung zu attackieren";
$l_cmb_hasbreachedarmorfighters = "[cmb_targetinfo_ship_name] hat deine Panzerung mit Fightern durchbrichen";
$l_cmb_yourarmorishitfordmgby   = "Deien panzerung wurde von [cmb_targetfighters] getroffen un beschädigt cvon [cmb_targetinfo_ship_name]'s Fighters";
$l_cmb_nofightersleftheforyourarmor     = "[cmb_targetinfo_ship_name] hat keine Fighter mehr umd diene Panzerung zu attakieren";
$l_cmb_hehasbeendestroyed       = "[cmb_targetinfo_ship_name] wurde zerstört";
$l_cmb_escapepodlaunched        = "Eine Rettungskapsel wurde aktiviert!";
$l_cmb_yousalvaged      = "Du hast  [cmb_salv_ore] Einheiten Erz, [cmb_salv_organics] Einheiten Lebensmittels, [cmb_salv_goods] Einheiten Waren geborgen, und du erbeutest [cmb_salvage_rate]% der Schiffs [cmb_salvage] Credits .<BR>Du erhälst [cmb_number_rating_change] Punkte.";
$l_cmb_youdidntdestroyhim       = "Du zerstörtest [cmb_targetinfo_ship_name] nich";
$l_cmb_shiptoshipcombatstats    = "Schiffskampfstatus";

// check_mines.php3

$l_chm_youhitsomemines  = "You hit [chm_roll] mines!";
$l_chm_hehitminesinsector       = "[chm_playerinfo_character_name] hit [chm_roll] mines in sector [chm_sector].";
$l_chm_youlostminedeflectors    = "You lost [chm_roll] mine deflectors.";
$l_chm_youlostallminedeflectors = "You lost all your mine deflectors.";
$l_chm_youhadnominedeflectors  = "You had no mine deflectors.";
$l_chm_yourshieldshitforminesdmg        = "Your shields are hit for [chm_mines_left] damage.";
$l_chm_yourshieldsaredown       = "Your shields are down!";
$l_chm_youlostallyourshields    = "You lost all your shields!";
$l_chm_yourarmorhitforminesdmg  = "Your armour is hit for [chm_mines_left] damage.";
$l_chm_yourhullisbreached       = "Your hull is breached!";
$l_chm_hewasdestroyedbyyourmines        = "[chm_playerinfo_character_name] was destroyed by your mines in sector [chm_sector].";
$l_chm_yourshiphasbeendestroyed = "Your ship has been destroyed!";
$l_chm_luckescapepod    = "Luckily you have an escape pod!";

// check_fighters.php3

$l_chf_youretreatback   = "You retreat back to your previous location";
$l_chf_notenoughcreditstoll     = "You do not have enough credits to pay the toll.";
$l_chf_movefailed       = "Move failed.";
$l_chf_youpaidsometoll  = "You paid [chf_tollstring] credits for the toll.";
$l_chf_thefightersdetectyou     = "The fighters detect you!";
$l_chf_therearetotalfightersindest      = "There are [chf_total_sector_fighters] fighters in your destination sector.";
$l_chf_creditsdemanded  = "They demand [chf_number_fighterstoll] credits to enter this sector.";
$l_chf_youcanretreat    = "You can <BR><INPUT TYPE=RADIO NAME=response VALUE=retreat><B>Retreat</B> - Will cost an extra turn.<BR></INPUT>";
$l_chf_inputpay = "<INPUT TYPE=RADIO NAME=response CHECKED VALUE=pay><B>Pay</B> the toll and enter without harm from the fighters.<BR></INPUT>";
$l_chf_inputfight       = "<INPUT TYPE=RADIO NAME=response CHECKED VALUE=fight><B>Fight</B> - you must defeat all the fighters to enter the sector.<BR></INPUT>";
$l_chf_inputcloak       = "<INPUT TYPE=RADIO NAME=response CHECKED VALUE=sneak><B>Cloak</B> - Use your cloaking device and try to avoid the fighters.<BR></INPUT>";
$l_chf_go       = "Go";

// mines.php

$l_mines_title			="Deploy Sector Mines & Fighters";
$l_mines_noturn		 	="You need at least one turn to deploy sector defences.";
$l_mines_nopermit		="Deploying Mines and Fighters in this sector is not permitted.";
$l_mines_nodeploy		="Can not deploy here. Another Ship or Alliance has mines or fighters in this sector.";
$l_mines_info1			="You are presently in sector [sector]. There are [mines] mines and [fighters] fighters here.";
$l_mines_info2			="You have [mines] mines and [fighters] fighters available to deploy";
$l_mines_deploy			="Deploy";
$l_mines_deployed		="Deployed";
$l_mines_att			="Attack";
$l_mines_toll			="Toll";
$l_mines_notorps		="You do not have enough torpedos.";
$l_mines_nofighters		="You do not have enough fighters";
$l_mines_dmines			="Deployed [mines] mines.";
$l_mines_dfighter		="Deployed [fighters] fighters in [mode] mode.";

//alliance-planets.php

$l_teamplanet_title		="Alliance Planet Report";
$l_teamplanet_notally		="You aren't in an alliance.";
$l_teamplanet_personal		="Show personal planets";
$l_teamplanet_noplanet		="Your alliance has no planets";

$l_feedback_title		="Send Feedback";
$l_feedback_to			="TO:";
$l_feedback_from		="FROM:";
$l_feedback_topi		="SUBJECT:";
$l_feedback_feedback		="Feedback";
$l_feedback_message		="MESSAGE:";
$l_feedback_messent		="Message Sent";
$l_feedback_subj		="WTW Feedback";
$l_feedback_info		="Please send feedback in english only"; // gameadmins put all your languages here

// corp.php
$l_corpm_title			="Corporation Menu";
$l_corpm_tocorp			="Planet is now a Corporate Planet!";
$l_corpm_topersonal		="Planet is now a Personal Planet!";
$l_corpm_exploit		="You intercept a garbled borg message on your scanner... you should probably start worrying...";


// login.php login2.php
$l_login_title			="Login"; 
$l_login_email			="E-mail Address:";
$l_login_pw			="Password:";
$l_login_chooseres		="Unable to determine your screen resolution. Please choose the best fit:";
$l_login_newp			= "If you are a new player, click <A HREF=\"new.php3\">here</A>.";
$l_login_prbs			= "Problems?";
$l_login_emailus		= "E-mail us";
$l_login_sclosed		= "Server Closed";
$l_login_closed_message		="Server closed until further notice.";
$l_login_title2			="Login Phase Two"; 
$l_login_banned			="<b>You have been banned from this game by the administrator. You are no longer welcome to play on this server. Next time, behave.</b>";
$l_login_died			="Your ship was destroyed, but your escape pod saved you and your crew.  Click <A HREF=main.php3>here</A> to continue with a new ship.";
$l_login_newbie			="Due to the seriousness of this crime and the vicious attack against you, the Federation has graciously decided to provide a free of charge cloning from your remains.  Sadly, even in this day and age, new clones can not own property, aside from the basics to make a living.  You will be provided with a basic ship and a few credits to get you started.  Hopefully your next life will be better.";
$l_login_newlife		="Click <A HREF=main.php3>here</A> to continue in a new life.";
$l_login_looser			="You had no escape pod, and due to your modest success in this life, the Federation declines to clone you.  Your remains should eventually fall into a gravity well, hopefully to be used to create life elsewhere... several billion years from now.<BR><BR> Better luck next game...";
$l_login_4gotpw1		= "The password you entered is incorrect.<BR><BR>  If you have forgotten your password, ";
$l_login_4gotpw2		= "to have it e-mailed to you.<BR><BR>  Otherwise,";
$l_login_4gotpw3		= "to try again.  Attempt logged with IP address of";
$l_login_noone			= "No Such Player! - Create a new player <A HREF=new.php3>here</A>.";

// new.php new2.php
$l_new_title			= "Create New Player"; 
$l_new_title2			= "Create New Player Phase Two"; 
$l_new_shipname			= "Ship Name";
$l_new_pname			= "Player Character Name";
$l_new_info			= "We promise not to give out (or sell) your e-mail address to anyone.  It is required though, to send you your server generated password..";
$l_new_closed_message		="Game closed for tournament play";
$l_new_blank			="E-mail, ship name, and character name may not be blank.";
$l_new_inuse			="E-mail address is already in use.";
$l_new_4gotpw1			="If you have forgotten your password,";
$l_new_4gotpw2			="to have it e-mailed to you.";
$l_new_inusechar		="Character name $character, is already in use.";
$l_new_inuseship		="Ship name $shipname, is already in use.";
$l_new_pwsent			="Password has been sent to $username.";
$l_new_login			="to go to the login screen.";
$l_new_err			="Please go back or <a href=new.php3>click here</a> and try again.";
$l_new_topic			="Traders Password";
$l_new_message			="Greetings,\n\nSomeone from the IP address $ip requested that your password for Traders be sent to you.\n\nYour password is: [pass]\n\nThank you\n\nThe Traders web team.";

// logout.php

$l_logout_score			="You current score is";
$l_logout_text			="[name] is now logged out.  Click <A HREF=index.php3>here</A> to return to game.";

// mail.php

$l_mail_title			="Mail Password"; 
$l_mail_noplayer		="No Such Player! - Create a new player <a href=new.php3>here</a>.";
$l_mail_sent			="Password has been sent to";
$l_mail_topic			="$game_name Password";
$l_mail_message			="Greetings,\n\nSomeone from the IP address $ip requested that your password for $game_name be sent to you.\n\nYour password is: [pass]\n\nThank you\n\nThe $game_name web team.";
?>


