<?php

//general

$l_yes 			 = "Ja";
$l_no			 = "Nein";
$l_here			 = "hier";
$l_submit		 = "Best&auml;tigen";
$l_reset		 = "L&ouml;schen";
$l_all			 = "alle";

$l_ore			 = "Erz";
$l_organics		 = "Lebensmittel";
$l_goods		 = "G&uuml;ter";
$l_energy		 = "Energie";
$l_colonists		 = "Kolonisten";
$l_credits 		 = "Credits";
$l_units		 = "Einheiten ";
$l_special		 = "Spezial";

$l_cargo		 = "Fracht";
$l_fighters		 = "Fighter ";
$l_mines		 = "Minen ";
$l_torps		 = "Torpedos";

$l_none			 = "Keine";
$l_unnamed		 = "Unbenannt";
$l_name			 = "Name";
$l_unowned		 = "Unbesetzt";
$l_unknown		 = "Unbekannt";
$l_clickme 		 = "klicke hier";
$l_player  		 = "Spieler";
$l_ship			 = "Schiff";
$l_ships		 = "Schiffe";
$l_set			 = "setze";
$l_realspace		 = "Raumflug";
$l_armourpts		 = "Panzerungs Punkte";
$l_links		 = "Warp Tore";

// main.php

$l_main_title 		 = "Haupt Men&uuml;";
$l_main_warpto 		 = "Springe nach";
$l_main_other 		 = "Andere";

$l_traderoutes		 = "Handelsroute";
$l_trade_control	 = "Bearbeiten";

$l_youhave 		 = "Du hast ";
$l_turns_used		 = "Züge benutzt: ";
$l_turns_have		 = "Züge verfügbar: ";
$l_score		 = "Punkte: ";
$l_sector		 = "Sektor";
$l_help			 = "Hilfe";
$l_faq		         = "FAQ";
$l_feedback		 = "Feedback";
$l_forums		 = "Forum";
$l_logout		 = "Abmelden";

$l_commands		 = "Befehle";
$l_command_no		 = "Befehl nicht verfügbar.";
$l_devices		 = "Schiff";
$l_planets		 = "Planeten";
$l_log			 = "Logbuch";
$l_sector_def		 = "Sektor Verteidigung";
$l_defense		 = "Verteidigung";
$l_read_msg		 = "Lese Messis";
$l_send_msg		 = "Sende Messis";
$l_rankings		 = "R&auml;nge";
$l_teams		 = "Allianzen";
$l_ohno			 = "Selbstzerstörung";
$l_options		 = "Optionen";
$l_navcomp		 = "Navigation";

$l_incompletemove 	 = "Du hast Deinen vorherigen Zug nicht vollendet.";
$l_clicktocontinue	 = "Klicke hier um fortzufahren";
$l_toplanetmenu   	 = "um zum Planeten Men&uuml; zu gehen.";
$l_nonexistant_pl	 = "Auf einen nicht vorhandenen Planeten???";
$l_abord		 = ", an Bord der ";
$l_messages_wait	 = " neue Nachricht/en.";

$l_no_warplink		 = "Keine Warptore";
$l_scan			 = "Scan";
$l_fullscan		 = "voller Scan";

$l_port			 = "Hafen";
$l_tradingport		 = "Handelshafen";
$l_planet_in_sec	 = "Planeten in Sektor ";
$l_ships_in_sec		 = "Schiffe im Sektor ";
$l_sector_0		 = "Es gibt soviele Schiffe in Sol (Sektor 0), daß Deine Scanner keine Schiffe isolieren können!";

// report.php

$l_report_title		 = "Schiffs Report";

$l_level		 = "Level";

$l_ship_levels		 = "Schiff Levels";
$l_hull			 = "H&uuml;lle";
$l_engines		 = "Triebwerke";
$l_power		 = "Aggregate";
$l_computer		 = "Computer";
$l_sensors		 = "Sensoren";
$l_armour		 = "Panzerung";
$l_shields		 = "Schilde";
$l_beams		 = "Laserwaffen";
$l_torp_launch	         = "Torpedo-Phalanxen";
$l_cloak		 = "Tarnung";
$l_holds		 = "Frachtraum";
$l_deflect		 = "Minen Deflektoren";
$l_ewd			 = "Notfall Warp Ger&auml;t";


$l_arm_weap		 = "Panzerung & Waffen";
$l_beacons		 = "Raumsignal";
$l_warpedit		 = "Warptore";
$l_genesis		 = "Genesis Torpedo";
$l_escape_pod		 = "Rettungskapsel";
$l_fuel_scoop		 = "Sonnensegel";

// device.php

$l_device_title		 = "Schiffs Komponenten";

$l_device_expl		 = "Dein Schiff beeinhaltet folgende Komponenten (klicke auf die Komponente, die Du benutzen möchtest):";
$l_device		 = "Komponente";
$l_qty			 = "Menge";
$l_usage		 = "Benutze";
$l_manual		 = "Manuell";	
$l_automatic		 = "Automatisch";

// port.php port2.php

$l_trade		 = "Handel";
$l_title_port		 = "Handel im Raumhafen";
$l_title_trade		 = "Waren Handel";
$l_sector_war		 = "Kriegsembargo";
$l_war_info		 = "In diesem Sektor ist Krieg ausgebrochen. Auf Grund der Feindlichen Einheiten, kannst Du den Hafen nicht ereichen.";
$l_no_trade		 = "Handel verboten";
$l_no_trade_out		 = "Handeln in diesem Sektor ist für Aussenseiter nicht gestattet";
$l_no_trade_info	 = "Handeln in diesem Hafen ist nicht erlaubt";
$l_buying		 = "Ankauf";
$l_selling		 = "Verkauf";
$l_commodity		 = "Ware";
$l_amount		 = "Betrag";
$l_price		 = "Preis";
$l_buy			 = "Kaufen";
$l_sell			 = "Verkaufen";
$l_trade_st_info	 = "Du hast [free_holds] freien Frachtraum, Du hast noch Kapazität für [free_power] Energie Einheiten, und besitzt [credits] Credits.";
$l_special_port		 = "Spezial Hafen";
$l_no_credits		 = "Nicht gen&uuml;gend Credits";
$l_creds_to_spend	 = "Du hast [credits] Credits zum ausgeben.";
$l_cost			 = "Kosten";
$l_avail		 = "Verf&uuml;gbar";
$l_profit		 = "Profit";
$l_current		 = "momentan";
$l_current_qty		 = "derzeitige Menge";
$l_max			 = "Max";
$l_ifyouneedmore	 = "Wenn Du mehr benötigst, kannst Du von hier aus einen Zugang erstellen [igb] ";
$l_ifyouneedplan	 = "Zugang zum Planeten";
$l_igb_term		 = "IG Bank Terminal";
$l_upgrade		 = "Aufwerten?";
$l_unlimited		 = "Unbegrenzt";
$l_full			 = "Voll";
$l_equipped		 = "Eingebaut";
$l_n_a			 = "k/a";
$l_item			 = "Posten";
$l_totalcost		 = "Gesamtkosten";
$l_would_dump	         = "Wenn Du alle Deine Kolonisten abladen willst, klicke ";
$l_noport		 = "Hier ist kein Handelshafen";
$l_trade_turnneed	 = "Um in einem Hafen oder auf einem Planeten handeln zu können, benötigst Du einen Zug.";
$l_returnto_port         = " Klicke <A HREF=port.php>hier</A> um zum Handels Menue zurückzukommen.";
$l_notenough_cargo	 = "Du hast nicht genügend Platz für die Waren die du kaufen willst.";
$l_notenough_power	 = "Du hast nicht genügend Energie-Kapazität, um den Handel durchzuf&uuml;hren.";
$l_notenough_credits	 = "Du hast nicht genügend Credits um den Transfer abzuschliessen";
$l_notenough_turns	 = "Du hast nicht genügend Z&uuml;ge um den Transfer durchzuf&uuml;hren.";
$l_notenough_ore	 = "Du hast nicht genügend Erz um den Transfer durchzuf&uuml;hren.";
$l_notenough_goods	 = "Du hast nicht genügend G&uuml;ter um den Transfer durchzuf&uuml;hren.";
$l_notenough_energy	 = "Du hast nicht genügend Energie um den Transfer durchzuf&uuml;hren";
$l_notenough_organics	 = "Du hast nicht genügend Lebensmittel um den Transfer durchzuf&uuml;hren";
$l_exceed_organics	 = "Anzahl der Lebensmittel überschreitet Angebot/Nachfrage.  ";
$l_exceed_ore            = "Anzahl an Erz überschreitet Angebot/Nachfrage.  ";
$l_exceed_energy         = "Anzahl an Energy überschreitet Angebot/Nachfrage.  ";
$l_exceed_goods          = "Anzahl der Güter überschreitet Angebot/Nachfrage.  ";
$l_trade_result		 = "Ergebnis dieses Handels";
$l_traded_ore		 = "Gehandeltes Erz";
$l_traded_goods		 = "Gehandelte G&uuml;ter";
$l_traded_organics	 = "Gehandelte Lebensmittel";
$l_traded_energy	 = "Gehandelte Energie";
$l_trade_complete	 = "Handel beendet";
$l_trade_upgraded 	 = "aufgerüstet";
$l_trade_added 	 	 = "hinzugefügt";
$l_trade_installed 	 = "installiert";


// planet.php planet2.php planet3.php
$l_planet_title		 = "Planeten Men&uuml;";
$l_planet_none		 = "Du bist nicht im selben Sektor wie der Planet, deshalb kannst Du nicht mit ihm interagieren.";
$l_planet_capture1	 = "besetzen"; // thats the link's text
$l_planet_capture2	 = "Du kannst diesen Planeten [capture], oder ihn unbesetzt zurücklassen.";
$l_planet_unowned	 = "Dieser Planet ist unbesetzt";
$l_planet_unnamed        = "Willkommen auf [name]'s namenlosen Planeten.";
$l_planet_named		 = "Willkommen auf dem Planeten [planetname], der von [name] besetzt wurde.";
$l_planet_onsurface	 = "Du befindest Dich nun auf der Oberfl&auml;che des Planeten.";
$l_planet_orbit 	 = "Du befindest Dich nun im Orbit des Planetens.";
$l_planet_leave_link     = "Verlasse";
$l_planet_leave          = "[leave] Planet";
$l_planet_name_link 	 = "Benenne";
$l_planet_name2 	 = "[name] den Planeten";
$l_planet_land_link      = "Lande";
$l_planet_land           = "[land] auf dem Planeten";
$l_planet_logout	 = "Du kannst Dich im Schutze des Planeten <a href=logout.php>ausloggen</a>.";
$l_planet_selling	 = "Der Planet verkauft nun seine Waren.";
$l_planet_not_selling    = "Der Planet verkauft nun seine Waren nicht mehr.";
$l_planet_transfer_link	 = "Transferiere";
$l_planet_transfer	 = "[transfer] Waren/Ressourcen/Kolonisten zum/vom Planeten";
$l_planet_hasbase	 = "Du hast eine Basis auf dem Planeten";

$l_planet_perc		 = "Produktions Verteilung";
$l_planet_interest	 = "* Die Geld Produktion ist abhängig von der Produktion der anderen Waren. Desto niedriger die Gesamtproduktion aller Waren (prozentual) ist, desto höher ist die Geld-Produktion";
$l_planet_update	 = "Aktualisieren";
$l_planet_tsell_link	 = "Verkaufs";
$l_planet_tsell		 = "&Auml;ndere das Verkaufsverhalten [selling] des Planeten";
$l_planet_bbase_link	 = "eine Basis";
$l_planet_bbase		 = "Mit genügen Waren und Credits, kanst Du [build] bauen als Planetenverteidung aufbauen.";
$l_planet_bbuild	 = "Basis gebaut";
$l_planet_mcorp_linkC	 = "verbündetem Planeten";
$l_planet_mcorp_linkP	 = "persönlichem Planeten";
$l_planet_mcorp		 = "Du kannst diesen Planeten zu einem [planet] machen.";
$l_planet_buy_link	 = "Kaufe";
$l_planet_buy		 = "[buy] Waren von dem Planeten";
$l_planet_att_link	 = "Attackiere";
$l_planet_att		 = "[attack] den Planeten";
$l_planet_att_sure	 = "Bist Du SICHER...";
$l_planet_scn_link	 = "Scanne";
$l_planet_scn		 = "[scan] den Planet";
$l_planet_nowsell        = "Der Planet verkauft nun seine Waren.";
$l_planet_nownosell      = "Der Planet verkauft seine Waren nun nicht mehr.";
$l_planet_iname		 = "Gib einen Namen für den Planeten ein";
$l_planet_cname		 = "Der Planet heisst nun ";
$l_planet_landed	 = "Du bist auf der Planetenoberfl&auml;che gelandet.";
$l_planet_left		 = "Du bist nicht länger auf der Planetenoberfl&auml;che.";
$l_planet_cinfo		 = "Du hast Raum für [cargo] zus&auml;tzliche Fracht.  Du hast Kapazit&auml;t für [energy] Einheiten zusätzlicher Energie.";
$l_planet_toplanet	 = "Zum Planeten?";
$l_planet_baseinfo	 = "Um eine Basis auf den Planeten bauen zu können, brauchst Du $base_credits Credits, $base_ore Erz, $base_organics Lebensmittel, und $base_goods Güter auf dem Planeten .";
$l_planet_p_under        = "Du kannst das Produktionslevel nicht unter Null setzen.";
$l_planet_p_over	 = "Du kannst nicht mehr als insgesamt 100% produzieren.";
$l_planet_p_changed	 = "Produktionsverteilung ge&auml;ndert.";
$l_plant_scn_turn	 = "Du benötigst einen Zug, um den Planeten zu scannen.";
$l_planet_noscan	 = "Die Sensoren konnten den Planeten nicht Scannen, sie wurden gest&ouml;rt.";
$l_planet_logscanA	 = "[name] hat vergebens versucht, einen Deiner Planeten im Sektor [sector] zu scannen.";
$l_planet_logscanB	 = "Einer von deinem Planten in Sektor [sector] wurde von [name] gescannt.";
$l_planet_scn_report	 = "Scan Resultate von [name], besetzt von:  [owner]";
$l_base	  		 = "Basis";
$l_planet_ison		 = "ist auf diesem Planeten.";
$l_planet_captured	 = "Planet erobert";
$l_planet_notdef	 = "Planet nicht besiegt";
$l_planet_caplog	 = "Dein Planet '[planetname]' in Sektor [sector] wurde von [name] erobert.";
$l_planet_noone		 = "Niemand";

$l_planet2_title	 = "Planetarer Transfer";
$l_planet2_noturn	 = "Du benötigst einen Zug um den planetaren Transfer durchzufüren.";
$l_planet2_noten 	 = "Du hast nicht genug ";
$l_planet2_fortr	 = "um den Transfer durchzufüren.";
$l_planet2_settr	 = "Setze die Transfer-Menge auf ";
$l_planet2_losup	 = "Der Planet konnte insgesammt nur soviel liefern: ";
$l_planet2_notowner	 = "Du besitzt diesen Planeten nicht.";
$l_planet2_compl	 = "Transfer komplett.";
$l_planet2_power	 = "Energie Kapazität";
$l_planet2_comp 	 = "Computer Kapazizät";
$l_planet2_laun 	 = "Torpedo-Phalanx Kapazizät";
$l_planet2_nocorptransfer = "Du kannst keine Credits zu oder von einem verbündeten Planeten transferieren.";

$l_planet3_title	 = "Handel mit Planet";

// planet-report.php

$l_pr_title		 = "Planet Report";
$l_pr_teamlink		 = "Zeige allierte Planeten";
$l_pr_noplanet		 = "Du hast noch keinen Planeten besetzt.";
$l_pr_clicktosort	 = "Klicke auf die Tabellenköpfe um zu sortieren.";
$l_pr_totals		 = "Insgesamt";

// rsmove.php
$l_rs_title 		= "Raumflug";
$l_rs_whichsector       = "Welchen Sektor möchtest Du per Raumflug ereichen?";
$l_rs_insector		= "Du bist derzeit in Sektor [sector] - und die Sektoren reichen von 0 bis [sector_max].";
$l_rs_submit		= "Berechnen";
$l_rs_movetime		= "Mit Deinen Triebwerken, benötigst Du [triptime] Z&uuml;ge um dort hinzufliegen.";
$l_rs_energy		= "Deine Sonnensegel würden [energy] Einheiten Energie aufsammeln";
$l_rs_noturns		= "Du hast nicht genug Z&uuml;ge &uuml;brig und kannst nicht aufbrechen.";
$l_rs_engage_link	= "Starte";
$l_rs_engage		= "Du hast [turns] Z&uuml;ge. [engage] Triebwerke?";

$l_rs_invalid		= "Ung&uuml;ltiges Ziel";
$l_rs_ready 		= "Du bist nun im Sektor [sector]. Du hast [triptime] Z&uuml;ge, und [energy] Energie.";

// navcomp.php	

$l_nav_title		 = "Navigations Computer";
$l_nav_nocomp		 = "Navigations Computer ist nicht verfügbar";
$l_nav_query		 = "Gib den Sektor ein, zu dem Du einen Weg benötigst: ";
$l_nav_pathfnd		 = "Weg gefunden";
$l_nav_answ1		 = "Es wird Dich";
$l_nav_answ2		 = "Züge kosten, um in den Sektor zu gelangen.";
$l_nav_proper		 = "Deine Computertechnologie ist zu primitiv, um eine Weg zu berechnen.";


// attack.php

$l_att_title		 = "Attackiere Schiff";
$l_att_notarg		 = "Ziel nicht in diesem Sektor.";
$l_att_noturn		 = "Du ben&ouml;tigst einen Zug um anzugreifen.";
$l_att_noatt		 = "Es ist verboten, jemanden in diesem Sektor anzugreifen.";
$l_att_flee		 = "Ziel fl&uuml;chtet vor Dir";
$l_att_ewd		 = "Das Ziel benutzt ein Notfall Warp Ger&auml;t, als es angegriffen wurde";
$l_att_att		 = "Angriff ";
$l_att_beams		 = "Laserwaffen Terffer:";
$l_att_torps		 = "Torpedo Treffer:";
$l_att_fighters		 = "Fighter Angriff:";
$l_att_lost		 = "verloren";
$l_att_ylost		 = "Du verlierst";
$l_att_sdown		 = "Schilde sind runter!";
$l_att_ydown		 = "Deine Schilde sind runter!";
$l_att_shits		 = "'s Schilde erhielten ";
$l_att_yhits		 = "Deine Schilde erhielten ";
$l_att_dmg		 = " Punkte Schaden";
$l_att_sarm		 = " 's Panzerung ist durchbrochen!";
$l_att_yarm		 = "Deine Panzerung ist durchbrochen";
$l_att_ashit		 = "'s Panzerung erhielt ";
$l_att_ayhit		 = "Deine Panzerung erhielt ";
$l_att_lostf		 = "verlor alle Fighter.";
$l_att_ylostf		 = "Du verlierst alle Fighter.";
$l_att_sdest		 = "s Schiff wurde zerstört.";
$l_att_espod		 = "Eine Rettungskapsel wurde gestartet!";
$l_att_ysalv		 = "Du erbeutest [salv_ore] Erz Einheiten, [salv_organics] Lebensmittel Einheiten, [salv_goods] Güter, und erhälst [ship_salvage_rate]% von dem Schiff, insgesamt [ship_salvage] Credits.<BR>Deine Punktzahl verändert sich um [rating_change] Punkte.";
$l_att_andused		 = "und benutztest";
$l_att_stilship		 = "Du hast [name]'s Schiff nicht zertört.";
$l_att_atyou		 = "greifen Dich an";
$l_att_and		 = "und";
$l_att_yshiplost	 = "Dein Schiff wurde zerstört!";
$l_att_salv		 = "[name] erbeutete [salv_ore] Erz Einheiten, [salv_organics] Lebensmittel Einheiten, [salv_goods] Güter, und erhielt [ship_salvage_rate]% des Schiffs, insgesamt [ship_salvage] Credits.";

// warpedit 1-3.php

$l_warp_title		 = "Benutze Warptor Kits";
$l_warp_turn		 = "Um den Warptore zu bauen oder zu zerst&ouml;ren, ben&ouml;tigst Du einen Zug.";
$l_warp_none		 = "Du besitzt keine Warptor Kits.";
$l_warp_forbid		 = "Es ist verboten, ein Warptor Kits in diesem Sektor zu benutzen.";
$l_warp_nolink		 = "Es gibt keine Warptore aus diesem Sektor heraus.";
$l_warp_linkto		 = "Warptore führen aus diesem Sektor nach";
$l_warp_query		 = "Zu welchem Sektor möchtest Du einen Warptor bauen?";
$l_warp_oneway		 = "Nur eine Richtung?";
$l_warp_dest		 = "Alternativ dazu, kannst Du auch ein Warptor zerst&ouml;ren.";
$l_warp_destquery	 = "In welchem Sektor möchtest Du ein Warptor zerst&ouml;ren?";
$l_warp_bothway		 = "Beide Richtungen";
$l_warp_nosector	 = "Sektor existiert nicht.";
$l_warp_twoFehler	 = "Erstellen eines zwei-Wege Tors zum Sektor [target_sector] ist verboten.";
$l_warp_sectex		 = "Du kannst kein Warptor erstellen, da man maximal $link_max Tore pro Sektor erstellen kann.";
$l_warp_linked		 = "Der Ziel Sektor ([target_sector]) verfügt bereits über ein Warptor von diesem Sektor.";
$l_warp_unlinked	 = "Der Ziel Sektor ([target_sector]) verfügt nicht über ein Warptor von diesem Sektor.";
$l_warp_coneway	         = "Ein Warptor (eine Richtung) wurde erstellt von";
$l_warp_ctwoway		 = "Warptor wurde erstellt von und nach ";
$l_warp_forbidtwo	 = "Zerst&ouml;ren eines Warptors von und nach Sektor [target_sector] ist nicht möglich.";
$l_warp_removed		 = "Warptor zerst&ouml;rt zu Sektor ";
$l_warp_removedtwo	 = "Warptor zerst&ouml;rt von und nach Sektor";
$l_warp_cantsame 	 = "Du kannst kein Tor bauen wenn Quelle und Ziel gleich sind.";

// genesis.php

$l_gns_title		 = "Genesis Torpedo benutzen";
$l_gns_turn		 = "Du ben&ouml;tigst einen Zug, um den Genesis Torpedo abzufeuern.";
$l_gns_onplanet		 = "Du kannst dieses Ger&auml;t nicht auf der Planetenoberfl&auml;che benutzen.";
$l_gns_full		 = "Dieses Sonnensystem ist bereits voll!";
$l_gns_planetex		 = "Es gibt bereits einen Planeten in diesem Sektor.";
$l_gns_nogenesis	 = "Du besitzt keine Genesis Torpedos.";
$l_gns_forbid		 = "In diesem Sektor ist es verboten, einen Planeten zu erstellen.";
$l_gns_bforbid		 = "In diesem Sektor ist es unmöglich, einen Planeten zu erstellen. Die Planetenbais stört Dein Genesis Ger&auml;t.";
$l_gns_pcreate		 = "Planet wurde erschaffen.";

// ship.php

$l_ship_title		 = "Schiffs Kommando";
$l_ship_the		 = "Die";
$l_ship_nolonger	 = "ist nicht l&auml;nger im Sektor";
$l_ship_youc		 = "Du siehst die";
$l_ship_owned		 = "geführt von";
$l_ship_perform		 = "Du kannst folgende Aktionen durchführen:";

// selfdestruct.php

$l_die_title		 = "Selbst Zerstörung";
$l_die_rusure		 = "Bist Du Sicher, dass Du Dein Schiff zerst&ouml;ren m&ouml;chtest?.";
$l_die_goodbye		 = "Aufwiedersehen grausame Galaxie!";
$l_die_check		 = "Bist Du wirklich Sicher, dass Du wirklich aus dem Spiel ausscheiden m&ouml;chtest?";
$l_die_nonono		 = "Nein! Nein! Nein!";
$l_die_what		 = "Was habe ich mir nur dabei gedacht?";
$l_die_count		 = "5.. 4.. 3.. 2.. 1.. Boom!";
$l_die_vapor		 = "Dein Schiff und alle Passagiere wurden pulverisiert.";
$l_die_please		 = "Logge Dich bitte <A HREF=logout.php>aus</A>";
$l_die_exploit		 = "Spiele nicht mit etwas, was Du nicht verstehst !";

// move.php

$l_move_title 		 = "Warptor benutzung";
$l_move_turn		 = "Du ben&ouml;tigst einen Zug um Warptore zu benutzen.";
$l_move_failed		 = "Warptor benutzung fehlgeschlagen!";

// scan.php

$l_scan_title		 = "Scanne Schiff";
$l_scan_turn		 = "Du ben&ouml;tigst einen Zug um ein anderes Schiff zu scannen.";
$l_scan_ron		 = "Scan Resultate von";
$l_scan_capt		 = "Gef&uuml;hrt von:";
$l_scan_arma		 = "Bewaffnung:";
$l_scan_carry		 = "Ladung:";

// lrscan.php

$l_lrs_title		 = "Scan mit langer Reichweite";
$l_lrs_nofull		 = "Dein Scanner besitzt nicht die F&auml;higkeit, um einen Scan mit langer Reichweite durchzuf&uuml;hren.";
$l_lrs_noturns		 = "Du benötigst $fullscan_cost Z&uuml;ge, um einen Scan mit weiter Reichweite durchzuführen.";
$l_lrs_used		 = "Du hast";
$l_lrs_turns		 = "Z&uuml;ge benutzt";
$l_lrs_left		 = "&uuml;brig";
$l_lrs_reach		 = "Die folgenen Sektoren k&ouml;nnen von Sektor [sector] ereicht werden:";
$l_lrs_links		 = "Warptore";
$l_lrs_ships		 = "Schiffe";
$l_lrs_click		 = "Klicke auf die Warptore, um zu dem Sektor zu gelangen.";
$l_lrs_cantscan		 = "Du kannst den Sektor nicht scannen";
$l_lrs_zero		 = "Sektor 0 ist zu &uuml;berf&uuml;llt um nach anderen Schiffen zu scannen!";
$l_lrs_moveto		 = " um zu folgendem Sektor zu gelangen:";
$l_log_titlet = "Log ansehen";

// log.php

$l_log_months = array('Januar','Februar','März','April','Mai','Juni','Juli','August','September','Oktober','November','Dezember');
$l_log_months_short = array('Jan','Feb','Mrz','Apr','Mai','Jun','Jul','Aug','Sep','Okt','Nov','Dez');
$l_log_pod = "Zum Gl&uuml;ck hattest du eine Fluchtkapsel!";
$l_log_nopod = "<font color=yellow><b>Du hattest keine Fluchtkapsel, und starbst.</b></font>";
$l_log_log = "[player]s Log"; 
$l_log_start = "Logbuch Eintrag für"; 
$l_log_end = "Ende des Logbuch Eintrags für"; 
$l_log_click = "Klicke <A HREF=$interface><font color=#00ff00>hier</font></A> um zum Hauptmenü zurück zu kehren."; 
$l_log_note = "Hinweis: Wenn diese Seite nicht richtig angezeigt wird, oder wenn du einfach die dynamischen HTML effekte nicht magst oder sie dich nerven, kannst du sie <a href=options.php><font color=#00FF00>hier abstellen</font>"; 

$l_log_text[LOG_LOGIN] = "Du hast Dich eingeloggt, mit der IP [ip].";
$l_log_title[LOG_LOGIN] = "Eingelogt";
$l_log_text[LOG_LOGOUT] = "Du hast Dich mit der [ip] ausgeloggt.";
$l_log_title[LOG_LOGOUT] = "Ausgelogt";
$l_log_text[LOG_ATTACK_OUTMAN] = "[player] wurde auf einem Angriffs Vektor gesichtet, aber deine Talent und deine guten Triebwerke erlaubten es dir dem Angriff auszuweichen.";
$l_log_title[LOG_ATTACK_OUTMAN] = "Ausweich Man&ouml;ver!";
$l_log_text[LOG_ATTACK_OUTSCAN] = "Du entdecktest [player] als er versuchte seine Waffen auf dein Schiff zu richten, aber deine Tarnung schützte dich vor seinen primitiven Sensoren.";
$l_log_title[LOG_ATTACK_OUTSCAN] = "Tarnung erfolgreich!";
$l_log_text[LOG_ATTACK_EWD] = "Du wurdest von [player]s hinterhältigen Attacke überrascht. Du siehst eine Fülle von Schüssen auf dich zukommen als du panisch auf den Knopf des Notfallwarps schlägst. Die Welt um dich herum verschwimmt, und für eine Sekunde glaubst du, du wärst tot. Als du dann schliesslich die Augen wieder öffnest, erkennst du, dass du dich woanders befindest. Wo auch immer...";
$l_log_title[LOG_ATTACK_EWD] = "Notfall Warp!";
$l_log_text[LOG_ATTACK_EWDFAIL] = "Deine Sensoren entdecken [player]s Schiff auf einem Angriffs Vektor. \"Lieber Jetzt als Nie\", denkst du Dir als du auf den Notfall Warp Knopf drückst. Du h&ouml;rst ein merkwürdiges Klicken und Krachen aus dem Maschinendeck und riechst schmorendes Plastik. \"Scheiss Kiste!\", schreist Du, und trittst den Computer. Der Computer piepst protestierend, als Du Dich auf den Angriff vorbereitest..";
$l_log_title[LOG_ATTACK_EWDFAIL] = "Notfall Warp <font color=red>fehlgeschlagen!</font>";
$l_log_text[LOG_ATTACK_LOSE] = "Dein Schiff wurde von [player] angegriffen. Du bist nicht imstande etwas gegen die übermächtigen Waffen von [player] auszurichten. Dein Schiff wurde zerstört. ";
$l_log_title[LOG_ATTACK_LOSE] = "<font color=red>Kampf verloren!</font>";
$l_log_text[LOG_ATTACKED_WIN] = "Du wurdest von [player] angegriffen. Du kämpfst eine Weile, dann endlich ist der Kampf vorrüber. Du verlorst [armor] Panzerungs Punkte und [fighters] Fighter in dem Gemetzel.";
$l_log_title[LOG_ATTACKED_WIN] = "<font color=yellow>Gemetzel!</font>";
$l_log_text[LOG_TOLL_PAID] = "Du hast [toll] Credits Zoll für den Einflug in Sektor [sector] gezahlt. Du versprichst Dir selbst, dass Du einen Weg finden wirst um Dein Geld zurückzubekommen.";
$l_log_title[LOG_TOLL_PAID] = "Erpressung";
$l_log_text[LOG_HIT_MINES] = "Bei Deiner Reise durch den Sektor [sector], wurdest Du von [mines] Minen getroffen.";
$l_log_title[LOG_HIT_MINES] = "<font color=yellow>Minen Alarm!</font>";
$l_log_text[LOG_SHIP_DESTROYED_MINES] = "Dein Schiff wurde in einem Minenfeld vom Sektor [sector] zerstört. ";
$l_log_title[LOG_SHIP_DESTROYED_MINES] = "<font color=red>Minen Alarm!</font>";
$l_log_text[LOG_PLANET_DEFEATED_D] = "Dein Planet [planet_name] in Sektor [sector] wurde übernommen von [name]. Glücklicherweise führte die Loyalität deiner Bürger dazu, dass sie den Planeten lieber zerstörten, als ihn in die Hände des Feindes fallen zu lassen! Du organisierst wunderschöne Todesfeiern in Gedanken an die vielen Toten.";
$l_log_title[LOG_PLANET_DEFEATED_D] = "<font color=yellow>Planet zerstört</font>";
$l_log_text[LOG_PLANET_DEFEATED] = "Dein Planet [planet_name] in Sektor [sector] wurde im Verlauf eines Kampfes von [name] übernommen. Die Leute auf dem Planeten heissen ihren neuen Herrscher willkommen. Du hörst einen Bericht in den BNN : \"Wir sind erfreut, dass die Schreckensherrschaft endlich ein Ende hat! Wir wollen nicht länger von einem stinkenden Verlierer regiert werden, der uns nicht einmal beschützen kann!\". Du schwörst, dass Sie für ihre Arroganz bezahlen werden.";
$l_log_title[LOG_PLANET_DEFEATED] = "<font color=red>Planet eingenommen!</font>";
$l_log_text[LOG_PLANET_NOT_DEFEATED] = "Dein Planet [planet_name] in Sektor [sector] wurde von [name] angegriffen. Deine Zivilisation verteidigte den Planeten und besiegte den Angreifer. Sie konnten : [goods] Güter, [ore] Erz, [organics] Lebensmittel und [salvage]% des Schiffes, Wert [credits] Credits  bergen.";
$l_log_title[LOG_PLANET_NOT_DEFEATED] = "Sieg!";
$l_log_title[LOG_RAW] = "Notiz";
$l_log_text[LOG_TOLL_RECV] = "Deine Fighter in Sektor [sector] haben [toll] Credits an Zoll eingenommen.";
$l_log_title[LOG_TOLL_RECV] = "Zoll Einnahmen";
$l_log_text[LOG_DEFS_DESTROYED] = "[quantity] ([type]) wurden im Sektor [sector] zerstört.";
$l_log_title[LOG_DEFS_DESTROYED] = "Sektor verteidigung zerstört";
$l_log_text[LOG_PLANET_EJECT] = "Du musstest den Planeten in Sektor [sector] verlassen, weil [name] die Allianz verlassen hat.";
$l_log_title[LOG_PLANET_EJECT] = "Not Start!";
$l_log_text[LOG_BADLOGIN] = "Fehlgeschlagener Login Versuch mit der IP: [ip].";
$l_log_title[LOG_BADLOGIN] = "Login fehlgeschlagen";
$l_log_text[LOG_PLANET_SCAN] = "[name] hat Deinen Planeten [planet_name] in Sektor [sector] gescannt.";
$l_log_title[LOG_PLANET_SCAN] = "Planeten Scan";
$l_log_text[LOG_PLANET_SCAN_FAIL] = "[name] hat vergebens versucht Deinen Planeten [planet_name] in Sektor [sector] zu scannen.";
$l_log_title[LOG_PLANET_SCAN_FAIL] = "Planeten Scan fehlgeschlagen";
$l_log_text[LOG_SHIP_SCAN] = "[player] hat Dein Schiff gescannt.";
$l_log_title[LOG_SHIP_SCAN] = "Schiff Scan";
$l_log_text[LOG_SHIP_SCAN_FAIL] = "[player] hat vergebens versucht, Dein schiff zu scannen.";
$l_log_title[LOG_SHIP_SCAN_FAIL] = "Schiff Scan fehlgeschlagen";
$l_log_text[LOG_FURANGEE_ATTACK] = "Greife [player] an...";
$l_log_title[LOG_FURANGEE_ATTACK] = "Angriff";
$l_log_text[LOG_STARVATION] = "Auf einem Deiner Planeten im Sektor [sector] kann sich die Bevölkerung nicht vergrößern. Es werden mehr Lebensmittel benötigt! Bedauerlicherweise sind [starvation] Kolonisten den Hungertod gestorben!";
$l_log_title[LOG_STARVATION] = "<font color=yellow>Hungersnot!</font>";
$l_log_text[LOG_TOW] = "Dein Schiff wurde vom Sektor [sector] zu Sektor [newsector] abgeschleppt, weil Deine Hüllengrösse die maximale Größe überstieg.";
$l_log_title[LOG_TOW] = "Abgeschleppt!";
$l_log_text[LOG_DEFS_DESTROYED_F] = "Du hast [fighters] patrolierende Fighter in Sektor [sector] zerstört.";
$l_log_title[LOG_DEFS_DESTROYED_F] = "Patrolie zerstört";
$l_log_text[LOG_DEFS_KABOOM] = "Du wurdest von feindlichen Fightern in Sektor [sector] zerstört. ";
$l_log_title[LOG_DEFS_KABOOM] = "<font color=red>Schiff zerstört!</font>";
$l_log_text[LOG_HARAKIRI] = "Du warst es leid Kapitän von einem grossen Haufen Müll zu sein, und so entschiedest du dich, das Universum wäre besser ohne diesen Müll. Authorisiert von [ip].";
$l_log_title[LOG_HARAKIRI] = "<font color=red>Selbstzerstörung!</font>";
$l_log_text[LOG_TEAM_REJECT] = "[player] hat die Einladung in die Allianz nicht angenommen, [teamname].";
$l_log_title[LOG_TEAM_REJECT] = "Einladung abgelehnt";
$l_log_text[LOG_TEAM_RENAME] = "Du hast Deine Allianz in [team] umbenannt.";
$l_log_title[LOG_TEAM_RENAME] = "Allianz umbenannt";
$l_log_text[LOG_TEAM_M_RENAME] = "Der Führer der Allianz hat die Allianz in [team] umbenannt.";
$l_log_title[LOG_TEAM_M_RENAME] = "Allianz umbenannt";
$l_log_text[LOG_TEAM_KICK] = "Du wurdest aus der [team] Allianz geworfen.";
$l_log_title[LOG_TEAM_KICK] = "Man hat Dich aus der Allianz geworfen.";
$l_log_text[LOG_TEAM_CREATE] = "Du hast eine neue Allianz mit dem Namen [team] erstellt.";
$l_log_title[LOG_TEAM_CREATE] = "Neue Allianz erstellt";
$l_log_text[LOG_TEAM_LEAVE] = "Du hast die [team] Allianz verlassen.";
$l_log_title[LOG_TEAM_LEAVE] = "Verlasse Allianz";
$l_log_text[LOG_TEAM_NEWLEAD] = "Du hast die Allianz [team] verlassen. Du hast die Führung der Allianz an [name] übergeben.";
$l_log_title[LOG_TEAM_NEWLEAD] = "Verlasse Allianz";
$l_log_text[LOG_TEAM_LEAD] = "Der [team] Allianz Coordinator hat sich entschlossen, daß Team zu verlassen. Du kannst nun seinen Platz einnehmen.";
$l_log_title[LOG_TEAM_LEAD] = "Promotion!";
$l_log_text[LOG_TEAM_JOIN] = "Du bist der Allianz [team] beigetreten.";
$l_log_title[LOG_TEAM_JOIN] = "Allianz Beitritt";
$l_log_text[LOG_TEAM_NEWMEMBER] = "[name] hat der Einladung der [team] Allianz zugestimmt.";
$l_log_title[LOG_TEAM_NEWMEMBER] = "Neues Allianz Mitglied";
$l_log_text[LOG_TEAM_INVITE] = "Du wurdest eingeladen, um der [team] -Allianz beizutreten.";
$l_log_title[LOG_TEAM_INVITE] = "Einladung";
$l_log_text[LOG_TEAM_NOT_LEAVE] = "[player] hat die Allianz verlassen";
$l_log_title[LOG_TEAM_NOT_LEAVE] = "Allianz verliert ein Mitglied";
$l_log_text[LOG_ADMIN_HARAKIRI] = "[player] mit der ip [ip] hat sich selbst zerstört.";
$l_log_title[LOG_ADMIN_HARAKIRI] = "Selbstzerstörung";
$l_log_text[LOG_ADMIN_ILLEGVALUE] = "[player] hatte [quantity] [type], mit dem Maximum [holds]";
$l_log_title[LOG_ADMIN_ILLEGVALUE] = "Ungülter Schiffswert";
$l_log_text[LOG_ADMIN_PLANETDEL] = "[attacker] hat versucht [defender]s Planeten in Sektor [sector] zu übernehmen. Planet wurde statt dessen zerstört.";
$l_log_title[LOG_ADMIN_PLANETDEL] = "Planet zerstört";
$l_log_text[LOG_DEFENCE_DEGRADE] = "Sektor Verteidigung (Fighter) in Sektor [sector] wurden um [degrade]% reduziert, wegen mangelnder Planetenenergie.";
$l_log_test[LOG_DEFENCE_DEGRADE] = "Sektor Verteidigung reduziert.";
$l_log_text[LOG_PLANET_CAPTURED] = "Du übernahmst einen Planeten der [owner] gehört. Er hatte [cols] Kolonisten und [credits] Credits.";
$l_log_title[LOG_PLANET_CAPTURED] = "Planet übernommen!";

// modify-defences.php

$l_md_title		 = "Sektor Verteidigung";
$l_md_invalid		 = "Ungültige Sektorverteidigung";
$l_md_nolonger		 = "Die gewählte Sektorverteidigung ist nicht länger hier.";
$l_md_you		 = "Dich";
$l_md_bmines		 = "Deine Strahlenwaffen zerstören";
$l_md_msgdownerb	 = "[name] zerstörte [mines] Minen in Sektor [sector].";
$l_md_retr		 = "Du bargst";
$l_md_mode		 = "Die Fighter wurden in den [mode] Modus gewechselt.";
$l_md_consist		 = "Die Sektorverteidigung besteht aus [qty] ([type]) die [owner] gehören.";
$l_md_youcan		 = "Du kannst";
$l_md_retrieve		 = "Bergen";
$l_md_change		 = "Fighter Einstellungen wechseln";
$l_md_cmode		 = "Fighter Modus";
$l_md_attack		 = "Angriff";
$l_md_toll		 = "Zoll";
$l_md_attdef		 = "Greife die Sektor Verteidigung an. Alle Fighter werden partizipieren.";
$l_md_noturn	  	 = "Du brauchst mindestens einen Zug.";
$l_md_nothere            = "Du musst im selben Sektor wie die Verteidigung sein!.";
$l_md_notyours           = "Aktion nicht erlaubt. Diese Verteidigung gehört Dir nicht.";
$l_md_yours              = "Du kannst deine eigenen Sektor Verteidigungen nicht angreifen.";

// news.php

$l_news_title		 = "BlackNova Universe News";
$l_news_info		 = "BNN ist innerhalb der Galaxis führend<br>
                            in Sachen Nachrichten- und Informationsübermittlung.<br>
                            24 Stunden am Tag, 7 Tage die Woche, von egnagiertem <br>
                            Personal in BNN's Galaxie Hauptquartier <br>
                            auf Alpha Centaury und in Büros galaxienweit!";
$l_news_for		 = "Neuigkeiten für";
$l_news_prev		 = "vorheriger Tag";
$l_news_next		 = "nächster Tag";
$l_news_none		 = "Keine neuen Nachrichten heute.";
$l_news_flash		 = "News Flash";

// dump.php

$l_dump_title		 = "Kolonisten Abladen";
$l_dump_turn		 = "Du benötigst einen Zug um die Kolonisten abzuladen.";
$l_dump_nocol		 = "Du hast keine Kolonisten auf dem Schiff, die du abladen könntest.";
$l_dump_dumped		 = "Kolonisten beim abgeladen.";
$l_dump_nono		 = "Du musst bei einem Spezial Hafen sein, um das zu tun.";

// readmail.php

$l_readm_title		 = "Lese Nachricht";

$l_readm_delete		 = "NACHRICHT GELÖSCHT";
$l_readm_nomessage	 = "Keine Nachrichten warten auf Dich...";
$l_readm_center		 = "Nachrichten Empfangs-Center";
$l_readm_sender		 = "Nachrichten Sender";
$l_readm_captn		 = "Kapitän der";
$l_readm_del		 = "Löschen";
$l_readm_repl		 = "Antworten";

// mailto2.php

$l_sendm_title		 = "Sende Nachricht";
$l_sendm_to		 = "An";
$l_sendm_from		 = "Von";
$l_sendm_ally		 = "Allianz:";
$l_sendm_subj		 = "Betreff";
$l_sendm_mess		 = "Nachricht";
$l_sendm_send		 = "Sende";
$l_sendm_sent		 = "Nachricht gesendet";

// zoneinfo.php

$l_zi_title		 = "Zonen Information";
$l_zi_nexist		 = "Diese Sektion des Weltraums, existiert nicht!";
$l_zi_feds		 = "Föderation";
$l_zi_traders		 = "Die Freie Handels Koalition";
$l_zi_nobody		 = "Niemandem";
$l_zi_war		 = "Umkämpfter space";
$l_zi_allow		 = "Erlaubt";
$l_zi_notallow		 = "Nicht erlaubt";
$l_zi_limit		 = "Nur für Eigentümer udn Alliierte";
$l_zi_ul		 = "Unbegrenzt";
$l_zi_control		 = "Du bist im Besitz des Sektors";
$l_zi_tochange		 = "Um die Regeln zu ändern.";
$l_zi_owner		 = "Zonen Besitzer";
$l_zi_maxhull		 = "Maximale erlaubte Hüllengröße";

// zoneedit.php

$l_ze_title		 = "Verändere Zonen Regeln";
$l_ze_notowner		 = "Du kannst die Zonen Regeln nicht verändern, da Du nicht der Besitzer der Zone bist.";
$l_ze_name		 = "Zonen Name";
$l_ze_allow		 = "Erlaube";
$l_ze_attacks		 = "Erlaube Angriffe auf andere Schiffe";
$l_ze_genesis		 = "Erlaube neue Planeten zu erstellen";
$l_ze_return		 = "um zurück zur Informations-Seitezu gelangen";
$l_ze_saved		 = "Deine Veränderung wurde gespeichert.";

// teams.php

$l_team_title		 = "Allianzen";
$l_team_menu		 = "um zum Allianzen Menü zurück zu gelangen";
$l_team_galax		 = "In der Galaxie vorhandene Allianzen:";
$l_team_members		 = "Mitglieder";
$l_team_coord		 = "Co-ordinator";
$l_team_member		 = "Mitglied";
$l_team_noinvite	 = "Niemand hat dich in diese Allianz eingeladen.";
$l_team_ifyouwant	 = "Wenn du in eine Allianz eingeladen werden willst, sende doch einfach dem jeweiligen Allianz Coordinator eine Nachricht.";
$l_team_tocreate	 = "um eine neue Allianz zu erstellen.";
$l_team_injoin		 = "Du wurdest eingeladen in die Allianz";
$l_team_tojoin		 = "um der Allianz Beizutreten";
$l_team_or		 = "oder";
$l_team_reject		 = "um die Einladung abzulehnen.";
$l_team_ed		 = "Bearbeiten";
$l_team_inv		 = "Einladen";
$l_team_leave		 = "Verlassen";
$l_team_eject		 = "Herauswerfen";
$l_team_pending		 = "Personen die Eingeladen wurden in";
$l_team_noinvites	 = "Niemand wurde eingeladen Mitglied folgender Allianz zu werden: ";
$l_team_confirmleave	 = "Willst Du folgende Allianz wirklich verlassen: ";
$l_team_onlymember	 = "Du warst das einzige Mitglied, demnach gibt es [team_name] nun nicht mehr.";
$l_team_youarecoord	 = "Du bist der Co-Ordinator von";
$l_team_relinq		 = "Du mußt die Position an ein anderes Mitglied abgeben.";
$l_team_newc		 = "Neuer Co-Ordinator:";
$l_team_youveleft	 = "Du hast ";
$l_team_relto		 = "verlassen und die Co-Ordinator Position übergeben. Und zwar an: ";
$l_team_welcome		 = "Willkommen in der Allianz ";
$l_team_noinviteto	 = "Du wurdest in diese Allianz nicht eingeladen.";
$l_team_ejectsure	 = "Bist du sicher das du folgendes Mitglied herauswerfen willst: ";
$l_team_ejected 	 = "wurde aus der Allianz herausgeworfen!";
$l_team_testing		 = "Test Phase...";
$l_team_pw		 = "Passwort";
$l_team_entername	 = "Gebe den Namen der Allianz ein";
$l_team_enterdesc	 = "Gebe die Beschreibung der Allianz ein";
$l_team_hcreated	 = "wurde erstellt mit Dir als ihr Führer";
$l_team_alliance	 = "Allianz";
$l_team_selectp		 = "Wähle den Spieler, den du einladen möchtest";
$l_team_isorry		 = "Sorry, aber [name] wurde bereits in eine andere Allianz eingeladen - man kann aber nur in jeweils eine Allianz eingeladen sein";
$l_team_plinvted	 = "Spieler eingeladen.<BR>Du musst warten bis der Spieler die Einladung bestätigt oder ablehnt.";
$l_team_refuse		 = "Du hast es abgelehnt folgender Allianz beizutreten: ";
$l_team_edname		 = "Bearbeite den Namen der Allianz";
$l_team_eddesc		 = "Bearbeite die Beschreibung deiner Allianz";
$l_team_hasbeenr	 = "wurde umbenannt.";
$l_team_Fehler		 = "<b><font color=red>Ein fehler ist aufgetreten</font></b><br>Du bist nicht der Führer dieser Allianz.";
$l_team_notmember	 = "Du bist nicht Mitglied irgendeiner Allianz";
$l_team_urejected	 = "<B>ACHTUNG</B> - Du wurdest aus folgender Allianz geworfen";
$l_team_noalliances	 = "In dieser Galaxis gibt es noch keine Allianzen.";

// ranking.php

$l_ranks_title		 = "Top $max_rank Spieler";
$l_ranks_none		 = "Keine Ergebnisse vorhanden.";
$l_ranks_pnum		 = "Gesamt Spieleranzahl";
$l_ranks_dships		 = "Spieler mit zerstörten Schiffen werden nicht gezählt.";
$l_ranks_rank		 = "Platz";
$l_ranks_lastlog	 = "Letzter login";
$l_ranks_good		 = "Gut";
$l_ranks_evil		 = "Böse";

// beacon.php

$l_beacon_title		 = "Einsatz von Raum Signalen";
$l_beacon_notpermitted	 = "Der Einsatz von Raum Signalen in diesem Sektor ist nicht gestattet.";
$l_beacon_reads		 = "Derzeitiges Raum Signal lautet";
$l_beacon_none		 = "In diesem Sektor gibt es kein Raum Signal.";
$l_beacon_enter		 = "Gib den Signal Text ein";
$l_beacon_nowreads	 = "Signal lautet nun";
$l_beacon_donthave	 = "Du hast keine Raum Signal Bojen.";

// emerwarp.php

$l_ewd_title		 = "Benutzung des Notfall Warp Geräts";
$l_ewd_used		 = "Notfall Warp ausgelöst - in Sektor [sector] materialisiert.";
$l_ewd_none		 = "Du hast kein Notfall Warp Gerät.";

// defence-report.php

$l_sdf_title		 = "Sektor Verteidigungs Bericht";
$l_sdf_none		 = "Du hast keine Sektoren Verteidigt.";
$l_sdf_type		 = "Typ";
$l_sdf_mode		 = "Modus";

// traderoute.php
// cause its rather big i put everything in own vars than to re-use
// the old ones so we could export to own file if performance problems
// should occur

$l_tdr_title    	 = "Handels Routen";
$l_tdr_newtdr   	 = "<a href=\"traderoute.php?command=new\">Klicke  hier</a> um eine neue Handelsroute zu erstellen";
$l_tdr_modtdrset         = "Um deine allgemeinen Handelsrouten Einstellungen zu verändern <a href=\"traderoute.php?command=settings\">klicke hier</a>";
$l_tdr_confdel  	 = "<a href=\"traderoute.php?command=delete&confirm=yes&traderoute_id=[tdr_id]\">kicke hier</a> um die folgende Handelsroute wirklich zu löschen:";
$l_tdr_noactive 	 = "Du hast noch keine Handelsrouten erstellt";
$l_tdr_curtdr   	 = "Aktuelle Handelsrouten";
$l_tdr_deltdr   	 = "Lösche";
$l_tdr_src      	 = "Quelle";
$l_tdr_srctype  	 = "Quellen Typ";
$l_tdr_dest     	 = "Ziel";
$l_tdr_desttype 	 = "Ziel Typ";
$l_tdr_move     	 = "Bewegungsart";
$l_tdr_circuit  	 = "Wege";
$l_tdr_change   	 = "Aktualisieren";
$l_tdr_portin   	 = "Hafen in";
$l_tdr_planet   	 = "Planet";
$l_tdr_nonexistance      = "Nicht existierender Planet!";
$l_tdr_na       	 = "K/A";
$l_tdr_cargo    	 = "Fracht";
$l_tdr_none     	 = "Keine";
$l_tdr_colonists         = "Kolonisten";
$l_tdr_fighters 	 = "Fighter";
$l_tdr_torps    	 = "Torpedos";
$l_tdr_escooped 	 = "[tdr_dist_triptime] Züge <br>[tdr_dist_scooped] Energie gesammelt";
$l_tdr_warp     	 = "Warptor";
$l_tdr_turns    	 = "Züge";
$l_tdr_way      	 = "Weg";
$l_tdr_ways     	 = "Wege";
$l_tdr_edit     	 = "Bearbeiten";
$l_tdr_del      	 = "Löschen";
$l_tdr_nowlink1 	 = "Es gibt keine Warptor von Sektor [tdr_src_sector_id] nach Sektor [tdr_dest_sector_id]";
$l_tdr_nowlink2 	 = "Es gibt keine Warptor von Sektor [tdr_dest_sector_id] nach Sektor [tdr_src_sector_id]";
$l_tdr_sportissrc        = "Wenn ein Spezial Hafen die Quelle ist, muss ein Planet das Ziel (zur Kollonisierung) sein.";
$l_tdr_notownplanet      = "Du kannst einen Planeten nicht kollonisieren, der nicht Dir oder Deiner Allianz gehört.";
$l_tdr_planetisdest      = "Ein Planet kann nur dann Ziel sein, wenn die Quelle ein Spezialhafen ist.";
$l_tdr_samecom 		 = "Du kannst keine Handelsrouten zwischen Häfen erstellen, die das Selbe verkaufen";
$l_tdr_sportcom 	 = "Du kannst keine Waren eines Planeten an einem Spezial Hafen verkaufen";
$l_tdr_editerr  	 = "Fehler: konnte Handelsroute nicht in der Datenbank finden";
$l_tdr_maxtdr   	 = "Sorry, aber mehr Handelsrouten darfst du nicht erstellen!";
$l_tdr_createnew         = "Erstellen einer neuen";
$l_tdr_editinga 	 = "Bearbeiten einer";
$l_tdr_traderoute        = "Handelsroute";
$l_tdr_unnamed  	 = "Unbenannt";
$l_tdr_cursector         = "Du bist derzeit in Sektor";
$l_tdr_selspoint         = "Wähle einen Startpunkt :";
$l_tdr_port     	 = "Hafen";
$l_tdr_insector 	 = "in Sektor";
$l_tdr_selendpoint       = "Bitte wähle einen Zielpunkt";
$l_tdr_selmovetype       = "Bitte wähle die Fortbewegungsart";
$l_tdr_realspace         = "Raum Flug";
$l_tdr_selcircuit        = "Bitte wähle die Wege";
$l_tdr_oneway   	 = "Nur Hin";
$l_tdr_errnotvalidport   = "Fehler: der Quell Hafen [tdr_port_id] scheint ungültig zu sein.";
$l_tdr_bothways 	 = "Hin und zurück";
$l_tdr_create   	 = "Erstelle";
$l_tdr_modify   	 = "Modifiziere";
$l_tdr_returnmenu        = "<a href=traderoute.php>Klicke hier</a> um zum Handelsrouten Menü zurück zu kehren.";
$l_tdr_errnotvalidport   = "Fehler : der Quell Hafen [tdr_port_id] ist kein Gültiger Hafen.";
$l_tdr_errnoport         = "Fehler : es gibt keinen Hafen in Sektor [tdr_port_id].";
$l_tdr_errnosrc    	 = "Fehler : der angegebene Quell Planet existiert nicht.";
$l_tdr_errnotownnotsell  = "Fehler : Du bist nicht der Besitzer von [tdr_source_name] in Sektor [tdr_source_sector_id] und der Planet verkauft nichts.";
$l_tdr_errnotvaliddestport= "Fehler : der Ziel Hafen [tdr_port_id] ist kein gültiger Hafen.";
$l_tdr_errnoport2        = "Fehler : Es gibt keinen Hafen in Sektor [tdr_port_id].";
$l_tdr_errnodestplanet   = "Fehler : der angegebene Ziel Planet existiert nicht.";
$l_tdr_errnotownnotsell2 = "Fehler : Du bist nicht der Besitzer von [tdr_dest_name] in Sektor [tdr_dest_sector_id] und der Planet verkauft nichts.";
$l_tdr_newtdrcreated     = "Neue Handelsroute erstellt!";
$l_tdr_tdrmodified       = "Handelsroute bearbeitet!";
$l_tdr_doesntexist       = "Diese Handelsroute existiert nicht!";
$l_tdr_notowntdr         = "Du besitzt diese Handelsroute nicht!";
$l_tdr_tdrdeleted        = "Handelsroute gelöscht!.";
$l_tdr_globalset         = "Globale Handelsrouten Einstellungen";
$l_tdr_tdrsportsrc       = "Bei Handelsrouten mit einem Spezialhafen als Quelle kaufe";
$l_tdr_tdrescooped       = "Bei Handelsrouten per Raumflug, was passiert mit der gesammelten Energie?";
$l_tdr_trade    	 = "Handeln";
$l_tdr_keep    	 	 = "Behalten";
$l_tdr_save    	 	 = "Speichern";
$l_tdr_globalsetsaved    = "Globale Einstellungen gespeichert.";
$l_tdr_engagenonexist    = "Versuchte zu einem nicht vorhandenen Ziel loszufliegen!Handelsroute ungültig!";
$l_tdr_invalidspoint     = "Starthafen scheint ungültig zu sein!";
$l_tdr_inittdr  	 = "Du befindest dich nicht in Sektor [tdr_source_id]! Du must im jeweiligen Startsektor sein um eine Handelsroute benutzen zu können";
$l_tdr_invalidsrc        = "Quell Planet scheint ungültig zu sein!";
$l_tdr_inittdrsector     = "Du bist nicht in Sektor [tdr_source_sector_id]! Du must im jeweiligen Startsektor sein um eine Handelsroute benutzen zu können";
$l_tdr_notyourplanet     = "Du bist nicht besitzer von [tdr_source_name] in Sektor [tdr_source_sector_id]!";
$l_tdr_invalidssector    = "Start Sektor scheint nicht gültig zu sein!";
$l_tdr_invaliddport      = "Ziel Hafen scheint nicht gültig zu sein!";
$l_tdr_invaliddplanet    = "Ziel Planet scheint nicht gültig zu sein!";
$l_tdr_invaliddsector    = "Ziel Sektor scheint nicht gültig zu sein!";
$l_tdr_moreturnsneeded   = "Diese Handelsroute benötigt [tdr_dist_triptime] Züge, du hast aber nur noch [tdr_playerinfo_turns] Züge übrig.";
$l_tdr_tdrhostdef        = "Du kannst keine Handelsrouten zwischen Sektoren mit feindlicher Verteidigung benutzen. Schalte zuerst die Verteidigung aus.";
$l_tdr_globalsetbuynothing= "Deine allgemeinen Einstellungen sind so gesetzt, das du nichts kaufen würdest, es wäre also eine reine Zugverschwendung!";
$l_tdr_nosrcporttrade    = "Handel mit dem Quellhafen ist nicht erlaubt.";
$l_tdr_tradesrcportoutsider= "Handel mit dem Quellhafen ist für Fremde nicht erlaubt.";
$l_tdr_nodestporttrade   = "Handel mit dem Zielhafen ist nicht erlaubt.";
$l_tdr_tradedestportoutsider= "Handel mit dem Zielhafen ist für Fremde nicht erlaubt.";
$l_tdr_tdrres  		 = "Handelsrouten Ergebnisse";
$l_tdr_bought  		 = "gekauft";
$l_tdr_nothingtotrade    = "Nichts zu handeln";
$l_tdr_sold   	  	 = "verkauft";
$l_tdr_ore    		 = $l_ore;
$l_tdr_portisfull        = "Hafen ist voll";
$l_tdr_goods    	 = $l_goods;
$l_tdr_organics 	 = $l_organics;
$l_tdr_energy   	 = $l_energy;
$l_tdr_portisempty       = "Hafen ist ausverkauft";
$l_tdr_loaded   	 = "geladen";
$l_tdr_nothingtoload     = "Nichts zu laden";
$l_tdr_scooped  	 = "gesammelt";
$l_tdr_dumped   	 = "abgeladen";
$l_tdr_planetisovercrowded= "Planet ist überbevölkert";
$l_tdr_nothingtodump     = "Nichts zu entladen";
$l_tdr_onlyonewaytdr     = "Nichts getan, Handelsroute war nur in eine Richtung";
$l_tdr_profit 		 = "Profit";
$l_tdr_cost   		 = "Kosten";
$l_tdr_totalprofit       = "Profit insgesamt";
$l_tdr_totalcost         = "Kosten Insgesamt";
$l_tdr_credits  	 = "Credits";
$l_tdr_turnsused         = "Züge benutzt";
$l_tdr_turnsleft         = "Züge übrig";
$l_tdr_engageagain       = "<A HREF=\"traderoute.php?engage=[tdr_engage]\">klicke hier</A> um diese Handelsroute noch einmal durchzuführen.";
$l_tdr_notowner 	 = $l_tdr_notowntdr;

// IGB.php

$l_igb_title    = "Die Intergalaktische Bank";
$l_igb_malfunction      = "Dieser IGB terminal hat eine Fehlfunktion. Die Intergalaktische Bank entschuldig sich für jegliche Schwierigkeiten.";
$l_igb_quit     = "Quit";
$l_igb_login    = "Login";
$l_igb_welcometoigb     = "Willkommen zu diesem Intergalaktischen Bank Terminal";
$l_igb_accountholder    = "Kontoinhaber";
$l_igb_shipaccount      = "Schiffskonto";
$l_igb_igbaccount       = "IGB Konto";
$l_igb_operations       = "Aufträge";
$l_igb_withdraw = "Auszahlen";
$l_igb_deposit  = "Einzahlen";
$l_igb_transfer = "Transferieren";
$l_igb_back     = "Zurück";
$l_igb_logout   = "Logout";
$l_igb_withdrawfunds    = "Kapital Abheben";
$l_igb_fundsavailable   = "Kapital verfügbar";
$l_igb_selwithdrawamount        = "Bitte wähle die Höhe der Auszahlung";
$l_igb_depositfunds     = "Kapital einzahlen";
$l_igb_seldepositamount = "Bitte wähle die Höhe der Einzahlung";
$l_igb_transfertype     = "Art des Transfers ";
$l_igb_toanothership    = "Zu einem anderen Schiff";
$l_igb_shiptransfer     = "Zum eigenem Schiff";
$l_igb_fromplanet       = "Von einem Planten zu einen anderem";
$l_igb_unnamed  = "Unbenannt";
$l_igb_in       = "in";
$l_igb_none     = "Kein";
$l_igb_destination      = "Ziel";
$l_igb_planettransfer   = "Planeten Transfer";
$l_igb_sendyourself     = "Du kannst dir nich selber Geld schicken!";
$l_igb_unknowntargetship        = "Unbekanntes Zielschiff!";
$l_igb_min_turns        = "Spieler [igb_target_char_name] muss mindestens [igb_min_turns] Züge gespielt haben um Geld empfangen zu können.";
$l_igb_min_turns2       = "Du musst mindestens [igb_min_turns] Züge gespielt haben um Geld zu senden.";
$l_igb_mustwait = "Du hast schon einen transfer zu [igb_target_char_name] in den letzten [igb_trate] Minuten getätigt. Du musst [igb_difftime] Minuten warten bevor Du zu diesem spieler wieder Credits senden kannst.";
$l_igb_maxtransfer      = "Maximaler erlaubter transfer";
$l_igb_unlimited        = "Unbegrenzt";
$l_igb_maxtransferpercent       = "Maximum Transfer erlaubt ([igb_percent]% vom Nettowert)";
$l_igb_recipient        = "Empfänger";
$l_igb_seltransferamount        = "Bitte wähle die Höhe des Transfers";
$l_igb_transferrate     = "Die jetzige Rate des Transfers beträgt [igb_num_percent]% der totalen Geldmenge. Sie wird automatisch reduziert auf die Geldmenge die du transferierst.";
$l_igb_errplanetsrcanddest      = "Ein Planet kann nich gleichzeitig die Quelle und das Ziel sein.";
$l_igb_errunknownplanet = "DB Fehler! Unbekannter Planet!";
$l_igb_errnotyourplanet = "Du kannst kein Geld von/zu einem Planeten transferieren der dir nich gehört.";
$l_igb_srcplanet        = "Quelle -> Planet";
$l_igb_destplanet       = "Ziel -> Planet";
$l_igb_transferrate2     = "Die jetzige Rate des Transfers beträgt [igb_num_percent]% der totalen Geldmenge. Sie wird automatisch reduziert>auf die Geldmenge die du transferierst.";
$l_igb_errsendyourself  = "Du kannst dir nich selber Geld schicken!";
$l_igb_min_turns3        = "Spieler [igb_target_char_name] muss mindestens [igb_min_turns] Züge gespielt haben um Geld empfangen zu können.";
$l_igb_min_turns4       = "Du musst mindestens [igb_min_turns] Züge gespielt haben um Geld zu senden.";
$l_igb_mustwait2 = "Du hast schon einen transfer zu [igb_target_char_name] in den letzten [igb_trate] Minuten getätigt. Du musst [igb_difftime] Minuten warten bevor Du zu diesem spieler wieder Credits senden kannst.";
$l_igb_invalidtransferinput     = "Falsche Eingabe des Transfers.";
$l_igb_nozeroamount     = "Die Höhe des Tranfers darf nich Null sein.";
$l_igb_notenoughcredits = "Du hast nich genug Credits um diesen Auftrag auszuführen.";
$l_igb_amounttoogreat   = "Die Geldmenge die du eingegeben hast is höher als deine maximal erlaubte Mengen.";
$l_igb_transfersuccessful       = "Transfer erfolgreich";
$l_igb_creditsto        = "Credits wurden transferiert zu";
$l_igb_transferamount   = "Transferhöhe";
$l_igb_transferfee      = "Transferpreis";
$l_igb_amounttransferred        = "Geldmenge Transferiert";
$l_igb_notenoughcredits2        = "Es sind nich genug Credits auf dem Quellplaneten um diesen Transfer zu beenden.";
$l_igb_to       = "zu";
$l_igb_ctransferredfrom = "Credits wurden transferiert von";
$l_igb_invaliddepositinput      = "Falsche Eingabe der Einzahlung.";
$l_igb_nozeroamount2    = "Die Höhe der Einzahlung darf nich Null sein.";
$l_igb_operationsuccessful      = "Auftrag erfolgreich";
$l_igb_creditstoyou     = "Credits wurden zu deinem IGB Konto transferiert.";
$l_igb_accounts = "Konto";
$l_igb_invalidwithdrawinput     = "Falsche Eingabe der Auszahlung.";
$l_igb_nozeroamount3    = "Die Höhe der Auszahlung darf nich Null sein.";
$l_igb_creditstoyourship        = "Credits wurden zu deinem Schiffskonto transferiert.";
$l_igb_igberrreport     = "IGB Fehler-Bericht";
$l_igb_source   = "Quelle";

// combat.php

$l_cmb_atleastoneturn   = "Du brauchst mindesten ein Zug um einen Planeten angreifen zu können.";
$l_cmb_shipenergybb     = "Schiffsenergie vor dem benutzen STrahlenwaffen";
$l_cmb_shipenergyab     = "Schiffsenergie nach dem benutzen STrahlenwaffen";
$l_cmb_shipenergyas     = "Schiffsenergie vor den Schilden";
$l_cmb_shiptorpsbtl     = "Schiffstopredos vor dem abfeuern der Torpedos";
$l_cmb_shiptorpsatl     = "Schiffstopredos nach dem abfeuern der Torpedos";
$l_cmb_planettorpdamage = "Planetentorpedoschaden";
$l_cmb_attackertorpdamage       = "Angreifertorpedoschaden";
$l_cmb_beams    = "Strahlen";
$l_cmb_fighters = "Fighter";
$l_cmb_shields  = "Schilde";
$l_cmb_torps    = "Torpedos";
$l_cmb_torpdamage       = "Torpedoschaden";
$l_cmb_armor    = "Panzerung";
$l_cmb_you      = "Du";
$l_cmb_planet   = "Planet";
$l_cmb_combatflow       = "Kampfstarke";
$l_cmb_defender = "Verteidiger";
$l_cmb_attackingplanet  = "Planeten im Sektor angreifenr";
$l_cmb_youfireyourbeams = "Du feuerst diene STrahlenwaffen ab";
$l_cmb_defenselost      = "Planeten Verteidigung verlor [cmb_planetfighters] Fighter durch deine Strahlenwaffen";
$l_cmb_defenselost2     = "Planeten Verteidigung verlor [cmb_attackerbeams]  Fighter, aber es kommen noch mehr!";
$l_cmb_planetarybeams   = "Planeten Strahlenwaffen zerstörten [cmb_temp] von deinen Figtern";
$l_cmb_planetarybeams   = "Planeten Strahlenwaffen zerstörten [cmb_planetbeams] von deinen Figtern";
$l_cmb_youdestroyedplanetshields        = "Deine Strahlenwaffen haben die Schilde des Planeten zerstört";
$l_cmb_beamsexhausted   = "Du zerstörtest [cmb_attackerbeams] die Schilde des Planeten bevor deinn Strahlenwaffen aufgebraucht waren";
$l_cmb_breachedyourshields      = "Planeten Strahlenwaffen haben deine Schilde durchbrochen";
$l_cmb_destroyedyourshields     = "Planeten Strahlenwaffen haben [cmb_planetbeams] von diene Schilden zerstört";
$l_cmb_breachedyourarmor        = "Planeten Strahlenwaffen haben deine Panzerung durchbrochenr";
$l_cmb_destroyedyourarmor       = "Planeten Strahlenwaffen haben [cmb_planetbeams] Punkte diener Pazerung zerstört";
$l_cmb_torpedoexchangephase     = "Torpedokampf Phase";
$l_cmb_nofightersleft   = "Deine Torpedos zerstörten [cmb_planetfighters] Fighter des Planeten, keine Fighter übrig";
$l_cmb_youdestroyfighters       = "Deine Torpedos zerstörten [cmb_attackertorpdamage] Fighter des Planeten";
$l_cmb_planettorpsdestroy       = "Planetem Torpedos zerstörten [cmb_temp] von deinen Fightern";
$l_cmb_planettorpsdestroy2      = "Planetem Torpedos zerstörten [cmb_planettorpdamage] von deinen Fightern";
$l_cmb_torpsbreachedyourarmor   = "Planetem Torpedos haben deien Panzerung durchbrochen";
$l_cmb_planettorpsdestroy3      = "Planetem Torpedos haben [cmb_planettorpdamage] Punkte deiner Panzerung zerstört";
$l_cmb_youdestroyedallfighters  = "Deine Torpedos zerstörten alles Fighter des Planeten";
$l_cmb_youdestroyplanetfighters = "Deine Torpedos zerstörten [cmb_attackertorpdamage] Fighter des Planeten";
$l_cmb_fightercombatphase       = "Fighterkampf Phase";
$l_cmb_youdestroyedallfighters2  = "Deien ighter haben alle Fighter des Planeten zerstört.";
$l_cmb_youdestroyplanetfighters2        = "Deien ighter haben [cmb_attackerfighters] Fighter des Planeten zerstört";
$l_cmb_allyourfightersdestroyed = "Alle deine Fighter wurden zerstört";
$l_cmb_fightertofighterlost     = "Du hast [cmb_planetfighters] Fighter Fighterkampf verloren";
$l_cmb_youbreachedplanetshields = "Deien Fighter haben die Schilde des Planeten durchbrochen";
$l_cmb_shieldsremainup  = "Deien Fighter haben [cmb_attackerfighters] Schilde des Planeten zerstört,aber sie erholen sich";
$l_cmb_fighterswarm     = "fighter des Planeten uschwärmen dein Schiff,deien Panzerung wurde durchbrochen";
$l_cmb_swarmandrepel    = "fighter des Planeten uschwärmen dein Schiff, aber dien Panzerung konnte sie abwehren";
$l_cmb_engshiptoshipcombat      = "Aktievie Schiffskamof.";
$l_cmb_shipdock = "Es sind [cmb_shipsonplanet] Schiffe am Raumhafen angedockt!";
$l_cmb_approachattackvector     = "kommt aus einer Angriffposition auf dich zu";
$l_cmb_noshipsdocked    = "Es sind KEINE Schiffe am Raumhafen angedockt!";
$l_cmb_yourshipdestroyed        = "Dein Schiff wurde zerstört!";
$l_cmb_escapepod        = "Glücklichwerweis hattest Du eine Rettungskapsel!";
$l_cmb_finalcombatstats = "Final Combat Stats";
$l_cmb_youlostfighters  = "Du hast [cmb_fighters_lost] von deinen insgesamt [cmb_playerinfo_ship_fighters] Fightern verloren.";
$l_cmb_youlostarmorpoints       = "Du hast [cmb_armor_lost] von deinen insgesamt [cmb_playerinfo_armour_pts] Panzerungspunkten verloren, du hast noch [cmb_attackerarmor] Punkte übrig.";
$l_cmb_energyused       = "Du hast [cmb_energy] Energie, von deiner [cmb_playerinfo_ship_energy] Energier verbraucht.";
$l_cmb_planetdefeated   = "Planet wurde geschlagen";
$l_cmb_citizenswanttodie        = "Die Einwohner des Planeten haben entschieden eher zu sterben anstatt Dich als einen Anführer wie Dich  zu akzeptieren. Sie benutzten ein Lserbphrer um einn Loch zum kern des Planeten zu bohren.Du hattest grade noch Zeit genug um Dich von dem Planeten in den Orbit zu retten bevor der Planet auf eine Ball geschmolzener Lava reduziert wurde.";
$l_cmb_youmaycapture    = "Du kannst <a href=planet.php?planet_id=[cmb_planetinfo_planet_id]&command=capture>capture</a> den Planeten oder sie unverteidigt zurücklassen.";
$l_cmb_youmaycapture2   = "Du kannst <a href=planet.php?planet_id=[cmb_planetinfo_planet_id]&command=capture>capture</a> den Planeten oder sie unverteidigt zurücklassen.";
$l_cmb_planetnotdefeated        = "Planet urde nicht geschlagen";
$l_cmb_planetstatistics = "Planeten statistic";
$l_cmb_fighterloststat  = "Fighters verloren: [cmb_fighters_lost] von [cmb_planetinfo_fighters] ([cmb_planetfighters] sind am Leben)";
$l_cmb_energyleft       = "Energy übrig";
$l_cmb_startingstats    = "Starte Status";
$l_cmb_statattackerbeams        = "Strahkenwaffen des Angreifers";
$l_cmb_statattackerfighters     = "Fighter des Angreifers";
$l_cmb_statattackershields      = "Schilde des Angreifers";
$l_cmb_statattackertorps        = "Toorpedos des Angreifers";
$l_cmb_statattackerarmor        = "Panzerung des Angreifersr";
$l_cmb_statattackertorpdamage   = "Torpedoschade des Angreifers";
$l_cmb_isattackingyou   = "greift Dich an";
$l_cmb_beamexchange     = "Strahlenwaffenbeschuss";
$l_cmb_beamsdestroy     = "Deine Strahlenwaffen zerstörten [cmb_lost] Fighter";
$l_cmb_beamsdestroy2    = "Deine Strahlenwaffen zerstörten [cmb_attackerbeams] Fighter, aber es kommen mehr";
$l_cmb_nobeamsareleft   = "Du haste keine Strahlenwaffen mehr um die hernahenden Figter zu zerstören!";
$l_cmb_beamshavenotarget        = "Deine Strahlenwaffen habe keine Fighter zu zerstören";
$l_cmb_fighterdestroyedbybeams  = "[cmb_targetinfo_ship_name] zerstörte [cmb_lost] von deinen Fightern mit Strahlenwaffen<BR>";
$l_cmb_beamsdestroystillhave    = "[cmb_targetinfo_ship_name] zerstörte [cmb_targetbeams] von deinen Fightern mit Strahlenwaffen, aber du hast immernoch [cmb_attackerfighters] übrig";
$l_cmb_fighterunhindered        = "Deine Fighter attakieren ungehindert, der Gegner hat keine Strahlenwaffen mehr.";
$l_cmb_youhavenofightersleft    = "Du haste keine Fighter mehr um zu attackieren";
$l_cmb_breachedsomeshields      = "Du hast [cmb_targetinfo_ship_name]'s Schilde  mit diene Strahlenwaffen durchbrochen";
$l_cmb_shieldsarehitbybeams     = "[cmb_targetinfo_ship_name]'s Schilde wurden getroffen von [cmb_attackerbeams] und beschädigt von diene Strahlenwaffen";
$l_cmb_nobeamslefttoattack      = "Du ahste keien Strahlenwaffen mehr übrig um [cmb_targetinfo_ship_name]'s Schilde zu attackieren";
$l_cmb_yourshieldsbreachedby    = "[cmb_targetinfo_ship_name]'s Strahlenwaffen haben deine SChild durchbrochen";
$l_cmb_yourshieldsarehit        = "[cmb_targetinfo_ship_name]'s Strahlenwaffen haben deine Schilde getroffen und [cmb_targetbeams] neschädigt.";
$l_cmb_hehasnobeamslefttoattack = "[cmb_targetinfo_ship_name] hat keine Strahelnwaffen mehr um deine Schilde zu attackieren";
$l_cmb_yourbeamsbreachedhim     = "Deien Strahlenwaffen haben [cmb_targetinfo_ship_name]'s Panzreung durchbrochen";
$l_cmb_yourbeamshavedonedamage  = "Deien Strahelnwaffen aheb  [cmb_attackerbeams] an [cmb_targetinfo_ship_name]'s Panzerung angerichtet";
$l_cmb_nobeamstoattackarmor     = "Du hate keien Strahlenwaffen mehr ürig um [cmb_targetinfo_ship_name]'s Panzerung zu attackieren";
$l_cmb_yourarmorbreachedbybeams = "Deine Panzerung wurde won [cmb_targetinfo_ship_name]'s Strahlenwaffen durchbrochen";
$l_cmb_yourarmorhitdamaged      = "Deine Panzerung wunrde von [cmb_targetbeams] damage by [cmb_targetinfo_ship_name]'s Strahlenwaffen getroffen";
$l_cmb_torpedoexchange  = "Torpedobeschuss";
$l_cmb_hehasnobeamslefttoattackyou      = "[cmb_targetinfo_ship_name] hat keien Strahlenwaffen mehr übrig um deine Panzerung zu attackieren";
$l_cmb_yourtorpsdestroy = "Deine Torpedos zerstörten [cmb_lost] von [cmb_targetinfo_ship_name]'s Fightern";
$l_cmb_yourtorpsdestroy2        = "Deine Torpedos zerstörten [cmb_attackertorpdamage] von [cmb_targetinfo_ship_name]'s Fightern";
$l_cmb_youhavenotorpsleft       = "Du hast keine Torpedos mehr übrig um [cmb_targetinfo_ship_name]'s Fighter zu attackieren.";
$l_cmb_hehasnofighterleft       = "[cmb_targetinfo_ship_name] hat keien Fighter mehr , die Du mit dienen Torpedos zerstören könntest";
$l_cmb_torpsdestroyyou  = "[cmb_targetinfo_ship_name]'s Torpedos zerstörten  [cmb_lost] von deinen Figtern";
$l_cmb_someonedestroyedfighters = "[cmb_targetinfo_ship_name] zerstörte [cmb_targettorpdmg] von deinen Figtern mit Torpedos";
$l_cmb_hehasnotorpsleftforyou   = "[cmb_targetinfo_ship_name] hat keien Torpedos mehr übrig um deine Fighter zu attackieren";
$l_cmb_youhavenofightersanymore = "Du haste keien Fighter mehr die von [cmb_targetinfo_ship_name]'s torpedos Zerstört werden könnten";
$l_cmb_youbreachedwithtorps     = "Du hast [cmb_targetinfo_ship_name]'s Panzerung mit deinen Torpedos durchbrochen";
$l_cmb_hisarmorishitbytorps     = "[cmb_targetinfo_ship_name]'s Panzerung nahm [cmb_attackertorpdamage] Schaden von deinen Torpedos";
$l_cmb_notorpslefttoattackarmor = "Du ahst ekien Torpedos mehr übrig um [cmb_targetinfo_ship_name]'s Panzerung zuattackieren";
$l_cmb_yourarmorbreachedbytorps = "Deien panerung wurde von [cmb_targetinfo_ship_name]'s Torpedos durchbrochen";
$l_cmb_yourarmorhitdmgtorps     = "Deine Panzerung nahm  [cmb_targettorpdmg] Schaden von [cmb_targetinfo_ship_name]'s Torpedos";
$l_cmb_hehasnotorpsforyourarmor = "[cmb_targetinfo_ship_name] hat keine Torpedos mehr übrig um deine Panzerung zu attackieren";
$l_cmb_fightersattackexchange   = "Fighterkampf";
$l_cmb_enemylostallfighters     = "[cmb_targetinfo_ship_name] verlor alle seine Fighter.";
$l_cmb_helostsomefighters       = "[cmb_targetinfo_ship_name] verlor [cmb_attackerfighters] Fighter.";
$l_cmb_youlostallfighters       = "Du has alle deien Fighter verloren.";
$l_cmb_youalsolostsomefighters  = "Du hast [cmb_targetfighters] Fighter verloren.";
$l_cmb_hehasnofightersleftattack        = "[cmb_targetinfo_ship_name] hat keien Fighter mehr um deien FIght zu attackieren";
$l_cmb_younofightersattackleft  = "Du hast keien Fighter mehr übrig um [cmb_targetinfo_ship_name]'s Fighter zu attackieren";
$l_cmb_youbreachedarmorwithfighters     = "Du hast [cmb_targetinfo_ship_name]'s Panzerung mit deine Fightern durchbrochen";
$l_cmb_youhitarmordmgfighters   = "Du hast an [cmb_targetinfo_ship_name]'s Panzerung [cmb_attackerfighters] Schaden mit deinen Fightern angerichtet";
$l_cmb_youhavenofighterstoarmor = "Du hast keien Fighter mehr um [cmb_targetinfo_ship_name]'s Panzerung zu attackieren";
$l_cmb_hasbreachedarmorfighters = "[cmb_targetinfo_ship_name] hat deine Panzerung mit Fightern durchbrichen";
$l_cmb_yourarmorishitfordmgby   = "Deien panzerung wurde von [cmb_targetfighters] getroffen un beschädigt cvon [cmb_targetinfo_ship_name]'s Fighters";
$l_cmb_nofightersleftheforyourarmor     = "[cmb_targetinfo_ship_name] hat keine Fighter mehr umd diene Panzerung zu attakieren";
$l_cmb_hehasbeendestroyed       = "[cmb_targetinfo_ship_name] wurde zerstört";
$l_cmb_escapepodlaunched        = "Eine Rettungskapsel wurde aktiviert!";
$l_cmb_yousalvaged      = "Du hast  [cmb_salv_ore] Einheiten Erz, [cmb_salv_organics] Einheiten Lebensmittels, [cmb_salv_goods] Einheiten Waren geborgen, und du erbeutest [cmb_salvage_rate]% der Schiffs [cmb_salvage] Credits .<BR>Du erhälst [cmb_number_rating_change] Punkte.";
$l_cmb_youdidntdestroyhim       = "Du zerstörtest [cmb_targetinfo_ship_name] nich";
$l_cmb_shiptoshipcombatstats    = "Schiffskampfstatus";

// check_mines.php

$l_chm_youhitsomemines  = "Du hast [chm_roll] Minen getroffen!";
$l_chm_hehitminesinsector       = "[chm_playerinfo_character_name] traf [chm_roll] Minen in Sektor [chm_sector].";
$l_chm_youlostminedeflectors    = "Du hast [chm_roll] Minen Deflektoren verloren.";
$l_chm_youlostallminedeflectors = "Du hast alle Deine Minen Deflektoren verloren.";
$l_chm_youhadnominedeflectors  = "Du hattest keine Minen Deflektoren.";
$l_chm_yourshieldshitforminesdmg        = "Deine Schilde erhielten [chm_mines_left] Schadenspunkte.";
$l_chm_yourshieldsaredown       = "Deine Schilde wurden durchbrochen!";
$l_chm_youlostallyourshields    = "Du hast deine Schilde verloren!";
$l_chm_yourarmorhitforminesdmg  = "Deine Panzerung erhielt [chm_mines_left] Schaden.";
$l_chm_yourhullisbreached       = "Deine Hülle wurde durchbrochen!";
$l_chm_hewasdestroyedbyyourmines        = "[chm_playerinfo_character_name] wurde durch deine Minen in Sektor  [chm_sector] zerstört.";
$l_chm_yourshiphasbeendestroyed = "Dein Schiff wurde zerstört";
$l_chm_luckescapepod    = "Zum Glück hattest du eine Rettungskapsel!";

// check_fighters.php

$l_chf_youretreatback   = "Du hast Dich in den ursprünglichen Sektor zurückgezogen";
$l_chf_notenoughcreditstoll     = "Du hast nicht genug Geld um den Zoll zu bezahlen.";
$l_chf_movefailed       = "Zug fehlgeschlagen.";
$l_chf_youpaidsometoll  = "Du hast [chf_tollstring] Credits Zoll bezahlt.";
$l_chf_thefightersdetectyou     = "Die Fighter haben dich entdeckt!";
$l_chf_therearetotalfightersindest      = "Es sind insgesamt [chf_total_sector_fighters] Fighter im Zielsektor.";
$l_chf_creditsdemanded  = "Sie verlangen [chf_number_fighterstoll] Credits als Wegezoll.";
$l_chf_youcanretreat    = "Du kannst dich <BR><INPUT TYPE=RADIO NAME=response VALUE=retreat><B>zurück ziehen</B> - kostet einen extra Zug.<BR></INPUT>";
$l_chf_inputpay = "<INPUT TYPE=RADIO NAME=response CHECKED VALUE=pay>den Zoll<B>bezahlen</B> und in den Sektor einfliegen.<BR></INPUT>";
$l_chf_inputfight       = "<INPUT TYPE=RADIO NAME=response CHECKED VALUE=fight><B>Angreifen</B> - du must alle Fighter zerstören um in den Sektor einfliegen zu können.<BR></INPUT>";
$l_chf_inputcloak       = "<INPUT TYPE=RADIO NAME=response CHECKED VALUE=sneak>Du kannst dich auch <B>Tarnen</B> - und versuchen unerkannt in den Sektor einzufliegen.<BR></INPUT>";
$l_chf_go       = "Bestätigen";

// mines.php

$l_mines_title			="Einsetzten von Minen oder Fightern";
$l_mines_noturn		 	="Dir fehlt ein Zug um Minen oder Fighter einzusetzen.";
$l_mines_nopermit		="Der Einsatz von Minen oder Fightern in diesem Sektor ist nicht gestattet.";
$l_mines_nodeploy		="Kann keine Fighter oder Minen einsetzten, da bereits ein anderer Spieler bzw. eine andere Allianz Fighter oder Minen hier einsetzt..";
$l_mines_info1			="Du bist derzeit in Sektor [sector]. Hier befinden sich [mines] Minen und  [fighters] Fighter.";
$l_mines_info2			="Du kannst [mines] Minen und [fighters] Fighter einsetzen";
$l_mines_deploy			="Einsetzen";
$l_mines_deployed		="Eingesetzt";
$l_mines_att			="Angriff";
$l_mines_toll			="Zoll";
$l_mines_notorps		="Du hast nicht genug Torpedos.";
$l_mines_nofighters		="Du hast nicht genug Fighter";
$l_mines_dmines			="[mines] Minen eingesetzt.";
$l_mines_dfighter		="[fighters] Fighters im [mode] Modus eingesetzt.";
$l_mines_fmode			="Fighter Modus";

//alliance-planets.php

$l_teamplanet_title		="Allianz Planeten Übersicht";
$l_teamplanet_notally		="Du bist in keiner Allianz.";
$l_teamplanet_personal		="Zeige deine Persönlichen Planeten";
$l_teamplanet_noplanet		="Deine Allianz hat noch keine Planeten";

$l_feedback_title		="Sende Feedback";
$l_feedback_to			="AN:";
$l_feedback_from		="VON:";
$l_feedback_topi		="THEMA:";
$l_feedback_feedback		="Feedback";
$l_feedback_message		="NACHRICHT:";
$l_feedback_messent		="Nachricht gesendet";
$l_feedback_subj		="Blacknova WWW Feedback";
$l_feedback_info		="Please send feedback in english or german only"; // gameadmins put all your languages here

// corp.php
$l_corpm_title			="Allianz Planeten Menü";
$l_corpm_tocorp			="Planet ist nun ein Allianz Planet!";
$l_corpm_topersonal		="Planet ist nun ein persönlicher Planet!";
$l_corpm_exploit		="Ne Ne, so geht das nicht!...";


// login.php login2.php
$l_login_title			="Einloggen"; 
$l_login_email			="E-mail Addresse:";
$l_login_pw			="Passwort:";
$l_login_chooseres		="Konnte deine Bildschirm auflösung nicht erkennen. Bitte wähle eine passende aus:";
$l_login_newp			= "Wenn du ein neuer Mitspieler bist, klicke <A HREF=\"new.php\">hier</A>.";
$l_login_prbs			= "Probleme?";
$l_login_emailus		= "E-maile uns";
$l_login_sclosed		= "Server geschlossen";
$l_login_closed_message		="Server ist derzeitig nicht geöffnet.";
$l_login_title2			="Login Phase Zwei"; 
$l_login_banned			="<b>Du wurdest vom Administrator gebannt. Du bist in diesem Spiel nicht länger willkommen. Nächstes mal versuche nicht zu schummeln!</b>";
$l_login_died			="Dein Schiff wurde zerstört, aber deine Fluchtkapsel rettete Dich und deine Crew.  Klicke <A HREF=main.php>hier</A> um mit einem neuen Schiff fortzufahren";
$l_login_newbie			="Wegen des bösartigen Verbrechens und der ruchlosen Attacke gegen dich entschied die Föderation dich kostenlos aus deinen Überresten clonen zu lassen.  Traurigerweise, selbst in diesen Zeiten, Clone können ihren Besitz nicht übernehmen und so erhälst du nur ein einfaches Schiff und ein paar wenige Credits als Neuanfang. Hoffentlich hast du dieses Mal mehr Glück.";
$l_login_newlife		="Klicke <A HREF=main.php>hier</A> um ein neues Leben zu beginnen.";
$l_login_looser			="Du hattest keine Fluchtkapsel, und da du schon einigen Erfolg im Leben hattest weigert sich die Föderation dich clonen zu lassen.  Deine Überreste fallen schon bald in ein schwarzes Loch, und lassen vielleicht irgendwo anders Leben entstehen... viele Milliarden Lichtjahre von hier.<BR><BR> Viel Glück beim nächsten Mal...";
$l_login_4gotpw1		= "Das eingegebene Passwort ist falsch.<BR><BR>  Wenn du dein Passwort vergessen hast, ";
$l_login_4gotpw2		= "um es Dir zuschicken zu lassen.<BR><BR>  Ansonsten,";
$l_login_4gotpw3		= "um es noch einmal zu versuchen.  Einlog Versuch aufgezeichnet mit der IP";
$l_login_noone			= "Kein Spieler mit dem Namen vorhanden! - Erstelle neue Spieler <A HREF=new.php>hier</A>.";
$l_login_lang = "Sprache";
$l_login_settings = "Spiel Einstellungen";
$l_login_change = "Ändern";

// new.php new2.php
$l_new_title			= "Erstelle neuen Spieler"; 
$l_new_title2			= "Erstelle neuen Spieler Phase Zwei"; 
$l_new_shipname			= "Schiffs Name";
$l_new_pname			= "Charakter (Spieler) Name";
$l_new_info			= "Wir versichern das die Daten, vor allem die Email adressen vertraulich behandelt werden, und nicht verkauft oder an andere übermittelt werden. Wir brauchen die Email lediglich zur zusendung eines Servergenerierten Passwortes.";
$l_new_closed_message		="Game geschlossen zur Durchführung eines Turniers";
$l_new_blank			="E-mail Adresse, Schiffs Name, und Charakter Name dürfen nicht freigelassen werden.";
$l_new_inuse			="Du bist bereits bei diesem Spiel angemeldet.";
$l_new_4gotpw1			="Wenn du dein Passwort vergessen hast,";
$l_new_4gotpw2			="um es dir zusenden zu lassen.";
$l_new_inusechar		="Der Name $character wird bereits von einem anderen Spieler benutzt.";
$l_new_inuseship		="Schiffs Name $shipname, wird bereits benutzt.";
$l_new_pwsent			="Passwort wurde an $username geschickt.";
$l_new_login			="um zum Login zurück zu gelangen.";
$l_new_err			="Bitte gehe zurück oder <a href=new.php>klicke hier</a> und versuche es noch einmal.";
$l_new_topic			="BlackNova Passwort";
$l_new_message			="Langes Leben und Frieden,\n\nJemand mit der IP Adresse $ip hat ein Passwort von BlackNova angefordert.\n\nDeinDein Passwort ist: [pass]\n\nDanke schön\n\nDas BlackNova Team.";

// logout.php

$l_logout_score			="Deine aktuelel Punktzahl";
$l_logout_text			="[name] wurde ausgelogt.  Klicke <A HREF=index.php>hier</A> um zum Menü zurück zukehren.";

// mail.php

$l_mail_title			="Sende Passwort"; 
$l_mail_noplayer		="Spieler nicht vorhanden! - Erstelle neuen Spieler <a href=new.php>hier</a>.";
$l_mail_sent			="Passwort erfolgreich geschickt an:";
$l_mail_topic			="$game_name Passwort";
$l_mail_message			="Frieden und langes Leben,\n\nJemand mir der IP Adresse $ip hat ein neues Passwort für $game_name angefordert.\n\nDein Passwort lautet: [pass]\n\nDanke schön\n\nDas $game_name Web Team.";

// global_funcs.php

$l_global_mmenu			="Klicke <A HREF=main.php>hier</A> um zum Hauptmenü zu gelangen.";
$l_global_mlogin		="Klicke <A HREF=login.php>hier</A> um zum Log-In zurück zu kehren!.";
$l_global_needlogin		="Du musst dich einloggen, klicke <A HREF=login.php>hier</A>.";
$l_global_died			="Spieler ist gestorben! <a href=log.php>Klicke hier</a> um zu sehen was passiert ist<BR><BR>Viel Glück beim nächsten mal.";
$l_global_warzone		="Zone ist nun eine Kriegszone!";
$l_global_nzone			="Zone ist nun neutral.";
$l_global_team			="Zone gehört nun der Allianz";
$l_global_player		="Zone gehört nun dem Spieler";

// texts for the news flashes

$l_news_planets		  = " Planeten";
$l_news_cols		      = " Millionen Kolonisten";
$l_news_p_headline = "[player]\'s Imperium umfasst nun ";

$l_killheadline=" starb bei einem tragischen unfall";
$l_news_killed = "[name] starb heute bei einem tragischen Unfall. Wie heroisch - Kapitain [name] war das letzte Besatzungsmitglied an board des Schiffes, als er bemerkte, dass keine Rettungskapsel mehr für ihn übrig war. Möge er in Frieden ruhen!";
$l_news_p_text5		= "Das aufstrebende Imperium von [name] besitzt nun bereits fünf				   Planeten, die BNN werden die Aktionen von [name] in Zukunft genauer verfolgen!";
$l_news_p_text10		= "Das wachsende Imperium von [name] kontrolliert nun schon zehn Planeten,                   Berichte der BNN zeigen das eine weitere Ausbreitung von [name] zu kriegen führen könnte!";
$l_news_p_text25		= "Das riesige Imperium von [name] kolonisierte bereits 25 Planeten,                   in einem Interview verkündete [name], dass er es in bertracht ziehe seine Expansion von nun an zu verlangsamen!";
$l_news_p_text50		= "Das gigantische Imperium von [name], representiert von bereits 50 Planeten in der ganzen Galaxie bekommt eine bedrohliche Stärke. Einer der BNN Reporter fand heraus, dass [name] sein Schiff aufrüstet und einen grösseren Krieg plant. In einem Interview verkündete [name]                   jedoch, dass dies lediglich zu Verteidigungs zwecken geschieht!";
$l_news_c_text25		= "Das aufstrebende Imperium [name] besteht nun bereits aus über 25 Millionen Kolonisten, die BNN werden die Aktionen von [name] in Zukunft genauer verfolgen,                   aber es ist offensichtlich, dass die Geburtenraten bald explodieren werden!";
$l_news_c_text100		= "Das wachsende Imperium von [name] hat nun 100 million Kolonisten,                   nach einer explosionsartigen Steigerung der Geburtenrate schienen [name]\'s Kolinien einfach ein guter Platz für Familien zu sein um zu siedeln!";
$l_news_c_text500		= "Das riesige Imperium von [name] umfasst nun über 500 Millionen Menschen,                   [name] erzählte in einem Interview, dass die Kolonisierung der Galaxie gerade erst begonnen hätte";
$l_news_c_text1000		= "Das exorbitante Imperium von [name] übersteigt nun die Zahl von einer				   Milliarde Kolonisten, BNN Reporter fanden heraus, dass [name] im besitz eines Merkwürdigen Mechanismusses ist, der es erlaubt neue Kolonisten in gigantischen Mengen zu Clonen. Mit dieser Anzahl an Kolonisten ist die wirtschaftliche Stärke des Imperiums Enorm, die BNN hoffen, dass [name] diese Geld nicht zu Kriegszwecken ausgibt!";

// Options.php

$l_opt_title = "Optionen";
$l_opt_chpass = "Ändere Passwort";
$l_opt_curpass = "Aktuelles Passwort:";
$l_opt_newpass = "Neues Passwort:";
$l_opt_newpagain = "Neues Passwort (nochmal):";
$l_opt_userint = "User interface";
$l_opt_usenew = "Use new layout?";
$l_opt_lang = "Sprache";
$l_opt_select = "Auswählen:";
$l_opt_enabled = "eingeschaltet";
$l_opt_save = "Speichern";

// Option2.php

$l_opt2_title = "Speichere Optionen";
$l_opt2_passunchanged = "Passwort wurde nicht verändert.<BR><BR>";
$l_opt2_srcpassfalse = "Original Passwort falsch. $l_opt2_passunchanged";
$l_opt2_newpassnomatch = "Passwörter stimmen nicht überein. $l_opt2_passunchanged";
$l_opt2_passchanged = "Passwort verändert.<BR><BR>";
$l_opt2_passchangeerr = "Fehler beim ändern des Passworts<BR><BR>";
$l_opt2_userintup = "User interface setting updated.<BR><BR>";
$l_opt2_userintfail = "Failed to update user interface setting.<BR><BR>";
$l_opt2_chlang = "[lang] als Sprache gewählt.<p>";
$l_opt2_dhtmlup = "Dynamic html Einstellung aktualisiert.<BR><BR>";
$l_opt2_dhtmlfail = "Konnte Dynamic html Einstellung nicht aktualisieren.<BR><BR>";

// Presets.php

$l_pre_title = "Ändere Raumflug Voreinstellungen";
$l_pre_exceed = "Einstellung [preset] ist grösser als [sector_max]. Veränderungen nicht gespeichert.<BR><BR>"; 
$l_pre_set = "1 -> [preset1] <br> 2 -> [preset2] <br> 3 -> [preset3].<BR><BR>";
$l_pre_save = "Speichern";

// Mailto.php

$l_mt_title = "Sende Nachricht";
$l_mt_from = "Von:";
$l_mt_subject = "Thema:";
$l_mt_message = "Nachricht:";
$l_mt_sent = "Nachricht gesendet";
$l_mt_send = "Senden";

// sector_fighters.php
$l_sf_attacking = "Die Sektorverteidigung (Fighter) greift dich an!<BR>";
$l_sf_destfight = "Deine Laser zerstörten [lost] Fighter<BR>";
$l_sf_destfightb = $l_sf_destfight;
$l_sf_torphit = "Torpedo Treffer:";
$l_sf_destfightt = "Deine Torpedos zerstörten [lost] Fighter<BR>";
$l_sf_fighthit = "Fighter Attacke:";
$l_sf_destfightall = "Du hast alle Fighter zerstört.<BR>";
$l_sf_destfightt2 = "Du hast [lost] Fighter zerstört.<BR>";
$l_sf_lostfight = "Du hast all Deine Fighter verloren.<BR>";
$l_sf_lostfight2 = "Du hast [lost] Fighter verloren.<BR>";
$l_sf_armorbreach = "Deine Panzerung wurde durchbrochen!<BR>";
$l_sf_armorbreach2 = "Deine Panzerung erhielt [lost] Schadenspunkte.<BR>";
$l_sf_sendlog = "[player] zerstörte [lost] Fighter der Sektorverteidigung in Sektor [sector].";
$l_sf_lreport = "Du verlorst [armor] Panzerungspunkte, [fighters] Fighter, und benutztest [torps] Torpedos.<BR><BR>";
$l_sf_shipdestroyed = "Dein Schiff wurde zerstört!<BR><BR>";
$l_sf_sendlog2 = "Deine Sektorverteidigung in Sektor [sector] zerstörte den Spieler [player].";
$l_sf_escape = "Zum Glück hattest Du eine Fluchtkapsel!<BR><BR>";

// Zone names

$l_zname[1] = "Neutrale Zone";
$l_zname[2] = "Föderations Raum";
$l_zname[3] = "Feie Handels Zone";
$l_zname[4] = "Kriegs Zone";

// ADDITION TO warpedit2.php

$l_warp_cantsame = "You can't create a link when the source is the same as the destination.";

// Bounty
$l_by_title = "Bounties";
$l_by_noturn = "You need at least one turn to place or modify a bounty.";
$l_by_amount = "Bounty Amount";
$l_by_place = "Place Bounty";
$l_by_nobounties = "There are currently no bounties.";
$l_by_bountyon = "Bounty On";
$l_by_placedby = "Placed by";
$l_by_thefeds  = "The Federation";
$l_by_cancel   = "Cancel";
$l_by_yourself = "You can not place a bounty on your self.";
$l_by_notenough = "You do not have enough credits to place a bounty of that amount.";
$l_by_toomuch   = "You can not place that bounty. Maximum bounty allowed on another player is $percent percent of your net worth";
$l_by_zeroamount = "Bounties must be greater than 0 credits.";
$l_by_placed     = "The bounty has been placed.";
$l_by_nobounty = "That bounty no longer exists.";
$l_by_notyours = "That bounty was not placed by you.";
$l_by_canceled = "The bounty has been canceled.";
$l_by_action   = "Action";
$l_by_placebounty = "Place or view bounties.";
$l_by_moredetails = "Click on the name for more details.";
$l_by_fedbounty = "Attacking this player would result in The Federation placing a bounty on you.";
$l_by_fedbounty2 = "The Federation does not approve of attacking much smaller ships. It has placed a bounty on you.";
$l_by_notexists = "The player you are putting the bounty on does not exist.";
$l_by_destroyed = "You can not place a bounty on a player with a destroyed ship.";
$l_log_text[LOG_BOUNTY_CLAIMED] = "You claimed a bounty of [amount] credits for the destruction of the ship belonging to [bounty_on]. The bounty was placed by [placed_by].";
$l_log_title[LOG_BOUNTY_CLAIMED] = "Bounty Claimed.";
$l_log_text[LOG_BOUNTY_PAID] = "Your bounty on [bounty_on] has been paid for the amount of [amount] credits.";
$l_log_title[LOG_BOUNTY_PAID] = "Bounty Paid.";
$l_log_text[LOG_BOUNTY_CANCELLED] = "Your bounty on [bounty_on] for the amount of [amount] credits has been refunded.";
$l_log_title[LOG_BOUNTY_CANCELLED] = "Bounty Refunded.";
$l_log_text[LOG_SPACE_PLAGUE] = "Your planet [name] in sector [sector] has been hit by Space Plague. Fifty percent of the colonists were killed.";
$l_log_title[LOG_SPACE_PLAGUE] = "Space Plague!";
$l_log_text[LOG_PLASMA_STORM] = "Your planet [name] in sector [sector] has been hit by a Plasma Storm. All stored Energy has been lost.";
$l_log_title[LOG_PLASMA_STORM] = "Plasma Storm!";
$l_log_text[LOG_BOUNTY_FEDBOUNTY] = "The Federation has placed a bounty on you for the amount of [amount] credits.";
$l_log_title[LOG_BOUNTY_FEDBOUNTY] = "Federation Bounty!";
$l_new_pwis = "Your password is";
$l_planet2_sector = "You are not in the same sector as that planet.";
$l_planet_destroyplanet = "Destroy Planet";
$l_planet_warning = "Doing this will totally destroy this planet";
$l_planet_confirm = "Do you really want to destroy this planet?";
$l_port_bounty = "You can not access a special port while you have a bounty on you placed by The Federation.<BR>";
$l_port_bounty = "Click <a href=\"port.php?pay=1\">here</a> to pay the bounty of [amount] credits.";
$l_port_btynotenough = "You do not have enough credtis to pay the bounty of [amount] credits.<BR>";
$l_port_bountypaid = "You have paid the bounty. Click <a href=\"port.php\">here</a> to continue.<BR>";
$l_team_notyours = "You must be in the Alliance in order to invite someone.";
$l_team_leavefirst = "You must leave a team first before joining another.";


$l_tdr_engageagain = "Click <A HREF=\"traderoute.php?engage=[tdr_engage]\">here</A> to do this trade route again, or here to do it <A HREF=\"traderoute.php?engage=[tdr_engage]&tr_repeat=5\">five</A> or <A HREF=\"traderoute.php?engage=[tdr_engage]&tr_repeat=10\">ten</A> or <A HREF=\"traderoute.php?engage=[tdr_engage]&tr_repeat=50\">fifty</A> times<p>";
$l_scan_bounty = "This ship has a total bounty on it of [amount] credits.";
$l_scan_fedbounty = "This ship has a bounty on it from The Federation.";

//Fig Drops

$l_sofa = "Sub-Orbital Fighter Attack";
$l_bombsaway = "You send your fighters spiralling towards the planet as you streak by at maximum range.";
$l_bigfigs = "Your huge ship has given them ample warning.  Your fighters will be less successful.";
$l_bigbeams = "There is a bright flash of discharging beams.  Your fighters probably didn't make it to the atmosphere.";
$l_bigtorps = "A large explosion blossoms in the upper air of the planet.  Your fighters probably didn't have time to attack.";
$l_strafesuccess = "It looks like some of your fighters made it through, although you can't tell how many from here.";
$l_log_text[LOG_PLANET_BOMBED] = "Your planet [planet_name] in sector [sector] was bombed by [name]. You used [beams] energy and [torps] torpedoes in your defense.  You lost [figs] fighters.";
$l_log_title[LOG_PLANET_BOMBED] = "<font color=red>Planet bombed!</font>";
?>
