<?php

/****************************************************
*               Clement Nicolaescu                  *
*              Clement@AdAcademy.ro                 *
*        http://www.AdAcademy.ro/BlackNova/         *
****************************************************/



//general

$l_yes 			 = "Da";
$l_no			 = "Nu";
$l_here			 = "aici";
$l_submit		 = "Trimite";
$l_reset		 = "Sterge";
$l_all			 = "Tot";

$l_ore			 = "Minereu";
$l_organics		 = "Alimente";
$l_goods		 = "Bunuri";
$l_energy		 = "Energie";
$l_colonists		 = "Colonisti";
$l_credits 		 = "Credite";
$l_units		 = "unitati de ";

$l_cargo		 = "Cargo";
$l_fighters		 = "Luptatori ";
$l_mines		 = "Mine ";
$l_torps		 = "Torpile ";

$l_none			 = "Nimic";
$l_unnamed		 = "Nedenumita";
$l_name			 = "Nume";
$l_unowned		 = "Nedetinuta";
$l_unknown		 = "Necunoscut";
$l_clickme 		 = "Click aici";
$l_player  		 = "Jucatorul";
$l_ship			 = "Nava";
$l_set			 = "setare";
$l_realspace		 = "SpatiulReal";
$l_armourpts		 = "Puncte de Armura";


// main.php

$l_main_title 		 = "Meniu Principal";

$l_traderoutes		 = "Rute de Comert";
$l_trade_control	 = "Control Comert";

$l_youhave 		 = "Aveti ";
$l_turns_used		 = "Drumuri folosite: ";
$l_turns_have		 = "Drumuri disponibile: ";
$l_score		 = "Scor: ";
$l_sector		 = "Sector";
$l_help			 = "Help";
$l_faq		         = "FAQ";
$l_feedback		 = "Feedback";
$l_forums		 = "Forum";
$l_logout		 = "Iesire";

$l_commands		 = "Comenzi";
$l_command_no		 = "Comanda indisponibila";
$l_devices		 = "Dispozitive";
$l_planets		 = "Planete";
$l_log			 = "Jurnal de Bord";
$l_sector_def		 = "Aparare Sector";
$l_defense		 = "Aparare";
$l_read_msg		 = "Citire Mesaje";
$l_send_msg		 = "Trimitere Mesaj";
$l_rankings		 = "Clasament";
$l_teams		 = "Aliante";
$l_ohno			 = "Auto-Distrugere";
$l_options		 = "Optiuni";
$l_navcomp		 = "Computer Nava";

$l_incompletemove 	 = "Nu s-a executat deplasarea.";
$l_clicktocontinue	 = "Click Aici pentru a continua";
$l_toplanetmenu   	 = "pentru a merge la Meniul Planetei.";
$l_nonexistant_pl	 = "Pe o Planeta neexistenta???";
$l_abord		 = ", conduce nava ";
$l_messages_wait	 = " Mesaje asteapta sa le cititi.";

$l_no_warplink		 = "Nici o Cale de Teleportare";
$l_scan			 = "scan";
$l_fullscan		 = "Scanare Totala";

$l_port			 = "Port";
$l_tradingport		 = "Port de Comert";
$l_planet_in_sec	 = "Planets in sector ";
$l_ships_in_sec		 = "Alte Nave in Sector ";
$l_sector_0		 = "Este asa mult trafic la Baza (Sector 0) incat nici nu pot fi distinse celelalte nave!";

// report.php

$l_report_title		 = "Raportul Navei";

$l_level		 = "Nivel";

$l_ship_levels		 = "Nivelul Dispozitivelor Navei";
$l_hull			 = "Carena";
$l_engines		 = "Motoare";
$l_power		 = "Putere";
$l_computer		 = "Computer";
$l_sensors		 = "Senzori";
$l_armour		 = "Armura";
$l_shields		 = "Scuturi";
$l_beams		 = "Lasere";
$l_torp_launch	         = "Lansatoare de Torpile";
$l_cloak		 = "Camuflaj";
$l_holds		 = "Cala";
$l_deflect		 = "Neutralizatoare Mine";
$l_ewd			 = "Dispozitiv de Teleportare de Urgenta";


$l_arm_weap		 = "Armura & Arme";
$l_beacons		 = "Dispozitive pt. Mesaje de Ghidare";
$l_warpedit		 = "Editoare Cale de Teleportare";
$l_genesis		 = "Torpile de Geneza";
$l_escape_pod		 = "Dispozitiv de Salvare";
$l_fuel_scoop		 = "Colector de Combustibil";

// device.php

$l_device_title		 = "Dispozitive";

$l_device_expl		 = "Nava dvs. este echipata cu urmatoarele Dispozitive (click pe un Dispozitiv pentru a-l folosi):";
$l_device		 = "Dispozitiv";
$l_qty			 = "Cantitate";
$l_usage		 = "Uzura";
$l_manual		 = "Manual";
$l_automatic		 = "Automat";

// port.php port2.php

$l_trade		 = "Comert";
$l_title_port		 = "Port de Comert";
$l_title_trade		 = "Comercializare Marfuri";
$l_sector_war		 = "Embargo de Razboi";
$l_war_info		 = "Razboiul face ravagii in acest sector. Nu puteti ajunge la Port printre toate aceste forte ostile.";
$l_no_trade		 = "Comertul Interzis!";
$l_no_trade_out		 = "Comertul in acest port nu este permis pentru outsider-i!";
$l_no_trade_info	 = "Comertul in acest port nu este permis!";
$l_buying		 = "Cumparare";
$l_selling		 = "Vanzare";
$l_commodity		 = "Marfa";
$l_amount		 = "Cantitate";
$l_price		 = "Pret";
$l_buy			 = "Cumpara";
$l_sell			 = "Vinde";
$l_trade_st_info	 = "Aveti [free_holds] locuri goale in Cala pentru marfuri, mai puteti incarca inca [free_power] unitati de energie si aveti [credits] credite.";
$l_special_port		 = "Port Special";
$l_no_credits		 = "Prea putine credite";
$l_creds_to_spend	 = "Aveti [credits] credite de cheltuit.";
$l_cost			 = "Cost";
$l_avail		 = "Disponibil";
$l_profit		 = "Profit";
$l_current		 = "Curent";
$l_current_qty		 = "Cantitati Curente";
$l_max			 = "Max";
$l_ifyouneedmore	 = "Daca aveti nevoie de mai mult, puteti accesa [igb] din acest Port ";
$l_ifyouneedplan	 = "Accesati de pe Planeta, ";
$l_igb_term		 = "IGB Banking Terminal";
$l_upgrade		 = "Modernizare?";
$l_unlimited		 = "Nelimitat";
$l_full			 = "Plin";
$l_equipped		 = "Echipat";
$l_n_a			 = "n/a";
$l_item			 = "Item";
$l_totalcost		 = "Cost Total";
$l_would_dump	         = "Daca doriti sa descarcati toti Colonistii aici, click ";
$l_noport		 = "Nu este nici un Port aici!";
$l_trade_turnneed	 = "Aveti nevoie de cel putin un Drum pentru a futea face comert intr-un Port sau pe o Planeta.";
$l_returnto_port         = " Click <A HREF=port.php>aici</A> pentru intoarcerea la Meniul Portului.";
$l_notenough_cargo	 = "Nu aveti destule locuri libere in Cala pentru Marfurile pe care doriti sa le procurati.";
$l_notenough_power	 = "Nu aveti destul spatiu liber pentru depozitarea Energiei pe care doriti sa o procurati.";
$l_notenough_credits	 = "Nu aveti destule Credite disponibile pentru a incheia aceasta tranzactie.";
$l_notenough_turns	 = "Nu aveti destule Drumuri disponibile pentru a incheia aceasta tranzactie.";
$l_notenough_ore	 = "Nu aveti destul Minereu pentru a incheia aceasta tranzactie.";
$l_notenough_goods	 = "Nu aveti destule Bunuri pentru a incheia aceasta tranzactie.";
$l_notenough_energy	 = "Nu aveti destula Energie pentru a incheia aceasta tranzactie.";
$l_notenough_organics	 = "Nu aveti destule Alimente pentru a incheia aceasta tranzactie.";
$l_exceed_organics	 = "Cantitatea de Alimente depaseste stocul disponibil.  ";
$l_exceed_ore            = "Cantitatea de Minereu depaseste stocul disponibil.  ";
$l_exceed_energy         = "Cantitatea de Energie depaseste stocul disponibil.  ";
$l_exceed_goods          = "Cantitatea de Bunuri depaseste stocul disponibil.  ";
$l_trade_result		 = "Rezultatele acestei afaceri";
$l_traded_ore		 = "Minereu comercializat";
$l_traded_goods		 = "Bunuri comercializate";
$l_traded_organics	 = "Alimente comercializate";
$l_traded_energy	 = "Energie comercializata";
$l_trade_complete	 = "Afacere terminata!";
$l_trade_upgraded = "Modernizata";
$l_trade_added = "adaugat";
$l_trade_installed = "instalat";


// planet.php planet2.php planet3.php
$l_planet_title		 = "Meniu Planeta";
$l_planet_none		 = "Nu va aflati in acelasi Sector cu aceasta. Drept urmare, nu puteti interactiona cu ea.";
$l_planet_capture1	 = "capturare"; // thats the link's text
$l_planet_capture2	 = "Puteti [capture] aceasta Planeta sau o puteti lasa neaparata.";
$l_planet_unowned	 = "Aceasta Planeta este nestapanita de nimeni.";
$l_planet_unnamed        = "Bun venit pe Planeta nedenumita a lui [name] .";
$l_planet_named		 = "Bun venit pe Planeta [planetname], stapanita de [name].";
$l_planet_onsurface	 = "Sunteti prezent pe suprafata Planetei.";
$l_planet_orbit 	 = "Sunteti prezent pe orbita Planetei.";
$l_planet_leave_link     = "Plecare";
$l_planet_leave          = "[leave] de pe Planeta";
$l_planet_name_link = "Denumire";
$l_planet_name2 = "[name] Planeta";
$l_planet_land_link      = "Coborare";
$l_planet_land           = "[land] pe Planeta";
$l_planet_logout	 = "Puteti sa <a href=logout.php>iesiti</a> din joc lasand nava in siguranta pe Planeta.";
$l_planet_selling	 = "Planeta acum VINDE marfuri.";
$l_planet_not_selling    = "Planeta acum NU VINDE marfuri.";
$l_planet_transfer_link	 = "Transferare";
$l_planet_transfer	 = "[transfer] marfuri/resurse/colonisti pe/de pe Planeta";
$l_planet_hasbase	 = "Aveti o Baza pe aceasta Planeta.";

$l_planet_perc		 = "Procentajul Productivitatii";
$l_planet_interest	 = "* Productivitatea creditelor este data de diferenta intre 100 si celelalte productivitati (procente) inmultit cu 3.";
$l_planet_update	 = "Actualizare";
$l_planet_tsell_link	 = "Vanzare";
$l_planet_tsell		 = "Comutare Planeta pe [selling] marfuri.";
$l_planet_bbase_link	 = "construi o Baza";
$l_planet_bbase		 = "Daca aveti destule credite, puteti [build] o Baza care va va ajuta sa aparati Planeta.";
$l_planet_bbuild	 = "Baza a fost construita.";
$l_planet_mcorp_linkC	 = "Planeta a Aliantei";
$l_planet_mcorp_linkP	 = "Planeta Personala";
$l_planet_mcorp		 = "Puteti face aceasta Planeta o [planet].";
$l_planet_buy_link	 = "Cumparare";
$l_planet_buy		 = "[buy] marfuri de pe Planeta";
$l_planet_att_link	 = "Atac";
$l_planet_att		 = "[attack] asupra Planetei";
$l_planet_att_sure	 = "Sunteti SIGUR...";
$l_planet_scn_link	 = "Scanare";
$l_planet_scn		 = "[scan] Planeta";
$l_planet_nowsell        = "Planeta este acum programata sa VANDA.";
$l_planet_nownosell      = "Planeta este acum programata sa NU VANDA.";
$l_planet_iname		 = "Introduceti noul Nume al Planetei.";
$l_planet_cname		 = "Numele Planetei este acum ";
$l_planet_landed	 = "Ati coborat pe Suprafata Planetei.";
$l_planet_left		 = "Nu mai sunteti pe Suprafata Planetei.";
$l_planet_cinfo		 = "Aveti spatiu liber pentru inca [cargo] unitati de marfuri.  Aveti capacitate de stocare pentru inca [energy] unitati de energie.";
$l_planet_toplanet	 = "Pe Planeta?";
$l_planet_baseinfo	 = "Pentru a construi o Baza, trebuie sa aveti cel putin $base_credits credite, $base_ore unitati de Minereu, $base_organics unitati de Alimente si $base_goods unitati de Bunuri pe  Planeta .";
$l_planet_p_under        = "Nu puteti schimba Procentajul Productivitatii la un numar negativ.";
$l_planet_p_over	 = "Nu puteti schimba Procentajul Productivitatii cu un total mai mare decat 100%.";
$l_planet_p_changed	 = "Procentajul Productivitatii a fost schimbat.";
$l_plant_scn_turn	 = "Aveti nevoie de cel putin un Drum pentru a putea scana o Planeta.";
$l_planet_noscan	 = "Senzorii nu s-au putut fixa pe tinta!";
$l_planet_logscanA	 = "[name] a incercat sa scaneze una dintre Planetele dvs. din Sectorul [sector], dar a esuat.";
$l_planet_logscanB	 = "Una din Planetele dvs. din Sectorul [sector] a fost scanata de [name].";
$l_planet_scn_report	 = "Rezultatele scanarii Planetei [name], stapanita de:  [owner]";
$l_base	  		 = "Baza";
$l_planet_ison		 = "este pe Planeta.";
$l_planet_captured	 = "Planeta a fost capturata!";
$l_planet_notdef	 = "Planeta nu a fost infranta!";
$l_planet_caplog	 = "Planeta dvs. '[planetname]' din Sectorul [sector] a fost capturata de [name].";

$l_planet2_title	 = "Transfer Planeetar";
$l_planet2_noturn	 = "Aveti nevoie de cel putin un Drum pentru a efectua un Transfer Planetar.";
$l_planet2_noten 	 = "Nu aveti destule ";
$l_planet2_fortr	 = "pentru transferul solicitat.";
$l_planet2_settr	 = "Setarea cantitatii transferate la ";
$l_planet2_losup	 = "Planeta nu a putut oferi decat ";
$l_planet2_notowner	 = "Dvs. nu stapaniti aceasta Planeta.";
$l_planet2_compl	 = "Transferul a fost efectuat.";
$l_planet2_power	 = "capacitatea de Putere";
$l_planet2_comp 	 = "capacitatea computerului";
$l_planet2_laun 	 = "capacitatea Lansatoarelor";
$l_planet2_nocorptransfer = "Nu puteti transfera Credite la/de la o Planeta a Aliantei.";

$l_planet3_title	 = "Comert pe Planeta";

// planet-report.php

$l_pr_title		 = "Raportul Planetelor";
$l_pr_teamlink		 = "Arata Planetele Aliantei";
$l_pr_noplanet		 = "Nu aveti nici o Planeta.";
$l_pr_clicktosort	 = "Click pe capatul de tabel pentru sortare.";
$l_pr_totals		 = "Total";

// rsmove.php
$l_rs_title 		= "Deplasare in SpatiulReal";
$l_rs_whichsector       = "In ce Sector ati dori sa ajungeti prin SpatiulReal?";
$l_rs_insector		= "Acum sunteti in Sectorul [sector] - exista sectoare de la 0 la [sector_max].";
$l_rs_submit		= "Calculeaza";
$l_rs_movetime		= "Cu motoarele dvs. va va costa [triptime] Drumuri pentru a incheia deplasarea.";
$l_rs_energy		= "Veti colecta [energy] unitati de Energie.";
$l_rs_noturns		= "Nu aveti destule Drumuri disponibile si nu puteti realiza aceasta deplasare.";
$l_rs_engage_link	= "Pornire";
$l_rs_engage		= "Aveti [turns] Drumuri. [engage] motoare?";

$l_rs_invalid		= "Destinatie Invalida!";
$l_rs_ready 		= "Acum sunteti in Sectorul [sector]. Ati folosit [triptime] Drumuri si ati acumulat [energy] unitati de Energie.";

// navcomp.php

$l_nav_title		 = "Computerul de Navigare";
$l_nav_nocomp		 = "Computerul de Navigare nu este disponibil.";
$l_nav_query		 = "Introduceti Sectorul dorit pt. a afla ruta: ";
$l_nav_pathfnd		 = "Ruta depistata.";
$l_nav_answ1		 = "Va va costa";
$l_nav_answ2		 = "Drumuri pentru a ajunge in acest Sector.";
$l_nav_proper		 = "Tehnologia computerului dvs. de pe Nava este prea primitiva pentru a descoperi o ruta la aceasta distanta.";


// attack.php

$l_att_title		 = "Atacare Nava";
$l_att_notarg		 = "Tinta nu este in acest Sector.";
$l_att_noturn		 = "Aveti nevoie de cel putin un Drum pentru a ataca.";
$l_att_noatt		 = "Atacul asupra cuiva nu este permis in acest Sector.";
$l_att_flee		 = "Tinta a reusit sa va evite!";
$l_att_ewd		 = "Tinta a activat Dispozitivul de Teleportare de Urgenta atunci cand a fost atacata!";
$l_att_att		 = "Atacare ";
$l_att_beams		 = "Lovituri Laser:";
$l_att_torps		 = "Lovituri Torpila:";
$l_att_fighters		 = "Atac Luptatori:";
$l_att_lost		 = "pierdut";
$l_att_ylost		 = "Ati pierdut";
$l_att_sdown		 = "are Scutul distrus!";
$l_att_ydown		 = "Scutul dvs. este distrus!";
$l_att_shits		 = "are Scutul lovit in";
$l_att_yhits		 = "Dvs. aveti Scutul lovit in";
$l_att_dmg		 = "puncte";
$l_att_sarm		 = "are Armura distrusa!";
$l_att_yarm		 = "Armura dvs. a fost distrus!";
$l_att_ashit		 = "are Armura lovita in";
$l_att_ayhit		 = "Dvs. aveti Armura lovita in";
$l_att_lostf		 = "a pierdut toti Luptatorii.";
$l_att_ylostf		 = "Dvs. ati pierdut toti Luptatorii.";
$l_att_sdest		 = "are Nava distrusa.";
$l_att_espod		 = "Un Dispozitiv de Salvare a fost lansat!";
$l_att_ysalv		 = "Ati capturat [salv_ore] unitati de Minereu, [salv_organics] unitati de Alimente, [salv_goods] unitati de Bunuri si [ship_salvage_rate]% din Nava, adica [ship_salvage] credite.<BR>Rating-ul dvs. a fost modificat la [rating_change] puncte.";
$l_att_andused		 = "si folosita";
$l_att_stilship		 = "Nu ati distrus Nava lui [name].";
$l_att_atyou		 = " v-a Atacat";
$l_att_and		 = "si";
$l_att_yshiplost	 = "Nava dvs. a fost distrusa!";
$l_att_salv		 = "[name] a capturat [salv_ore] unitati de Minereu, [salv_organics] unitati de Alimente, [salv_goods] unitati de Bunuri si [ship_salvage_rate]% din Nava, adica [ship_salvage] credite";

// warpedit 1-3.php

$l_warp_title		 = "Folosire Editor Cale de Teleportare";
$l_warp_turn		 = "Aveti nevoie de cel putin un Drum pentru a folosi un Editor de Cale de Teleportare.";
$l_warp_none		 = "Nu aveti nici un Editor de Cale de Teleportare.";
$l_warp_forbid		 = "Folosirea Editoarelor de Cai de Teleportare in acest Sector nu este permisa.";
$l_warp_nolink		 = "Nu exista nici o Cale de Teleportare in afara acestui Sector.";
$l_warp_linkto		 = "Caile de Teleportare dinspre acest Sector catre";
$l_warp_query		 = "Catre ce Sector doriti sa creati o Cale de Teleportare?";
$l_warp_oneway		 = "Doar dus?";
$l_warp_dest		 = "De asemenea, puteti distruge (desfiinta) o Cale de Teleportare catre un Sector.";
$l_warp_destquery	 = "Catre ce Sector doriti sa desfiintati Calea de Teleportare?";
$l_warp_bothway		 = "Dus-Intors";
$l_warp_nosector	 = "Sectorul nu exista.";
$l_warp_twoerror	 = "Folosirea unui Editor pentru crearea unei Cai de Teleportare Dus-Intors catre Sectorul [target_sector] nu este permisa.";
$l_warp_sectex		 = "Nu puteti crea o Cale de Teleportare de la acest Sector pentru ca s-ar depasi numarul maxim de cai - $link_max - peentru un sector.";
$l_warp_linked		 = "Sectorul tinta ([target_sector]) are deja o Cale de Teleportare dinspre acest Sector.";
$l_warp_unlinked	 = "Sectorul tinta ([target_sector]) nu are o Cale de Teleportare dinspre acest Sector.";
$l_warp_coneway	         = "A fost creata Calea de Teleportare Dus catre";
$l_warp_ctwoway		 = "A fost creata Calea de Teleportare catre si dinspre";
$l_warp_forbidtwo	 = "Folosirea unui Editor pentru a distruge (desfiinta) o Cale de Teleportare Dus-Intors catre Sectorul [target_sector] nu este permisa.";
$l_warp_removed		 = "A fost distrusa Calea de Teleportare catre";
$l_warp_removedtwo	 = "A fost distrusa Calea de Teleportare catre si dinspre";

// genesis.php

$l_gns_title		 = "Folosire Dispozitiv de Geneza";
$l_gns_turn		 = "Aveti nevoie de cel putin un Drum pentru a folosi un Dispozitiv de Geneza.";
$l_gns_onplanet		 = "Nu puteti folosi acest dispozitiv in timp ce sunteti pe suprafata unei Planete.";
$l_gns_full		 = "Acest Sistem Solar este deja Plin.";
$l_gns_planetex		 = "Mai exista Planete in acest Sector.";
$l_gns_nogenesis	 = "Dvs. nu aveti nici un Dispozitiv de Geneza.";
$l_gns_forbid		 = "Crearea de  Planete in acest Sector nu este permisa.";
$l_gns_bforbid		 = "Bazele de aparare din acest Sector interfereaza cu Dispozitivul de Geneza. Crearea Planetei este imposibila.";
$l_gns_pcreate		 = "Planeta a fost creata.";

// ship.php

$l_ship_title		 = "Comenzi Nava";
$l_ship_the		 = "";
$l_ship_nolonger	 = "nu mai este in Sector";
$l_ship_youc		 = "Dvs. vedeti";
$l_ship_owned		 = "detinuta de";
$l_ship_perform		 = "Puteti realiza urmatoarele actiuni:";

// selfdestruct.php

$l_die_title		 = "Auto-Distrugere";
$l_die_rusure		 = "Sunteti sigur ca doriti sa va distrugeti Nava? Acest lucru va va scoate afara din joc.";
$l_die_goodbye		 = "Adio, Galaxie cruda!";
$l_die_check		 = "Sunteti absolut sigur ca doriti sa va Auto-Distrugeti?";
$l_die_nonono		 = "NU! NU! NU!";
$l_die_what		 = "Unde mi-a fost capul?";
$l_die_count		 = "5.. 4.. 3.. 2.. 1.. Boom!";
$l_die_vapor		 = "Dvs., Nava si tot ce exista la bordul ei au fost vaporizate.";
$l_die_please		 = "Va rugam, <A HREF=logout.php>iesiti</A>!";
$l_die_exploit		 = "Nu va jucati cu ceea ce nu intelegeti.";

// move.php

$l_move_title 		 = "Deplasare";
$l_move_turn		 = "Aveti nevoie de cel putin un Drum pentru a va deplasa.";
$l_move_failed		 = "Deplasarea a esuat!";

// scan.php

$l_scan_title		 = "Scanare Nava";
$l_scan_turn		 = "Aveti nevoie de cel putin un Drum pentru a scana o alta Nava.";
$l_scan_ron		 = "Rezultatul scanarii ";
$l_scan_capt		 = "Condusa de:";
$l_scan_arma		 = "Armament:";
$l_scan_carry		 = "Incarcatura:";

// lrscan.php

$l_lrs_title		 = "Scanare la Mare Distanta";
$l_lrs_nofull		 = "Scanerele dvs. nu sunt capabile sa scaneze la o distanta asa mare.";
$l_lrs_noturns		 = "Aveti nevoie de cel putin $fullscan_cost Drum(uri) pentru a realiza o Scanare la Mare Distanta.";
$l_lrs_used		 = "Ati folosit";
$l_lrs_turns		 = "Drum(uri)";
$l_lrs_left		 = "ramase.";
$l_lrs_reach		 = "Din Sectorul [sector] puteti ajunge in urmatoarele locatii:";
$l_lrs_links		 = "Rute";
$l_lrs_ships		 = "Nave";
$l_lrs_click		 = "Click pe o Ruta (nr. sector) pentru a va deplasa in acel Sector.";
$l_lrs_cantscan		 = "Sectorul ales nu poate fi scanat din acest Sector!";
$l_lrs_zero		 = "Sectorul 0 este prea aglomerat pentru a scana navele!";
$l_lrs_moveto		 = "pentru deplasare in Sector";

// log.php

$l_log_months = array('Ianurie','Februarie','Martie','Aprilie','Mai','Iunie','Iulie','August','Septembrie','Octombrie','Noiembrie','Decembrie');
$l_log_months_short = array('Ian','Feb','Mar','Apr','Mai','Iun','Iul','Aug','Sep','Oct','Nov','Dec');
$l_log_pod = "Din fericire, ati avut o Dispozitiv de Salvare!";
$l_log_nopod = "<font color=yellow><b>Ati murit pentru ca nu ati avut un Dispozitiv de Salvare.</b></font>";
$l_log_log = "Jurnalul de Bord al lui [player]";
$l_log_start = "Inregistrarile din Jurnalul de Bord pentru";
$l_log_end = "Sfarsitul Jurnalului de Bord pentru";
$l_log_click = "Click <A HREF=$interface><font color=#00ff00>aici</font></A> pentru intoarcerea la Meniul Principal.";
$l_log_note = "NOTA: Daca aceasta pagina este afisata incorect sau daca nu agreati efectele dinamice HTML sau le gasiti deranjante, puteti sa le dazactivati <a href=options.php><font color=#00FF00>aici</font>";

$l_log_text[LOG_LOGIN] = "Ati intrat de la IP [ip].";
$l_log_title[LOG_LOGIN] = "Intrare";
$l_log_text[LOG_LOGOUT] = "Ati iesit de la IP [ip].";
$l_log_title[LOG_LOGOUT] = "Iesire";
$l_log_text[LOG_ATTACK_OUTMAN] = "[player] si-a concentrat atacul asupra Navei, dar extraordinarele dvs. abilitati de pilot si motoarele pe care le detineti v-au permis efectuati niste manevre care v-au scos din raza de actiune a inamicului.";
$l_log_title[LOG_ATTACK_OUTMAN] = "Actiune Nefinalizata!";
$l_log_text[LOG_ATTACK_OUTSCAN] = "Ati detectat armele lui [player] incercand sa va tinteasca Nava, dar Camuflajul dvs. a reusit sa pacaleasca Senzorii (cam primitivi) ai inamicului.";
$l_log_title[LOG_ATTACK_OUTSCAN] = "Camuflaj Reusit!";
$l_log_text[LOG_ATTACK_EWD] = "Ati fost surprins de atacul inselator al lui [player]. Sunteti orbit de Laserele inamice in timp ce cautati infrigurat butonul pentru Salvarea de Urgenta. Lumea s-a incetosat in jurul dvs. si, pentru o milisecunda, ati crezut ca sunteti mort. Cand, in sfasit, ati deschis ochii, ati constatat ca ati fost transportat in siguranta in alta parte. Dar nu stiti exact unde...";
$l_log_title[LOG_ATTACK_EWD] = "Salvare de Urgenta!";
$l_log_text[LOG_ATTACK_EWDFAIL] = "Senzorii dvs. detecteaza atacul Navei lui [player]. \"Mai bine sa fiu in siguranta dacat sa-mi para rau\", ati gandit, activand butonul de Salvare de Urgenta. S-a auzit un ciudat sunet infundat din sala motoarelor si a aparut un miros de circuite arse. \"Nenorocita masinarie!\", ati tipat, lovind computerul de bord. Computerul emite beep-uri de protest in timp ce dvs. va pregatiti pentru lupta iminenta...";
$l_log_title[LOG_ATTACK_EWDFAIL] = "Salvare de Urgenta <font color=red>esuata!</font>";
$l_log_text[LOG_ATTACK_LOSE] = "Nava dvs. este atacata de [player]. Oricat ati incerca nu reusiti sa va aparati singur impotriva armamentului superior al lui [player]. Nava dvs. A FOST DISTRUSA. ";
$l_log_title[LOG_ATTACK_LOSE] = "<font color=red>Lupta Pierduta!</font>";
$l_log_text[LOG_ATTACKED_WIN] = "Nava dvs. a fost atacata de [player]. V-ati luptat pentru o vreme si apoi lupta a fost intrerupta. In ambuscada ati pierdut [armor] puncte din Armura si [fighters] Luptatori.";
$l_log_title[LOG_ATTACKED_WIN] = "<font color=yellow>Ambuscada!</font>";
$l_log_text[LOG_TOLL_PAID] = "Ati fost nevoit sa platiti [toll] credite pentru a intra in Sectorul [sector]. Cu aceasta ocazie v-ati promis ca veti gasi o cale pentru a va recupera banii.";
$l_log_title[LOG_TOLL_PAID] = "Vamuire!";
$l_log_text[LOG_HIT_MINES] = "V-ati lovit de [mines] Mine cand ati trecut prin Sectorul [sector].";
$l_log_title[LOG_HIT_MINES] = "<font color=yellow>Alerta - Mine!</font>";
$l_log_text[LOG_SHIP_DESTROYED_MINES] = "Nava dvs. a fost distrusa de o zona minata in Sectorul [sector]. ";
$l_log_title[LOG_SHIP_DESTROYED_MINES] = "<font color=red>Alerta - Mine!</font>";
$l_log_text[LOG_PLANET_DEFEATED_D] = "Planeta dvs., [planet_name], din Sectorul [sector] a fost atacata de [name]. Din fericire, puternica loialitate a cetatenilor planetei a lucrat pentru dvs. Ei au distrus eroic Planeta evitand ca aceasta sa cada in mainile inamicului. Ati organizat niste funeralii somptuase in memoria credinciosului dvs. popor.";
$l_log_title[LOG_PLANET_DEFEATED_D] = "<font color=yellow>Planeta Distrusa</font>";
$l_log_text[LOG_PLANET_DEFEATED] = "Planeta dvs., [planet_name], din Sectorul [sector] a fost capturata in urma luptei cu ticalosul [name]. Populatia planetei l-a primit cu bucurie pe noul conducator. Ati putut avea o dovada citind BNN (stirile BlackNova) : \"Suntem incantati sa fim eliberati de sub tirania vechiului conducator de nimic! Noi nu dorim un ratat incapabil sa ne protejeze!\". Ati jurat sa ii faceti sa plateasca pentru aroganta lor.";
$l_log_title[LOG_PLANET_DEFEATED] = "<font color=red>Planeta Capturata!</font>";
$l_log_text[LOG_PLANET_NOT_DEFEATED] = "Planeta dvs., [planet_name], din Sectorul [sector] a fost atacata de [name]. Oricum, cetatenii planetei au organizat o aparare eroica si au reusit sa distruga inamicul. Ei au recuperat cateva resurse dintre resturile din spatiu : [goods] Bunuri, [ore] Minereu, [organics] Alimente si [salvage]% din Nava, adica [credits] credite.";
$l_log_title[LOG_PLANET_NOT_DEFEATED] = "Victorie!";
$l_log_title[LOG_RAW] = "Nota";
$l_log_text[LOG_TOLL_RECV] = "Luptatorii dvs. din Sectorul [sector] au colectat o 'taxa' de [toll] credite.";
$l_log_title[LOG_TOLL_RECV] = "Incasare Taxa";
$l_log_text[LOG_DEFS_DESTROYED] = "[quantity] [type] au fost distrusi(e) in Sectorul [sector].";
$l_log_title[LOG_DEFS_DESTROYED] = "Distrugeri in Apararea Sectorului";
$l_log_text[LOG_PLANET_EJECT] = "Ati fost expulzat de pe Planeta din Sectorul [sector] deoarece [name] a parasit Alianta.";
$l_log_title[LOG_PLANET_EJECT] = "Expulzare!";
$l_log_text[LOG_BADLOGIN] = "Incercare nereusita de a intra de la IP [ip].";
$l_log_title[LOG_BADLOGIN] = "Intrare Nereusita";
$l_log_text[LOG_PLANET_SCAN] = "[name] v-a scanat Planeta [planet_name] din Sectorul [sector].";
$l_log_title[LOG_PLANET_SCAN] = "Planeta Scanata";
$l_log_text[LOG_PLANET_SCAN_FAIL] = "[name] a incercat sa va scaneze Planeta [planet_name] din Sectorul [sector], dar a esuat.";
$l_log_title[LOG_PLANET_SCAN_FAIL] = "Scanarea Planetei Esuata";
$l_log_text[LOG_SHIP_SCAN] = "[player] v-a scanat Nava.";
$l_log_title[LOG_SHIP_SCAN] = "Nava Scanata";
$l_log_text[LOG_SHIP_SCAN_FAIL] = "[player] a incercat sa va scaneze Nava, dar a esuat.";
$l_log_title[LOG_SHIP_SCAN_FAIL] = "Scanare Nava Esuata";
$l_log_text[LOG_FURANGEE_ATTACK] = "Atac asupra [player]...";
$l_log_title[LOG_FURANGEE_ATTACK] = "Atac";
$l_log_text[LOG_STARVATION] = "Populatia de pe una dintre Planetele dvs. din Sectorul [sector] nu mai are cu ce se hrani! Este nevoie de mai multe Alimente. [starvation] Colonisti au murit infometati.";
$l_log_title[LOG_STARVATION] = "<font color=yellow>Infometare!</font>";
$l_log_text[LOG_TOW] = "Nava dvs. a fost remorcata din Sectorul [sector] in Sectorul [newsector] deoarece dimensiunile Carenei depasesc limita admisa de [hull].";
$l_log_title[LOG_TOW] = "Remorcare!";
$l_log_text[LOG_DEFS_DESTROYED_F] = "Ati omorat [fighters] Luptatori de Patrula din Sectorul [sector].";
$l_log_title[LOG_DEFS_DESTROYED_F] = "Luptatori omorati";
$l_log_text[LOG_DEFS_KABOOM] = "Ati fost distrusi de niste Luptatori din Sectorul [sector]. ";
$l_log_title[LOG_DEFS_KABOOM] = "<font color=red>Nava Distrusa!</font>";
$l_log_text[LOG_HARAKIRI] = "Fiind obosit de conducerea acestei nave spatiale, ati decis ca universul ar fi mai bun fara ea. Autorizat de [ip].";
$l_log_title[LOG_HARAKIRI] = "<font color=red>Auto-Distrugere!</font>";
$l_log_text[LOG_TEAM_REJECT] = "[player] a respins invitatia de a se alatura aliantei dvs., [teamname].";
$l_log_title[LOG_TEAM_REJECT] = "Invitatie respinsa";
$l_log_text[LOG_TEAM_RENAME] = "Ati redenumit Alianta dvs. in [team].";
$l_log_title[LOG_TEAM_RENAME] = "Redenumire Alianta";
$l_log_text[LOG_TEAM_M_RENAME] = "Coordonatorul Aliantei dvs. a redenumit-o in [team].";
$l_log_title[LOG_TEAM_M_RENAME] = "Redenumire Alianta";
$l_log_text[LOG_TEAM_KICK] = "Ati fost expulzat din Alianta [team].";
$l_log_title[LOG_TEAM_KICK] = "Expulzare din Alianta!";
$l_log_text[LOG_TEAM_CREATE] = "Ati creat o noua Alianta, [team].";
$l_log_title[LOG_TEAM_CREATE] = "Creare Alianta Noua";
$l_log_text[LOG_TEAM_LEAVE] = "Ati parasit Alianta [team].";
$l_log_title[LOG_TEAM_LEAVE] = "Parasire Alianta";
$l_log_text[LOG_TEAM_NEWLEAD] = "Ati parasit Alianta [team]. Ati transferat drepturile de coordonare lui [name].";
$l_log_title[LOG_TEAM_NEWLEAD] = "Parasire Alianta";
$l_log_text[LOG_TEAM_LEAD] = "Coordonatorul Aliantei [team] din care faceti parte a decis sa o paraseasca. V-a desemnat pe dvs. sa il inlocuiti.";
$l_log_title[LOG_TEAM_LEAD] = "Promovare!";
$l_log_text[LOG_TEAM_JOIN] = "V-ati alaturat Aliantei [team].";
$l_log_title[LOG_TEAM_JOIN] = "Intrare Alianta";
$l_log_text[LOG_TEAM_NEWMEMBER] = "[name] a acceptat sa se alature Aliantei [team]. Acest eveniment va apropie cu inca un pas de Dominatia Galactica.";
$l_log_title[LOG_TEAM_NEWMEMBER] = "Nou Membru in Alianta";
$l_log_text[LOG_TEAM_INVITE] = "Ati fost invitat sa faceti parte din Alianta [team].";
$l_log_title[LOG_TEAM_INVITE] = "Invitatie";
$l_log_text[LOG_TEAM_NOT_LEAVE] = "[player] a parasit Alianta dvs.";
$l_log_title[LOG_TEAM_NOT_LEAVE] = "Alianta a pierdut un membru";
$l_log_text[LOG_ADMIN_HARAKIRI] = "[player] s-a Auto-Distrus de la IP [ip].";
$l_log_title[LOG_ADMIN_HARAKIRI] = "Auto-Distrugere";
$l_log_text[LOG_ADMIN_ILLEGVALUE] = "[player] had [quantity] [type], with max holds of [holds]"; // NETRADUS ##################################################
$l_log_title[LOG_ADMIN_ILLEGVALUE] = "Valori Ilegale ale Navei";
$l_log_text[LOG_ADMIN_PLANETDEL] = "[attacker] a incercat sa captureze Planeta [defender] din Sectorul [sector]. In schimb, Planeta a fost distrusa.";
$l_log_title[LOG_ADMIN_PLANETDEL] = "Planeta Distrusa";
$l_log_text[LOG_DEFENCE_DEGRADE] = "Sector Defences Fighters in sector [sector] degraded by [degrade] percent due to insufficient energy."; // NETRADUS ##################################################
$l_log_test[LOG_DEFENCE_DEGRADE] = "Sector Defences degraded.";  // NETRADUS ##################################################

// modify-defences.php

$l_md_title		 = "Sistem Aparare Sector";
$l_md_invalid		 = "Sistem Invalid Aparare Sector";
$l_md_nolonger		 = "Sistemul de Aparare Sector selectat nu mai este acolo.";
$l_md_you		 = "dvs.";
$l_md_bmines		 = "Laserele dvs. au distrus";
$l_md_msgdownerb	 = "[name] a distrus [mines] Mine in Sectorul [sector].";
$l_md_retr		 = "Ati redobandit";
$l_md_mode		 = "Luptatorii selectati au primit comanda [mode] .";
$l_md_consist		 = "Sistemul de Aparare consta in [qty] [type] detinuti(e) de [owner].";
$l_md_youcan		 = "Puteti sa";
$l_md_retrieve		 = "Redobanditi";
$l_md_change		 = "Schimbati Ordinul Luptatorilor";
$l_md_cmode		 = "Ordin Luptatori";
$l_md_attack		 = "Atac";
$l_md_toll		 = "Taxe";
$l_md_attdef		 = "Atac asupra Sistemului de Aparare al Sectorului. Toti Luptatorii Sectorului vor riposta.";

// news.php

$l_news_title		 = "BlackNova Universe News";
$l_news_info		 = "BNN este unul dintre liderii galaxiei<br>
                            in livrarea informatiilor si a stirilor.<br>
                            Timp de 24 de ore, sapte zile pe saptamana o armata <br>
                            de oameni lucreaza pentru dvs. in Sediul Central Galactic <br>
                            din Alpha Centauri si in Birouri raspandite in toata Galaxia!";
$l_news_for		 = "Stirile din";
$l_news_prev		 = "ziua anterioara";
$l_news_next		 = "ziua urmatoare";
$l_news_none		 = "Ne pare rau, astazi nu exista nici o stire.";
$l_news_flash		 = "Flash Stiri";

// dump.php

$l_dump_title		 = "Descarcare Colonisti";
$l_dump_turn		 = "Aveti nevoie de cel putin un Drum pentru descarcarea Colonistilor.";
$l_dump_nocol		 = "Nu aveti nici un Colonist pe Nava.";
$l_dump_dumped		 = "Colonistii au fost descarcati la Depozitul Special.";
$l_dump_nono		 = "Trebuie sa va aflati la un Depozit Special pentru a face acest lucru.";

// readmail.php

$l_readm_title		 = "Citire Mesaj";

$l_readm_delete		 = "MESAJ STERS";
$l_readm_nomessage	 = "Nu aveti nici un Mesaj necitit...";
$l_readm_center		 = "Centrul de Primire Mesaje";
$l_readm_sender		 = "Expeditor Mesaj";
$l_readm_captn		 = "Capitan al";
$l_readm_del		 = "Sterge";
$l_readm_repl		 = "Raspunde";

// mailto2.php

$l_sendm_title		 = "Trimitere Mesaj";
$l_sendm_to		 = "Catre";
$l_sendm_from		 = "De La";
$l_sendm_ally		 = "Alianta:";
$l_sendm_subj		 = "Subiect";
$l_sendm_mess		 = "Mesaj";
$l_sendm_send		 = "Trimite";
$l_sendm_sent		 = "Mesaj Trimis";

// zoneinfo.php

$l_zi_title		 = "Informatii Zona";
$l_zi_nexist		 = "Aceasta sectiune a spatiului nu exista!";
$l_zi_feds		 = "Federatie";
$l_zi_traders		 = "Coalitia Comertului Liber";
$l_zi_nobody		 = "Nimeni";
$l_zi_war		 = "Spatiu Disputat";
$l_zi_allow		 = "Permis";
$l_zi_notallow		 = "Nepermis";
$l_zi_limit		 = "Limitat la Proprietar si Aliati";
$l_zi_ul		 = "Nelimitat";
$l_zi_control		 = "Dvs. controlati aceasta zona";
$l_zi_tochange		 = "pentru a schimba Legile Zonei.";
$l_zi_owner		 = "Stapanul Zonei";
$l_zi_maxhull		 = "Dimensiunea maxima a Carenei";

// zoneedit.php

$l_ze_title		 = "Editare Zona";
$l_ze_notowner		 = "Nu sunteti Stapanul acestei Zone, deci nu o puteti edita.";
$l_ze_name		 = "Numele Zonei";
$l_ze_allow		 = "Permis";
$l_ze_attacks		 = "Atacul altor Nave Permis";
$l_ze_genesis		 = "Crearea de noi Planete Permisa";
$l_ze_return		 = "pentru intoarcerea la pagina Informatii Zona";
$l_ze_saved		 = "Schimbarile dvs. au fost salvate.";

// teams.php

$l_team_title		 = "Aliante";
$l_team_menu		 = "pentru intoarcerea la Meniul Aliantelor";
$l_team_galax		 = "Aliante prezente in Galaxie:";
$l_team_members		 = "Membri";
$l_team_coord		 = "Coordonator";
$l_team_member		 = "Membru";
$l_team_noinvite	 = "Nimeni nu a fost invitat sa se alature Aliantei.";
$l_team_ifyouwant	 = "Daca doriti sa faceti parte dintr-o Alianta, trimiteti un mesaj Coordonatorului ei si cereti-i sa va invite.";
$l_team_tocreate	 = "pentru a crea o noua Alianta.";
$l_team_injoin		 = "Ati fost invitat sa va alaturati Aliantei";
$l_team_tojoin		 = "pentru a va alatura Aliantei";
$l_team_or		 = "sau";
$l_team_reject		 = "pentru a respinge invitatia.";
$l_team_ed		 = "Editare";
$l_team_inv		 = "Invitatie";
$l_team_leave		 = "Parasire";
$l_team_eject		 = "Expulzare";
$l_team_pending		 = "Invitatie in asteptare pentru Alianta";
$l_team_noinvites	 = "Nimeni nu este invitat sa faca parte din";
$l_team_confirmleave	 = "Sunteti sigur ca doriti sa plecati";
$l_team_onlymember	 = "Erati singurul membru, drept urmare, Alianta [team_name] nu mai exista.";
$l_team_youarecoord	 = "Dvs. sunteti Coordonatorul";
$l_team_relinq		 = "Trebuie sa transferati functia dvs. unui alt jucator.";
$l_team_newc		 = "Noul Coordonator:";
$l_team_youveleft	 = "Ati parasit Alianta";
$l_team_relto		 = "transferand functia de Coordonator catre";
$l_team_welcome		 = "Bun Venit in Alianta";
$l_team_noinviteto	 = "Nu ati fost invitat sa faceti parte din aceasta Alianta.";
$l_team_ejectsure	 = "sunteti sigur ca doriti expulzarea";
$l_team_ejected 	 = "a fost expulzat din Alianta!";
$l_team_testing		 = "Faza de Testare...";
$l_team_pw		 = "Parola";
$l_team_entername	 = "Introduceti numele Aliantei";
$l_team_enterdesc	 = "Introduceti descrierea Aliantei";
$l_team_hcreated	 = "a fost creata iar dvs. sunteti Liderul (Coordonatorul) ei";
$l_team_alliance	 = "Alianta";
$l_team_selectp		 = "Selectati Jucatorul pe care doriti sa il invitati";
$l_team_isorry		 = "Sorry, dar [name] a fost deja invitat sa se alature unei Aliante - numai o singura invitatie poate fi activa la un moment dat";
$l_team_plinvted	 = "Invitatia a fost transmisa.<BR>Trebuie sa asteptati ca Jucatorul sa accepte invitatia dvs.";
$l_team_refuse		 = "Ati refuzat invitatia de a va alatura";
$l_team_edname		 = "Editati numele Aliantei dvs.";
$l_team_eddesc		 = "Editati descrierea Aliantei dvs.";
$l_team_hasbeenr	 = "a fost redenumita.";
$l_team_error		 = "<b><font color=red>A aparut o eroare!</font></b><br>Nu sunteti Coordonatorul acestei Aliante.";
$l_team_notmember	 = "Nu sunteti membru in nici o Alianta";
$l_team_urejected	 = "<B>ATENTIE!</B> - ati fost expulzat din Alianta";
$l_team_noalliances	 = "Nu s-a format inca nici o Alianta in Galaxie.";

// ranking.php

$l_ranks_title		 = "Top $max_rank Jucatori";
$l_ranks_none		 = "Nici un rezultat pentru afisare.";
$l_ranks_pnum		 = "Numarul total de Jucatori";
$l_ranks_dships		 = "Jucatorii cu navele distruse nu sunt luati in considerare.";
$l_ranks_rank		 = "Loc";
$l_ranks_lastlog	 = "Ultima intrare";
$l_ranks_good		 = "Bun";
$l_ranks_evil		 = "Rau";

// beacon.php

$l_beacon_title		 = "Scriere Mesaje de Ghidare";
$l_beacon_notpermitted	 = "Scrierea Mesajelor de Ghidare in acest Sector nu este permisa.";
$l_beacon_reads		 = "Mesajul de Ghidare prezent";
$l_beacon_none		 = "Nu este nici un mesaj de ghidare in acest Sector.";
$l_beacon_enter		 = "Introduceti textul Mesajului de Ghidare";
$l_beacon_nowreads	 = "Mesajul de Ghidare afisat acum este";
$l_beacon_donthave	 = "Nu aveti nici un Dispezitiv pentru Mesaje de Ghidare.";

// emerwarp.php

$l_ewd_title		 = "Folosire Dispozitiv de Teleportare de Urgenta";
$l_ewd_used		 = "Dispozitivul de Teleportare de Urgenta a fost activat - ati sosit in Sectorul [sector].";
$l_ewd_none		 = "Nu aveti nici un Dispozitiv de Teleportare de Urgenta.";

// defence-report.php

$l_sdf_title		 = "Raport Sistem Aparare Sector";
$l_sdf_none		 = "Nu aveti lansat nici un Sistem de Aparare a sectorului.";
$l_sdf_type		 = "Tip";
$l_sdf_mode		 = "Comanda";

// traderoute.php
// cause its rather big i put everything in own vars than to re-use
// the old ones so we could export to own file if performance problems
// should occur

$l_tdr_title    	 = "Rute de Comert";
$l_tdr_newtdr   	 = "Click <a href=\"traderoute.php?command=new\">aici</a> pentru a crea o noua Ruta de Comert";
$l_tdr_modtdrset         = "Pentru a modifica setarile generale pentru Comert, click <a
href=\"traderoute.php?command=settings\">aici</a>";
$l_tdr_confdel  	 = "Click <a
href=\"traderoute.php?command=delete&confirm=yes&traderoute_id=[tdr_id]\">aici</a> pentru a confirma stergerea urmatoarei Rute de Comert :";
$l_tdr_noactive 	 = "Nu aveti nici o Ruta de Comert care sa fie afisata.";
$l_tdr_curtdr   	 = "Ruta de Comert Curenta";
$l_tdr_deltdr   	 = "Stergere Ruta de Comert";
$l_tdr_src      	 = "Sursa";
$l_tdr_srctype  	 = "Tip Sursa";
$l_tdr_dest     	 = "Destinatie";
$l_tdr_desttype 	 = "Tip Dest";
$l_tdr_move     	 = "Deplasare";
$l_tdr_circuit  	 = "Circuit";
$l_tdr_change   	 = "Schimbare";
$l_tdr_portin   	 = "Port in"; // De Verificat ################################################################
$l_tdr_planet   	 = "Planeta";
$l_tdr_nonexistance      = "Planeta inexistenta!";
$l_tdr_na       	 = "N/A";
$l_tdr_cargo    	 = "Cargo"; // De verificat #################################################################
$l_tdr_none     	 = "Nimic";
$l_tdr_colonists         = "Colonisti";
$l_tdr_fighters 	 = "Luptatori";
$l_tdr_torps    	 = "Torpile";
$l_tdr_escooped 	 = "[tdr_dist_triptime] Drumuri<br>[tdr_dist_scooped] Energie
Colectata";
$l_tdr_warp     	 = "Teleportare";
$l_tdr_turns    	 = "Drumuri";
$l_tdr_way      	 = "sens";
$l_tdr_ways     	 = "sensuri";
$l_tdr_edit     	 = "Editare";
$l_tdr_del      	 = "Stergere";
$l_tdr_nowlink1 	 = "Nu exista o Cale de Teleportare de la Sectorul [tdr_src_sector_id] la
Sectorul [tdr_dest_sector_id]";
$l_tdr_nowlink2 	 = "Nu exista o Cale de Teleportare de la Sectorul [tdr_dest_sector_id] la
Sectorul [tdr_src_sector_id]";
$l_tdr_sportissrc        = "Daca sursa este un Port Special, destinatar trebuie sa fie o Planeta pentru colonizare.";
$l_tdr_notownplanet      = "Nu puteti coloniza o Planeta care nu este a dvs. sau a Aliantei din care faceti parte.";
$l_tdr_planetisdest      = "O Planeta nu poate fi destinatar decat daca sursa este un Port Special.";
$l_tdr_samecom 		 = "Nu puteti crea o Ruta de Comert intre doua Porturi care vand aceeasi marfaYou can't make a traderoute for ports selling the same.";
$l_tdr_sportcom 	 = "Nu puteti vinde marfuri de pe o Planeta intr-un Port Special.";
$l_tdr_editerr  	 = "Eroare de Editare : Ruta de Comert nu a fost gasita in baza de date";
$l_tdr_maxtdr   	 = "Sorry, aveti deja numarul maxim permis de Rute de Comert.";
$l_tdr_createnew         = "Crearea unei noi";
$l_tdr_editinga 	 = "Editarea unei";
$l_tdr_traderoute        = "Rute de Comert";
$l_tdr_unnamed  	 = "Nedenumita";
$l_tdr_cursector         = "Acum sunteti in Sectorul";
$l_tdr_selspoint         = "Selectati Punctul de Pornire :";
$l_tdr_port     	 = "Port";
$l_tdr_insector 	 = "in Sectorul";
$l_tdr_selendpoint       = "Selectati Punctul Final";
$l_tdr_selmovetype       = "Selectati modul de deplasare";
$l_tdr_realspace         = "SpatiulReal";
$l_tdr_selcircuit        = "Selectati Circuitul";
$l_tdr_oneway   	 = "Dus";
// $l_tdr_errnotvalidport   = "Eroare : Portul sursa, [tdr_port_id], nu este un Port valid.";
$l_tdr_bothways 	 = "Dus-Intors";
$l_tdr_create   	 = "Creaza";
$l_tdr_modify   	 = "Modifica";
$l_tdr_returnmenu        = "Click <a href=traderoute.php>aici</a> pentru a va intoarce la Meniul rutelor de Comert.";
$l_tdr_errnotvalidport   = "Eroare : Portul sursa, [tdr_port_id], nu este un Port valid.";
$l_tdr_errnoport         = "Eroare : nu exista nici un Port in Sectorul [tdr_port_id].";
$l_tdr_errnosrc    	 = "Eroare : Planeta sursa pe care ati specificat-o nu exista.";
$l_tdr_errnotownnotsell  = "Eroare : dvs. nu stapaniti Planeta [tdr_source_name] din Sectorul [tdr_source_sector_id] si aceasta Planeta nu vinde marfuri.";
$l_tdr_errnotvaliddestport= "Eroare : Portul de destinatie, [tdr_port_id], nu este un port valid.";
$l_tdr_errnoport2        = "Eroare : nu exista nici un Port in Sectorul [tdr_port_id].";
$l_tdr_errnodestplanet   = "Eroare : Planeta de destinatie pe care ati specificat-o nu exista.";
$l_tdr_errnotownnotsell2 = "Eroare : dvs. nu stapaniti Planeta [tdr_dest_name] din Sectorul [tdr_dest_sector_id] si aceasta Planeta nu vinde marfuri.";
$l_tdr_newtdrcreated     = "Noua Ruta de Comert a fost creata!";
$l_tdr_tdrmodified       = "Ruta de Comert a fost modificata!";
$l_tdr_doesntexist       = "Aceasta Ruta de Comert nu exista!";
$l_tdr_notowntdr         = "Dvs. nu sunteti proprietarul acestei Rute de Comert!";
$l_tdr_tdrdeleted        = "Ruta de Comert a fost stearsa.";
$l_tdr_globalset         = "Setarile Generale ale Rutelor de Comert";
$l_tdr_tdrsportsrc       = "Pentru Rutele de Comert care au ca sursa un Port Special, comercializeaza";
$l_tdr_tdrescooped       = "Ce se intampla cu Energia colectata in cazul Rutelor de Comert in SpatiulReal?";
$l_tdr_trade    	 = "Comercializare";
$l_tdr_keep    	 	 = "Pastrare";
$l_tdr_save    	 	 = "Salvare";
$l_tdr_globalsetsaved    = "Setarile Generale ale Rutelor de Comert au fost salvate.";
$l_tdr_engagenonexist    = "Ati incercat pornirea pe o Ruta de Comert inexistenta!";
$l_tdr_invalidspoint     = "Portul de Pornire se pare ca nu este valid!";
$l_tdr_inittdr  	 = "Acum nu sunteti in Sectorul [tdr_source_id]! Trebuie sa va aflati in Sectorul de Pornire inainte de a folosi o Ruta de Comert!";
$l_tdr_invalidsrc        = "Planeta sursa se pare ca nu este valida!";
$l_tdr_inittdrsector     = "Acum nu sunteti in Sectorul [tdr_source_sector_id]! Trebuie sa va aflati in Sectorul de Pornire inainte de a folosi o Ruta de Comert!";
$l_tdr_notyourplanet     = "Dvs. nu stapaniti Planeta [tdr_source_name] din Sectorul [tdr_source_sector_id]!";
$l_tdr_invalidssector    = "Sectorul de Start se pare ca nu este valid!";
$l_tdr_invaliddport      = "Portul de Destinatie se pare ca nu este valid!";
$l_tdr_invaliddplanet    = "Planeta de Destinatie se pare ca nu este valida!";
$l_tdr_invaliddsector    = "Sectorul de Destinatie se pare ca nu este valid!";
$l_tdr_moreturnsneeded   = "Aceasta Ruta de Comert necesita [tdr_dist_triptime] Drumuri pentru a fi parcursa. Dvs. mai aveti doar [tdr_playerinfo_turns].";
$l_tdr_tdrhostdef        = "Nu puteti folosi Rute de Comert intre Sectoare cu Sisteme de Aparare ostile. Trebuie, mai intai, sa infrangeti Sistemul de Aparare al sectorului.";
$l_tdr_globalsetbuynothing = "Setarile Globale ale Rutelor de Comert sunt fixate sa nu cumpere nimic! Astfel, va veti risipi Drumurile daca folositi aceasta Ruta de Comert!";
$l_tdr_nosrcporttrade    = "Comercializarea din Portul sursa nu este permisa.";
$l_tdr_tradesrcportoutsider = "Comercializarea in Portul sursa nu este permisa pentru cei din afara";
$l_tdr_nodestporttrade   = "Comercializarea din Portul de destinatie nu este permisa.";
$l_tdr_tradedestportoutsider = "Comercializarea in Portul de destinatie nu este permisa pentru cei din afara";


// DUPLICATE

// $l_tdr_notyourplanet     = "You do not own planet [tdr_source_name] in sector [tdr_source_sector_id]!";
// $l_tdr_invalidssector    = "Starting sector does not seem to be valid!";
// $l_tdr_invaliddport      = "Destination port does not seem to be valid!";
// $l_tdr_invaliddplanet    = "Destination planet doesn't seem to be a valid planet!";
// $l_tdr_invaliddsector    = "Destination sector does not seem to be valid!";
// $l_tdr_moreturnsneeded   = "This trade route requires [tdr_dist_triptime] turns to complete. You only have [tdr_playerinfo_turns] left.";
// $l_tdr_tdrhostdef        = "You can not use trade routes between sectors with hostile defences. You must defeat the defences first.";
// $l_tdr_globalsetbuynothing = "Your global settings are set to buy nothing! You would only waste turns doing this route!";
// $l_tdr_nosrcporttrade    = "Trading from source port is not allowed.";
// $l_tdr_tradesrcportoutsider = "Trading at source port is not allowed for outsiders";
// $l_tdr_nodestporttrade   = "Trading from destination port is not allowed.";
// $l_tdr_tradedestportoutsider = "Trading at destination port is not allowed for outsiders";

// END DUPLICATE

$l_tdr_tdrres  		 = "Rezultatele Rutei de Comert";
$l_tdr_bought  		 = "Cumparat";
$l_tdr_nothingtotrade    = "Nimic de comercializat";
$l_tdr_sold   	  	 = "Vandut";
$l_tdr_ore    		 = "Minereu";
$l_tdr_portisfull        = "Portul este plin";
$l_tdr_goods    	 = "Bunuri";
$l_tdr_organics 	 = "Aalimente";
$l_tdr_energy   	 = "Energie";
$l_tdr_portisempty       = "Portul este gol";
$l_tdr_loaded   	 = "Incarcat";
$l_tdr_nothingtoload     = "Nimic de incarcat";
$l_tdr_scooped  	 = "Colectat";
$l_tdr_dumped   	 = "Descarcat";
$l_tdr_planetisovercrowded= "Planeta este supraaglomerata";
$l_tdr_nothingtodump     = "Nimic de descarcat";
$l_tdr_onlyonewaytdr     = "Nu s-a intamplat nimic, Ruta de Comert a fost numai Dus";
$l_tdr_profit 		 = "Profit";
$l_tdr_cost   		 = "Cost";
$l_tdr_totalprofit       = "Profit Total";
$l_tdr_totalcost         = "Cost Total";
$l_tdr_credits  	 = "Credite";
$l_tdr_turnsused         = "Drumuri folosite";
$l_tdr_turnsleft         = "Drumuri ramase";
$l_tdr_engageagain       = "Click <A HREF=\"traderoute.php?engage=[tdr_engage]\">aici</A> pentru a parcurge aceasta Ruta de Comert inca o data.";

// IGB.php

$l_igb_title    = "InterGalactic Bank";
$l_igb_malfunction      = "Acest Terminal IGB are dificultati de functionare. InterGalatic Bank doreste sa isi ceara scuze pentru orice inconvenienta intervenita.";
$l_igb_quit     = "Terminare";
$l_igb_login    = "Intrare";
$l_igb_welcometoigb     = "Bun Venit la acest Terminal al InterGalactic Banking";
$l_igb_accountholder    = "Titularul Contului";
$l_igb_shipaccount      = "Cont Nava";
$l_igb_igbaccount       = "Cont IGB";
$l_igb_operations       = "Operatiuni";
$l_igb_withdraw = "Retragere";
$l_igb_deposit  = "Depozit";
$l_igb_transfer = "Transfer";
$l_igb_back     = "Inapoi";
$l_igb_logout   = "Iesire";
$l_igb_withdrawfunds    = "Retragere Fonduri";
$l_igb_fundsavailable   = "Fonduri Disponibile";
$l_igb_selwithdrawamount        = "Va rugam sa selectati suma pentru retragere";
$l_igb_depositfunds     = "Fonduri Depozitate";
$l_igb_seldepositamount = "Va rugam sa selectati suma pentru depozit";
$l_igb_transfertype     = "Tipul Transferului";
$l_igb_toanothership    = "Catre alta Nava";
$l_igb_shiptransfer     = "Transfer Nava";
$l_igb_fromplanet       = "De la o Planeta la alta";
$l_igb_unnamed  = "Nedenumita";
$l_igb_in       = "in";
$l_igb_none     = "Nu";
$l_igb_destination      = "Destinatia";
$l_igb_planettransfer   = "Transfer Planeta";
$l_igb_sendyourself     = "Nu va puteti trimite bani dumneavoastra insiva!";
$l_igb_unknowntargetship        = "Nava destinatar necunoscuta!";
$l_igb_min_turns        = "Jucatorul [igb_target_char_name] trebuie sa fi folosit cel putin [igb_min_turns] Drumuri inainte de a putea primi banii.";
$l_igb_min_turns2       = "Dvs. trebuie sa fi folosit cel putin [igb_min_turns] Drumuri inainte de a putea trimite banii.";
$l_igb_mustwait = "Ati facut deja un transfer catre [igb_target_char_name] in ultimele [igb_trate] minute. Trebuie sa asteptati [igb_difftime] minute inainte de a putea transfera iar bani catre acest jucator.";
$l_igb_maxtransfer      = "Nivelul maxim de Transfer acceptat";
$l_igb_unlimited        = "Nelimitat";
$l_igb_maxtransferpercent       = "Nivelul maxim de Transfer acceptat ([igb_percent]% din valoarea neta)";
$l_igb_recipient        = "Primitor";
$l_igb_seltransferamount        = "Va rugam sa selectati suma pentru Transfer";
$l_igb_transferrate     = "Rata curenta pentru Transfer este [igb_num_percent]% din suma totala. Aceasta va fi dedusa automat din suma transferata.";
$l_igb_errplanetsrcanddest      = "Aceeasi Planeta nu poate fi in acelasi timp si sursa si destinatar.";
$l_igb_errunknownplanet = "Eroare in baza de date! Planeta Necunoscuta!";
$l_igb_errnotyourplanet = "Nu puteti transfera bani la/de la o Planeta care nu va apartine.";
$l_igb_srcplanet        = "Sursa -> Planeta";
$l_igb_destplanet       = "Dest. -> Planeta";
$l_igb_transferrate2     = "Rata curenta pentru Transfer este [igb_num_percent]% din suma totala. Aceasta va fi dedusa automat din suma transferata.";
$l_igb_errsendyourself  = "Nu va puteti trimite bani dvs. insiva!";
$l_igb_min_turns3        = "Jucatorul [igb_target_char_name] trebuie sa fi folosit cel putin [igb_min_turns] Drumuri inainte de a putea primi banii.";
$l_igb_min_turns4       = "Dvs. trebuie sa fi folosit cel putin [igb_min_turns] Drumuri inainte de a putea trimite banii.";
$l_igb_mustwait2 = "Ati facut deja un transfer catre [igb_target_char_name] in ultimele [igb_trate] minute. Trebuie sa asteptati [igb_difftime] minute inainte de a putea transfera iar bani catre acest jucator.";
$l_igb_invalidtransferinput     = "Introducere invalida pentru transfer.";
$l_igb_nozeroamount     = "Suma transferata nu trebuie sa fie zero.";
$l_igb_notenoughcredits = "Nu aveti destule Credite pentru a realiza aceasta operatiune.";
$l_igb_amounttoogreat   = "Suma pe care ati introdus-o este mai mare decat Nivelul Maxim de Transfer permis.";
$l_igb_transfersuccessful       = "Transfer Efectuat cu Succes";
$l_igb_creditsto        = "Credite au fost transferate catre";
$l_igb_transferamount   = "Suma de Transfer";
$l_igb_transferfee      = "Taxe Transfer";
$l_igb_amounttransferred        = "Suma Transferata";
$l_igb_notenoughcredits2        = "Nu exista destule Credite pe Planeta sursa pentru a incheia aceasta tranzactie.";
$l_igb_to       = "catre";
$l_igb_ctransferredfrom = "Credite au fost Transferate de la";
$l_igb_invaliddepositinput      = "Introducere invalida pentru Depozit.";
$l_igb_nozeroamount2    = "Suma pentru Depozit nu poate fi zero.";
$l_igb_operationsuccessful      = "Operatiune efectuata cu succes";
$l_igb_creditstoyou     = "Credite au fost Transferate in contul dvs. IGB.";
$l_igb_accounts = "Conturi";
$l_igb_invalidwithdrawinput     = "Introducere invalida pentru Retragere.";
$l_igb_nozeroamount3    = "Suma pentru Retragere nu poate fi zero.";
$l_igb_creditstoyourship        = "Credite au fost Transferate in contul Navei dvs..";
$l_igb_igberrreport     = "Eroare in Raportul IGB";
$l_igb_source   = "Sursa";

// combat.php

$l_cmb_atleastoneturn   = "Aveti nevoie de cel putin un Drum pentru a ataca o Planeta.";
$l_cmb_shipenergybb     = "Energia Navei inainte de folosirea Laserelor";
$l_cmb_shipenergyab     = "Energia Navei dupa folosirea Laserelor";
$l_cmb_shipenergyas     = "Energia Navei dupa folosirea Scuturilor";
$l_cmb_shiptorpsbtl     = "Torpilele Navei inainte de lansare";
$l_cmb_shiptorpsatl     = "Torpilele Naveei dupa lansare";
$l_cmb_planettorpdamage = "Pagubele facute de Torpilele Planetei";
$l_cmb_attackertorpdamage       = "Pagubele facute de Torpilele Atacatorului";
$l_cmb_beams    = "Lasere";
$l_cmb_fighters = "Luptatori";
$l_cmb_shields  = "Scuturi";
$l_cmb_torps    = "Torpile";
$l_cmb_torpdamage       = "Pagube Torpile";
$l_cmb_armor    = "Armura";
$l_cmb_you      = "Dvs.";
$l_cmb_planet   = "Planeta";
$l_cmb_combatflow       = "Desfasurarea Luptei";
$l_cmb_defender = "Aparator";
$l_cmb_attackingplanet  = "Atacarea Planetei in Sectorul";
$l_cmb_youfireyourbeams = "V-ati folosit Laserele";
$l_cmb_defenselost      = "Apararea Planetei a pierdut [cmb_planetfighters] Luptatori loviti de Laserele dvs.";
$l_cmb_defenselost2     = "Apararea Planetei a pierdut [cmb_attackerbeams] Luptatori, dar vin intariri!";

//  There may be a problem withe double variable ############################################

$l_cmb_planetarybeams   = "Laserele Planetei au omorat [cmb_temp] dintre Luptatorii dvs.";
$l_cmb_planetarybeams   = "Laserele Planetei au omorat [cmb_planetbeams] dintre Luptatorii dvs.";

// End of possible problem #################################################################

$l_cmb_youdestroyedplanetshields        = "Laserele dvs. au distrus Scuturile Planetei";
$l_cmb_beamsexhausted   = "Ati lovit Scuturile Planetei in [cmb_attackerbeams] puncte inainte ca Laserele dvs. sa se epuizeze";
$l_cmb_breachedyourshields      = "Laserele Planetei v-au distrus Scuturile Navei";
$l_cmb_destroyedyourshields     = "Laserele Planetei au lovit Scuturile Navei dvs. in [cmb_planetbeams] puncte";
$l_cmb_breachedyourarmor        = "Laserele Planetei au distrus Armura Navei dvs.";
$l_cmb_destroyedyourarmor       = "Laserele Planetei au lovit Armura Navei dvs. in [cmb_planetbeams] puncte";
$l_cmb_torpedoexchangephase     = "Faza schimbului de Torpile";
$l_cmb_nofightersleft   = "Torpilele dvs. au omorat [cmb_planetfighters] Luptatori ai Planetei. Nu a mai ramas nici un Luptator";
$l_cmb_youdestroyfighters       = "Torpilele dvs. au omorat [cmb_attackertorpdamage] dintre Luptatorii Planetei";

//  There may be a problem withe double variable ############################################
// like line 964

$l_cmb_planettorpsdestroy       = "Torpilele Planetei v-au omorat [cmb_temp] Luptatori";
$l_cmb_planettorpsdestroy2      = "Torpilele Planetei v-au omorat [cmb_planettorpdamage] Luptatori";

// End of possible problem #################################################################

$l_cmb_torpsbreachedyourarmor   = "Torpilele Planetei au distrus Armura Navei dvs.";
$l_cmb_planettorpsdestroy3      = "Torpilele Planetei au lovit Armura Navei dvs. in [cmb_planettorpdamage] puncte";
$l_cmb_youdestroyedallfighters  = "Torpilele dvs. au omorat toti Luptatorii Planetei";
$l_cmb_youdestroyplanetfighters = "Torpilele dvs. au omorat [cmb_attackertorpdamage] dintre Luptatorii Planetei";
$l_cmb_fightercombatphase       = "Faza Confruntarii cu Luptatori";
$l_cmb_youdestroyedallfighters2  = "Luptatorii dvs. au omorat toti Luptatorii Planetei.";
$l_cmb_youdestroyplanetfighters2        = "Luptatorii dvs. au omorat [cmb_attackerfighters] dintre Luptatorii Planetei";
$l_cmb_allyourfightersdestroyed = "Toti Luptatorii dvs. au fost omorati";
$l_cmb_fightertofighterlost     = "Ati pierdut [cmb_planetfighters] Luptatori in Confruntarea Luptatorilor";
$l_cmb_youbreachedplanetshields = "Luptatorii dvs. au distrus Scuturile Planetei";
$l_cmb_shieldsremainup  = "Luptatorii dvs. au lovit Scuturile Planetei in [cmb_attackerfighters] puncte, dar ele au ramas in functiune";
$l_cmb_fighterswarm     = "Luptatorii Planetei au inconjurat Nava dvs. si i-au distrus Armura";
$l_cmb_swarmandrepel    = "Luptatorii Planetei v-au inconjurat Nava, dar Armura ei i-a respins";
$l_cmb_engshiptoshipcombat      = "Angajarea in Lupta Nava - Nava.";
$l_cmb_shipdock = "Pe planeta sunt [cmb_shipsonplanet] Nave stationate in Hangarele Spatiale!";
$l_cmb_approachattackvector     = "se apropie atacand";  // DE VERIFICAT ##############################################
$l_cmb_noshipsdocked    = "NU se afla nici o Nava pe Planeta in Hangarele Spatiale!";
$l_cmb_yourshipdestroyed        = "Nava dvs. a fost distrusa!";
$l_cmb_escapepod        = "Din fericire, aveti un Dispozitiv de Salvare!";
$l_cmb_finalcombatstats = "Raportul Final al Luptei";
$l_cmb_youlostfighters  = "Ati pierdut [cmb_fighters_lost] Luptatori dintr-un Total de [cmb_playerinfo_ship_fighters].";
$l_cmb_youlostarmorpoints       = "Ati pirdut [cmb_armor_lost] puncte din Armura dintr-un Total de [cmb_playerinfo_armour_pts] puncte, v-au ramas [cmb_attackerarmor].";
$l_cmb_energyused       = "Ati folosit [cmb_energy] unitati de Energie dintr-un Total de [cmb_playerinfo_ship_energy] unitati.";
$l_cmb_planetdefeated   = "Planeta a fost Infranta";
$l_cmb_citizenswanttodie        = "Cetatenii acestei Planete au decis ca e mai bine sa moara decat sa serveasca un conducator patetic ca dvs.. Ei au folosit un Laser pentru a face o gaura imensa pana in centrul Planetei. Dvs. abia ati avut timp sa va smulgeti de pe orbita inainte ca intreaga Planeta sa se transforme intr-un glob de lava fierbinte.";
$l_cmb_youmaycapture    = "Puteti <a href=planet.php?planet_id=[cmb_planetinfo_planet_id]&command=capture>ocupa</a> aceasta Planeta sau o puteti lasa necucerita.";
$l_cmb_youmaycapture2   = "Puteti <a href=planet.php?planet_id=[cmb_planetinfo_planet_id]&command=capture>ocupa</a> aceasta Planeta sau o puteti lasa necucerita.";
$l_cmb_planetnotdefeated        = "Planeta NU a fost cucerita";
$l_cmb_planetstatistics = "Situatia planetei";
$l_cmb_fighterloststat  = "Luptatori pierduti: [cmb_fighters_lost] dintr-un Total de [cmb_planetinfo_fighters] ([cmb_planetfighters] in viata)";
$l_cmb_energyleft       = "Energie ramasa";
$l_cmb_startingstats    = "Situatia initiala";
$l_cmb_statattackerbeams        = "Laserele Atacatorului";
$l_cmb_statattackerfighters     = "Luptatorii Atacatorului";
$l_cmb_statattackershields      = "Scuturile Atacatorului";
$l_cmb_statattackertorps        = "Torpilele Atacatorului";
$l_cmb_statattackerarmor        = "Armura Atacatorului";
$l_cmb_statattackertorpdamage   = "Distrugerile Torpilelor Atacatorului";
$l_cmb_isattackingyou   = "va ataca pe dvs.";
$l_cmb_beamexchange     = "Schimbul de Lovituri Laser";
$l_cmb_beamsdestroy     = "Laserele dvs. au omorat [cmb_lost] Luptatori";
$l_cmb_beamsdestroy2    = "Laserele dvs. au omorat [cmb_attackerbeams] Luptatori, dar mai vin intariri";
$l_cmb_nobeamsareleft   = "Laserele dvs. nu mai au putere sa omoare Luptatorii care mai vin!";
$l_cmb_beamshavenotarget        = "Laserele dvs. nu gasesc nici un Luptator pe care sa il atace";
$l_cmb_fighterdestroyedbybeams  = "[cmb_targetinfo_ship_name] a distrus cu Laserele [cmb_lost] dintre Luptatorii dvs.<BR>";
$l_cmb_beamsdestroystillhave    = "[cmb_targetinfo_ship_name] a distrus cu Laserele [cmb_targetbeams] dintre Luptatorii dvs., dar mai aveti inca [cmb_attackerfighters].";
$l_cmb_fighterunhindered        = "Luptatorii dvs. ataca nestanjeniti, inamicul nu mai are Lasere.";
$l_cmb_youhavenofightersleft    = "Nu mai aveti nici un Luptator cu care sa atacati.";
$l_cmb_breachedsomeshields      = "Ati distrus cu ajutorul Laserelor scuturile de pe Nava [cmb_targetinfo_ship_name].";
$l_cmb_shieldsarehitbybeams     = "Scuturile Navei [cmb_targetinfo_ship_name] au fost lovite in [cmb_attackerbeams] puncte de catre lasere dvs.";
$l_cmb_nobeamslefttoattack      = "Laserele dvs. nu mai au putere sa atace Scuturile Navei [cmb_targetinfo_ship_name].";
$l_cmb_yourshieldsbreachedby    = "Scuturile dvs. au fost distruse de Laserele Navei [cmb_targetinfo_ship_name].";
$l_cmb_yourshieldsarehit        = "Laserele Navei [cmb_targetinfo_ship_name] au lovit Scuturile dvs. in [cmb_targetbeams] puncte.";
$l_cmb_hehasnobeamslefttoattack = "Laserele Navei [cmb_targetinfo_ship_name] nu mai au putere sa atace Scuturile dvs.";
$l_cmb_yourbeamsbreachedhim     = "Laserele dvs. au distrus Armura Navei [cmb_targetinfo_ship_name].";
$l_cmb_yourbeamshavedonedamage  = "Laserele dvs. au lovit Armura Navei [cmb_attackerbeams] in [cmb_targetinfo_ship_name] puncte.";
$l_cmb_nobeamstoattackarmor     = "Laserele dvs. nu mai au putere sa atace Armura Navei [cmb_targetinfo_ship_name].";
$l_cmb_yourarmorbreachedbybeams = "Armura dvs. a fost distrusa de Laserele Navei [cmb_targetinfo_ship_name].";
$l_cmb_yourarmorhitdamaged      = "Armura dvs. a fost lovita in [cmb_targetbeams] puncte de Laserele Navei [cmb_targetinfo_ship_name].";
$l_cmb_torpedoexchange  = "Schimbul de Torpile";
$l_cmb_hehasnobeamslefttoattackyou      = "Laserele Navei [cmb_targetinfo_ship_name] nu mai au putere sa atace Armura dvs.";
$l_cmb_yourtorpsdestroy = "Torpilele dvs. au omorat [cmb_lost] dintre Luptatorii Navei [cmb_targetinfo_ship_name].";
$l_cmb_yourtorpsdestroy2        = "Torpilele dvs. au omorat [cmb_attackertorpdamage] dintre Luptatorii Navei [cmb_targetinfo_ship_name].";
$l_cmb_youhavenotorpsleft       = "Nu mai aveti nici o Torpila pentru a ataca Luptatorii Navei [cmb_targetinfo_ship_name].";
$l_cmb_hehasnofighterleft       = "Nava [cmb_targetinfo_ship_name] nu mai are nici un Luptator pe care sa il atacati cu Torpile";
$l_cmb_torpsdestroyyou  = "Torpilele Navei [cmb_targetinfo_ship_name] au omorat [cmb_lost] dintre Luptatorii dvs.";
$l_cmb_someonedestroyedfighters = "Torpilele Navei [cmb_targetinfo_ship_name] au omorat [cmb_targettorpdmg] dintre Luptatorii dvs.";
$l_cmb_hehasnotorpsleftforyou   = "Nava [cmb_targetinfo_ship_name] nu mai are nici o Torpila cu care sa atace Luptatorii dvs.";
$l_cmb_youhavenofightersanymore = "Nu mai aveti nici un Luptator care sa fie omorat de Torpilele Navei [cmb_targetinfo_ship_name].";
$l_cmb_youbreachedwithtorps     = "Torpilele dvs. au distrus Armura Navei [cmb_targetinfo_ship_name].";
$l_cmb_hisarmorishitbytorps     = "Torpilele dvs. au lovit Armura Navei [cmb_targetinfo_ship_name] in [cmb_attackertorpdamage] puncte.";
$l_cmb_notorpslefttoattackarmor = "Nu mai aveti nici o Torpila cu care sa atacati Armura Navei [cmb_targetinfo_ship_name].";
$l_cmb_yourarmorbreachedbytorps = "Armura dvs. a fost distrusa de Torpilele Navei [cmb_targetinfo_ship_name].";
$l_cmb_yourarmorhitdmgtorps     = "Armura dvs. a fost lovita in [cmb_targettorpdmg] puncte de Torpilele Navei [cmb_targetinfo_ship_name].";
$l_cmb_hehasnotorpsforyourarmor = "Nava [cmb_targetinfo_ship_name] nu mai are nici o Torpila penru a ataca Armura dvs.";
$l_cmb_fightersattackexchange   = "Faza Confruntarii cu Luptatori";
$l_cmb_enemylostallfighters     = "Nava [cmb_targetinfo_ship_name] a pierdut toti Luptatorii.";
$l_cmb_helostsomefighters       = "Nava [cmb_targetinfo_ship_name] a pierdut [cmb_attackerfighters] Luptatori.";
$l_cmb_youlostallfighters       = "Dvs. ati pierdut toti Luptatorii.";
$l_cmb_youalsolostsomefighters  = "Ati pierdut [cmb_targetfighters] Luptatori.";
$l_cmb_hehasnofightersleftattack        = "Nava [cmb_targetinfo_ship_name] nu mai are nici un Lupatori pe care sa il atace Luptatorii dvs.";
$l_cmb_younofightersattackleft  = "Dvs. nu mai aveti nici un Luptator care sa atace Luptatorii Navei [cmb_targetinfo_ship_name].";
$l_cmb_youbreachedarmorwithfighters     = "Luptatorii dvs. au distrus Armura Navei [cmb_targetinfo_ship_name].";
$l_cmb_youhitarmordmgfighters   = "Luptatorii dvs. au lovit Armura Navei [cmb_targetinfo_ship_name] in  [cmb_attackerfighters] puncte.";
$l_cmb_youhavenofighterstoarmor = "Dvs. nu mai aveti nici un Luptator care sa atace Armura Navei [cmb_targetinfo_ship_name].";
$l_cmb_hasbreachedarmorfighters = "Luptatorii Navei [cmb_targetinfo_ship_name] au distrus Armura dvs.";
$l_cmb_yourarmorishitfordmgby   = "Armura dvs. a fost lovita in [cmb_targetfighters] puncte de Luptatorii Navei [cmb_targetinfo_ship_name].";
$l_cmb_nofightersleftheforyourarmor     = "Nava [cmb_targetinfo_ship_name] nu mai are nici un Luptator care sa atace Armura dvs.";
$l_cmb_hehasbeendestroyed       = "Nava [cmb_targetinfo_ship_name] a fost distrusa.";
$l_cmb_escapepodlaunched        = "Un Dispozitiv de Salvare a fost lansat!";
$l_cmb_yousalvaged      = "Ati recuperat [cmb_salv_ore] unitati de Minereu, [cmb_salv_organics] unitati de Alimente, [cmb_salv_goods] unitati de Bunuri si [cmb_salvage_rate]% din nava, adica [cmb_salvage] credite.<BR>Rating-ul dvs. s-a modificat la [cmb_number_rating_change] puncte.";
$l_cmb_youdidntdestroyhim       = "Nu ati distrus Nava [cmb_targetinfo_ship_name]";
$l_cmb_shiptoshipcombatstats    = "Raportul Luptei Nava - Nava";

// check_mines.php

$l_chm_youhitsomemines  = "Ati lovit [chm_roll] Mine!";
$l_chm_hehitminesinsector       = "[chm_playerinfo_character_name] a lovit [chm_roll] Mine in Sectorul [chm_sector].";
$l_chm_youlostminedeflectors    = "Ati folosit [chm_roll] Neutralizatoare Mine.";
$l_chm_youlostallminedeflectors = "Ati folosit toate Neutralizatoarele de Mine.";
$l_chm_youhadnominedeflectors  = "Nu aveti Neutralizatoare de Mine.";
$l_chm_yourshieldshitforminesdmg        = "Scuturile dvs. au fost lovite de Mine in [chm_mines_left] puncte.";
$l_chm_yourshieldsaredown       = "Scuturile dvs. sunt dezactivate!";
$l_chm_youlostallyourshields    = "Ati pierdut toate Scuturile!";
$l_chm_yourarmorhitforminesdmg  = "Armura dvs. a fost lovita de Mine in [chm_mines_left] puncte.";
$l_chm_yourhullisbreached       = "Carena dvs. este distrusa!";
$l_chm_hewasdestroyedbyyourmines        = "[chm_playerinfo_character_name] a fost distrus de minele dvs. din Sectorul [chm_sector].";
$l_chm_yourshiphasbeendestroyed = "Nava dvs. a fost distrusa!";
$l_chm_luckescapepod    = "Din fericire, ati avut un Dispozitiv de Salvare!";

// check_fighters.php

$l_chf_youretreatback   = "V-ati retras in locatia anterioara";
$l_chf_notenoughcreditstoll     = "Nu aveti destule Credite pentru a plati taxa.";
$l_chf_movefailed       = "Deplasare esuata.";
$l_chf_youpaidsometoll  = "Ati platit [chf_tollstring] Credite drept Taxa.";
$l_chf_thefightersdetectyou     = "Luptatorii din Patrula v-au detectat!";
$l_chf_therearetotalfightersindest      = "In Sectorul de destinatie sunt [chf_total_sector_fighters] Luptatori.";
$l_chf_creditsdemanded  = "Ei solicita [chf_number_fighterstoll] Credite pentru a intra in Sector.";
$l_chf_youcanretreat    = "Puteti sa <BR><INPUT TYPE=RADIO NAME=response VALUE=retreat><B>Va Retrageti</B> - Va va costa inca un Drum.<BR></INPUT>";
$l_chf_inputpay = "<INPUT TYPE=RADIO NAME=response CHECKED VALUE=pay><B>Platiti</B> Taxa si intrati in Sector fara a avea de-a face cu Luptatorii.<BR></INPUT>";
$l_chf_inputfight       = "<INPUT TYPE=RADIO NAME=response CHECKED VALUE=fight><B>Luptati</B> - trebuie sa infrangeti toti Luptatorii pentru a intra in Sector.<BR></INPUT>";
$l_chf_inputcloak       = "<INPUT TYPE=RADIO NAME=response CHECKED VALUE=sneak><B>Va Camuflati</B> - Folositi Camuflajul si incercati sa evitati Luptatorii.<BR></INPUT>";
$l_chf_go       = "Porneste";

// mines.php

$l_mines_title			="Raspandire Mine si Luptatori in Sector";
$l_mines_noturn		 	="Aveti nevoie de cel putin un Drum pentru a raspandi aparatori in Sector.";
$l_mines_nopermit		="Raspandirea de Mine si Luptatori in acest Sector nu este permisa.";
$l_mines_nodeploy		="Nu ii puteti raspandi aici pentru ca o alta Nava are Mine sau Luptatori in acest Sector.";
$l_mines_info1			="Sunteti prezent in Sectorul [sector]. Aici sunt [mines] Mine si [fighters] Luptatori.";
$l_mines_info2			="Aveti [mines] Mine si [fighters] Luptatori disponibili sa fie raspanditi in Sector";
$l_mines_deploy			="Raspandire";
$l_mines_deployed		="Raspanditi";
$l_mines_att			="Atac";
$l_mines_toll			="Taxe";
$l_mines_notorps		="Nu aveti destule Torpile.";
$l_mines_nofighters		="Nu aveti destui Luptatori";
$l_mines_dmines			="Au fost raspandite [mines] Mine.";
$l_mines_dfighter		="Au fost raspanditi [fighters] Luptatori cu ordinul [mode].";

//alliance-planets.php

$l_teamplanet_title		="Raportul Planetelor Aliantei";
$l_teamplanet_notally		="Dvs. nu faceti parte dintr-o Alianta.";
$l_teamplanet_personal		="Arata Planetele Personale";
$l_teamplanet_noplanet		="Alianta dvs. nu are Planete";

$l_feedback_title		="Trimitere Feedback";
$l_feedback_to			="Catre:";
$l_feedback_from		="De La:";
$l_feedback_topi		="SUBIECT:";
$l_feedback_feedback		="Feedback";
$l_feedback_message		="MESAJ:";
$l_feedback_messent		="Mesajul a fost trimis";
$l_feedback_subj		="Feedback";
$l_feedback_info		="Please send your feedback only in english or romanian"; // gameadmins put all your languages here

// corp.php
$l_corpm_title			="Meniu Corporatie";
$l_corpm_tocorp			="Planeta este acum o Planeta a Aliantei!";
$l_corpm_topersonal		="Planeta este acum o Planeta Personala!";
$l_corpm_exploit		="Ati interceptat un mesaj bruiat din Spatiu... %4^##2*9&^%$# ... e cazul sa va faceti griji...";


// login.php login2.php
$l_login_title			="Intrare";
$l_login_email			="Adresa E-mail:";
$l_login_pw			="Parola:";
$l_login_chooseres		="Nu poate fi determinata rezolutia ecranului dvs.. Va rugam sa alegeti cea mai buna varianta:";
$l_login_newp			= "Daca sunteti jucator nou, click <A HREF=\"new.php\">aici</A>.";
$l_login_prbs			= "Probleme?";
$l_login_emailus		= "Trimiteti un E-mail";
$l_login_sclosed		= "Server Inchis";
$l_login_closed_message		="Serverul este inchis temporar. Va rugam sa reveniti.";
$l_login_title2			="Intrare - Faza II";
$l_login_banned			="<b>Ati fost Ban-at (blocat) de la acest joc de catre Administrator. Nu mai sunteti binevenit pe acest server. Data viitoare purtati-va frumos!</b>";
$l_login_died			="Nava v-a fost distrusa, dar Dispozitivul de Salvare v-a tinut in viata pe dvs. si intregul echipaj.  Click <A HREF=main.php>aici</A> pentru a continua cu o noua Nava.";
$l_login_newbie			="Avand in vedere seriozitatea acestei crime si oribilul atac asupra dvs., federatia a hotarat sa realizeze (in mod gratuit) o clona din ramasitele recuperate. Totusi, chiar si in aceste zile clonele nu se pot autointretine fara o mica sustinere pentru a trai. Veti fi dotat cu o Nava de baza si cateva Credite pentru a putea incepe noua viata. Speram ca viata dvs. viitoare va fi mai buna.";
$l_login_newlife		="Click <A HREF=main.php>aici</A> pentru a continua cu o noua viata.";
$l_login_looser			="Nu ati avut un Dispozitiv de Salvare si, avand in vedere succesul dvs. modest din viata anterioara, Federatia a refuzat sa va cloneze. Ramasitele graviteaza acum pe undeva prin spatiu in speranta ca vor fi folosite pentru a crea viata undeva... peste bilioane de ani. <BR><BR> Mai mult noroc in jocul viitor...";
$l_login_4gotpw1		= "Parola pe care ati introsus-o este incorecta.<BR><BR>  Daca ati uitat parola, ";
$l_login_4gotpw2		= "pentru a va fi transmisa prin e-mail.<BR><BR>  De asemenea,";
$l_login_4gotpw3		= "pentru a mai incerca o data. Incercare de a intra de la IP";
$l_login_noone			= "Nu exista acest Jucator! - Creati un Jucator nou <A HREF=new.php>aici</A>.";

// new.php new2.php
$l_new_title			= "Creare Jucator Nou";
$l_new_title2			= "Creare Jucator Nou - Faza II";
$l_new_shipname			= "Nume Nava";
$l_new_pname			= "Nume Jucator";
$l_new_info			= "Va promitem ca nu vom da (sau vinde) e-mail-ul dvs. nimanui. Adresa de e-mail va este solicitata pentru a va trimite parola generata de sever..";
$l_new_closed_message		="Jocul este inchis pentru noii veniti.";
$l_new_blank			="E-mail-ul, Numele Navei si Numele Jucatorului nu pot fi goale.";
$l_new_inuse			="Aceasta adresa E-mail este deeja folosita.";
$l_new_4gotpw1			="Daca ati uitat parola,";
$l_new_4gotpw2			="pentru a o primi prin e-mail.";
$l_new_inusechar		="Numele de Jucator, $character, este deja folosit.";
$l_new_inuseship		="Numele de Nava, $shipname, este deja folosit.";
$l_new_pwsent			="Parola a fost trimisa la $username.";
$l_new_login			="pentru a merge la pagina de intrare.";
$l_new_err			="Va rugam sa va intoarceti sau <a href=new.php>click aici</a> pentru a incerca inca o data.";
$l_new_topic			="Parola BlackNova Traders";
$l_new_message			="Bun gasit,\n\nDe la adresa IP $ip s-a solicitat ca parola jocului BlackNova Traders sa fie transmisa la acest e-mail.\n\nParola dvs. este: [pass]\n\nAceasta parola o puteti schimba imediat dupa ce ati intrat in joc folosind sectiunea -Optiuni-\n\nMultumim pentru vizita,\n\nBlackNova Admin\n\n\nVa asteptam sa va intoarceti la\nhttp://www.AdAcademy.ro/BlackNova/.";

// logout.php

$l_logout_score			="Scorul dvs. curent este";
$l_logout_text			="[name] este acum in afara jocului.  Click <A HREF=index.php>aici</A> pentru a va intoarce in joc.";

// mail.php

$l_mail_title			="E-mail Parola";
$l_mail_noplayer		="Nu exista acest Jucator! - Creati un Jucator nou <A HREF=new.php>aici</A>.";
$l_mail_sent			="Parola a fost trimisa la";
$l_mail_topic			="Parola $game_name";
$l_mail_message			="Bun gasit,\n\nDe la adresa IP $ip s-a solicitat ca parola jocului $game_name sa fie transmisa la acest e-mail.\n\nParola dvs. este: [pass]\n\nAceasta parola o puteti schimba imediat dupa ce ati intrat in joc folosind sectiunea -Optiuni-\n\nMultumim pentru vizita,\n\nBlackNova Admin\n\n\nVa asteptam sa va intoarceti la\nhttp://www.AdAcademy.ro/BlackNova/.";

// global_funcs.php

$l_global_mmenu			="Click <A HREF=main.php>here</A> to return to the main menu.";
$l_global_mlogin		="Click <A HREF=login.php>here</A> to return to the login screen.";
$l_global_needlogin		="You need to log in, click <A HREF=login.php>here</A>.";
$l_global_died			="Player is DEAD! <a href=log.php>Here</a>'s what happened<BR><BR>Better Luck Next Time!";
$l_global_warzone		="Zone is now a War Zone!";
$l_global_nzone			="Zone is a neutral zone.";
$l_global_team			="Zone now belongs to alliance";
$l_global_player		="Zone now belongs to player";

// texts for the news flashes

$l_news_planets		  = " planets";
$l_news_cols		      = " Million colonists";
$l_news_p_headline = "[player]\'s Empire now has ";

$l_killheadline=" was killed in an accident";
$l_news_killed = "[name] was killed in a tragic accident today. How heroic - captain [name] was the last member on board of his ship, when he noticed there was no escape pod left for him. May he rest in peace!";
$l_news_p_text5		= "The rising empire of [name] now has five planets, the BNN will watch the actions of [name] more closely in the future!";
$l_news_p_text10		= "The growing empire of [name] now controls ten planets, Reports of BNN say that further expansion of [name] might lead to war!";
$l_news_p_text25		= "The huge empire of [name] colonized 25 planets already, in an interview, [name] announced that he might consider slowing down his expansion in the future!";
$l_news_p_text50		= "The enormous vast empire of [name], represented by 50 planets in the whole galaxy is getting a threatening strength. One of the BNN reporters found out that [name] is upgrading his ship planning a major war. In an interview [name] announced that is done on defence purpose only!";
$l_news_c_text25		= "The rising empire of [name] now has 25 million colonists, the BNN will watch the actions of [name] more closely in the future, but its highly obvious that birthrates are going to explode!";
$l_news_c_text100		= "The aspiring empire of [name] now has 100 million colonists, after an explosion of birth rates, [name] colonies seemed to be a good place for families to settle!";
$l_news_c_text500		= "The large empire of [name] now has 500 million colonists, [name] said in an interview that colonization of the galaxy has just yet begun";
$l_news_c_text1000		= "The humongous empire of [name] now has one billion colonists, BNN reporters found out that [name] is in possesion of some weird cloning mechanism allowing him to breed new colonists in huge amounts. With this amount of colonists, the econmic strength of this empire is enormous, BNN hopes that [name] does not spend his money on warfare";

// Options.php

$l_opt_title = "Options";
$l_opt_chpass = "Change password";
$l_opt_curpass = "Current password:";
$l_opt_newpass = "New password:";
$l_opt_newpagain = "New password (again):";
$l_opt_userint = "User interface";
$l_opt_usenew = "Use new layout?";
$l_opt_lang = "Language";
$l_opt_select = "Select One:";
$l_opt_enabled = "Enabled";
$l_opt_save = "Save";

// Option2.php

$l_opt2_title = "Save Options";
$l_opt2_passunchanged = "Password was left unchanged.<BR><BR>";
$l_opt2_srcpassfalse = "Original password incorrect. Password was left unchanged.<BR><BR>";
$l_opt2_newpassnomatch = "New password fields do not match. Password was left unchanged.<BR><BR>";
$l_opt2_passchanged = "Password changed.<BR><BR>";
$l_opt2_passchangeerr = "Error changing password<BR><BR>";
$l_opt2_userintup = "User interface setting updated.<BR><BR>";
$l_opt2_userintfail = "Failed to update user interface setting.<BR><BR>";
$l_opt2_chlang = "Language has been set to [lang].<p>";
$l_opt2_dhtmlup = "Dynamic html setting updated.<BR><BR>";
$l_opt2_dhtmlfail = "Failed to update dynamic html setting.<BR><BR>";

// Presets.php

$l_pre_title = "Change Realspace Presets";
$l_pre_exceed = "Preset [preset] exceeds universe max of [sector_max]. No presets saved.<BR><BR>"; 
$l_pre_set = "Preset 1 set to [preset1], preset 2 set to [preset2] and preset 3 set to [preset3].<BR><BR>";
$l_pre_save = "Save";

// Mailto.php

$l_mt_title = "Send Message";
$l_mt_from = "From:";
$l_mt_subject = "Subject:";
$l_mt_message = "Message:";
$l_mt_sent = "Message sent";
$l_mt_send = "Send";

// sector_fighters.php
$l_sf_attacking = "Sector defence fighters are attacking you!<BR>";
$l_sf_destfight = "Your beams destroyed [lost] fighters<BR>";
$l_sf_destfightb = "Your beams destroyed [lost] fighters<BR>";
$l_sf_torphit = "Torpedoes hit:";
$l_sf_destfightt = "Your torpedoes destroyed [lost] fighters<BR>";
$l_sf_fighthit = "Fighters Attack:";
$l_sf_destfightall = "You destroyed all the fighters.<BR>";
$l_sf_destfightt2 = "You destroyed [lost] fighters.<BR>";
$l_sf_lostfight = "You lost all fighters.<BR>";
$l_sf_lostfight2 = "You lost [lost] fighters.<BR>";
$l_sf_armorbreach = "Your armour is breached!<BR>";
$l_sf_armorbreach2 = "Your armour is hit for [lost] damage.<BR>";
$l_sf_sendlog = "[player] destroyed [lost] sector defence fighters in sector [sector].";
$l_sf_lreport = "You lost [armor] armour points, [fighters] fighters, and used [torps] torpedoes.<BR><BR>";
$l_sf_shipdestroyed = "Your ship has been destroyed!<BR><BR>";
$l_sf_sendlog2 = "Sector defence fighters destroyed [player] in sector [sector].";
$l_sf_escape = "Luckily you have an escape pod!<BR><BR>";

// Zone names

$l_zname[1] = "Unchartered space";
$l_zname[2] = "Federation space";
$l_zname[3] = "Free-trade space";
$l_zname[4] = "War Zone";

// ADDITION TO warpedit2.php

$l_warp_cantsame = "You can't create a link when the source is the same as the destination.";

//Addition to modify defences

$l_md_noturn	  	 = "You need at least one turn.";
$l_md_nothere            = "You need to be in the same sector as the sector defences.";
$l_md_notyours           = "Action not permitted. Those sector defences do not belong to you.";
$l_md_yours              = "You can not attack your own sector defences.";

// Bounty
$l_by_title = "Bounties";
$l_by_noturn = "You need at least one turn to place or modify a bounty.";
$l_by_amount = "Bounty Amount";
$l_by_place = "Place Bounty";
$l_by_nobounties = "There are currently no bounties.";
$l_by_bountyon = "Bounty On";
$l_by_placedby = "Placed by";
$l_by_thefeds  = "The Federation";
$l_by_cancel   = "Cancel";
$l_by_yourself = "You can not place a bounty on your self.";
$l_by_notenough = "You do not have enough credits to place a bounty of that amount.";
$l_by_toomuch   = "You can not place that bounty. Maximum bounty allowed on another player is $percent percent of your net worth";
$l_by_zeroamount = "Bounties must be greater than 0 credits.";
$l_by_placed     = "The bounty has been placed.";
$l_by_nobounty = "That bounty no longer exists.";
$l_by_notyours = "That bounty was not placed by you.";
$l_by_canceled = "The bounty has been canceled.";
$l_by_action   = "Action";
$l_by_placebounty = "Place or view bounties.";
$l_by_moredetails = "Click on the name for more details.";
$l_by_fedbounty = "Attacking this player would result in The Federation placing a bounty on you.";
$l_by_fedbounty2 = "The Federation does not approve of attacking much smaller ships. It has placed a bounty on you.";
$l_by_notexists = "The player you are putting the bounty on does not exist.";
$l_by_destroyed = "You can not place a bounty on a player with a destroyed ship.";
$l_log_text[LOG_BOUNTY_CLAIMED] = "You claimed a bounty of [amount] credits for the destruction of the ship belonging to [bounty_on]. The bounty was placed by [placed_by].";
$l_log_title[LOG_BOUNTY_CLAIMED] = "Bounty Claimed.";
$l_log_text[LOG_BOUNTY_PAID] = "Your bounty on [bounty_on] has been paid for the amount of [amount] credits.";
$l_log_title[LOG_BOUNTY_PAID] = "Bounty Paid.";
$l_log_text[LOG_BOUNTY_CANCELLED] = "Your bounty on [bounty_on] for the amount of [amount] credits has been refunded.";
$l_log_title[LOG_BOUNTY_CANCELLED] = "Bounty Refunded.";
$l_log_text[LOG_SPACE_PLAGUE] = "Your planet [name] in sector [sector] has been hit by Space Plague. Fifty percent of the colonists were killed.";
$l_log_title[LOG_SPACE_PLAGUE] = "Space Plague!";
$l_log_text[LOG_PLASMA_STORM] = "Your planet [name] in sector [sector] has been hit by a Plasma Storm. All stored Energy has been lost.";
$l_log_title[LOG_PLASMA_STORM] = "Plasma Storm!";
$l_log_text[LOG_BOUNTY_FEDBOUNTY] = "The Federation has placed a bounty on you for the amount of [amount] credits.";
$l_log_title[LOG_BOUNTY_FEDBOUNTY] = "Federation Bounty!";
$l_new_pwis = "Your password is";
$l_planet2_sector = "You are not in the same sector as that planet.";
$l_planet_destroyplanet = "Destroy Planet";
$l_planet_warning = "Doing this will totally destroy this planet";
$l_planet_confirm = "Do you really want to destroy this planet?";
$l_port_bounty = "You can not access a special port while you have a bounty on you placed by The Federation.<BR>";
$l_port_bounty = "Click <a href=\"port.php?pay=1\">here</a> to pay the bounty of [amount] credits.";
$l_port_btynotenough = "You do not have enough credtis to pay the bounty of [amount] credits.<BR>";
$l_port_bountypaid = "You have paid the bounty. Click <a href=\"port.php\">here</a> to continue.<BR>";
$l_team_notyours = "You must be in the Alliance in order to invite someone.";
$l_team_leavefirst = "You must leave a team first before joining another.";


$l_tdr_engageagain = "Click <A HREF=\"traderoute.php?engage=[tdr_engage]\">here</A> to do this trade route again, or here to do it <A HREF=\"traderoute.php?engage=[tdr_engage]&tr_repeat=5\">five</A> or <A HREF=\"traderoute.php?engage=[tdr_engage]&tr_repeat=10\">ten</A> or <A HREF=\"traderoute.php?engage=[tdr_engage]&tr_repeat=50\">fifty</A> times<p>";
$l_scan_bounty = "This ship has a total bounty on it of [amount] credits.";
$l_scan_fedbounty = "This ship has a bounty on it from The Federation.";

//Fig Drops

$l_sofa = "Sub-Orbital Fighter Attack";
$l_bombsaway = "You send your fighters spiralling towards the planet as you streak by at maximum range.";
$l_bigfigs = "Your huge ship has given them ample warning.  Your fighters will be less successful.";
$l_bigbeams = "There is a bright flash of discharging beams.  Your fighters probably didn't make it to the atmosphere.";
$l_bigtorps = "A large explosion blossoms in the upper air of the planet.  Your fighters probably didn't have time to attack.";
$l_strafesuccess = "It looks like some of your fighters made it through, although you can't tell how many from here.";
$l_log_text[LOG_PLANET_BOMBED] = "Your planet [planet_name] in sector [sector] was bombed by [name]. You used [beams] energy and [torps] torpedoes in your defense.  You lost [figs] fighters.";
$l_log_title[LOG_PLANET_BOMBED] = "<font color=red>Planet bombed!</font>";

?>
